# 09 - Refinamiento fino de los tres mejores candidatos

Este nodo no repite la búsqueda amplia. Espera a que el nodo 07 complete su evaluación OOF de cinco folds y selecciona exactamente tres puntos de partida:

1. los dos mejores candidatos por **log loss OOF cross-calibrado de cinco folds**;
2. el mejor candidato 3D;
3. si el 3D ya pertenece al top 2, completa el tercer cupo con el siguiente candidato del ranking.

Cada rama conserva arquitectura, pooling, variante y lateralidad. Optuna sólo explora un vecindario local informado por las mejores trayectorias del nodo 07: learning rate más bajo, regularización, dropout, intensidad de augmentation y configuración tabular. Cada trial usa tres folds; los tres ganadores se reentrenan después con cinco folds congelados.

In [1]:
from __future__ import annotations

import json
import os
import sys
from dataclasses import replace
from pathlib import Path

import pandas as pd
import torch
from IPython.display import Markdown, display

PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name.lower() == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from modeling.cnn.io import RunLock
from modeling.node09_refinement import (
    RefinementExperiment,
    prepare_refinement,
    run_final_stage,
    run_search_stage,
)

RUN_ID = os.environ.get("DAT_NODE09_RUN_ID", "node09_fine_v1")
SOURCE_NODE07_RUN_ID = os.environ.get("DAT_NODE09_SOURCE_RUN_ID", "dat_spect_slab_v4")
NODE4_PROFILE = os.environ.get("DAT_NODE09_NODE4_PROFILE", "v3")
TRIALS_PER_MODEL = int(os.environ.get("DAT_NODE09_TRIALS_PER_MODEL", "18"))
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

EXPERIMENT = RefinementExperiment(
    run_id=RUN_ID,
    source_node07_run_id=SOURCE_NODE07_RUN_ID,
)
EXPERIMENT = replace(
    EXPERIMENT,
    data=replace(EXPERIMENT.data, node4_profile=NODE4_PROFILE),
    search=replace(EXPERIMENT.search, trials_per_model=TRIALS_PER_MODEL),
)
RUN_DIR = PROJECT_ROOT / "outputs" / "private_eda" / "node09_runs" / RUN_ID

display(Markdown(
    f"**Run nodo 09:** `{RUN_ID}` · **fuente nodo 07:** `{SOURCE_NODE07_RUN_ID}` · "
    f"**device:** `{DEVICE}` · **trials completos por rama:** `{TRIALS_PER_MODEL}` · "
    f"**máximo:** `{EXPERIMENT.search.max_epochs_search}` épocas"
))

**Run nodo 09:** `node09_fine_v1` · **fuente nodo 07:** `dat_spect_slab_v4` · **device:** `cuda` · **trials completos por rama:** `18` · **máximo:** `32` épocas

## 1. Gate de comparabilidad

La selección no se habilita con OOF parciales ni con el score de los tres folds de Optuna. Debe existir `final_metrics.csv` del nodo 07, lo que implica que sus tres finalistas ya pasaron por el mismo CV5.

In [2]:
SOURCE_RUN_DIR = (
    PROJECT_ROOT / "outputs" / "private_eda" / "node07_runs" / SOURCE_NODE07_RUN_ID
)
source_metrics_path = SOURCE_RUN_DIR / "final" / "final_metrics.csv"
source_finalists_path = SOURCE_RUN_DIR / "search" / "finalists.json"
source_oof = sorted((SOURCE_RUN_DIR / "final").glob("oof_*.csv"))
display(pd.DataFrame({
    "artefacto": ["finalistas búsqueda", "OOF finalistas completos", "ranking CV5 final"],
    "estado": [
        source_finalists_path.exists(),
        len(source_oof),
        source_metrics_path.exists(),
    ],
}))
if not source_metrics_path.exists():
    raise RuntimeError(
        "El nodo 07 todavía no terminó los tres finalistas CV5. "
        "Reanuda su celda final y vuelve aquí cuando exista final_metrics.csv."
    )
display(pd.read_csv(source_metrics_path))

                  artefacto estado
0       finalistas búsqueda   True
1  OOF finalistas completos      3
2         ranking CV5 final   True

,candidate_id,architecture,feature_variant,lateral_strategy,raw_log_loss,raw_brier,raw_auc,raw_balanced_accuracy_0_5,raw_ece_10,calibrated_log_loss,calibrated_brier,calibrated_auc,calibrated_balanced_accuracy_0_5,calibrated_ece_10,deployment_temperature
0,23f042f62f40d03e,slab2d,image_radiomics_sbr,random_flip,0.556924,0.187166,0.799906,0.735958,0.064860,0.551498,0.184972,0.796822,0.735958,0.045810,1.266840
1,fb93ea204b0ec32f,2.5d,image_radiomics_sbr,random_flip,0.560599,0.187826,0.797649,0.739593,0.071564,0.552242,0.184982,0.793100,0.739593,0.043068,1.333065
2,3f9bbf24164bd1dc,3d,image_radiomics_sbr,random_flip,0.586020,0.195744,0.780836,0.727110,0.087526,0.565622,0.190079,0.775836,0.727110,0.029703,1.508521

## 2. Preparación y selección de las tres referencias

Se reutilizan los mismos 1362 pacientes, caches y folds congelados. Esta etapa no vuelve a ejecutar registro ni extracción de características. La tabla permite comprobar qué modelo entró por top global, cuál por mejor 3D y cuál completó diversidad si hubo solapamiento.

In [3]:
with RunLock(RUN_DIR / "prepare.lock"):
    prepared = prepare_refinement(EXPERIMENT, project_root=PROJECT_ROOT)

references = pd.read_csv(RUN_DIR / "config" / "selected_references.csv")
display(references)
display(pd.DataFrame({
    "indicador": [
        "Pacientes únicos", "Ramas Optuna", "Folds por trial",
        "Trials completos por rama", "Entrenamientos CV de búsqueda objetivo",
        "Folds de evaluación final",
    ],
    "valor": [
        prepared.cohort["uid"].nunique(), 3,
        EXPERIMENT.search.n_splits_search,
        EXPERIMENT.search.trials_per_model,
        3 * EXPERIMENT.search.trials_per_model * EXPERIMENT.search.n_splits_search,
        EXPERIMENT.search.n_splits_final,
    ],
}))

,source_candidate_id,node07_rank,node07_calibrated_log_loss,selection_roles,architecture,feature_variant,lateral_strategy,source_learning_rate,source_fixed_epochs,source_completed_trials
0,23f042f62f40d03e,1,0.551498,top_1_overall,slab2d,image_radiomics_sbr,random_flip,0.000317,9,4
1,fb93ea204b0ec32f,2,0.552242,top_2_overall,2.5d,image_radiomics_sbr,random_flip,0.000317,9,2
2,3f9bbf24164bd1dc,3,0.565622,best_3d,3d,image_radiomics_sbr,random_flip,0.000317,3,2

                                indicador  valor
0                        Pacientes únicos   1362
1                            Ramas Optuna      3
2                         Folds por trial      3
3               Trials completos por rama     18
4  Entrenamientos CV de búsqueda objetivo    162
5               Folds de evaluación final      5

In [4]:
spaces = json.loads(
    (RUN_DIR / "config" / "refinement_spaces.json").read_text(encoding="utf-8")
)["spaces"]
space_rows = []
for source_id, space in spaces.items():
    source = next(
        item for item in prepared.references if item["source_candidate_id"] == source_id
    )
    space_rows.append({
        "source_candidate_id": source_id,
        "architecture": source["architecture"],
        "source_learning_rate": source["train_config"]["learning_rate"],
        "node09_learning_rate_min": space["learning_rate"][0],
        "node09_learning_rate_max": space["learning_rate"][1],
        "dropout_range": tuple(space["dropout"]),
        "weight_decay_range": tuple(space["weight_decay"]),
        "tabular_embedding_dim": tuple(space["tabular_embedding_dim"]),
        "feature_top_k": tuple(space["feature_top_k"]),
        "pca_variance": tuple(space["pca_variance"]),
    })
display(pd.DataFrame(space_rows))

,source_candidate_id,architecture,source_learning_rate,node09_learning_rate_min,node09_learning_rate_max,dropout_range,weight_decay_range,tabular_embedding_dim,feature_top_k,pca_variance
0,23f042f62f40d03e,slab2d,0.000317,0.00007,0.000247,"(0.23006770120532094, 0.38006770120532096)","(4.970547987064239e-07, 2.9823287922385433e-05)","(16, 24, 48)","(32, 64, 128)","(0.95, 0.98, none)"
1,3f9bbf24164bd1dc,3d,0.000317,0.00007,0.000247,"(0.22728152879644464, 0.37728152879644467)","(2.8895967463213424e-06, 0.00017337580477928054)","(16, 24, 48)","(32, 64, 128)","(0.95, 0.98, none)"
2,fb93ea204b0ec32f,2.5d,0.000317,0.00007,0.000247,"(0.22728152879644464, 0.37728152879644467)","(2.8895967463213424e-06, 0.00017337580477928054)","(16, 24, 48)","(32, 64, 128)","(0.95, 0.98, none)"

## 3. Tres búsquedas Optuna finas y reanudables

Son **tres estudios**, no tres trials. Por defecto cada estudio exige 18 trials completos y cada trial recorre tres folds. Los primeros ocho trials completos forman el calentamiento del pruner; después puede cortar configuraciones claramente inferiores. Un apagado conserva SQLite, checkpoints por época e historias.

In [5]:
with RunLock(RUN_DIR / "search.lock"):
    search_result = run_search_stage(prepared, EXPERIMENT, device=DEVICE)
display(search_result.summary)
display(Markdown(
    "Abre o vuelve a ejecutar el **nodo 08** y selecciona "
    f"`node09:{RUN_ID}` para comparar estas trayectorias con los nodos 06 y 07."
))

[I 2026-08-31 01:03:04,809] A new study created in RDB with name: node09_slab2d_23f042f62f

[nodo07] fold=0 epoch=1/32 train=0.7314 val=0.6521
[nodo07] fold=0 epoch=2/32 train=0.7028 val=0.6021
[nodo07] fold=0 epoch=3/32 train=0.6516 val=0.5855
[nodo07] fold=0 epoch=4/32 train=0.6392 val=0.5700
[nodo07] fold=0 epoch=5/32 train=0.6239 val=0.5560
[nodo07] fold=0 epoch=6/32 train=0.6078 val=0.5539
[nodo07] fold=0 epoch=7/32 train=0.6092 val=0.5476
[nodo07] fold=0 epoch=8/32 train=0.6103 val=0.5405
[nodo07] fold=0 epoch=9/32 train=0.5960 val=0.5362
[nodo07] fold=0 epoch=10/32 train=0.5927 val=0.5317
[nodo07] fold=0 epoch=11/32 train=0.5763 val=0.5475
[nodo07] fold=0 epoch=12/32 train=0.5834 val=0.5437
[nodo07] fold=0 epoch=13/32 train=0.5959 val=0.5240
[nodo07] fold=0 epoch=14/32 train=0.5458 val=0.5276
[nodo07] fold=0 epoch=15/32 train=0.5748 val=0.5244
[nodo07] fold=0 epoch=16/32 train=0.5568 val=0.5301
[nodo07] fold=0 epoch=17/32 train=0.5372 val=0.5333
[nodo07] fold=0 epoch=18/32 train=0.5495 val=0.5245
[nodo07] fold=0 epoch=19/32 train=0.5609 val=0.5192
[nodo07] fold=0 epoch=20/32 train=0.5537 val=0.5191
[nodo07] fold=0 epoch=21/32 train=0.5480 val=0.5178
[nodo07] fold=0 epoch=22/32 train=0.5113 val=0.5194
[nodo07] fold=0 epoch=23/32 train=0.5195 val=0.5203
[nodo07] fold=0 epoch=24/32 train=0.5474 val=0.5171
[nodo07] fold=0 epoch=25/32 train=0.5182 val=0.5186
[nodo07] fold=0 epoch=26/32 train=0.5034 val=0.5218
[nodo07] fold=0 epoch=27/32 train=0.5277 val=0.5188
[nodo07] fold=0 epoch=28/32 train=0.5316 val=0.5180
[nodo07] fold=0 epoch=29/32 train=0.5045 val=0.5188
[nodo07] fold=0 epoch=30/32 train=0.5303 val=0.5190
[nodo07] fold=0 epoch=31/32 train=0.5165 val=0.5190
[nodo07] fold=0 epoch=32/32 train=0.4815 val=0.5191
[nodo07] fold=1 epoch=1/32 train=0.7430 val=0.6536
[nodo07] fold=1 epoch=2/32 train=0.6926 val=0.6226
[nodo07] fold=1 epoch=3/32 train=0.6391 val=0.6230
[nodo07] fold=1 epoch=4/32 train=0.6303 val=0.5851
[nodo07] fold=1 epoch=5/32 train=0.6001 val=0.5884
[nodo07] fold=1 epoch=6/32 train=0.6039 val=0.5782
[nodo07] fold=1 epoch=7/32 train=0.5678 val=0.5770
[nodo07] fold=1 epoch=8/32 train=0.5753 val=0.5662
[nodo07] fold=1 epoch=9/32 train=0.5444 val=0.5745
[nodo07] fold=1 epoch=10/32 train=0.5690 val=0.5620
[nodo07] fold=1 epoch=11/32 train=0.5374 val=0.5749
[nodo07] fold=1 epoch=12/32 train=0.5394 val=0.5678
[nodo07] fold=1 epoch=13/32 train=0.5613 val=0.5652
[nodo07] fold=1 epoch=14/32 train=0.5167 val=0.5737
[nodo07] fold=1 epoch=15/32 train=0.5117 val=0.5835
[nodo07] fold=1 epoch=16/32 train=0.4819 val=0.5890
[nodo07] fold=1 epoch=17/32 train=0.5196 val=0.5850
[nodo07] fold=1 epoch=18/32 train=0.5277 val=0.5765
[nodo07] fold=1 epoch=19/32 train=0.5107 val=0.5886
[nodo07] fold=2 epoch=1/32 train=0.7389 val=0.6454
[nodo07] fold=2 epoch=2/32 train=0.6656 val=0.5800
[nodo07] fold=2 epoch=3/32 train=0.6446 val=0.5836
[nodo07] fold=2 epoch=4/32 train=0.6595 val=0.5816
[nodo07] fold=2 epoch=5/32 train=0.6086 val=0.5708
[nodo07] fold=2 epoch=6/32 train=0.5835 val=0.6068
[nodo07] fold=2 epoch=7/32 train=0.5799 val=0.5753
[nodo07] fold=2 epoch=8/32 train=0.5855 val=0.5622
[nodo07] fold=2 epoch=9/32 train=0.5729 val=0.5676
[nodo07] fold=2 epoch=10/32 train=0.5898 val=0.5642
[nodo07] fold=2 epoch=11/32 train=0.5602 val=0.5563
[nodo07] fold=2 epoch=12/32 train=0.5469 val=0.5799
[nodo07] fold=2 epoch=13/32 train=0.5622 val=0.5562
[nodo07] fold=2 epoch=14/32 train=0.5364 val=0.5723
[nodo07] fold=2 epoch=15/32 train=0.5398 val=0.5912
[nodo07] fold=2 epoch=16/32 train=0.5359 val=0.5591
[nodo07] fold=2 epoch=17/32 train=0.5369 val=0.5717
[nodo07] fold=2 epoch=18/32 train=0.5106 val=0.5703
[nodo07] fold=2 epoch=19/32 train=0.5700 val=0.5683
[nodo07] fold=2 epoch=20/32 train=0.5110 val=0.5709
[nodo07] fold=2 epoch=21/32 train=0.5240 val=0.5839
[nodo07] fold=2 epoch=22/32 train=0.4995 val=0.5782

[I 2026-08-31 01:31:26,439] Trial 0 finished with value: 0.545080794944553 and parameters: {'dropout': 0.30506770120532095, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.1026067125234453, 'augmentation_probability': 0.8009586631176213, 'rotation_degrees': 1.5935397493341092, 'learning_rate': 0.00013134702829321461, 'weight_decay': 3.8501699150849195e-06, 'auxiliary_weight': 0.14550204100106018, 'consistency_weight': 0.0653384855658812, 'feature_top_k': 64, 'pca_variance': 'none'}. Best is trial 0 with value: 0.545080794944553.

[nodo07] fold=0 epoch=1/32 train=0.7362 val=0.6607
[nodo07] fold=0 epoch=2/32 train=0.6945 val=0.5735
[nodo07] fold=0 epoch=3/32 train=0.6397 val=0.5603
[nodo07] fold=0 epoch=4/32 train=0.6301 val=0.5605
[nodo07] fold=0 epoch=5/32 train=0.6250 val=0.5446
[nodo07] fold=0 epoch=6/32 train=0.6248 val=0.5394
[nodo07] fold=0 epoch=7/32 train=0.6290 val=0.5285
[nodo07] fold=0 epoch=8/32 train=0.6040 val=0.5210
[nodo07] fold=0 epoch=9/32 train=0.6051 val=0.5170
[nodo07] fold=0 epoch=10/32 train=0.5953 val=0.5144
[nodo07] fold=0 epoch=11/32 train=0.5832 val=0.5220
[nodo07] fold=0 epoch=12/32 train=0.5979 val=0.5244
[nodo07] fold=0 epoch=13/32 train=0.6044 val=0.5039
[nodo07] fold=0 epoch=14/32 train=0.5585 val=0.5063
[nodo07] fold=0 epoch=15/32 train=0.5852 val=0.5096
[nodo07] fold=0 epoch=16/32 train=0.5557 val=0.5068
[nodo07] fold=0 epoch=17/32 train=0.5340 val=0.5075
[nodo07] fold=0 epoch=18/32 train=0.5426 val=0.5040
[nodo07] fold=0 epoch=19/32 train=0.5516 val=0.5040
[nodo07] fold=0 epoch=20/32 train=0.5549 val=0.5001
[nodo07] fold=0 epoch=21/32 train=0.5530 val=0.4966
[nodo07] fold=0 epoch=22/32 train=0.5374 val=0.4993
[nodo07] fold=0 epoch=23/32 train=0.5331 val=0.5018
[nodo07] fold=0 epoch=24/32 train=0.5503 val=0.4989
[nodo07] fold=0 epoch=25/32 train=0.5385 val=0.4993
[nodo07] fold=0 epoch=26/32 train=0.5170 val=0.5003
[nodo07] fold=0 epoch=27/32 train=0.5234 val=0.4992
[nodo07] fold=0 epoch=28/32 train=0.5560 val=0.4991
[nodo07] fold=0 epoch=29/32 train=0.5178 val=0.4993
[nodo07] fold=0 epoch=30/32 train=0.5295 val=0.4995
[nodo07] fold=1 epoch=1/32 train=0.7433 val=0.6329
[nodo07] fold=1 epoch=2/32 train=0.6994 val=0.6288
[nodo07] fold=1 epoch=3/32 train=0.6542 val=0.6374
[nodo07] fold=1 epoch=4/32 train=0.6523 val=0.6007
[nodo07] fold=1 epoch=5/32 train=0.6402 val=0.5894
[nodo07] fold=1 epoch=6/32 train=0.6367 val=0.5946
[nodo07] fold=1 epoch=7/32 train=0.6051 val=0.5640
[nodo07] fold=1 epoch=8/32 train=0.6006 val=0.5527
[nodo07] fold=1 epoch=9/32 train=0.5855 val=0.5570
[nodo07] fold=1 epoch=10/32 train=0.5979 val=0.5534
[nodo07] fold=1 epoch=11/32 train=0.5968 val=0.5496
[nodo07] fold=1 epoch=12/32 train=0.5945 val=0.5545
[nodo07] fold=1 epoch=13/32 train=0.5906 val=0.5469
[nodo07] fold=1 epoch=14/32 train=0.5620 val=0.5498
[nodo07] fold=1 epoch=15/32 train=0.5647 val=0.5578
[nodo07] fold=1 epoch=16/32 train=0.5361 val=0.5585
[nodo07] fold=1 epoch=17/32 train=0.5521 val=0.5540
[nodo07] fold=1 epoch=18/32 train=0.5874 val=0.5388
[nodo07] fold=1 epoch=19/32 train=0.5488 val=0.5569
[nodo07] fold=1 epoch=20/32 train=0.5247 val=0.5613
[nodo07] fold=1 epoch=21/32 train=0.5438 val=0.5478
[nodo07] fold=1 epoch=22/32 train=0.5419 val=0.5432
[nodo07] fold=1 epoch=23/32 train=0.5499 val=0.5389
[nodo07] fold=1 epoch=24/32 train=0.5489 val=0.5449
[nodo07] fold=1 epoch=25/32 train=0.5607 val=0.5408
[nodo07] fold=1 epoch=26/32 train=0.5461 val=0.5364
[nodo07] fold=1 epoch=27/32 train=0.5145 val=0.5421
[nodo07] fold=1 epoch=28/32 train=0.5741 val=0.5390
[nodo07] fold=1 epoch=29/32 train=0.5379 val=0.5382
[nodo07] fold=1 epoch=30/32 train=0.5563 val=0.5365
[nodo07] fold=1 epoch=31/32 train=0.5474 val=0.5365
[nodo07] fold=1 epoch=32/32 train=0.5517 val=0.5366
[nodo07] fold=2 epoch=1/32 train=0.7653 val=0.6680
[nodo07] fold=2 epoch=2/32 train=0.6871 val=0.5858
[nodo07] fold=2 epoch=3/32 train=0.6528 val=0.5843
[nodo07] fold=2 epoch=4/32 train=0.6700 val=0.5876
[nodo07] fold=2 epoch=5/32 train=0.6313 val=0.5723
[nodo07] fold=2 epoch=6/32 train=0.6018 val=0.6154
[nodo07] fold=2 epoch=7/32 train=0.5973 val=0.5697
[nodo07] fold=2 epoch=8/32 train=0.6093 val=0.5618
[nodo07] fold=2 epoch=9/32 train=0.5876 val=0.5838
[nodo07] fold=2 epoch=10/32 train=0.6201 val=0.5614
[nodo07] fold=2 epoch=11/32 train=0.5712 val=0.5537
[nodo07] fold=2 epoch=12/32 train=0.5737 val=0.5628
[nodo07] fold=2 epoch=13/32 train=0.5726 val=0.5607
[nodo07] fold=2 epoch=14/32 train=0.5612 val=0.5526
[nodo07] fold=2 epoch=15/32 train=0.5713 val=0.5518
[nodo07] fold=2 epoch=16/32 train=0.5621 val=0.5536
[nodo07] fold=2 epoch=17/32 train=0.5591 val=0.5598
[nodo07] fold=2 epoch=18/32 train=0.5324 val=0.5469
[nodo07] fold=2 epoch=19/32 train=0.5806 val=0.5624
[nodo07] fold=2 epoch=20/32 train=0.5495 val=0.5563
[nodo07] fold=2 epoch=21/32 train=0.5425 val=0.5955
[nodo07] fold=2 epoch=22/32 train=0.5265 val=0.5671
[nodo07] fold=2 epoch=23/32 train=0.5622 val=0.5610
[nodo07] fold=2 epoch=24/32 train=0.5310 val=0.5606
[nodo07] fold=2 epoch=25/32 train=0.5135 val=0.5510
[nodo07] fold=2 epoch=26/32 train=0.5252 val=0.5490
[nodo07] fold=2 epoch=27/32 train=0.5108 val=0.5499

[I 2026-08-31 02:04:02,919] Trial 1 finished with value: 0.526610784796341 and parameters: {'dropout': 0.33736718284136136, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 1.8698261938463234, 'augmentation_probability': 0.7935982011508709, 'rotation_degrees': 1.424912319967584, 'learning_rate': 0.00023468160086831781, 'weight_decay': 1.0139295533312985e-05, 'auxiliary_weight': 0.16761014849246753, 'consistency_weight': 0.043237159129940396, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 1 with value: 0.526610784796341.

[nodo07] fold=0 epoch=1/32 train=0.7153 val=0.6157
[nodo07] fold=0 epoch=2/32 train=0.6699 val=0.5694
[nodo07] fold=0 epoch=3/32 train=0.6332 val=0.5677
[nodo07] fold=0 epoch=4/32 train=0.6172 val=0.5530
[nodo07] fold=0 epoch=5/32 train=0.6067 val=0.5345
[nodo07] fold=0 epoch=6/32 train=0.5893 val=0.5327
[nodo07] fold=0 epoch=7/32 train=0.5792 val=0.5275
[nodo07] fold=0 epoch=8/32 train=0.5844 val=0.5220
[nodo07] fold=0 epoch=9/32 train=0.5707 val=0.5163
[nodo07] fold=0 epoch=10/32 train=0.5618 val=0.5121
[nodo07] fold=0 epoch=11/32 train=0.5492 val=0.5355
[nodo07] fold=0 epoch=12/32 train=0.5509 val=0.5170
[nodo07] fold=0 epoch=13/32 train=0.5536 val=0.5111
[nodo07] fold=0 epoch=14/32 train=0.5069 val=0.5187
[nodo07] fold=0 epoch=15/32 train=0.5311 val=0.5125
[nodo07] fold=0 epoch=16/32 train=0.5017 val=0.5219
[nodo07] fold=0 epoch=17/32 train=0.4891 val=0.5238
[nodo07] fold=0 epoch=18/32 train=0.4988 val=0.5286
[nodo07] fold=0 epoch=19/32 train=0.5091 val=0.5207
[nodo07] fold=0 epoch=20/32 train=0.4984 val=0.5177
[nodo07] fold=0 epoch=21/32 train=0.4911 val=0.5123
[nodo07] fold=0 epoch=22/32 train=0.4720 val=0.5194
[nodo07] fold=1 epoch=1/32 train=0.7345 val=0.6331
[nodo07] fold=1 epoch=2/32 train=0.6725 val=0.6171
[nodo07] fold=1 epoch=3/32 train=0.6153 val=0.6158
[nodo07] fold=1 epoch=4/32 train=0.5983 val=0.5870
[nodo07] fold=1 epoch=5/32 train=0.5668 val=0.6014
[nodo07] fold=1 epoch=6/32 train=0.5796 val=0.5804
[nodo07] fold=1 epoch=7/32 train=0.5423 val=0.5715
[nodo07] fold=1 epoch=8/32 train=0.5459 val=0.5609
[nodo07] fold=1 epoch=9/32 train=0.5160 val=0.5889
[nodo07] fold=1 epoch=10/32 train=0.5472 val=0.5496
[nodo07] fold=1 epoch=11/32 train=0.5093 val=0.5871
[nodo07] fold=1 epoch=12/32 train=0.5133 val=0.5708
[nodo07] fold=1 epoch=13/32 train=0.5304 val=0.5636
[nodo07] fold=1 epoch=14/32 train=0.4930 val=0.5859
[nodo07] fold=1 epoch=15/32 train=0.4689 val=0.5982
[nodo07] fold=1 epoch=16/32 train=0.4416 val=0.6182
[nodo07] fold=1 epoch=17/32 train=0.4907 val=0.5963
[nodo07] fold=1 epoch=18/32 train=0.4889 val=0.6016
[nodo07] fold=1 epoch=19/32 train=0.4730 val=0.6045
[nodo07] fold=2 epoch=1/32 train=0.7348 val=0.6270
[nodo07] fold=2 epoch=2/32 train=0.6442 val=0.5766
[nodo07] fold=2 epoch=3/32 train=0.6318 val=0.5812
[nodo07] fold=2 epoch=4/32 train=0.6477 val=0.5880
[nodo07] fold=2 epoch=5/32 train=0.5862 val=0.5694
[nodo07] fold=2 epoch=6/32 train=0.5531 val=0.6213
[nodo07] fold=2 epoch=7/32 train=0.5500 val=0.5803
[nodo07] fold=2 epoch=8/32 train=0.5550 val=0.5685
[nodo07] fold=2 epoch=9/32 train=0.5473 val=0.5702
[nodo07] fold=2 epoch=10/32 train=0.5623 val=0.5767
[nodo07] fold=2 epoch=11/32 train=0.5230 val=0.5527
[nodo07] fold=2 epoch=12/32 train=0.5104 val=0.5927
[nodo07] fold=2 epoch=13/32 train=0.5374 val=0.5531
[nodo07] fold=2 epoch=14/32 train=0.4912 val=0.5720
[nodo07] fold=2 epoch=15/32 train=0.4947 val=0.5923
[nodo07] fold=2 epoch=16/32 train=0.4958 val=0.5684
[nodo07] fold=2 epoch=17/32 train=0.4995 val=0.5724
[nodo07] fold=2 epoch=18/32 train=0.4650 val=0.5725
[nodo07] fold=2 epoch=19/32 train=0.5289 val=0.5751
[nodo07] fold=2 epoch=20/32 train=0.4746 val=0.5740

[I 2026-08-31 02:25:58,724] Trial 2 finished with value: 0.5378051889481661 and parameters: {'dropout': 0.2451053404222632, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.0334476622920667, 'augmentation_probability': 0.7449761715877123, 'rotation_degrees': 1.898426586401027, 'learning_rate': 0.00019167297053759473, 'weight_decay': 2.497389876010352e-06, 'auxiliary_weight': 0.14415136715805948, 'consistency_weight': 0.04097450018638918, 'feature_top_k': 64, 'pca_variance': 'none'}. Best is trial 1 with value: 0.526610784796341.

[nodo07] fold=0 epoch=1/32 train=0.7350 val=0.6736
[nodo07] fold=0 epoch=2/32 train=0.7315 val=0.6663
[nodo07] fold=0 epoch=3/32 train=0.7095 val=0.6416
[nodo07] fold=0 epoch=4/32 train=0.6912 val=0.6349
[nodo07] fold=0 epoch=5/32 train=0.6691 val=0.5851
[nodo07] fold=0 epoch=6/32 train=0.6539 val=0.5799
[nodo07] fold=0 epoch=7/32 train=0.6460 val=0.5843
[nodo07] fold=0 epoch=8/32 train=0.6408 val=0.5628
[nodo07] fold=0 epoch=9/32 train=0.6196 val=0.5502
[nodo07] fold=0 epoch=10/32 train=0.6226 val=0.5572
[nodo07] fold=0 epoch=11/32 train=0.6088 val=0.5678
[nodo07] fold=0 epoch=12/32 train=0.6198 val=0.5516
[nodo07] fold=0 epoch=13/32 train=0.6308 val=0.5361
[nodo07] fold=0 epoch=14/32 train=0.5970 val=0.5415
[nodo07] fold=0 epoch=15/32 train=0.6178 val=0.5493
[nodo07] fold=0 epoch=16/32 train=0.6032 val=0.5482
[nodo07] fold=0 epoch=17/32 train=0.6011 val=0.5508
[nodo07] fold=0 epoch=18/32 train=0.5849 val=0.5400
[nodo07] fold=0 epoch=19/32 train=0.5952 val=0.5335
[nodo07] fold=0 epoch=20/32 train=0.6062 val=0.5379
[nodo07] fold=0 epoch=21/32 train=0.5946 val=0.5350
[nodo07] fold=0 epoch=22/32 train=0.5610 val=0.5273
[nodo07] fold=0 epoch=23/32 train=0.5717 val=0.5242
[nodo07] fold=0 epoch=24/32 train=0.6053 val=0.5243
[nodo07] fold=0 epoch=25/32 train=0.5705 val=0.5264
[nodo07] fold=0 epoch=26/32 train=0.5650 val=0.5367
[nodo07] fold=0 epoch=27/32 train=0.5747 val=0.5242
[nodo07] fold=0 epoch=28/32 train=0.5919 val=0.5225
[nodo07] fold=0 epoch=29/32 train=0.5634 val=0.5256
[nodo07] fold=0 epoch=30/32 train=0.5675 val=0.5257
[nodo07] fold=0 epoch=31/32 train=0.5754 val=0.5256
[nodo07] fold=0 epoch=32/32 train=0.5451 val=0.5255
[nodo07] fold=1 epoch=1/32 train=0.7527 val=0.6715
[nodo07] fold=1 epoch=2/32 train=0.7246 val=0.6586
[nodo07] fold=1 epoch=3/32 train=0.7092 val=0.6848
[nodo07] fold=1 epoch=4/32 train=0.6949 val=0.6225
[nodo07] fold=1 epoch=5/32 train=0.6690 val=0.5903
[nodo07] fold=1 epoch=6/32 train=0.6566 val=0.5982
[nodo07] fold=1 epoch=7/32 train=0.6267 val=0.5802
[nodo07] fold=1 epoch=8/32 train=0.6352 val=0.5828
[nodo07] fold=1 epoch=9/32 train=0.6254 val=0.5705
[nodo07] fold=1 epoch=10/32 train=0.6107 val=0.5721
[nodo07] fold=1 epoch=11/32 train=0.6291 val=0.5732
[nodo07] fold=1 epoch=12/32 train=0.6219 val=0.5704
[nodo07] fold=1 epoch=13/32 train=0.6174 val=0.5728
[nodo07] fold=1 epoch=14/32 train=0.5903 val=0.5735
[nodo07] fold=1 epoch=15/32 train=0.5988 val=0.5695
[nodo07] fold=1 epoch=16/32 train=0.5559 val=0.5685
[nodo07] fold=1 epoch=17/32 train=0.5783 val=0.5778
[nodo07] fold=1 epoch=18/32 train=0.6173 val=0.5629
[nodo07] fold=1 epoch=19/32 train=0.5736 val=0.5795
[nodo07] fold=1 epoch=20/32 train=0.5482 val=0.5852
[nodo07] fold=1 epoch=21/32 train=0.5719 val=0.5898
[nodo07] fold=1 epoch=22/32 train=0.5658 val=0.5767
[nodo07] fold=1 epoch=23/32 train=0.5845 val=0.5733
[nodo07] fold=1 epoch=24/32 train=0.5844 val=0.5703
[nodo07] fold=1 epoch=25/32 train=0.5986 val=0.5648
[nodo07] fold=1 epoch=26/32 train=0.5922 val=0.5686
[nodo07] fold=1 epoch=27/32 train=0.5434 val=0.5682
[nodo07] fold=2 epoch=1/32 train=0.7496 val=0.6748
[nodo07] fold=2 epoch=2/32 train=0.7289 val=0.6556
[nodo07] fold=2 epoch=3/32 train=0.7039 val=0.6418
[nodo07] fold=2 epoch=4/32 train=0.6971 val=0.6261
[nodo07] fold=2 epoch=5/32 train=0.6599 val=0.5832
[nodo07] fold=2 epoch=6/32 train=0.6273 val=0.6049
[nodo07] fold=2 epoch=7/32 train=0.6194 val=0.5774
[nodo07] fold=2 epoch=8/32 train=0.6224 val=0.5616
[nodo07] fold=2 epoch=9/32 train=0.6095 val=0.5923
[nodo07] fold=2 epoch=10/32 train=0.6340 val=0.5630
[nodo07] fold=2 epoch=11/32 train=0.6035 val=0.5566
[nodo07] fold=2 epoch=12/32 train=0.5927 val=0.5792
[nodo07] fold=2 epoch=13/32 train=0.5990 val=0.5688
[nodo07] fold=2 epoch=14/32 train=0.5837 val=0.5646
[nodo07] fold=2 epoch=15/32 train=0.5940 val=0.5815
[nodo07] fold=2 epoch=16/32 train=0.5906 val=0.5695
[nodo07] fold=2 epoch=17/32 train=0.5871 val=0.5794
[nodo07] fold=2 epoch=18/32 train=0.5641 val=0.5709
[nodo07] fold=2 epoch=19/32 train=0.6198 val=0.5655
[nodo07] fold=2 epoch=20/32 train=0.5719 val=0.5591

[I 2026-08-31 02:55:13,976] Trial 3 finished with value: 0.5473182214478062 and parameters: {'dropout': 0.34190514074202627, 'tabular_embedding_dim': 16, 'augmentation_magnitude': 2.0117943809914314, 'augmentation_probability': 0.8332219603274141, 'rotation_degrees': 1.1635275958553704, 'learning_rate': 9.97369665692088e-05, 'weight_decay': 1.3356799490329072e-05, 'auxiliary_weight': 0.1623959454405417, 'consistency_weight': 0.04230043959460177, 'feature_top_k': 64, 'pca_variance': '0.98'}. Best is trial 1 with value: 0.526610784796341.

[nodo07] fold=0 epoch=1/32 train=0.7252 val=0.6458
[nodo07] fold=0 epoch=2/32 train=0.6973 val=0.6151
[nodo07] fold=0 epoch=3/32 train=0.6518 val=0.5793
[nodo07] fold=0 epoch=4/32 train=0.6429 val=0.5757
[nodo07] fold=0 epoch=5/32 train=0.6258 val=0.5570
[nodo07] fold=0 epoch=6/32 train=0.6203 val=0.5593
[nodo07] fold=0 epoch=7/32 train=0.6286 val=0.5557
[nodo07] fold=0 epoch=8/32 train=0.6270 val=0.5462
[nodo07] fold=0 epoch=9/32 train=0.6152 val=0.5420
[nodo07] fold=0 epoch=10/32 train=0.6057 val=0.5400
[nodo07] fold=0 epoch=11/32 train=0.6031 val=0.5562
[nodo07] fold=0 epoch=12/32 train=0.6064 val=0.5550
[nodo07] fold=0 epoch=13/32 train=0.6288 val=0.5376
[nodo07] fold=0 epoch=14/32 train=0.5741 val=0.5365
[nodo07] fold=0 epoch=15/32 train=0.6037 val=0.5485
[nodo07] fold=0 epoch=16/32 train=0.5886 val=0.5514
[nodo07] fold=0 epoch=17/32 train=0.5845 val=0.5395
[nodo07] fold=0 epoch=18/32 train=0.5795 val=0.5335
[nodo07] fold=0 epoch=19/32 train=0.5883 val=0.5306
[nodo07] fold=0 epoch=20/32 train=0.5993 val=0.5321
[nodo07] fold=0 epoch=21/32 train=0.5930 val=0.5366
[nodo07] fold=0 epoch=22/32 train=0.5659 val=0.5269
[nodo07] fold=0 epoch=23/32 train=0.5729 val=0.5277
[nodo07] fold=0 epoch=24/32 train=0.6039 val=0.5254
[nodo07] fold=0 epoch=25/32 train=0.5610 val=0.5270
[nodo07] fold=0 epoch=26/32 train=0.5641 val=0.5292
[nodo07] fold=0 epoch=27/32 train=0.5640 val=0.5276
[nodo07] fold=0 epoch=28/32 train=0.5783 val=0.5263
[nodo07] fold=0 epoch=29/32 train=0.5590 val=0.5276
[nodo07] fold=0 epoch=30/32 train=0.5671 val=0.5274
[nodo07] fold=0 epoch=31/32 train=0.5570 val=0.5276
[nodo07] fold=0 epoch=32/32 train=0.5392 val=0.5275
[nodo07] fold=1 epoch=1/32 train=0.7436 val=0.6604
[nodo07] fold=1 epoch=2/32 train=0.7050 val=0.6666
[nodo07] fold=1 epoch=3/32 train=0.6634 val=0.6314
[nodo07] fold=1 epoch=4/32 train=0.6554 val=0.5868
[nodo07] fold=1 epoch=5/32 train=0.6220 val=0.5922
[nodo07] fold=1 epoch=6/32 train=0.6438 val=0.5851
[nodo07] fold=1 epoch=7/32 train=0.6185 val=0.5701
[nodo07] fold=1 epoch=8/32 train=0.6220 val=0.5704
[nodo07] fold=1 epoch=9/32 train=0.6174 val=0.5661
[nodo07] fold=1 epoch=10/32 train=0.6065 val=0.5743
[nodo07] fold=1 epoch=11/32 train=0.6095 val=0.5688
[nodo07] fold=1 epoch=12/32 train=0.5988 val=0.5635
[nodo07] fold=1 epoch=13/32 train=0.6041 val=0.5706
[nodo07] fold=1 epoch=14/32 train=0.5841 val=0.5682
[nodo07] fold=1 epoch=15/32 train=0.5759 val=0.5789
[nodo07] fold=1 epoch=16/32 train=0.5357 val=0.5786
[nodo07] fold=1 epoch=17/32 train=0.5657 val=0.5767
[nodo07] fold=1 epoch=18/32 train=0.5949 val=0.5624
[nodo07] fold=1 epoch=19/32 train=0.5677 val=0.5780
[nodo07] fold=1 epoch=20/32 train=0.5406 val=0.5839
[nodo07] fold=1 epoch=21/32 train=0.5598 val=0.5767
[nodo07] fold=1 epoch=22/32 train=0.5605 val=0.5719
[nodo07] fold=1 epoch=23/32 train=0.5691 val=0.5691
[nodo07] fold=1 epoch=24/32 train=0.5715 val=0.5715
[nodo07] fold=1 epoch=25/32 train=0.5879 val=0.5635
[nodo07] fold=1 epoch=26/32 train=0.5784 val=0.5628
[nodo07] fold=1 epoch=27/32 train=0.5303 val=0.5675
[nodo07] fold=2 epoch=1/32 train=0.7398 val=0.6698
[nodo07] fold=2 epoch=2/32 train=0.7046 val=0.6290
[nodo07] fold=2 epoch=3/32 train=0.6728 val=0.5997
[nodo07] fold=2 epoch=4/32 train=0.6696 val=0.5997
[nodo07] fold=2 epoch=5/32 train=0.6415 val=0.5761
[nodo07] fold=2 epoch=6/32 train=0.6104 val=0.6001
[nodo07] fold=2 epoch=7/32 train=0.6064 val=0.5716
[nodo07] fold=2 epoch=8/32 train=0.6209 val=0.5633
[nodo07] fold=2 epoch=9/32 train=0.6024 val=0.5712
[nodo07] fold=2 epoch=10/32 train=0.6278 val=0.5604
[nodo07] fold=2 epoch=11/32 train=0.5806 val=0.5535
[nodo07] fold=2 epoch=12/32 train=0.6015 val=0.5595
[nodo07] fold=2 epoch=13/32 train=0.5928 val=0.5513
[nodo07] fold=2 epoch=14/32 train=0.5774 val=0.5593
[nodo07] fold=2 epoch=15/32 train=0.5969 val=0.5627
[nodo07] fold=2 epoch=16/32 train=0.5809 val=0.5501
[nodo07] fold=2 epoch=17/32 train=0.5789 val=0.5507
[nodo07] fold=2 epoch=18/32 train=0.5596 val=0.5515
[nodo07] fold=2 epoch=19/32 train=0.6198 val=0.5580
[nodo07] fold=2 epoch=20/32 train=0.5691 val=0.5546
[nodo07] fold=2 epoch=21/32 train=0.5759 val=0.5708
[nodo07] fold=2 epoch=22/32 train=0.5612 val=0.5539
[nodo07] fold=2 epoch=23/32 train=0.5880 val=0.5610
[nodo07] fold=2 epoch=24/32 train=0.5654 val=0.5507
[nodo07] fold=2 epoch=25/32 train=0.5505 val=0.5477
[nodo07] fold=2 epoch=26/32 train=0.5601 val=0.5487
[nodo07] fold=2 epoch=27/32 train=0.5534 val=0.5494
[nodo07] fold=2 epoch=28/32 train=0.5419 val=0.5491
[nodo07] fold=2 epoch=29/32 train=0.5675 val=0.5470
[nodo07] fold=2 epoch=30/32 train=0.5590 val=0.5487
[nodo07] fold=2 epoch=31/32 train=0.5550 val=0.5484
[nodo07] fold=2 epoch=32/32 train=0.5542 val=0.5485

[I 2026-08-31 03:27:56,431] Trial 4 finished with value: 0.5449402592557796 and parameters: {'dropout': 0.3322227012167345, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.333382929769059, 'augmentation_probability': 0.7952322347706857, 'rotation_degrees': 1.5765713186033294, 'learning_rate': 0.0001430195237388269, 'weight_decay': 9.031798339085021e-07, 'auxiliary_weight': 0.1313207754728502, 'consistency_weight': 0.08019724249678817, 'feature_top_k': 64, 'pca_variance': '0.95'}. Best is trial 1 with value: 0.526610784796341.

[nodo07] fold=0 epoch=1/32 train=0.7403 val=0.6555
[nodo07] fold=0 epoch=2/32 train=0.7230 val=0.6111
[nodo07] fold=0 epoch=3/32 train=0.6745 val=0.5980
[nodo07] fold=0 epoch=4/32 train=0.6592 val=0.5920
[nodo07] fold=0 epoch=5/32 train=0.6373 val=0.5685
[nodo07] fold=0 epoch=6/32 train=0.6348 val=0.5607
[nodo07] fold=0 epoch=7/32 train=0.6259 val=0.5571
[nodo07] fold=0 epoch=8/32 train=0.6267 val=0.5451
[nodo07] fold=0 epoch=9/32 train=0.6134 val=0.5453
[nodo07] fold=0 epoch=10/32 train=0.6098 val=0.5410
[nodo07] fold=0 epoch=11/32 train=0.6006 val=0.5539
[nodo07] fold=0 epoch=12/32 train=0.6108 val=0.5522
[nodo07] fold=0 epoch=13/32 train=0.6258 val=0.5351
[nodo07] fold=0 epoch=14/32 train=0.5769 val=0.5396
[nodo07] fold=0 epoch=15/32 train=0.6030 val=0.5395
[nodo07] fold=0 epoch=16/32 train=0.5864 val=0.5417
[nodo07] fold=0 epoch=17/32 train=0.5730 val=0.5423
[nodo07] fold=0 epoch=18/32 train=0.5801 val=0.5336
[nodo07] fold=0 epoch=19/32 train=0.5832 val=0.5303
[nodo07] fold=0 epoch=20/32 train=0.5860 val=0.5317
[nodo07] fold=0 epoch=21/32 train=0.5784 val=0.5300
[nodo07] fold=0 epoch=22/32 train=0.5491 val=0.5269
[nodo07] fold=0 epoch=23/32 train=0.5502 val=0.5287
[nodo07] fold=0 epoch=24/32 train=0.5828 val=0.5245
[nodo07] fold=0 epoch=25/32 train=0.5502 val=0.5274
[nodo07] fold=0 epoch=26/32 train=0.5428 val=0.5304
[nodo07] fold=0 epoch=27/32 train=0.5592 val=0.5274
[nodo07] fold=0 epoch=28/32 train=0.5710 val=0.5257
[nodo07] fold=0 epoch=29/32 train=0.5419 val=0.5265
[nodo07] fold=0 epoch=30/32 train=0.5541 val=0.5264
[nodo07] fold=0 epoch=31/32 train=0.5626 val=0.5266
[nodo07] fold=0 epoch=32/32 train=0.5208 val=0.5266
[nodo07] fold=1 epoch=1/32 train=0.7505 val=0.6646
[nodo07] fold=1 epoch=2/32 train=0.7141 val=0.6289
[nodo07] fold=1 epoch=3/32 train=0.6688 val=0.6311
[nodo07] fold=1 epoch=4/32 train=0.6558 val=0.6148
[nodo07] fold=1 epoch=5/32 train=0.6315 val=0.5884
[nodo07] fold=1 epoch=6/32 train=0.6305 val=0.5863
[nodo07] fold=1 epoch=7/32 train=0.5967 val=0.5756
[nodo07] fold=1 epoch=8/32 train=0.6003 val=0.5702
[nodo07] fold=1 epoch=9/32 train=0.5704 val=0.5734
[nodo07] fold=1 epoch=10/32 train=0.5865 val=0.5682
[nodo07] fold=1 epoch=11/32 train=0.5745 val=0.5705
[nodo07] fold=1 epoch=12/32 train=0.5635 val=0.5707
[nodo07] fold=1 epoch=13/32 train=0.5830 val=0.5668
[nodo07] fold=1 epoch=14/32 train=0.5426 val=0.5813
[nodo07] fold=1 epoch=15/32 train=0.5401 val=0.5891
[nodo07] fold=1 epoch=16/32 train=0.5119 val=0.5926
[nodo07] fold=1 epoch=17/32 train=0.5410 val=0.5838
[nodo07] fold=1 epoch=18/32 train=0.5588 val=0.5679
[nodo07] fold=1 epoch=19/32 train=0.5336 val=0.5870
[nodo07] fold=1 epoch=20/32 train=0.4947 val=0.6013
[nodo07] fold=1 epoch=21/32 train=0.5278 val=0.5968
[nodo07] fold=1 epoch=22/32 train=0.5193 val=0.5919
[nodo07] fold=2 epoch=1/32 train=0.7471 val=0.6556
[nodo07] fold=2 epoch=2/32 train=0.6913 val=0.5875
[nodo07] fold=2 epoch=3/32 train=0.6569 val=0.5924
[nodo07] fold=2 epoch=4/32 train=0.6710 val=0.5904
[nodo07] fold=2 epoch=5/32 train=0.6290 val=0.5793
[nodo07] fold=2 epoch=6/32 train=0.5994 val=0.6193
[nodo07] fold=2 epoch=7/32 train=0.5917 val=0.5823
[nodo07] fold=2 epoch=8/32 train=0.5999 val=0.5643
[nodo07] fold=2 epoch=9/32 train=0.5879 val=0.5825
[nodo07] fold=2 epoch=10/32 train=0.6077 val=0.5689
[nodo07] fold=2 epoch=11/32 train=0.5808 val=0.5573
[nodo07] fold=2 epoch=12/32 train=0.5683 val=0.5726
[nodo07] fold=2 epoch=13/32 train=0.5798 val=0.5604
[nodo07] fold=2 epoch=14/32 train=0.5617 val=0.5734
[nodo07] fold=2 epoch=15/32 train=0.5681 val=0.5802
[nodo07] fold=2 epoch=16/32 train=0.5596 val=0.5674
[nodo07] fold=2 epoch=17/32 train=0.5642 val=0.5690
[nodo07] fold=2 epoch=18/32 train=0.5423 val=0.5699
[nodo07] fold=2 epoch=19/32 train=0.5962 val=0.5712
[nodo07] fold=2 epoch=20/32 train=0.5458 val=0.5698

[I 2026-08-31 03:54:11,456] Trial 5 finished with value: 0.5495183283423472 and parameters: {'dropout': 0.36457257425933665, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.393699456167611, 'augmentation_probability': 0.8603826972453703, 'rotation_degrees': 0.9715999958155667, 'learning_rate': 0.00010426582883223896, 'weight_decay': 5.7153955880442795e-06, 'auxiliary_weight': 0.1555770455941053, 'consistency_weight': 0.040327217171351376, 'feature_top_k': 64, 'pca_variance': 'none'}. Best is trial 1 with value: 0.526610784796341.

[nodo07] fold=0 epoch=1/32 train=0.7492 val=0.6702
[nodo07] fold=0 epoch=2/32 train=0.7215 val=0.6343
[nodo07] fold=0 epoch=3/32 train=0.6710 val=0.5780
[nodo07] fold=0 epoch=4/32 train=0.6487 val=0.5757
[nodo07] fold=0 epoch=5/32 train=0.6326 val=0.5618
[nodo07] fold=0 epoch=6/32 train=0.6294 val=0.5522
[nodo07] fold=0 epoch=7/32 train=0.6261 val=0.5564
[nodo07] fold=0 epoch=8/32 train=0.6166 val=0.5495
[nodo07] fold=0 epoch=9/32 train=0.6193 val=0.5440
[nodo07] fold=0 epoch=10/32 train=0.6117 val=0.5400
[nodo07] fold=0 epoch=11/32 train=0.6024 val=0.5575
[nodo07] fold=0 epoch=12/32 train=0.6138 val=0.5571
[nodo07] fold=0 epoch=13/32 train=0.6276 val=0.5397
[nodo07] fold=0 epoch=14/32 train=0.5906 val=0.5392
[nodo07] fold=0 epoch=15/32 train=0.6023 val=0.5456
[nodo07] fold=0 epoch=16/32 train=0.5951 val=0.5413
[nodo07] fold=0 epoch=17/32 train=0.5804 val=0.5392
[nodo07] fold=0 epoch=18/32 train=0.5761 val=0.5343
[nodo07] fold=0 epoch=19/32 train=0.5757 val=0.5312
[nodo07] fold=0 epoch=20/32 train=0.5920 val=0.5521
[nodo07] fold=0 epoch=21/32 train=0.5902 val=0.5401
[nodo07] fold=0 epoch=22/32 train=0.5404 val=0.5244
[nodo07] fold=0 epoch=23/32 train=0.5593 val=0.5244
[nodo07] fold=0 epoch=24/32 train=0.5977 val=0.5217
[nodo07] fold=0 epoch=25/32 train=0.5739 val=0.5226
[nodo07] fold=0 epoch=26/32 train=0.5577 val=0.5312
[nodo07] fold=0 epoch=27/32 train=0.5731 val=0.5255
[nodo07] fold=0 epoch=28/32 train=0.5807 val=0.5220
[nodo07] fold=0 epoch=29/32 train=0.5557 val=0.5258
[nodo07] fold=0 epoch=30/32 train=0.5653 val=0.5250
[nodo07] fold=0 epoch=31/32 train=0.5611 val=0.5245
[nodo07] fold=0 epoch=32/32 train=0.5321 val=0.5241
[nodo07] fold=1 epoch=1/32 train=0.7428 val=0.6561
[nodo07] fold=1 epoch=2/32 train=0.7078 val=0.6556
[nodo07] fold=1 epoch=3/32 train=0.6586 val=0.6364
[nodo07] fold=1 epoch=4/32 train=0.6599 val=0.5965
[nodo07] fold=1 epoch=5/32 train=0.6378 val=0.5894
[nodo07] fold=1 epoch=6/32 train=0.6349 val=0.5892
[nodo07] fold=1 epoch=7/32 train=0.6074 val=0.5664
[nodo07] fold=1 epoch=8/32 train=0.6132 val=0.5708
[nodo07] fold=1 epoch=9/32 train=0.6144 val=0.5575
[nodo07] fold=1 epoch=10/32 train=0.6062 val=0.5556
[nodo07] fold=1 epoch=11/32 train=0.6046 val=0.5438
[nodo07] fold=1 epoch=12/32 train=0.6170 val=0.5592
[nodo07] fold=1 epoch=13/32 train=0.6075 val=0.5521
[nodo07] fold=1 epoch=14/32 train=0.5761 val=0.5491
[nodo07] fold=1 epoch=15/32 train=0.5666 val=0.5573
[nodo07] fold=1 epoch=16/32 train=0.5550 val=0.5544
[nodo07] fold=1 epoch=17/32 train=0.5712 val=0.5628
[nodo07] fold=1 epoch=18/32 train=0.6083 val=0.5498
[nodo07] fold=1 epoch=19/32 train=0.5606 val=0.5694
[nodo07] fold=1 epoch=20/32 train=0.5346 val=0.5546
[nodo07] fold=2 epoch=1/32 train=0.7413 val=0.6516
[nodo07] fold=2 epoch=2/32 train=0.6820 val=0.5949
[nodo07] fold=2 epoch=3/32 train=0.6549 val=0.5929
[nodo07] fold=2 epoch=4/32 train=0.6734 val=0.5969
[nodo07] fold=2 epoch=5/32 train=0.6389 val=0.5769
[nodo07] fold=2 epoch=6/32 train=0.6129 val=0.6154
[nodo07] fold=2 epoch=7/32 train=0.6060 val=0.5777
[nodo07] fold=2 epoch=8/32 train=0.6216 val=0.5735
[nodo07] fold=2 epoch=9/32 train=0.6017 val=0.5836
[nodo07] fold=2 epoch=10/32 train=0.6318 val=0.5684
[nodo07] fold=2 epoch=11/32 train=0.5861 val=0.5670
[nodo07] fold=2 epoch=12/32 train=0.6027 val=0.5695
[nodo07] fold=2 epoch=13/32 train=0.5940 val=0.5612
[nodo07] fold=2 epoch=14/32 train=0.5690 val=0.5700
[nodo07] fold=2 epoch=15/32 train=0.5972 val=0.5726
[nodo07] fold=2 epoch=16/32 train=0.5838 val=0.5806
[nodo07] fold=2 epoch=17/32 train=0.5756 val=0.5780
[nodo07] fold=2 epoch=18/32 train=0.5452 val=0.5659
[nodo07] fold=2 epoch=19/32 train=0.6112 val=0.5694
[nodo07] fold=2 epoch=20/32 train=0.5612 val=0.5733
[nodo07] fold=2 epoch=21/32 train=0.5701 val=0.6122
[nodo07] fold=2 epoch=22/32 train=0.5607 val=0.5757

[I 2026-08-31 04:21:06,257] Trial 6 finished with value: 0.5422099223205259 and parameters: {'dropout': 0.24621589969603538, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 1.9988561191748677, 'augmentation_probability': 0.8489729346131216, 'rotation_degrees': 1.851853034502012, 'learning_rate': 0.00018266638948374167, 'weight_decay': 1.377013398103055e-06, 'auxiliary_weight': 0.16687385439013738, 'consistency_weight': 0.06118768911426155, 'feature_top_k': 32, 'pca_variance': '0.95'}. Best is trial 1 with value: 0.526610784796341.

[nodo07] fold=0 epoch=1/32 train=0.7545 val=0.6713
[nodo07] fold=0 epoch=2/32 train=0.7394 val=0.6522
[nodo07] fold=0 epoch=3/32 train=0.7071 val=0.6089
[nodo07] fold=0 epoch=4/32 train=0.6766 val=0.5810
[nodo07] fold=0 epoch=5/32 train=0.6479 val=0.5677
[nodo07] fold=0 epoch=6/32 train=0.6437 val=0.5661
[nodo07] fold=0 epoch=7/32 train=0.6391 val=0.5761
[nodo07] fold=0 epoch=8/32 train=0.6276 val=0.5474
[nodo07] fold=0 epoch=9/32 train=0.6346 val=0.5452
[nodo07] fold=0 epoch=10/32 train=0.6228 val=0.5366
[nodo07] fold=0 epoch=11/32 train=0.6079 val=0.5676
[nodo07] fold=0 epoch=12/32 train=0.6167 val=0.5410
[nodo07] fold=0 epoch=13/32 train=0.6279 val=0.5298
[nodo07] fold=0 epoch=14/32 train=0.5840 val=0.5316
[nodo07] fold=0 epoch=15/32 train=0.6009 val=0.5394
[nodo07] fold=0 epoch=16/32 train=0.5913 val=0.5303
[nodo07] fold=0 epoch=17/32 train=0.5838 val=0.5368
[nodo07] fold=0 epoch=18/32 train=0.5704 val=0.5318
[nodo07] fold=0 epoch=19/32 train=0.5783 val=0.5210
[nodo07] fold=0 epoch=20/32 train=0.6011 val=0.5344
[nodo07] fold=0 epoch=21/32 train=0.5909 val=0.5258
[nodo07] fold=0 epoch=22/32 train=0.5517 val=0.5146
[nodo07] fold=0 epoch=23/32 train=0.5572 val=0.5131
[nodo07] fold=0 epoch=24/32 train=0.5926 val=0.5107
[nodo07] fold=0 epoch=25/32 train=0.5669 val=0.5098
[nodo07] fold=0 epoch=26/32 train=0.5601 val=0.5245
[nodo07] fold=0 epoch=27/32 train=0.5773 val=0.5106
[nodo07] fold=0 epoch=28/32 train=0.5810 val=0.5099
[nodo07] fold=0 epoch=29/32 train=0.5558 val=0.5127
[nodo07] fold=0 epoch=30/32 train=0.5670 val=0.5137
[nodo07] fold=0 epoch=31/32 train=0.5651 val=0.5136
[nodo07] fold=0 epoch=32/32 train=0.5271 val=0.5133
[nodo07] fold=1 epoch=1/32 train=0.7592 val=0.6628
[nodo07] fold=1 epoch=2/32 train=0.7192 val=0.6542
[nodo07] fold=1 epoch=3/32 train=0.6734 val=0.6266
[nodo07] fold=1 epoch=4/32 train=0.6615 val=0.5898
[nodo07] fold=1 epoch=5/32 train=0.6369 val=0.5786
[nodo07] fold=1 epoch=6/32 train=0.6449 val=0.5911
[nodo07] fold=1 epoch=7/32 train=0.6129 val=0.5756
[nodo07] fold=1 epoch=8/32 train=0.6218 val=0.5644
[nodo07] fold=1 epoch=9/32 train=0.6053 val=0.5680
[nodo07] fold=1 epoch=10/32 train=0.6226 val=0.5761
[nodo07] fold=1 epoch=11/32 train=0.6087 val=0.5609
[nodo07] fold=1 epoch=12/32 train=0.6126 val=0.5681
[nodo07] fold=1 epoch=13/32 train=0.6102 val=0.5604
[nodo07] fold=1 epoch=14/32 train=0.5794 val=0.5674
[nodo07] fold=1 epoch=15/32 train=0.5779 val=0.5669
[nodo07] fold=1 epoch=16/32 train=0.5623 val=0.5642
[nodo07] fold=1 epoch=17/32 train=0.5606 val=0.5657
[nodo07] fold=1 epoch=18/32 train=0.5970 val=0.5546
[nodo07] fold=1 epoch=19/32 train=0.5465 val=0.5829
[nodo07] fold=1 epoch=20/32 train=0.5453 val=0.5704
[nodo07] fold=1 epoch=21/32 train=0.5572 val=0.5698
[nodo07] fold=1 epoch=22/32 train=0.5576 val=0.5548
[nodo07] fold=1 epoch=23/32 train=0.5561 val=0.5551
[nodo07] fold=1 epoch=24/32 train=0.5585 val=0.5573
[nodo07] fold=1 epoch=25/32 train=0.5697 val=0.5491
[nodo07] fold=1 epoch=26/32 train=0.5679 val=0.5516
[nodo07] fold=1 epoch=27/32 train=0.5445 val=0.5535
[nodo07] fold=1 epoch=28/32 train=0.5955 val=0.5503
[nodo07] fold=1 epoch=29/32 train=0.5585 val=0.5511
[nodo07] fold=1 epoch=30/32 train=0.5787 val=0.5495
[nodo07] fold=1 epoch=31/32 train=0.5530 val=0.5506
[nodo07] fold=1 epoch=32/32 train=0.5550 val=0.5507
[nodo07] fold=2 epoch=1/32 train=0.7657 val=0.6843
[nodo07] fold=2 epoch=2/32 train=0.7390 val=0.6459
[nodo07] fold=2 epoch=3/32 train=0.6965 val=0.6028
[nodo07] fold=2 epoch=4/32 train=0.6834 val=0.5953
[nodo07] fold=2 epoch=5/32 train=0.6480 val=0.5761
[nodo07] fold=2 epoch=6/32 train=0.6161 val=0.6115
[nodo07] fold=2 epoch=7/32 train=0.6182 val=0.5698
[nodo07] fold=2 epoch=8/32 train=0.6184 val=0.5629
[nodo07] fold=2 epoch=9/32 train=0.6071 val=0.5779
[nodo07] fold=2 epoch=10/32 train=0.6182 val=0.5595
[nodo07] fold=2 epoch=11/32 train=0.5823 val=0.5553
[nodo07] fold=2 epoch=12/32 train=0.5956 val=0.5696
[nodo07] fold=2 epoch=13/32 train=0.5831 val=0.5574
[nodo07] fold=2 epoch=14/32 train=0.5667 val=0.5570
[nodo07] fold=2 epoch=15/32 train=0.5802 val=0.5451
[nodo07] fold=2 epoch=16/32 train=0.5714 val=0.5665
[nodo07] fold=2 epoch=17/32 train=0.5720 val=0.5589
[nodo07] fold=2 epoch=18/32 train=0.5368 val=0.5467
[nodo07] fold=2 epoch=19/32 train=0.5993 val=0.5554
[nodo07] fold=2 epoch=20/32 train=0.5511 val=0.5548
[nodo07] fold=2 epoch=21/32 train=0.5534 val=0.5894
[nodo07] fold=2 epoch=22/32 train=0.5345 val=0.5568
[nodo07] fold=2 epoch=23/32 train=0.5638 val=0.5676
[nodo07] fold=2 epoch=24/32 train=0.5431 val=0.5597

[I 2026-08-31 04:52:17,349] Trial 7 finished with value: 0.5346982911107144 and parameters: {'dropout': 0.2908187196819846, 'tabular_embedding_dim': 16, 'augmentation_magnitude': 1.9073206737196347, 'augmentation_probability': 0.7596862000450263, 'rotation_degrees': 2.0760553635594015, 'learning_rate': 0.00018177977364521765, 'weight_decay': 1.2945864772815934e-06, 'auxiliary_weight': 0.18746180689573327, 'consistency_weight': 0.05538670223672111, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 1 with value: 0.526610784796341.

[nodo07] fold=0 epoch=1/32 train=0.7414 val=0.6620
[nodo07] fold=0 epoch=2/32 train=0.7148 val=0.6218
[nodo07] fold=0 epoch=3/32 train=0.6592 val=0.5833
[nodo07] fold=0 epoch=4/32 train=0.6414 val=0.5787
[nodo07] fold=0 epoch=5/32 train=0.6378 val=0.5571
[nodo07] fold=0 epoch=6/32 train=0.6332 val=0.5574
[nodo07] fold=0 epoch=7/32 train=0.6341 val=0.5533
[nodo07] fold=0 epoch=8/32 train=0.6196 val=0.5425
[nodo07] fold=0 epoch=9/32 train=0.6224 val=0.5413
[nodo07] fold=0 epoch=10/32 train=0.6186 val=0.5416
[nodo07] fold=0 epoch=11/32 train=0.6049 val=0.5542
[nodo07] fold=0 epoch=12/32 train=0.6121 val=0.5586
[nodo07] fold=0 epoch=13/32 train=0.6285 val=0.5406
[nodo07] fold=0 epoch=14/32 train=0.5864 val=0.5393
[nodo07] fold=0 epoch=15/32 train=0.5954 val=0.5556
[nodo07] fold=0 epoch=16/32 train=0.5917 val=0.5503
[nodo07] fold=0 epoch=17/32 train=0.5830 val=0.5475
[nodo07] fold=0 epoch=18/32 train=0.5837 val=0.5380
[nodo07] fold=0 epoch=19/32 train=0.5741 val=0.5338
[nodo07] fold=0 epoch=20/32 train=0.5992 val=0.5401
[nodo07] fold=0 epoch=21/32 train=0.5846 val=0.5339
[nodo07] fold=0 epoch=22/32 train=0.5476 val=0.5290
[nodo07] fold=0 epoch=23/32 train=0.5532 val=0.5309
[nodo07] fold=0 epoch=24/32 train=0.5975 val=0.5273
[nodo07] fold=0 epoch=25/32 train=0.5757 val=0.5296
[nodo07] fold=0 epoch=26/32 train=0.5683 val=0.5349
[nodo07] fold=0 epoch=27/32 train=0.5757 val=0.5305
[nodo07] fold=0 epoch=28/32 train=0.5770 val=0.5289
[nodo07] fold=0 epoch=29/32 train=0.5606 val=0.5310
[nodo07] fold=0 epoch=30/32 train=0.5749 val=0.5310
[nodo07] fold=0 epoch=31/32 train=0.5559 val=0.5308
[nodo07] fold=0 epoch=32/32 train=0.5361 val=0.5307
[nodo07] fold=1 epoch=1/32 train=0.7424 val=0.6569
[nodo07] fold=1 epoch=2/32 train=0.7072 val=0.6458
[nodo07] fold=1 epoch=3/32 train=0.6529 val=0.6447
[nodo07] fold=1 epoch=4/32 train=0.6558 val=0.5971
[nodo07] fold=1 epoch=5/32 train=0.6294 val=0.5933
[nodo07] fold=1 epoch=6/32 train=0.6383 val=0.5930
[nodo07] fold=1 epoch=7/32 train=0.6143 val=0.5709
[nodo07] fold=1 epoch=8/32 train=0.6227 val=0.5655
[nodo07] fold=1 epoch=9/32 train=0.6100 val=0.5614
[nodo07] fold=1 epoch=10/32 train=0.6103 val=0.5692
[nodo07] fold=1 epoch=11/32 train=0.6139 val=0.5505
[nodo07] fold=1 epoch=12/32 train=0.6166 val=0.5736
[nodo07] fold=1 epoch=13/32 train=0.6092 val=0.5557
[nodo07] fold=1 epoch=14/32 train=0.5795 val=0.5516
[nodo07] fold=1 epoch=15/32 train=0.5804 val=0.5729
[nodo07] fold=1 epoch=16/32 train=0.5570 val=0.5666
[nodo07] fold=1 epoch=17/32 train=0.5706 val=0.5575
[nodo07] fold=1 epoch=18/32 train=0.6079 val=0.5654
[nodo07] fold=1 epoch=19/32 train=0.5634 val=0.5693
[nodo07] fold=1 epoch=20/32 train=0.5336 val=0.5646
[nodo07] fold=2 epoch=1/32 train=0.7420 val=0.6522
[nodo07] fold=2 epoch=2/32 train=0.6850 val=0.5933
[nodo07] fold=2 epoch=3/32 train=0.6592 val=0.5894
[nodo07] fold=2 epoch=4/32 train=0.6725 val=0.5944
[nodo07] fold=2 epoch=5/32 train=0.6439 val=0.5792
[nodo07] fold=2 epoch=6/32 train=0.6162 val=0.6092
[nodo07] fold=2 epoch=7/32 train=0.6119 val=0.5785
[nodo07] fold=2 epoch=8/32 train=0.6236 val=0.5649
[nodo07] fold=2 epoch=9/32 train=0.6058 val=0.5739
[nodo07] fold=2 epoch=10/32 train=0.6288 val=0.5658
[nodo07] fold=2 epoch=11/32 train=0.5838 val=0.5639
[nodo07] fold=2 epoch=12/32 train=0.6029 val=0.5707
[nodo07] fold=2 epoch=13/32 train=0.5967 val=0.5655
[nodo07] fold=2 epoch=14/32 train=0.5772 val=0.5641
[nodo07] fold=2 epoch=15/32 train=0.6029 val=0.5708
[nodo07] fold=2 epoch=16/32 train=0.5899 val=0.5623
[nodo07] fold=2 epoch=17/32 train=0.5891 val=0.5560
[nodo07] fold=2 epoch=18/32 train=0.5439 val=0.5638
[nodo07] fold=2 epoch=19/32 train=0.6190 val=0.5547
[nodo07] fold=2 epoch=20/32 train=0.5802 val=0.5571
[nodo07] fold=2 epoch=21/32 train=0.5821 val=0.5860
[nodo07] fold=2 epoch=22/32 train=0.5656 val=0.5614
[nodo07] fold=2 epoch=23/32 train=0.5900 val=0.5636
[nodo07] fold=2 epoch=24/32 train=0.5634 val=0.5572
[nodo07] fold=2 epoch=25/32 train=0.5502 val=0.5536
[nodo07] fold=2 epoch=26/32 train=0.5622 val=0.5513
[nodo07] fold=2 epoch=27/32 train=0.5546 val=0.5523
[nodo07] fold=2 epoch=28/32 train=0.5376 val=0.5538
[nodo07] fold=2 epoch=29/32 train=0.5615 val=0.5528
[nodo07] fold=2 epoch=30/32 train=0.5505 val=0.5527
[nodo07] fold=2 epoch=31/32 train=0.5521 val=0.5523
[nodo07] fold=2 epoch=32/32 train=0.5501 val=0.5524

[I 2026-08-31 05:21:58,720] Trial 8 finished with value: 0.5430187051861028 and parameters: {'dropout': 0.3693917178103092, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 1.8684268493493554, 'augmentation_probability': 0.8074467013292352, 'rotation_degrees': 1.4293941902019327, 'learning_rate': 0.00023529049924237886, 'weight_decay': 2.2339515233823593e-06, 'auxiliary_weight': 0.14724757620716042, 'consistency_weight': 0.04182712934659705, 'feature_top_k': 32, 'pca_variance': '0.95'}. Best is trial 1 with value: 0.526610784796341.

[nodo07] fold=0 epoch=1/32 train=0.7152 val=0.6537
[nodo07] fold=0 epoch=2/32 train=0.6655 val=0.5856
[nodo07] fold=0 epoch=3/32 train=0.6257 val=0.5645
[nodo07] fold=0 epoch=4/32 train=0.6208 val=0.5595
[nodo07] fold=0 epoch=5/32 train=0.6113 val=0.5396
[nodo07] fold=0 epoch=6/32 train=0.6067 val=0.5402
[nodo07] fold=0 epoch=7/32 train=0.6135 val=0.5303
[nodo07] fold=0 epoch=8/32 train=0.5944 val=0.5228
[nodo07] fold=0 epoch=9/32 train=0.5972 val=0.5166
[nodo07] fold=0 epoch=10/32 train=0.5831 val=0.5161
[nodo07] fold=0 epoch=11/32 train=0.5738 val=0.5287
[nodo07] fold=0 epoch=12/32 train=0.5858 val=0.5247
[nodo07] fold=0 epoch=13/32 train=0.5875 val=0.5035
[nodo07] fold=0 epoch=14/32 train=0.5441 val=0.5103
[nodo07] fold=0 epoch=15/32 train=0.5710 val=0.5177
[nodo07] fold=0 epoch=16/32 train=0.5410 val=0.5100
[nodo07] fold=0 epoch=17/32 train=0.5182 val=0.5062
[nodo07] fold=0 epoch=18/32 train=0.5300 val=0.5025
[nodo07] fold=0 epoch=19/32 train=0.5404 val=0.5034
[nodo07] fold=0 epoch=20/32 train=0.5500 val=0.5009
[nodo07] fold=0 epoch=21/32 train=0.5372 val=0.4980
[nodo07] fold=0 epoch=22/32 train=0.5226 val=0.5015
[nodo07] fold=0 epoch=23/32 train=0.5184 val=0.5037
[nodo07] fold=0 epoch=24/32 train=0.5394 val=0.5009
[nodo07] fold=0 epoch=25/32 train=0.5221 val=0.5043
[nodo07] fold=0 epoch=26/32 train=0.5002 val=0.5062
[nodo07] fold=0 epoch=27/32 train=0.5119 val=0.5053
[nodo07] fold=0 epoch=28/32 train=0.5430 val=0.5032
[nodo07] fold=0 epoch=29/32 train=0.4979 val=0.5056
[nodo07] fold=0 epoch=30/32 train=0.5114 val=0.5053
[nodo07] fold=1 epoch=1/32 train=0.7330 val=0.6460
[nodo07] fold=1 epoch=2/32 train=0.6914 val=0.6259
[nodo07] fold=1 epoch=3/32 train=0.6417 val=0.6395
[nodo07] fold=1 epoch=4/32 train=0.6389 val=0.5917
[nodo07] fold=1 epoch=5/32 train=0.6281 val=0.5838
[nodo07] fold=1 epoch=6/32 train=0.6234 val=0.5876
[nodo07] fold=1 epoch=7/32 train=0.5930 val=0.5635
[nodo07] fold=1 epoch=8/32 train=0.5907 val=0.5544
[nodo07] fold=1 epoch=9/32 train=0.5716 val=0.5585
[nodo07] fold=1 epoch=10/32 train=0.5875 val=0.5616
[nodo07] fold=1 epoch=11/32 train=0.5781 val=0.5557
[nodo07] fold=1 epoch=12/32 train=0.5850 val=0.5544
[nodo07] fold=1 epoch=13/32 train=0.5825 val=0.5470
[nodo07] fold=1 epoch=14/32 train=0.5525 val=0.5503
[nodo07] fold=1 epoch=15/32 train=0.5574 val=0.5582
[nodo07] fold=1 epoch=16/32 train=0.5293 val=0.5602
[nodo07] fold=1 epoch=17/32 train=0.5409 val=0.5477
[nodo07] fold=1 epoch=18/32 train=0.5784 val=0.5411
[nodo07] fold=1 epoch=19/32 train=0.5375 val=0.5509
[nodo07] fold=1 epoch=20/32 train=0.5098 val=0.5527
[nodo07] fold=1 epoch=21/32 train=0.5382 val=0.5356
[nodo07] fold=1 epoch=22/32 train=0.5271 val=0.5370
[nodo07] fold=1 epoch=23/32 train=0.5409 val=0.5300
[nodo07] fold=1 epoch=24/32 train=0.5332 val=0.5324
[nodo07] fold=1 epoch=25/32 train=0.5496 val=0.5275
[nodo07] fold=1 epoch=26/32 train=0.5280 val=0.5285
[nodo07] fold=1 epoch=27/32 train=0.4975 val=0.5341
[nodo07] fold=1 epoch=28/32 train=0.5607 val=0.5288
[nodo07] fold=1 epoch=29/32 train=0.5306 val=0.5285
[nodo07] fold=1 epoch=30/32 train=0.5437 val=0.5276
[nodo07] fold=1 epoch=31/32 train=0.5322 val=0.5280
[nodo07] fold=1 epoch=32/32 train=0.5378 val=0.5280
[nodo07] fold=2 epoch=1/32 train=0.7510 val=0.6626
[nodo07] fold=2 epoch=2/32 train=0.6731 val=0.5882
[nodo07] fold=2 epoch=3/32 train=0.6428 val=0.5853
[nodo07] fold=2 epoch=4/32 train=0.6619 val=0.5932
[nodo07] fold=2 epoch=5/32 train=0.6238 val=0.5701
[nodo07] fold=2 epoch=6/32 train=0.5920 val=0.6277
[nodo07] fold=2 epoch=7/32 train=0.5897 val=0.5741
[nodo07] fold=2 epoch=8/32 train=0.5984 val=0.5729
[nodo07] fold=2 epoch=9/32 train=0.5797 val=0.5810
[nodo07] fold=2 epoch=10/32 train=0.6020 val=0.5652
[nodo07] fold=2 epoch=11/32 train=0.5586 val=0.5554
[nodo07] fold=2 epoch=12/32 train=0.5633 val=0.5723
[nodo07] fold=2 epoch=13/32 train=0.5636 val=0.5620
[nodo07] fold=2 epoch=14/32 train=0.5473 val=0.5607
[nodo07] fold=2 epoch=15/32 train=0.5564 val=0.5565
[nodo07] fold=2 epoch=16/32 train=0.5553 val=0.5666
[nodo07] fold=2 epoch=17/32 train=0.5442 val=0.5670
[nodo07] fold=2 epoch=18/32 train=0.5127 val=0.5548
[nodo07] fold=2 epoch=19/32 train=0.5702 val=0.5617
[nodo07] fold=2 epoch=20/32 train=0.5365 val=0.5549
[nodo07] fold=2 epoch=21/32 train=0.5311 val=0.5894
[nodo07] fold=2 epoch=22/32 train=0.5162 val=0.5631
[nodo07] fold=2 epoch=23/32 train=0.5545 val=0.5593
[nodo07] fold=2 epoch=24/32 train=0.5166 val=0.5567
[nodo07] fold=2 epoch=25/32 train=0.4963 val=0.5549
[nodo07] fold=2 epoch=26/32 train=0.5162 val=0.5468
[nodo07] fold=2 epoch=27/32 train=0.5042 val=0.5467
[nodo07] fold=2 epoch=28/32 train=0.4862 val=0.5518
[nodo07] fold=2 epoch=29/32 train=0.5297 val=0.5515
[nodo07] fold=2 epoch=30/32 train=0.5247 val=0.5529
[nodo07] fold=2 epoch=31/32 train=0.5174 val=0.5513
[nodo07] fold=2 epoch=32/32 train=0.5162 val=0.5518

[I 2026-08-31 05:56:10,588] Trial 9 finished with value: 0.5240601584208706 and parameters: {'dropout': 0.31199034171252765, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 1.8853143902232394, 'augmentation_probability': 0.7882067479834647, 'rotation_degrees': 1.3715293004437705, 'learning_rate': 0.00023898554182056632, 'weight_decay': 1.853168861655518e-05, 'auxiliary_weight': 0.12726924105313958, 'consistency_weight': 0.032263775427849195, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 9 with value: 0.5240601584208706.

[nodo07] fold=0 epoch=1/32 train=0.7325 val=0.6594
[nodo07] fold=0 epoch=2/32 train=0.7059 val=0.6346
[nodo07] fold=0 epoch=3/32 train=0.6579 val=0.5724
[nodo07] fold=0 epoch=4/32 train=0.6361 val=0.5914
[nodo07] fold=0 epoch=5/32 train=0.6247 val=0.5591
[nodo07] fold=0 epoch=6/32 train=0.6217 val=0.5541
[nodo07] fold=0 epoch=7/32 train=0.6209 val=0.5610
[nodo07] fold=0 epoch=8/32 train=0.6116 val=0.5450
[nodo07] fold=0 epoch=9/32 train=0.6089 val=0.5450
[nodo07] fold=0 epoch=10/32 train=0.6033 val=0.5432
[nodo07] fold=0 epoch=11/32 train=0.5942 val=0.5545
[nodo07] fold=0 epoch=12/32 train=0.6030 val=0.5622
[nodo07] fold=0 epoch=13/32 train=0.6248 val=0.5421
[nodo07] fold=0 epoch=14/32 train=0.5808 val=0.5433
[nodo07] fold=0 epoch=15/32 train=0.5923 val=0.5481
[nodo07] fold=0 epoch=16/32 train=0.5872 val=0.5464
[nodo07] fold=0 epoch=17/32 train=0.5745 val=0.5535
[nodo07] fold=0 epoch=18/32 train=0.5734 val=0.5401
[nodo07] fold=0 epoch=19/32 train=0.5594 val=0.5375
[nodo07] fold=0 epoch=20/32 train=0.5870 val=0.5447
[nodo07] fold=0 epoch=21/32 train=0.5751 val=0.5346
[nodo07] fold=0 epoch=22/32 train=0.5386 val=0.5315
[nodo07] fold=0 epoch=23/32 train=0.5457 val=0.5282
[nodo07] fold=0 epoch=24/32 train=0.5919 val=0.5292
[nodo07] fold=0 epoch=25/32 train=0.5682 val=0.5292
[nodo07] fold=0 epoch=26/32 train=0.5525 val=0.5363
[nodo07] fold=0 epoch=27/32 train=0.5696 val=0.5321
[nodo07] fold=0 epoch=28/32 train=0.5716 val=0.5309
[nodo07] fold=0 epoch=29/32 train=0.5514 val=0.5325
[nodo07] fold=0 epoch=30/32 train=0.5631 val=0.5321
[nodo07] fold=0 epoch=31/32 train=0.5454 val=0.5321
[nodo07] fold=0 epoch=32/32 train=0.5243 val=0.5319
[nodo07] fold=1 epoch=1/32 train=0.7279 val=0.6623
[nodo07] fold=1 epoch=2/32 train=0.6991 val=0.6525
[nodo07] fold=1 epoch=3/32 train=0.6502 val=0.6300
[nodo07] fold=1 epoch=4/32 train=0.6535 val=0.5978
[nodo07] fold=1 epoch=5/32 train=0.6270 val=0.5949
[nodo07] fold=1 epoch=6/32 train=0.6293 val=0.6007
[nodo07] fold=1 epoch=7/32 train=0.6077 val=0.5726
[nodo07] fold=1 epoch=8/32 train=0.6160 val=0.5784
[nodo07] fold=1 epoch=9/32 train=0.6151 val=0.5618
[nodo07] fold=1 epoch=10/32 train=0.6065 val=0.5685
[nodo07] fold=1 epoch=11/32 train=0.6113 val=0.5591
[nodo07] fold=1 epoch=12/32 train=0.6066 val=0.5717
[nodo07] fold=1 epoch=13/32 train=0.6062 val=0.5606
[nodo07] fold=1 epoch=14/32 train=0.5754 val=0.5543
[nodo07] fold=1 epoch=15/32 train=0.5725 val=0.5610
[nodo07] fold=1 epoch=16/32 train=0.5486 val=0.5639
[nodo07] fold=1 epoch=17/32 train=0.5687 val=0.5584
[nodo07] fold=1 epoch=18/32 train=0.6102 val=0.5646
[nodo07] fold=1 epoch=19/32 train=0.5600 val=0.5670
[nodo07] fold=1 epoch=20/32 train=0.5349 val=0.5647
[nodo07] fold=1 epoch=21/32 train=0.5537 val=0.5637
[nodo07] fold=1 epoch=22/32 train=0.5477 val=0.5514
[nodo07] fold=1 epoch=23/32 train=0.5579 val=0.5461
[nodo07] fold=1 epoch=24/32 train=0.5538 val=0.5506
[nodo07] fold=1 epoch=25/32 train=0.5647 val=0.5480
[nodo07] fold=1 epoch=26/32 train=0.5664 val=0.5504
[nodo07] fold=1 epoch=27/32 train=0.5310 val=0.5476
[nodo07] fold=1 epoch=28/32 train=0.5919 val=0.5465
[nodo07] fold=1 epoch=29/32 train=0.5495 val=0.5451
[nodo07] fold=1 epoch=30/32 train=0.5734 val=0.5439
[nodo07] fold=1 epoch=31/32 train=0.5490 val=0.5441
[nodo07] fold=1 epoch=32/32 train=0.5569 val=0.5442
[nodo07] fold=2 epoch=1/32 train=0.7281 val=0.6584
[nodo07] fold=2 epoch=2/32 train=0.6777 val=0.5993
[nodo07] fold=2 epoch=3/32 train=0.6386 val=0.5974
[nodo07] fold=2 epoch=4/32 train=0.6576 val=0.5969
[nodo07] fold=2 epoch=5/32 train=0.6267 val=0.5799
[nodo07] fold=2 epoch=6/32 train=0.5994 val=0.6151
[nodo07] fold=2 epoch=7/32 train=0.5950 val=0.5826
[nodo07] fold=2 epoch=8/32 train=0.6142 val=0.5687
[nodo07] fold=2 epoch=9/32 train=0.5877 val=0.5839
[nodo07] fold=2 epoch=10/32 train=0.6149 val=0.5653
[nodo07] fold=2 epoch=11/32 train=0.5736 val=0.5704
[nodo07] fold=2 epoch=12/32 train=0.5901 val=0.5685
[nodo07] fold=2 epoch=13/32 train=0.5834 val=0.5601
[nodo07] fold=2 epoch=14/32 train=0.5592 val=0.5634
[nodo07] fold=2 epoch=15/32 train=0.5832 val=0.5648
[nodo07] fold=2 epoch=16/32 train=0.5741 val=0.5705
[nodo07] fold=2 epoch=17/32 train=0.5727 val=0.5610
[nodo07] fold=2 epoch=18/32 train=0.5331 val=0.5601
[nodo07] fold=2 epoch=19/32 train=0.6045 val=0.5647
[nodo07] fold=2 epoch=20/32 train=0.5557 val=0.5635
[nodo07] fold=2 epoch=21/32 train=0.5611 val=0.6126
[nodo07] fold=2 epoch=22/32 train=0.5569 val=0.5717
[nodo07] fold=2 epoch=23/32 train=0.5733 val=0.5829
[nodo07] fold=2 epoch=24/32 train=0.5582 val=0.5655
[nodo07] fold=2 epoch=25/32 train=0.5343 val=0.5530
[nodo07] fold=2 epoch=26/32 train=0.5530 val=0.5540
[nodo07] fold=2 epoch=27/32 train=0.5391 val=0.5528
[nodo07] fold=2 epoch=28/32 train=0.5196 val=0.5547
[nodo07] fold=2 epoch=29/32 train=0.5497 val=0.5537
[nodo07] fold=2 epoch=30/32 train=0.5395 val=0.5542
[nodo07] fold=2 epoch=31/32 train=0.5405 val=0.5533
[nodo07] fold=2 epoch=32/32 train=0.5402 val=0.5533

[I 2026-08-31 06:29:16,067] Trial 10 finished with value: 0.5416365576893232 and parameters: {'dropout': 0.31094106853759396, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.083072087348988, 'augmentation_probability': 0.8328131946493081, 'rotation_degrees': 1.100338441235612, 'learning_rate': 0.00019662712358210757, 'weight_decay': 1.8439516233456516e-05, 'auxiliary_weight': 0.1117489870347059, 'consistency_weight': 0.03268229711867995, 'feature_top_k': 32, 'pca_variance': '0.95'}. Best is trial 9 with value: 0.5240601584208706.

[nodo07] fold=0 epoch=1/32 train=0.7359 val=0.6583
[nodo07] fold=0 epoch=2/32 train=0.7026 val=0.6129
[nodo07] fold=0 epoch=3/32 train=0.6465 val=0.5698
[nodo07] fold=0 epoch=4/32 train=0.6351 val=0.5675
[nodo07] fold=0 epoch=5/32 train=0.6265 val=0.5524
[nodo07] fold=0 epoch=6/32 train=0.6239 val=0.5499
[nodo07] fold=0 epoch=7/32 train=0.6302 val=0.5506
[nodo07] fold=0 epoch=8/32 train=0.6082 val=0.5316
[nodo07] fold=0 epoch=9/32 train=0.6064 val=0.5289
[nodo07] fold=0 epoch=10/32 train=0.6013 val=0.5271
[nodo07] fold=0 epoch=11/32 train=0.5904 val=0.5397
[nodo07] fold=0 epoch=12/32 train=0.6033 val=0.5300
[nodo07] fold=0 epoch=13/32 train=0.6096 val=0.5113
[nodo07] fold=0 epoch=14/32 train=0.5627 val=0.5128
[nodo07] fold=0 epoch=15/32 train=0.5939 val=0.5257
[nodo07] fold=0 epoch=16/32 train=0.5649 val=0.5293
[nodo07] fold=0 epoch=17/32 train=0.5398 val=0.5233
[nodo07] fold=0 epoch=18/32 train=0.5485 val=0.5108
[nodo07] fold=0 epoch=19/32 train=0.5638 val=0.5091
[nodo07] fold=0 epoch=20/32 train=0.5690 val=0.5072
[nodo07] fold=0 epoch=21/32 train=0.5607 val=0.5040
[nodo07] fold=0 epoch=22/32 train=0.5416 val=0.5017
[nodo07] fold=0 epoch=23/32 train=0.5376 val=0.5046
[nodo07] fold=0 epoch=24/32 train=0.5585 val=0.4999
[nodo07] fold=0 epoch=25/32 train=0.5437 val=0.5040
[nodo07] fold=0 epoch=26/32 train=0.5223 val=0.5103
[nodo07] fold=0 epoch=27/32 train=0.5395 val=0.5043
[nodo07] fold=0 epoch=28/32 train=0.5646 val=0.5013
[nodo07] fold=0 epoch=29/32 train=0.5242 val=0.5051
[nodo07] fold=0 epoch=30/32 train=0.5402 val=0.5048
[nodo07] fold=0 epoch=31/32 train=0.5283 val=0.5049
[nodo07] fold=0 epoch=32/32 train=0.4975 val=0.5050
[nodo07] fold=1 epoch=1/32 train=0.7513 val=0.6590
[nodo07] fold=1 epoch=2/32 train=0.7125 val=0.6375
[nodo07] fold=1 epoch=3/32 train=0.6628 val=0.6448
[nodo07] fold=1 epoch=4/32 train=0.6666 val=0.6063
[nodo07] fold=1 epoch=5/32 train=0.6487 val=0.5950
[nodo07] fold=1 epoch=6/32 train=0.6441 val=0.6011
[nodo07] fold=1 epoch=7/32 train=0.6138 val=0.5708
[nodo07] fold=1 epoch=8/32 train=0.6099 val=0.5686
[nodo07] fold=1 epoch=9/32 train=0.5961 val=0.5638
[nodo07] fold=1 epoch=10/32 train=0.6076 val=0.5602
[nodo07] fold=1 epoch=11/32 train=0.6055 val=0.5521
[nodo07] fold=1 epoch=12/32 train=0.6015 val=0.5512
[nodo07] fold=1 epoch=13/32 train=0.6010 val=0.5458
[nodo07] fold=1 epoch=14/32 train=0.5675 val=0.5553
[nodo07] fold=1 epoch=15/32 train=0.5747 val=0.5695
[nodo07] fold=1 epoch=16/32 train=0.5434 val=0.5584
[nodo07] fold=1 epoch=17/32 train=0.5584 val=0.5546
[nodo07] fold=1 epoch=18/32 train=0.6034 val=0.5470
[nodo07] fold=1 epoch=19/32 train=0.5582 val=0.5562
[nodo07] fold=1 epoch=20/32 train=0.5262 val=0.5626
[nodo07] fold=1 epoch=21/32 train=0.5577 val=0.5475
[nodo07] fold=1 epoch=22/32 train=0.5477 val=0.5439
[nodo07] fold=1 epoch=23/32 train=0.5551 val=0.5409
[nodo07] fold=1 epoch=24/32 train=0.5528 val=0.5461
[nodo07] fold=1 epoch=25/32 train=0.5693 val=0.5410
[nodo07] fold=1 epoch=26/32 train=0.5466 val=0.5413
[nodo07] fold=1 epoch=27/32 train=0.5169 val=0.5428
[nodo07] fold=1 epoch=28/32 train=0.5786 val=0.5384
[nodo07] fold=1 epoch=29/32 train=0.5472 val=0.5403
[nodo07] fold=1 epoch=30/32 train=0.5651 val=0.5394
[nodo07] fold=1 epoch=31/32 train=0.5625 val=0.5397
[nodo07] fold=1 epoch=32/32 train=0.5554 val=0.5398
[nodo07] fold=2 epoch=1/32 train=0.7743 val=0.6796
[nodo07] fold=2 epoch=2/32 train=0.7091 val=0.5954
[nodo07] fold=2 epoch=3/32 train=0.6649 val=0.5872
[nodo07] fold=2 epoch=4/32 train=0.6794 val=0.5976
[nodo07] fold=2 epoch=5/32 train=0.6447 val=0.5765
[nodo07] fold=2 epoch=6/32 train=0.6153 val=0.6228
[nodo07] fold=2 epoch=7/32 train=0.6042 val=0.5754
[nodo07] fold=2 epoch=8/32 train=0.6180 val=0.5663
[nodo07] fold=2 epoch=9/32 train=0.5984 val=0.5835
[nodo07] fold=2 epoch=10/32 train=0.6200 val=0.5619
[nodo07] fold=2 epoch=11/32 train=0.5845 val=0.5574
[nodo07] fold=2 epoch=12/32 train=0.5812 val=0.5774
[nodo07] fold=2 epoch=13/32 train=0.5837 val=0.5614
[nodo07] fold=2 epoch=14/32 train=0.5637 val=0.5693
[nodo07] fold=2 epoch=15/32 train=0.5798 val=0.5655
[nodo07] fold=2 epoch=16/32 train=0.5704 val=0.5874
[nodo07] fold=2 epoch=17/32 train=0.5669 val=0.5634
[nodo07] fold=2 epoch=18/32 train=0.5351 val=0.5590
[nodo07] fold=2 epoch=19/32 train=0.5903 val=0.5619
[nodo07] fold=2 epoch=20/32 train=0.5550 val=0.5586

[I 2026-08-31 06:58:42,711] Trial 11 finished with value: 0.5319120850949459 and parameters: {'dropout': 0.31549426931995733, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 1.954435529925191, 'augmentation_probability': 0.7739739855353223, 'rotation_degrees': 1.302814516557131, 'learning_rate': 0.00018583510639994815, 'weight_decay': 2.487102742901439e-05, 'auxiliary_weight': 0.17622958781567122, 'consistency_weight': 0.05290274304488414, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 9 with value: 0.5240601584208706.

[nodo07] fold=0 epoch=1/32 train=0.7207 val=0.6577
[nodo07] fold=0 epoch=2/32 train=0.6815 val=0.5905
[nodo07] fold=0 epoch=3/32 train=0.6313 val=0.5805
[nodo07] fold=0 epoch=4/32 train=0.6328 val=0.5638
[nodo07] fold=0 epoch=5/32 train=0.6092 val=0.5532
[nodo07] fold=0 epoch=6/32 train=0.5983 val=0.5399
[nodo07] fold=0 epoch=7/32 train=0.6062 val=0.5346
[nodo07] fold=0 epoch=8/32 train=0.5988 val=0.5256
[nodo07] fold=0 epoch=9/32 train=0.5891 val=0.5225
[nodo07] fold=0 epoch=10/32 train=0.5806 val=0.5171
[nodo07] fold=0 epoch=11/32 train=0.5620 val=0.5250
[nodo07] fold=0 epoch=12/32 train=0.5812 val=0.5245
[nodo07] fold=0 epoch=13/32 train=0.5885 val=0.5089
[nodo07] fold=0 epoch=14/32 train=0.5424 val=0.5144
[nodo07] fold=0 epoch=15/32 train=0.5674 val=0.5118
[nodo07] fold=0 epoch=16/32 train=0.5497 val=0.5180
[nodo07] fold=0 epoch=17/32 train=0.5317 val=0.5184
[nodo07] fold=0 epoch=18/32 train=0.5329 val=0.5144
[nodo07] fold=0 epoch=19/32 train=0.5401 val=0.5101
[nodo07] fold=0 epoch=20/32 train=0.5457 val=0.5063
[nodo07] fold=0 epoch=21/32 train=0.5422 val=0.5060
[nodo07] fold=0 epoch=22/32 train=0.5162 val=0.5080
[nodo07] fold=0 epoch=23/32 train=0.5175 val=0.5088
[nodo07] fold=0 epoch=24/32 train=0.5436 val=0.5057
[nodo07] fold=0 epoch=25/32 train=0.5219 val=0.5081
[nodo07] fold=0 epoch=26/32 train=0.5048 val=0.5096
[nodo07] fold=0 epoch=27/32 train=0.5246 val=0.5067
[nodo07] fold=0 epoch=28/32 train=0.5389 val=0.5058
[nodo07] fold=0 epoch=29/32 train=0.5094 val=0.5082
[nodo07] fold=0 epoch=30/32 train=0.5281 val=0.5077
[nodo07] fold=0 epoch=31/32 train=0.5103 val=0.5077
[nodo07] fold=0 epoch=32/32 train=0.4867 val=0.5077
[nodo07] fold=1 epoch=1/32 train=0.7238 val=0.6317
[nodo07] fold=1 epoch=2/32 train=0.6849 val=0.6308
[nodo07] fold=1 epoch=3/32 train=0.6321 val=0.6368
[nodo07] fold=1 epoch=4/32 train=0.6306 val=0.5946
[nodo07] fold=1 epoch=5/32 train=0.6163 val=0.5813
[nodo07] fold=1 epoch=6/32 train=0.6243 val=0.5843
[nodo07] fold=1 epoch=7/32 train=0.5819 val=0.5699
[nodo07] fold=1 epoch=8/32 train=0.5911 val=0.5601
[nodo07] fold=1 epoch=9/32 train=0.5739 val=0.5606
[nodo07] fold=1 epoch=10/32 train=0.5949 val=0.5583
[nodo07] fold=1 epoch=11/32 train=0.5790 val=0.5617
[nodo07] fold=1 epoch=12/32 train=0.5781 val=0.5658
[nodo07] fold=1 epoch=13/32 train=0.5880 val=0.5627
[nodo07] fold=1 epoch=14/32 train=0.5524 val=0.5581
[nodo07] fold=1 epoch=15/32 train=0.5626 val=0.5671
[nodo07] fold=1 epoch=16/32 train=0.5410 val=0.5641
[nodo07] fold=1 epoch=17/32 train=0.5504 val=0.5653
[nodo07] fold=1 epoch=18/32 train=0.5841 val=0.5449
[nodo07] fold=1 epoch=19/32 train=0.5397 val=0.5676
[nodo07] fold=1 epoch=20/32 train=0.5107 val=0.5660
[nodo07] fold=1 epoch=21/32 train=0.5395 val=0.5681
[nodo07] fold=1 epoch=22/32 train=0.5373 val=0.5531
[nodo07] fold=1 epoch=23/32 train=0.5479 val=0.5481
[nodo07] fold=1 epoch=24/32 train=0.5356 val=0.5493
[nodo07] fold=1 epoch=25/32 train=0.5597 val=0.5458
[nodo07] fold=1 epoch=26/32 train=0.5358 val=0.5441
[nodo07] fold=1 epoch=27/32 train=0.5023 val=0.5527
[nodo07] fold=1 epoch=28/32 train=0.5649 val=0.5499
[nodo07] fold=1 epoch=29/32 train=0.5302 val=0.5477
[nodo07] fold=1 epoch=30/32 train=0.5514 val=0.5458
[nodo07] fold=1 epoch=31/32 train=0.5488 val=0.5462
[nodo07] fold=1 epoch=32/32 train=0.5316 val=0.5463
[nodo07] fold=2 epoch=1/32 train=0.7293 val=0.6328
[nodo07] fold=2 epoch=2/32 train=0.6554 val=0.5934
[nodo07] fold=2 epoch=3/32 train=0.6286 val=0.5932
[nodo07] fold=2 epoch=4/32 train=0.6562 val=0.5924
[nodo07] fold=2 epoch=5/32 train=0.6186 val=0.5766
[nodo07] fold=2 epoch=6/32 train=0.5901 val=0.6190
[nodo07] fold=2 epoch=7/32 train=0.5921 val=0.5782
[nodo07] fold=2 epoch=8/32 train=0.5957 val=0.5704
[nodo07] fold=2 epoch=9/32 train=0.5810 val=0.5856
[nodo07] fold=2 epoch=10/32 train=0.6032 val=0.5649
[nodo07] fold=2 epoch=11/32 train=0.5650 val=0.5655
[nodo07] fold=2 epoch=12/32 train=0.5630 val=0.5770
[nodo07] fold=2 epoch=13/32 train=0.5684 val=0.5647
[nodo07] fold=2 epoch=14/32 train=0.5443 val=0.5697
[nodo07] fold=2 epoch=15/32 train=0.5544 val=0.5728
[nodo07] fold=2 epoch=16/32 train=0.5644 val=0.5696
[nodo07] fold=2 epoch=17/32 train=0.5388 val=0.5811
[nodo07] fold=2 epoch=18/32 train=0.5207 val=0.5697
[nodo07] fold=2 epoch=19/32 train=0.5735 val=0.5722
[nodo07] fold=2 epoch=20/32 train=0.5295 val=0.5788
[nodo07] fold=2 epoch=21/32 train=0.5272 val=0.6010
[nodo07] fold=2 epoch=22/32 train=0.5218 val=0.5861

[I 2026-08-31 07:28:38,805] Trial 12 finished with value: 0.5381898877862988 and parameters: {'dropout': 0.2720089796030242, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 1.883720520454854, 'augmentation_probability': 0.8126302270618891, 'rotation_degrees': 1.1150313216532681, 'learning_rate': 0.0001802525932740821, 'weight_decay': 5.860733020612282e-06, 'auxiliary_weight': 0.11521461813054075, 'consistency_weight': 0.037070080457767204, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 9 with value: 0.5240601584208706.

[nodo07] fold=0 epoch=1/32 train=0.7166 val=0.6551
[nodo07] fold=0 epoch=2/32 train=0.6972 val=0.6369
[nodo07] fold=0 epoch=3/32 train=0.6611 val=0.5855
[nodo07] fold=0 epoch=4/32 train=0.6308 val=0.5709
[nodo07] fold=0 epoch=5/32 train=0.6230 val=0.5625
[nodo07] fold=0 epoch=6/32 train=0.6237 val=0.5642
[nodo07] fold=0 epoch=7/32 train=0.6316 val=0.5545
[nodo07] fold=0 epoch=8/32 train=0.6085 val=0.5420
[nodo07] fold=0 epoch=9/32 train=0.6072 val=0.5379
[nodo07] fold=0 epoch=10/32 train=0.6039 val=0.5367
[nodo07] fold=0 epoch=11/32 train=0.5890 val=0.5538
[nodo07] fold=0 epoch=12/32 train=0.6070 val=0.5459
[nodo07] fold=0 epoch=13/32 train=0.6175 val=0.5270
[nodo07] fold=0 epoch=14/32 train=0.5732 val=0.5265
[nodo07] fold=0 epoch=15/32 train=0.5962 val=0.5337
[nodo07] fold=0 epoch=16/32 train=0.5685 val=0.5324
[nodo07] fold=0 epoch=17/32 train=0.5509 val=0.5339
[nodo07] fold=0 epoch=18/32 train=0.5508 val=0.5281
[nodo07] fold=0 epoch=19/32 train=0.5686 val=0.5178
[nodo07] fold=0 epoch=20/32 train=0.5811 val=0.5207
[nodo07] fold=0 epoch=21/32 train=0.5729 val=0.5201
[nodo07] fold=0 epoch=22/32 train=0.5482 val=0.5154
[nodo07] fold=0 epoch=23/32 train=0.5409 val=0.5143
[nodo07] fold=0 epoch=24/32 train=0.5708 val=0.5127
[nodo07] fold=0 epoch=25/32 train=0.5514 val=0.5136
[nodo07] fold=0 epoch=26/32 train=0.5353 val=0.5164
[nodo07] fold=0 epoch=27/32 train=0.5427 val=0.5133
[nodo07] fold=0 epoch=28/32 train=0.5721 val=0.5109
[nodo07] fold=0 epoch=29/32 train=0.5350 val=0.5130
[nodo07] fold=0 epoch=30/32 train=0.5473 val=0.5134
[nodo07] fold=0 epoch=31/32 train=0.5410 val=0.5133
[nodo07] fold=0 epoch=32/32 train=0.5026 val=0.5133
[nodo07] fold=1 epoch=1/32 train=0.7318 val=0.6588
[nodo07] fold=1 epoch=2/32 train=0.7068 val=0.6421
[nodo07] fold=1 epoch=3/32 train=0.6616 val=0.6474
[nodo07] fold=1 epoch=4/32 train=0.6583 val=0.6091
[nodo07] fold=1 epoch=5/32 train=0.6434 val=0.6001
[nodo07] fold=1 epoch=6/32 train=0.6484 val=0.6197
[nodo07] fold=1 epoch=7/32 train=0.6224 val=0.5868
[nodo07] fold=1 epoch=8/32 train=0.6097 val=0.5719
[nodo07] fold=1 epoch=9/32 train=0.5990 val=0.5680
[nodo07] fold=1 epoch=10/32 train=0.6040 val=0.5704
[nodo07] fold=1 epoch=11/32 train=0.6117 val=0.5540
[nodo07] fold=1 epoch=12/32 train=0.5996 val=0.5620
[nodo07] fold=1 epoch=13/32 train=0.6008 val=0.5559
[nodo07] fold=1 epoch=14/32 train=0.5665 val=0.5563
[nodo07] fold=1 epoch=15/32 train=0.5725 val=0.5695
[nodo07] fold=1 epoch=16/32 train=0.5443 val=0.5613
[nodo07] fold=1 epoch=17/32 train=0.5669 val=0.5700
[nodo07] fold=1 epoch=18/32 train=0.6010 val=0.5489
[nodo07] fold=1 epoch=19/32 train=0.5594 val=0.5750
[nodo07] fold=1 epoch=20/32 train=0.5384 val=0.5647
[nodo07] fold=1 epoch=21/32 train=0.5567 val=0.5513
[nodo07] fold=1 epoch=22/32 train=0.5530 val=0.5469
[nodo07] fold=1 epoch=23/32 train=0.5611 val=0.5443
[nodo07] fold=1 epoch=24/32 train=0.5610 val=0.5471
[nodo07] fold=1 epoch=25/32 train=0.5666 val=0.5404
[nodo07] fold=1 epoch=26/32 train=0.5574 val=0.5431
[nodo07] fold=1 epoch=27/32 train=0.5277 val=0.5470
[nodo07] fold=1 epoch=28/32 train=0.5826 val=0.5400
[nodo07] fold=1 epoch=29/32 train=0.5533 val=0.5402
[nodo07] fold=1 epoch=30/32 train=0.5718 val=0.5394
[nodo07] fold=1 epoch=31/32 train=0.5724 val=0.5397
[nodo07] fold=1 epoch=32/32 train=0.5646 val=0.5397
[nodo07] fold=2 epoch=1/32 train=0.7547 val=0.6805
[nodo07] fold=2 epoch=2/32 train=0.7001 val=0.6070
[nodo07] fold=2 epoch=3/32 train=0.6575 val=0.5922
[nodo07] fold=2 epoch=4/32 train=0.6653 val=0.5940
[nodo07] fold=2 epoch=5/32 train=0.6323 val=0.5790
[nodo07] fold=2 epoch=6/32 train=0.6032 val=0.6164
[nodo07] fold=2 epoch=7/32 train=0.5949 val=0.5759
[nodo07] fold=2 epoch=8/32 train=0.6143 val=0.5721
[nodo07] fold=2 epoch=9/32 train=0.5943 val=0.5892
[nodo07] fold=2 epoch=10/32 train=0.6217 val=0.5692
[nodo07] fold=2 epoch=11/32 train=0.5771 val=0.5648
[nodo07] fold=2 epoch=12/32 train=0.5783 val=0.5737
[nodo07] fold=2 epoch=13/32 train=0.5837 val=0.5742
[nodo07] fold=2 epoch=14/32 train=0.5690 val=0.5742
[nodo07] fold=2 epoch=15/32 train=0.5821 val=0.5697
[nodo07] fold=2 epoch=16/32 train=0.5700 val=0.5794
[nodo07] fold=2 epoch=17/32 train=0.5641 val=0.5734
[nodo07] fold=2 epoch=18/32 train=0.5410 val=0.5679
[nodo07] fold=2 epoch=19/32 train=0.5940 val=0.5652
[nodo07] fold=2 epoch=20/32 train=0.5537 val=0.5632
[nodo07] fold=2 epoch=21/32 train=0.5576 val=0.5990
[nodo07] fold=2 epoch=22/32 train=0.5385 val=0.5779
[nodo07] fold=2 epoch=23/32 train=0.5736 val=0.5837
[nodo07] fold=2 epoch=24/32 train=0.5410 val=0.5643
[nodo07] fold=2 epoch=25/32 train=0.5246 val=0.5607
[nodo07] fold=2 epoch=26/32 train=0.5396 val=0.5590
[nodo07] fold=2 epoch=27/32 train=0.5245 val=0.5637
[nodo07] fold=2 epoch=28/32 train=0.5120 val=0.5657
[nodo07] fold=2 epoch=29/32 train=0.5522 val=0.5645
[nodo07] fold=2 epoch=30/32 train=0.5377 val=0.5653
[nodo07] fold=2 epoch=31/32 train=0.5339 val=0.5640
[nodo07] fold=2 epoch=32/32 train=0.5439 val=0.5643

[I 2026-08-31 08:01:17,498] Trial 13 finished with value: 0.5364164481852051 and parameters: {'dropout': 0.340921537323421, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 1.8667227514179974, 'augmentation_probability': 0.7478616957847763, 'rotation_degrees': 1.3447404750149514, 'learning_rate': 0.00014537271914183942, 'weight_decay': 2.0271626657735692e-05, 'auxiliary_weight': 0.1145119947043757, 'consistency_weight': 0.04710645387891107, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 9 with value: 0.5240601584208706.

[nodo07] fold=0 epoch=1/32 train=0.7067 val=0.5746
[nodo07] fold=0 epoch=2/32 train=0.6369 val=0.5463
[nodo07] fold=0 epoch=3/32 train=0.6167 val=0.5301
[nodo07] fold=0 epoch=4/32 train=0.5896 val=0.5124
[nodo07] fold=0 epoch=5/32 train=0.5673 val=0.5115
[nodo07] fold=0 epoch=6/32 train=0.5467 val=0.5078
[nodo07] fold=0 epoch=7/32 train=0.5259 val=0.5181
[nodo07] fold=0 epoch=8/32 train=0.5036 val=0.5244
[nodo07] fold=0 epoch=9/32 train=0.5053 val=0.5285
[nodo07] fold=0 epoch=10/32 train=0.5005 val=0.5131
[nodo07] fold=0 epoch=11/32 train=0.4564 val=0.5385
[nodo07] fold=0 epoch=12/32 train=0.4678 val=0.5283
[nodo07] fold=0 epoch=13/32 train=0.4519 val=0.5439
[nodo07] fold=0 epoch=14/32 train=0.4212 val=0.5547
[nodo07] fold=0 epoch=15/32 train=0.4290 val=0.5456
[nodo07] fold=1 epoch=1/32 train=0.7267 val=0.6134
[nodo07] fold=1 epoch=2/32 train=0.6591 val=0.5968
[nodo07] fold=1 epoch=3/32 train=0.5899 val=0.6149
[nodo07] fold=1 epoch=4/32 train=0.5831 val=0.5821
[nodo07] fold=1 epoch=5/32 train=0.5472 val=0.5845
[nodo07] fold=1 epoch=6/32 train=0.5703 val=0.5674
[nodo07] fold=1 epoch=7/32 train=0.5012 val=0.5884
[nodo07] fold=1 epoch=8/32 train=0.4824 val=0.5922
[nodo07] fold=1 epoch=9/32 train=0.4680 val=0.6217
[nodo07] fold=1 epoch=10/32 train=0.4757 val=0.5712
[nodo07] fold=1 epoch=11/32 train=0.4715 val=0.5975
[nodo07] fold=1 epoch=12/32 train=0.4562 val=0.6027
[nodo07] fold=1 epoch=13/32 train=0.4420 val=0.6169
[nodo07] fold=1 epoch=14/32 train=0.4172 val=0.6351
[nodo07] fold=1 epoch=15/32 train=0.3789 val=0.6577
[nodo07] fold=2 epoch=1/32 train=0.7256 val=0.6011
[nodo07] fold=2 epoch=2/32 train=0.6305 val=0.5664
[nodo07] fold=2 epoch=3/32 train=0.6025 val=0.5708
[nodo07] fold=2 epoch=4/32 train=0.6221 val=0.5675
[nodo07] fold=2 epoch=5/32 train=0.5729 val=0.5548
[nodo07] fold=2 epoch=6/32 train=0.5193 val=0.6056
[nodo07] fold=2 epoch=7/32 train=0.4896 val=0.5824
[nodo07] fold=2 epoch=8/32 train=0.5084 val=0.5937
[nodo07] fold=2 epoch=9/32 train=0.4781 val=0.6105
[nodo07] fold=2 epoch=10/32 train=0.4738 val=0.6050
[nodo07] fold=2 epoch=11/32 train=0.4424 val=0.6073
[nodo07] fold=2 epoch=12/32 train=0.4340 val=0.6231
[nodo07] fold=2 epoch=13/32 train=0.4567 val=0.6097
[nodo07] fold=2 epoch=14/32 train=0.4163 val=0.6291

[I 2026-08-31 08:16:53,434] Trial 14 finished with value: 0.5433374672314882 and parameters: {'dropout': 0.28665246502556296, 'tabular_embedding_dim': 16, 'augmentation_magnitude': 1.8331633784902068, 'augmentation_probability': 0.8305116213064706, 'rotation_degrees': 1.5198023348348257, 'learning_rate': 0.00021822222017091317, 'weight_decay': 1.502886036988253e-05, 'auxiliary_weight': 0.13908072271639144, 'consistency_weight': 0.0416948402202532, 'feature_top_k': 128, 'pca_variance': 'none'}. Best is trial 9 with value: 0.5240601584208706.

[nodo07] fold=0 epoch=1/32 train=0.7336 val=0.6628
[nodo07] fold=0 epoch=2/32 train=0.7093 val=0.6313
[nodo07] fold=0 epoch=3/32 train=0.6606 val=0.5900
[nodo07] fold=0 epoch=4/32 train=0.6389 val=0.5832
[nodo07] fold=0 epoch=5/32 train=0.6239 val=0.5628
[nodo07] fold=0 epoch=6/32 train=0.6150 val=0.5659
[nodo07] fold=0 epoch=7/32 train=0.6210 val=0.5603
[nodo07] fold=0 epoch=8/32 train=0.6127 val=0.5478
[nodo07] fold=0 epoch=9/32 train=0.6143 val=0.5459
[nodo07] fold=0 epoch=10/32 train=0.5961 val=0.5429
[nodo07] fold=0 epoch=11/32 train=0.5888 val=0.5526
[nodo07] fold=0 epoch=12/32 train=0.5998 val=0.5554
[nodo07] fold=0 epoch=13/32 train=0.6089 val=0.5354
[nodo07] fold=0 epoch=14/32 train=0.5614 val=0.5350
[nodo07] fold=0 epoch=15/32 train=0.5861 val=0.5426
[nodo07] fold=0 epoch=16/32 train=0.5668 val=0.5419
[nodo07] fold=0 epoch=17/32 train=0.5615 val=0.5403
[nodo07] fold=0 epoch=18/32 train=0.5533 val=0.5282
[nodo07] fold=0 epoch=19/32 train=0.5581 val=0.5260
[nodo07] fold=0 epoch=20/32 train=0.5782 val=0.5277
[nodo07] fold=0 epoch=21/32 train=0.5735 val=0.5260
[nodo07] fold=0 epoch=22/32 train=0.5256 val=0.5217
[nodo07] fold=0 epoch=23/32 train=0.5353 val=0.5215
[nodo07] fold=0 epoch=24/32 train=0.5726 val=0.5205
[nodo07] fold=0 epoch=25/32 train=0.5520 val=0.5211
[nodo07] fold=0 epoch=26/32 train=0.5457 val=0.5251
[nodo07] fold=0 epoch=27/32 train=0.5590 val=0.5218
[nodo07] fold=0 epoch=28/32 train=0.5519 val=0.5201
[nodo07] fold=0 epoch=29/32 train=0.5363 val=0.5216
[nodo07] fold=0 epoch=30/32 train=0.5464 val=0.5217
[nodo07] fold=0 epoch=31/32 train=0.5385 val=0.5219
[nodo07] fold=0 epoch=32/32 train=0.5125 val=0.5218
[nodo07] fold=1 epoch=1/32 train=0.7314 val=0.6587
[nodo07] fold=1 epoch=2/32 train=0.6869 val=0.6226
[nodo07] fold=1 epoch=3/32 train=0.6313 val=0.6154
[nodo07] fold=1 epoch=4/32 train=0.6245 val=0.5894
[nodo07] fold=1 epoch=5/32 train=0.6131 val=0.5821
[nodo07] fold=1 epoch=6/32 train=0.6162 val=0.5990
[nodo07] fold=1 epoch=7/32 train=0.5943 val=0.5679
[nodo07] fold=1 epoch=8/32 train=0.5910 val=0.5691
[nodo07] fold=1 epoch=9/32 train=0.5863 val=0.5624
[nodo07] fold=1 epoch=10/32 train=0.6005 val=0.5701
[nodo07] fold=1 epoch=11/32 train=0.5946 val=0.5615
[nodo07] fold=1 epoch=12/32 train=0.5880 val=0.5662
[nodo07] fold=1 epoch=13/32 train=0.5935 val=0.5518
[nodo07] fold=1 epoch=14/32 train=0.5624 val=0.5561
[nodo07] fold=1 epoch=15/32 train=0.5595 val=0.5658
[nodo07] fold=1 epoch=16/32 train=0.5500 val=0.5568
[nodo07] fold=1 epoch=17/32 train=0.5456 val=0.5583
[nodo07] fold=1 epoch=18/32 train=0.5768 val=0.5532
[nodo07] fold=1 epoch=19/32 train=0.5389 val=0.5743
[nodo07] fold=1 epoch=20/32 train=0.5237 val=0.5592
[nodo07] fold=1 epoch=21/32 train=0.5441 val=0.5605
[nodo07] fold=1 epoch=22/32 train=0.5435 val=0.5526
[nodo07] fold=2 epoch=1/32 train=0.7369 val=0.6734
[nodo07] fold=2 epoch=2/32 train=0.6814 val=0.6012
[nodo07] fold=2 epoch=3/32 train=0.6449 val=0.5949
[nodo07] fold=2 epoch=4/32 train=0.6480 val=0.6001
[nodo07] fold=2 epoch=5/32 train=0.6138 val=0.5629
[nodo07] fold=2 epoch=6/32 train=0.5815 val=0.6015
[nodo07] fold=2 epoch=7/32 train=0.5896 val=0.5672
[nodo07] fold=2 epoch=8/32 train=0.5879 val=0.5538
[nodo07] fold=2 epoch=9/32 train=0.5751 val=0.5814
[nodo07] fold=2 epoch=10/32 train=0.5851 val=0.5493
[nodo07] fold=2 epoch=11/32 train=0.5540 val=0.5522
[nodo07] fold=2 epoch=12/32 train=0.5625 val=0.5772
[nodo07] fold=2 epoch=13/32 train=0.5650 val=0.5503
[nodo07] fold=2 epoch=14/32 train=0.5336 val=0.5556
[nodo07] fold=2 epoch=15/32 train=0.5505 val=0.5561
[nodo07] fold=2 epoch=16/32 train=0.5539 val=0.5670
[nodo07] fold=2 epoch=17/32 train=0.5491 val=0.5579
[nodo07] fold=2 epoch=18/32 train=0.5130 val=0.5490
[nodo07] fold=2 epoch=19/32 train=0.5758 val=0.5550
[nodo07] fold=2 epoch=20/32 train=0.5254 val=0.5532
[nodo07] fold=2 epoch=21/32 train=0.5325 val=0.5950
[nodo07] fold=2 epoch=22/32 train=0.5205 val=0.5615
[nodo07] fold=2 epoch=23/32 train=0.5463 val=0.5656
[nodo07] fold=2 epoch=24/32 train=0.5178 val=0.5625
[nodo07] fold=2 epoch=25/32 train=0.5001 val=0.5514
[nodo07] fold=2 epoch=26/32 train=0.5236 val=0.5457
[nodo07] fold=2 epoch=27/32 train=0.5159 val=0.5470
[nodo07] fold=2 epoch=28/32 train=0.5035 val=0.5470
[nodo07] fold=2 epoch=29/32 train=0.5271 val=0.5493
[nodo07] fold=2 epoch=30/32 train=0.5158 val=0.5509
[nodo07] fold=2 epoch=31/32 train=0.5101 val=0.5499
[nodo07] fold=2 epoch=32/32 train=0.5065 val=0.5502

[I 2026-08-31 08:47:03,195] Trial 15 finished with value: 0.5391864696202665 and parameters: {'dropout': 0.26247768993622606, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 1.9755125178132935, 'augmentation_probability': 0.8121603179434765, 'rotation_degrees': 1.9064010356730379, 'learning_rate': 0.00019549439686486174, 'weight_decay': 1.9247083863826918e-05, 'auxiliary_weight': 0.10397289447944794, 'consistency_weight': 0.03655094202204423, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 9 with value: 0.5240601584208706.

[nodo07] fold=0 epoch=1/32 train=0.7555 val=0.6714
[nodo07] fold=0 epoch=2/32 train=0.7309 val=0.6278
[nodo07] fold=0 epoch=3/32 train=0.6734 val=0.5875
[nodo07] fold=0 epoch=4/32 train=0.6556 val=0.5851
[nodo07] fold=0 epoch=5/32 train=0.6395 val=0.5675
[nodo07] fold=0 epoch=6/32 train=0.6373 val=0.5614
[nodo07] fold=0 epoch=7/32 train=0.6379 val=0.5543
[nodo07] fold=0 epoch=8/32 train=0.6187 val=0.5508
[nodo07] fold=0 epoch=9/32 train=0.6301 val=0.5423
[nodo07] fold=0 epoch=10/32 train=0.6139 val=0.5395
[nodo07] fold=0 epoch=11/32 train=0.5952 val=0.5505
[nodo07] fold=0 epoch=12/32 train=0.6171 val=0.5426
[nodo07] fold=0 epoch=13/32 train=0.6239 val=0.5312
[nodo07] fold=0 epoch=14/32 train=0.5770 val=0.5316
[nodo07] fold=0 epoch=15/32 train=0.6034 val=0.5361
[nodo07] fold=0 epoch=16/32 train=0.5866 val=0.5422
[nodo07] fold=0 epoch=17/32 train=0.5695 val=0.5378
[nodo07] fold=0 epoch=18/32 train=0.5721 val=0.5306
[nodo07] fold=0 epoch=19/32 train=0.5707 val=0.5257
[nodo07] fold=0 epoch=20/32 train=0.5930 val=0.5256
[nodo07] fold=0 epoch=21/32 train=0.5868 val=0.5280
[nodo07] fold=0 epoch=22/32 train=0.5463 val=0.5234
[nodo07] fold=0 epoch=23/32 train=0.5489 val=0.5211
[nodo07] fold=0 epoch=24/32 train=0.5836 val=0.5194
[nodo07] fold=0 epoch=25/32 train=0.5691 val=0.5227
[nodo07] fold=0 epoch=26/32 train=0.5660 val=0.5256
[nodo07] fold=0 epoch=27/32 train=0.5692 val=0.5210
[nodo07] fold=0 epoch=28/32 train=0.5713 val=0.5205
[nodo07] fold=0 epoch=29/32 train=0.5555 val=0.5218
[nodo07] fold=0 epoch=30/32 train=0.5652 val=0.5217
[nodo07] fold=0 epoch=31/32 train=0.5499 val=0.5218
[nodo07] fold=0 epoch=32/32 train=0.5297 val=0.5218
[nodo07] fold=1 epoch=1/32 train=0.7567 val=0.6605
[nodo07] fold=1 epoch=2/32 train=0.7173 val=0.6271
[nodo07] fold=1 epoch=3/32 train=0.6537 val=0.6098
[nodo07] fold=1 epoch=4/32 train=0.6477 val=0.5899
[nodo07] fold=1 epoch=5/32 train=0.6366 val=0.5839
[nodo07] fold=1 epoch=6/32 train=0.6286 val=0.5888
[nodo07] fold=1 epoch=7/32 train=0.6173 val=0.5750
[nodo07] fold=1 epoch=8/32 train=0.6095 val=0.5699
[nodo07] fold=1 epoch=9/32 train=0.5977 val=0.5640
[nodo07] fold=1 epoch=10/32 train=0.6212 val=0.5670
[nodo07] fold=1 epoch=11/32 train=0.6127 val=0.5666
[nodo07] fold=1 epoch=12/32 train=0.6096 val=0.5620
[nodo07] fold=1 epoch=13/32 train=0.6083 val=0.5561
[nodo07] fold=1 epoch=14/32 train=0.5804 val=0.5612
[nodo07] fold=1 epoch=15/32 train=0.5781 val=0.5712
[nodo07] fold=1 epoch=16/32 train=0.5678 val=0.5632
[nodo07] fold=1 epoch=17/32 train=0.5614 val=0.5729
[nodo07] fold=1 epoch=18/32 train=0.6030 val=0.5560
[nodo07] fold=1 epoch=19/32 train=0.5549 val=0.5721
[nodo07] fold=1 epoch=20/32 train=0.5539 val=0.5767
[nodo07] fold=1 epoch=21/32 train=0.5647 val=0.5660
[nodo07] fold=1 epoch=22/32 train=0.5624 val=0.5614
[nodo07] fold=1 epoch=23/32 train=0.5689 val=0.5541
[nodo07] fold=1 epoch=24/32 train=0.5712 val=0.5573
[nodo07] fold=1 epoch=25/32 train=0.5809 val=0.5506
[nodo07] fold=1 epoch=26/32 train=0.5709 val=0.5542
[nodo07] fold=1 epoch=27/32 train=0.5368 val=0.5577
[nodo07] fold=1 epoch=28/32 train=0.6085 val=0.5533
[nodo07] fold=1 epoch=29/32 train=0.5537 val=0.5538
[nodo07] fold=1 epoch=30/32 train=0.5836 val=0.5524
[nodo07] fold=1 epoch=31/32 train=0.5720 val=0.5532
[nodo07] fold=1 epoch=32/32 train=0.5732 val=0.5534
[nodo07] fold=2 epoch=1/32 train=0.7651 val=0.6777
[nodo07] fold=2 epoch=2/32 train=0.7151 val=0.6005
[nodo07] fold=2 epoch=3/32 train=0.6659 val=0.5936
[nodo07] fold=2 epoch=4/32 train=0.6708 val=0.5957
[nodo07] fold=2 epoch=5/32 train=0.6349 val=0.5715
[nodo07] fold=2 epoch=6/32 train=0.6052 val=0.5973
[nodo07] fold=2 epoch=7/32 train=0.6143 val=0.5758
[nodo07] fold=2 epoch=8/32 train=0.6183 val=0.5610
[nodo07] fold=2 epoch=9/32 train=0.5980 val=0.5655
[nodo07] fold=2 epoch=10/32 train=0.6082 val=0.5579
[nodo07] fold=2 epoch=11/32 train=0.5731 val=0.5529
[nodo07] fold=2 epoch=12/32 train=0.5860 val=0.5659
[nodo07] fold=2 epoch=13/32 train=0.5823 val=0.5446
[nodo07] fold=2 epoch=14/32 train=0.5640 val=0.5564
[nodo07] fold=2 epoch=15/32 train=0.5732 val=0.5617
[nodo07] fold=2 epoch=16/32 train=0.5801 val=0.5508
[nodo07] fold=2 epoch=17/32 train=0.5747 val=0.5632
[nodo07] fold=2 epoch=18/32 train=0.5343 val=0.5507
[nodo07] fold=2 epoch=19/32 train=0.6018 val=0.5485
[nodo07] fold=2 epoch=20/32 train=0.5482 val=0.5591
[nodo07] fold=2 epoch=21/32 train=0.5643 val=0.5838
[nodo07] fold=2 epoch=22/32 train=0.5431 val=0.5633

[I 2026-08-31 09:20:19,505] Trial 16 finished with value: 0.538213874557475 and parameters: {'dropout': 0.3496669297557724, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.229256138797448, 'augmentation_probability': 0.8043024047820171, 'rotation_degrees': 1.5609473699905911, 'learning_rate': 0.00024023771012385764, 'weight_decay': 2.505621534995929e-05, 'auxiliary_weight': 0.17217405723758988, 'consistency_weight': 0.032482245907956814, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 9 with value: 0.5240601584208706.

[nodo07] fold=0 epoch=1/32 train=0.7198 val=0.6563
[nodo07] fold=0 epoch=2/32 train=0.6668 val=0.5852
[nodo07] fold=0 epoch=3/32 train=0.6294 val=0.5794
[nodo07] fold=0 epoch=4/32 train=0.6244 val=0.5626
[nodo07] fold=0 epoch=5/32 train=0.6060 val=0.5467
[nodo07] fold=0 epoch=6/32 train=0.5977 val=0.5346
[nodo07] fold=0 epoch=7/32 train=0.6025 val=0.5220
[nodo07] fold=0 epoch=8/32 train=0.5931 val=0.5183
[nodo07] fold=0 epoch=9/32 train=0.5850 val=0.5135
[nodo07] fold=0 epoch=10/32 train=0.5728 val=0.5078
[nodo07] fold=0 epoch=11/32 train=0.5565 val=0.5295
[nodo07] fold=0 epoch=12/32 train=0.5760 val=0.5243
[nodo07] fold=0 epoch=13/32 train=0.5828 val=0.5055
[nodo07] fold=0 epoch=14/32 train=0.5409 val=0.5062
[nodo07] fold=0 epoch=15/32 train=0.5602 val=0.5100
[nodo07] fold=0 epoch=16/32 train=0.5370 val=0.5153
[nodo07] fold=0 epoch=17/32 train=0.5232 val=0.5164
[nodo07] fold=0 epoch=18/32 train=0.5248 val=0.5089
[nodo07] fold=0 epoch=19/32 train=0.5375 val=0.5075
[nodo07] fold=0 epoch=20/32 train=0.5363 val=0.5045
[nodo07] fold=0 epoch=21/32 train=0.5300 val=0.5037
[nodo07] fold=0 epoch=22/32 train=0.5037 val=0.5023
[nodo07] fold=0 epoch=23/32 train=0.5113 val=0.5062
[nodo07] fold=0 epoch=24/32 train=0.5315 val=0.5005
[nodo07] fold=0 epoch=25/32 train=0.5099 val=0.5068
[nodo07] fold=0 epoch=26/32 train=0.4879 val=0.5079
[nodo07] fold=0 epoch=27/32 train=0.5096 val=0.5051
[nodo07] fold=0 epoch=28/32 train=0.5266 val=0.5050
[nodo07] fold=0 epoch=29/32 train=0.4967 val=0.5082
[nodo07] fold=0 epoch=30/32 train=0.5162 val=0.5076
[nodo07] fold=0 epoch=31/32 train=0.4971 val=0.5074
[nodo07] fold=0 epoch=32/32 train=0.4737 val=0.5075
[nodo07] fold=1 epoch=1/32 train=0.7251 val=0.6350
[nodo07] fold=1 epoch=2/32 train=0.6827 val=0.6169
[nodo07] fold=1 epoch=3/32 train=0.6277 val=0.6186
[nodo07] fold=1 epoch=4/32 train=0.6187 val=0.5846
[nodo07] fold=1 epoch=5/32 train=0.6096 val=0.5808
[nodo07] fold=1 epoch=6/32 train=0.6175 val=0.5819
[nodo07] fold=1 epoch=7/32 train=0.5728 val=0.5692
[nodo07] fold=1 epoch=8/32 train=0.5880 val=0.5570
[nodo07] fold=1 epoch=9/32 train=0.5646 val=0.5605
[nodo07] fold=1 epoch=10/32 train=0.5882 val=0.5570
[nodo07] fold=1 epoch=11/32 train=0.5697 val=0.5547
[nodo07] fold=1 epoch=12/32 train=0.5757 val=0.5580
[nodo07] fold=1 epoch=13/32 train=0.5836 val=0.5518
[nodo07] fold=1 epoch=14/32 train=0.5475 val=0.5529
[nodo07] fold=1 epoch=15/32 train=0.5575 val=0.5647
[nodo07] fold=1 epoch=16/32 train=0.5339 val=0.5597
[nodo07] fold=1 epoch=17/32 train=0.5404 val=0.5598
[nodo07] fold=1 epoch=18/32 train=0.5728 val=0.5385
[nodo07] fold=1 epoch=19/32 train=0.5362 val=0.5765
[nodo07] fold=1 epoch=20/32 train=0.5043 val=0.5690
[nodo07] fold=1 epoch=21/32 train=0.5383 val=0.5518
[nodo07] fold=1 epoch=22/32 train=0.5367 val=0.5470
[nodo07] fold=1 epoch=23/32 train=0.5419 val=0.5444
[nodo07] fold=1 epoch=24/32 train=0.5367 val=0.5424
[nodo07] fold=1 epoch=25/32 train=0.5553 val=0.5385
[nodo07] fold=1 epoch=26/32 train=0.5272 val=0.5379
[nodo07] fold=1 epoch=27/32 train=0.4994 val=0.5471
[nodo07] fold=1 epoch=28/32 train=0.5613 val=0.5445
[nodo07] fold=1 epoch=29/32 train=0.5226 val=0.5425
[nodo07] fold=1 epoch=30/32 train=0.5517 val=0.5402
[nodo07] fold=1 epoch=31/32 train=0.5454 val=0.5406
[nodo07] fold=1 epoch=32/32 train=0.5330 val=0.5408
[nodo07] fold=2 epoch=1/32 train=0.7294 val=0.6199
[nodo07] fold=2 epoch=2/32 train=0.6513 val=0.5889
[nodo07] fold=2 epoch=3/32 train=0.6312 val=0.5897
[nodo07] fold=2 epoch=4/32 train=0.6595 val=0.6025
[nodo07] fold=2 epoch=5/32 train=0.6254 val=0.5777
[nodo07] fold=2 epoch=6/32 train=0.5906 val=0.6232
[nodo07] fold=2 epoch=7/32 train=0.5971 val=0.5749
[nodo07] fold=2 epoch=8/32 train=0.5930 val=0.5639
[nodo07] fold=2 epoch=9/32 train=0.5767 val=0.5860
[nodo07] fold=2 epoch=10/32 train=0.5983 val=0.5668
[nodo07] fold=2 epoch=11/32 train=0.5625 val=0.5622
[nodo07] fold=2 epoch=12/32 train=0.5619 val=0.5774
[nodo07] fold=2 epoch=13/32 train=0.5604 val=0.5620
[nodo07] fold=2 epoch=14/32 train=0.5433 val=0.5727
[nodo07] fold=2 epoch=15/32 train=0.5562 val=0.5748
[nodo07] fold=2 epoch=16/32 train=0.5537 val=0.5618
[nodo07] fold=2 epoch=17/32 train=0.5431 val=0.5740
[nodo07] fold=2 epoch=18/32 train=0.5179 val=0.5724
[nodo07] fold=2 epoch=19/32 train=0.5688 val=0.5637
[nodo07] fold=2 epoch=20/32 train=0.5255 val=0.5751
[nodo07] fold=2 epoch=21/32 train=0.5290 val=0.5876
[nodo07] fold=2 epoch=22/32 train=0.5131 val=0.5691
[nodo07] fold=2 epoch=23/32 train=0.5528 val=0.5749
[nodo07] fold=2 epoch=24/32 train=0.5170 val=0.5648
[nodo07] fold=2 epoch=25/32 train=0.4927 val=0.5606
[nodo07] fold=2 epoch=26/32 train=0.5195 val=0.5523
[nodo07] fold=2 epoch=27/32 train=0.5146 val=0.5536
[nodo07] fold=2 epoch=28/32 train=0.4842 val=0.5544
[nodo07] fold=2 epoch=29/32 train=0.5267 val=0.5547
[nodo07] fold=2 epoch=30/32 train=0.5214 val=0.5575
[nodo07] fold=2 epoch=31/32 train=0.5088 val=0.5562
[nodo07] fold=2 epoch=32/32 train=0.5122 val=0.5565

[I 2026-08-31 10:07:30,160] Trial 17 finished with value: 0.5302131224144634 and parameters: {'dropout': 0.3098541346343268, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 1.8348716635776838, 'augmentation_probability': 0.8014211630019772, 'rotation_degrees': 1.9337007809977607, 'learning_rate': 0.0002433295688898961, 'weight_decay': 1.817090134279307e-05, 'auxiliary_weight': 0.11989279146212246, 'consistency_weight': 0.054390160866626416, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 9 with value: 0.5240601584208706.
[I 2026-08-31 10:07:30,465] A new study created in RDB with name: node09_25d_fb93ea204b

[nodo07] fold=0 epoch=1/32 train=0.7307 val=0.6572
[nodo07] fold=0 epoch=2/32 train=0.6927 val=0.5762
[nodo07] fold=0 epoch=3/32 train=0.6283 val=0.5658
[nodo07] fold=0 epoch=4/32 train=0.6301 val=0.5548
[nodo07] fold=0 epoch=5/32 train=0.6140 val=0.5427
[nodo07] fold=0 epoch=6/32 train=0.6062 val=0.5318
[nodo07] fold=0 epoch=7/32 train=0.6052 val=0.5340
[nodo07] fold=0 epoch=8/32 train=0.6044 val=0.5288
[nodo07] fold=0 epoch=9/32 train=0.5932 val=0.5297
[nodo07] fold=0 epoch=10/32 train=0.5956 val=0.5217
[nodo07] fold=0 epoch=11/32 train=0.5721 val=0.5321
[nodo07] fold=0 epoch=12/32 train=0.5793 val=0.5257
[nodo07] fold=0 epoch=13/32 train=0.6001 val=0.5146
[nodo07] fold=0 epoch=14/32 train=0.5539 val=0.5165
[nodo07] fold=0 epoch=15/32 train=0.5734 val=0.5157
[nodo07] fold=0 epoch=16/32 train=0.5492 val=0.5193
[nodo07] fold=0 epoch=17/32 train=0.5343 val=0.5324
[nodo07] fold=0 epoch=18/32 train=0.5389 val=0.5218
[nodo07] fold=0 epoch=19/32 train=0.5422 val=0.5212
[nodo07] fold=0 epoch=20/32 train=0.5263 val=0.5197
[nodo07] fold=0 epoch=21/32 train=0.5335 val=0.5186
[nodo07] fold=0 epoch=22/32 train=0.5012 val=0.5241
[nodo07] fold=1 epoch=1/32 train=0.7342 val=0.6430
[nodo07] fold=1 epoch=2/32 train=0.6708 val=0.6028
[nodo07] fold=1 epoch=3/32 train=0.6121 val=0.5887
[nodo07] fold=1 epoch=4/32 train=0.6164 val=0.5715
[nodo07] fold=1 epoch=5/32 train=0.5923 val=0.5691
[nodo07] fold=1 epoch=6/32 train=0.5971 val=0.5713
[nodo07] fold=1 epoch=7/32 train=0.5663 val=0.5627
[nodo07] fold=1 epoch=8/32 train=0.5761 val=0.5589
[nodo07] fold=1 epoch=9/32 train=0.5449 val=0.5676
[nodo07] fold=1 epoch=10/32 train=0.5729 val=0.5632
[nodo07] fold=1 epoch=11/32 train=0.5500 val=0.5678
[nodo07] fold=1 epoch=12/32 train=0.5516 val=0.5577
[nodo07] fold=1 epoch=13/32 train=0.5493 val=0.5655
[nodo07] fold=1 epoch=14/32 train=0.5259 val=0.5574
[nodo07] fold=1 epoch=15/32 train=0.5250 val=0.5702
[nodo07] fold=1 epoch=16/32 train=0.4934 val=0.5803
[nodo07] fold=1 epoch=17/32 train=0.5190 val=0.5703
[nodo07] fold=1 epoch=18/32 train=0.5378 val=0.5578
[nodo07] fold=1 epoch=19/32 train=0.5152 val=0.5787
[nodo07] fold=1 epoch=20/32 train=0.4731 val=0.5851
[nodo07] fold=1 epoch=21/32 train=0.5050 val=0.5725
[nodo07] fold=1 epoch=22/32 train=0.4959 val=0.5706
[nodo07] fold=1 epoch=23/32 train=0.5091 val=0.5710
[nodo07] fold=2 epoch=1/32 train=0.7364 val=0.6550
[nodo07] fold=2 epoch=2/32 train=0.6712 val=0.5820
[nodo07] fold=2 epoch=3/32 train=0.6327 val=0.5861
[nodo07] fold=2 epoch=4/32 train=0.6542 val=0.5914
[nodo07] fold=2 epoch=5/32 train=0.6096 val=0.5672
[nodo07] fold=2 epoch=6/32 train=0.5835 val=0.6137
[nodo07] fold=2 epoch=7/32 train=0.5850 val=0.5748
[nodo07] fold=2 epoch=8/32 train=0.5850 val=0.5667
[nodo07] fold=2 epoch=9/32 train=0.5692 val=0.5622
[nodo07] fold=2 epoch=10/32 train=0.5927 val=0.5587
[nodo07] fold=2 epoch=11/32 train=0.5497 val=0.5452
[nodo07] fold=2 epoch=12/32 train=0.5431 val=0.5666
[nodo07] fold=2 epoch=13/32 train=0.5633 val=0.5530
[nodo07] fold=2 epoch=14/32 train=0.5231 val=0.5733
[nodo07] fold=2 epoch=15/32 train=0.5339 val=0.5816
[nodo07] fold=2 epoch=16/32 train=0.5347 val=0.5585
[nodo07] fold=2 epoch=17/32 train=0.5291 val=0.5659
[nodo07] fold=2 epoch=18/32 train=0.5143 val=0.5600
[nodo07] fold=2 epoch=19/32 train=0.5644 val=0.5734
[nodo07] fold=2 epoch=20/32 train=0.5009 val=0.5608

[I 2026-08-31 10:57:45,373] Trial 0 finished with value: 0.5390543109002067 and parameters: {'dropout': 0.30506770120532095, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.266379892884978, 'augmentation_probability': 0.8309583876254734, 'rotation_degrees': 2.729671816596594, 'learning_rate': 0.00013134702829321461, 'weight_decay': 2.2382720151515393e-05, 'auxiliary_weight': 0.1199360604284022, 'consistency_weight': 0.007202609480904654, 'feature_top_k': 64, 'pca_variance': 'none'}. Best is trial 0 with value: 0.5390543109002067.

[nodo07] fold=0 epoch=1/32 train=0.7278 val=0.6512
[nodo07] fold=0 epoch=2/32 train=0.6984 val=0.5844
[nodo07] fold=0 epoch=3/32 train=0.6491 val=0.5748
[nodo07] fold=0 epoch=4/32 train=0.6483 val=0.5631
[nodo07] fold=0 epoch=5/32 train=0.6260 val=0.5449
[nodo07] fold=0 epoch=6/32 train=0.6267 val=0.5307
[nodo07] fold=0 epoch=7/32 train=0.6275 val=0.5301
[nodo07] fold=0 epoch=8/32 train=0.6237 val=0.5263
[nodo07] fold=0 epoch=9/32 train=0.6184 val=0.5250
[nodo07] fold=0 epoch=10/32 train=0.6119 val=0.5225
[nodo07] fold=0 epoch=11/32 train=0.5980 val=0.5333
[nodo07] fold=0 epoch=12/32 train=0.6102 val=0.5350
[nodo07] fold=0 epoch=13/32 train=0.6266 val=0.5193
[nodo07] fold=0 epoch=14/32 train=0.5822 val=0.5146
[nodo07] fold=0 epoch=15/32 train=0.6081 val=0.5274
[nodo07] fold=0 epoch=16/32 train=0.5936 val=0.5269
[nodo07] fold=0 epoch=17/32 train=0.5819 val=0.5252
[nodo07] fold=0 epoch=18/32 train=0.5748 val=0.5152
[nodo07] fold=0 epoch=19/32 train=0.5883 val=0.5171
[nodo07] fold=0 epoch=20/32 train=0.5975 val=0.5194
[nodo07] fold=0 epoch=21/32 train=0.5849 val=0.5183
[nodo07] fold=0 epoch=22/32 train=0.5468 val=0.5138
[nodo07] fold=0 epoch=23/32 train=0.5703 val=0.5144
[nodo07] fold=0 epoch=24/32 train=0.5860 val=0.5137
[nodo07] fold=0 epoch=25/32 train=0.5672 val=0.5139
[nodo07] fold=0 epoch=26/32 train=0.5486 val=0.5168
[nodo07] fold=0 epoch=27/32 train=0.5579 val=0.5156
[nodo07] fold=0 epoch=28/32 train=0.5761 val=0.5131
[nodo07] fold=0 epoch=29/32 train=0.5603 val=0.5150
[nodo07] fold=0 epoch=30/32 train=0.5562 val=0.5148
[nodo07] fold=0 epoch=31/32 train=0.5432 val=0.5150
[nodo07] fold=0 epoch=32/32 train=0.5265 val=0.5149
[nodo07] fold=1 epoch=1/32 train=0.7389 val=0.6699
[nodo07] fold=1 epoch=2/32 train=0.7161 val=0.6471
[nodo07] fold=1 epoch=3/32 train=0.6667 val=0.6304
[nodo07] fold=1 epoch=4/32 train=0.6495 val=0.6053
[nodo07] fold=1 epoch=5/32 train=0.6321 val=0.5883
[nodo07] fold=1 epoch=6/32 train=0.6362 val=0.5864
[nodo07] fold=1 epoch=7/32 train=0.6082 val=0.5778
[nodo07] fold=1 epoch=8/32 train=0.6011 val=0.5783
[nodo07] fold=1 epoch=9/32 train=0.6012 val=0.5762
[nodo07] fold=1 epoch=10/32 train=0.6103 val=0.5804
[nodo07] fold=1 epoch=11/32 train=0.6052 val=0.5808
[nodo07] fold=1 epoch=12/32 train=0.5915 val=0.5757
[nodo07] fold=1 epoch=13/32 train=0.6018 val=0.5805
[nodo07] fold=1 epoch=14/32 train=0.5701 val=0.5777
[nodo07] fold=1 epoch=15/32 train=0.5493 val=0.5847
[nodo07] fold=1 epoch=16/32 train=0.5370 val=0.5838
[nodo07] fold=1 epoch=17/32 train=0.5646 val=0.5841
[nodo07] fold=1 epoch=18/32 train=0.5884 val=0.5733
[nodo07] fold=1 epoch=19/32 train=0.5634 val=0.5979
[nodo07] fold=1 epoch=20/32 train=0.5349 val=0.5982
[nodo07] fold=1 epoch=21/32 train=0.5652 val=0.5782
[nodo07] fold=1 epoch=22/32 train=0.5477 val=0.5801
[nodo07] fold=1 epoch=23/32 train=0.5560 val=0.5757
[nodo07] fold=1 epoch=24/32 train=0.5602 val=0.5700
[nodo07] fold=1 epoch=25/32 train=0.5756 val=0.5651
[nodo07] fold=1 epoch=26/32 train=0.5682 val=0.5664
[nodo07] fold=1 epoch=27/32 train=0.5148 val=0.5729
[nodo07] fold=1 epoch=28/32 train=0.5786 val=0.5698
[nodo07] fold=1 epoch=29/32 train=0.5406 val=0.5732
[nodo07] fold=1 epoch=30/32 train=0.5724 val=0.5703
[nodo07] fold=1 epoch=31/32 train=0.5549 val=0.5704
[nodo07] fold=1 epoch=32/32 train=0.5516 val=0.5705
[nodo07] fold=2 epoch=1/32 train=0.7433 val=0.6717
[nodo07] fold=2 epoch=2/32 train=0.7158 val=0.6320
[nodo07] fold=2 epoch=3/32 train=0.6571 val=0.5792
[nodo07] fold=2 epoch=4/32 train=0.6552 val=0.5904
[nodo07] fold=2 epoch=5/32 train=0.6251 val=0.5621
[nodo07] fold=2 epoch=6/32 train=0.5932 val=0.6038
[nodo07] fold=2 epoch=7/32 train=0.5860 val=0.5642
[nodo07] fold=2 epoch=8/32 train=0.6079 val=0.5570
[nodo07] fold=2 epoch=9/32 train=0.5859 val=0.5642
[nodo07] fold=2 epoch=10/32 train=0.6103 val=0.5608
[nodo07] fold=2 epoch=11/32 train=0.5719 val=0.5473
[nodo07] fold=2 epoch=12/32 train=0.5784 val=0.5630
[nodo07] fold=2 epoch=13/32 train=0.5880 val=0.5480
[nodo07] fold=2 epoch=14/32 train=0.5759 val=0.5604
[nodo07] fold=2 epoch=15/32 train=0.5776 val=0.5653
[nodo07] fold=2 epoch=16/32 train=0.5792 val=0.5562
[nodo07] fold=2 epoch=17/32 train=0.5785 val=0.5547
[nodo07] fold=2 epoch=18/32 train=0.5499 val=0.5543
[nodo07] fold=2 epoch=19/32 train=0.6019 val=0.5627
[nodo07] fold=2 epoch=20/32 train=0.5628 val=0.5512

[I 2026-08-31 11:45:59,838] Trial 1 finished with value: 0.5418192862127755 and parameters: {'dropout': 0.27738672351262605, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 1.9907319114484223, 'augmentation_probability': 0.8951524498011663, 'rotation_degrees': 2.98222137087899, 'learning_rate': 0.00014700253462439266, 'weight_decay': 2.3119302741339274e-05, 'auxiliary_weight': 0.13118733346601416, 'consistency_weight': 0.023558114522388457, 'feature_top_k': 64, 'pca_variance': '0.95'}. Best is trial 0 with value: 0.5390543109002067.

[nodo07] fold=0 epoch=1/32 train=0.7247 val=0.6555
[nodo07] fold=0 epoch=2/32 train=0.6950 val=0.5950
[nodo07] fold=0 epoch=3/32 train=0.6475 val=0.5804
[nodo07] fold=0 epoch=4/32 train=0.6373 val=0.5721
[nodo07] fold=0 epoch=5/32 train=0.6351 val=0.5609
[nodo07] fold=0 epoch=6/32 train=0.6314 val=0.5546
[nodo07] fold=0 epoch=7/32 train=0.6364 val=0.5552
[nodo07] fold=0 epoch=8/32 train=0.6270 val=0.5458
[nodo07] fold=0 epoch=9/32 train=0.6290 val=0.5423
[nodo07] fold=0 epoch=10/32 train=0.6114 val=0.5404
[nodo07] fold=0 epoch=11/32 train=0.6019 val=0.5518
[nodo07] fold=0 epoch=12/32 train=0.6187 val=0.5540
[nodo07] fold=0 epoch=13/32 train=0.6371 val=0.5333
[nodo07] fold=0 epoch=14/32 train=0.5928 val=0.5331
[nodo07] fold=0 epoch=15/32 train=0.6059 val=0.5413
[nodo07] fold=0 epoch=16/32 train=0.5899 val=0.5500
[nodo07] fold=0 epoch=17/32 train=0.5829 val=0.5387
[nodo07] fold=0 epoch=18/32 train=0.5782 val=0.5305
[nodo07] fold=0 epoch=19/32 train=0.5685 val=0.5249
[nodo07] fold=0 epoch=20/32 train=0.6007 val=0.5291
[nodo07] fold=0 epoch=21/32 train=0.5868 val=0.5273
[nodo07] fold=0 epoch=22/32 train=0.5432 val=0.5248
[nodo07] fold=0 epoch=23/32 train=0.5582 val=0.5241
[nodo07] fold=0 epoch=24/32 train=0.5985 val=0.5229
[nodo07] fold=0 epoch=25/32 train=0.5771 val=0.5238
[nodo07] fold=0 epoch=26/32 train=0.5711 val=0.5259
[nodo07] fold=0 epoch=27/32 train=0.5780 val=0.5242
[nodo07] fold=0 epoch=28/32 train=0.5873 val=0.5232
[nodo07] fold=0 epoch=29/32 train=0.5675 val=0.5238
[nodo07] fold=0 epoch=30/32 train=0.5806 val=0.5239
[nodo07] fold=0 epoch=31/32 train=0.5564 val=0.5239
[nodo07] fold=0 epoch=32/32 train=0.5291 val=0.5238
[nodo07] fold=1 epoch=1/32 train=0.7422 val=0.6705
[nodo07] fold=1 epoch=2/32 train=0.7051 val=0.6336
[nodo07] fold=1 epoch=3/32 train=0.6431 val=0.6126
[nodo07] fold=1 epoch=4/32 train=0.6405 val=0.6025
[nodo07] fold=1 epoch=5/32 train=0.6276 val=0.5918
[nodo07] fold=1 epoch=6/32 train=0.6397 val=0.5814
[nodo07] fold=1 epoch=7/32 train=0.6111 val=0.5772
[nodo07] fold=1 epoch=8/32 train=0.6052 val=0.5692
[nodo07] fold=1 epoch=9/32 train=0.5985 val=0.5646
[nodo07] fold=1 epoch=10/32 train=0.6111 val=0.5757
[nodo07] fold=1 epoch=11/32 train=0.6067 val=0.5647
[nodo07] fold=1 epoch=12/32 train=0.6033 val=0.5555
[nodo07] fold=1 epoch=13/32 train=0.6102 val=0.5535
[nodo07] fold=1 epoch=14/32 train=0.5688 val=0.5553
[nodo07] fold=1 epoch=15/32 train=0.5738 val=0.5683
[nodo07] fold=1 epoch=16/32 train=0.5589 val=0.5517
[nodo07] fold=1 epoch=17/32 train=0.5558 val=0.5604
[nodo07] fold=1 epoch=18/32 train=0.5917 val=0.5417
[nodo07] fold=1 epoch=19/32 train=0.5460 val=0.5569
[nodo07] fold=1 epoch=20/32 train=0.5432 val=0.5571
[nodo07] fold=1 epoch=21/32 train=0.5682 val=0.5568
[nodo07] fold=1 epoch=22/32 train=0.5510 val=0.5518
[nodo07] fold=1 epoch=23/32 train=0.5495 val=0.5400
[nodo07] fold=1 epoch=24/32 train=0.5651 val=0.5441
[nodo07] fold=1 epoch=25/32 train=0.5725 val=0.5424
[nodo07] fold=1 epoch=26/32 train=0.5571 val=0.5400
[nodo07] fold=1 epoch=27/32 train=0.5339 val=0.5430
[nodo07] fold=1 epoch=28/32 train=0.5921 val=0.5410
[nodo07] fold=1 epoch=29/32 train=0.5535 val=0.5406
[nodo07] fold=1 epoch=30/32 train=0.5674 val=0.5394
[nodo07] fold=1 epoch=31/32 train=0.5525 val=0.5394
[nodo07] fold=1 epoch=32/32 train=0.5701 val=0.5394
[nodo07] fold=2 epoch=1/32 train=0.7483 val=0.6754
[nodo07] fold=2 epoch=2/32 train=0.7122 val=0.6139
[nodo07] fold=2 epoch=3/32 train=0.6636 val=0.5860
[nodo07] fold=2 epoch=4/32 train=0.6649 val=0.5964
[nodo07] fold=2 epoch=5/32 train=0.6451 val=0.5717
[nodo07] fold=2 epoch=6/32 train=0.6198 val=0.5903
[nodo07] fold=2 epoch=7/32 train=0.6209 val=0.5720
[nodo07] fold=2 epoch=8/32 train=0.6272 val=0.5624
[nodo07] fold=2 epoch=9/32 train=0.6102 val=0.5714
[nodo07] fold=2 epoch=10/32 train=0.6387 val=0.5637
[nodo07] fold=2 epoch=11/32 train=0.5892 val=0.5571
[nodo07] fold=2 epoch=12/32 train=0.6071 val=0.5672
[nodo07] fold=2 epoch=13/32 train=0.6072 val=0.5551
[nodo07] fold=2 epoch=14/32 train=0.5975 val=0.5608
[nodo07] fold=2 epoch=15/32 train=0.6087 val=0.5654
[nodo07] fold=2 epoch=16/32 train=0.6013 val=0.5578
[nodo07] fold=2 epoch=17/32 train=0.6001 val=0.5569
[nodo07] fold=2 epoch=18/32 train=0.5696 val=0.5574
[nodo07] fold=2 epoch=19/32 train=0.6356 val=0.5552
[nodo07] fold=2 epoch=20/32 train=0.5796 val=0.5516
[nodo07] fold=2 epoch=21/32 train=0.5936 val=0.5593
[nodo07] fold=2 epoch=22/32 train=0.5735 val=0.5531
[nodo07] fold=2 epoch=23/32 train=0.6124 val=0.5562
[nodo07] fold=2 epoch=24/32 train=0.5837 val=0.5529
[nodo07] fold=2 epoch=25/32 train=0.5616 val=0.5542
[nodo07] fold=2 epoch=26/32 train=0.5806 val=0.5510
[nodo07] fold=2 epoch=27/32 train=0.5714 val=0.5519
[nodo07] fold=2 epoch=28/32 train=0.5548 val=0.5529
[nodo07] fold=2 epoch=29/32 train=0.5779 val=0.5521
[nodo07] fold=2 epoch=30/32 train=0.5840 val=0.5506
[nodo07] fold=2 epoch=31/32 train=0.5660 val=0.5506
[nodo07] fold=2 epoch=32/32 train=0.5518 val=0.5508

[I 2026-08-31 12:38:39,992] Trial 2 finished with value: 0.5376441035028696 and parameters: {'dropout': 0.23702799159985097, 'tabular_embedding_dim': 16, 'augmentation_magnitude': 2.3674691140021085, 'augmentation_probability': 0.8472926368347024, 'rotation_degrees': 2.9170893359673724, 'learning_rate': 0.0001629555956893874, 'weight_decay': 1.3208922415005888e-05, 'auxiliary_weight': 0.12923999971730635, 'consistency_weight': 0.010155521096723213, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 2 with value: 0.5376441035028696.

[nodo07] fold=0 epoch=1/32 train=0.7257 val=0.6197
[nodo07] fold=0 epoch=2/32 train=0.6723 val=0.5637
[nodo07] fold=0 epoch=3/32 train=0.6310 val=0.5572
[nodo07] fold=0 epoch=4/32 train=0.6283 val=0.5415
[nodo07] fold=0 epoch=5/32 train=0.6063 val=0.5253
[nodo07] fold=0 epoch=6/32 train=0.6037 val=0.5170
[nodo07] fold=0 epoch=7/32 train=0.5948 val=0.5180
[nodo07] fold=0 epoch=8/32 train=0.5932 val=0.5173
[nodo07] fold=0 epoch=9/32 train=0.5822 val=0.5141
[nodo07] fold=0 epoch=10/32 train=0.5813 val=0.5099
[nodo07] fold=0 epoch=11/32 train=0.5648 val=0.5225
[nodo07] fold=0 epoch=12/32 train=0.5621 val=0.5140
[nodo07] fold=0 epoch=13/32 train=0.5806 val=0.5048
[nodo07] fold=0 epoch=14/32 train=0.5290 val=0.5082
[nodo07] fold=0 epoch=15/32 train=0.5459 val=0.5031
[nodo07] fold=0 epoch=16/32 train=0.5255 val=0.5149
[nodo07] fold=0 epoch=17/32 train=0.5190 val=0.5182
[nodo07] fold=0 epoch=18/32 train=0.5213 val=0.5138
[nodo07] fold=0 epoch=19/32 train=0.5140 val=0.5172
[nodo07] fold=0 epoch=20/32 train=0.5222 val=0.5111
[nodo07] fold=0 epoch=21/32 train=0.5098 val=0.5123
[nodo07] fold=0 epoch=22/32 train=0.4808 val=0.5180
[nodo07] fold=0 epoch=23/32 train=0.5024 val=0.5145
[nodo07] fold=0 epoch=24/32 train=0.5263 val=0.5123
[nodo07] fold=1 epoch=1/32 train=0.7161 val=0.6088
[nodo07] fold=1 epoch=2/32 train=0.6603 val=0.5991
[nodo07] fold=1 epoch=3/32 train=0.6157 val=0.6011
[nodo07] fold=1 epoch=4/32 train=0.6030 val=0.5689
[nodo07] fold=1 epoch=5/32 train=0.5755 val=0.5833
[nodo07] fold=1 epoch=6/32 train=0.5994 val=0.5885
[nodo07] fold=1 epoch=7/32 train=0.5575 val=0.5807
[nodo07] fold=1 epoch=8/32 train=0.5623 val=0.5705
[nodo07] fold=1 epoch=9/32 train=0.5369 val=0.5805
[nodo07] fold=1 epoch=10/32 train=0.5698 val=0.5723
[nodo07] fold=1 epoch=11/32 train=0.5256 val=0.5782
[nodo07] fold=1 epoch=12/32 train=0.5356 val=0.5743
[nodo07] fold=1 epoch=13/32 train=0.5503 val=0.5718
[nodo07] fold=2 epoch=1/32 train=0.7418 val=0.6358
[nodo07] fold=2 epoch=2/32 train=0.6584 val=0.5916
[nodo07] fold=2 epoch=3/32 train=0.6394 val=0.5852
[nodo07] fold=2 epoch=4/32 train=0.6523 val=0.5973
[nodo07] fold=2 epoch=5/32 train=0.6101 val=0.5669
[nodo07] fold=2 epoch=6/32 train=0.5743 val=0.6431
[nodo07] fold=2 epoch=7/32 train=0.5786 val=0.5760
[nodo07] fold=2 epoch=8/32 train=0.5803 val=0.5680
[nodo07] fold=2 epoch=9/32 train=0.5650 val=0.5773
[nodo07] fold=2 epoch=10/32 train=0.5798 val=0.5668
[nodo07] fold=2 epoch=11/32 train=0.5394 val=0.5560
[nodo07] fold=2 epoch=12/32 train=0.5401 val=0.5846
[nodo07] fold=2 epoch=13/32 train=0.5555 val=0.5566
[nodo07] fold=2 epoch=14/32 train=0.5093 val=0.5811
[nodo07] fold=2 epoch=15/32 train=0.5107 val=0.6005
[nodo07] fold=2 epoch=16/32 train=0.5180 val=0.5761
[nodo07] fold=2 epoch=17/32 train=0.5110 val=0.5761
[nodo07] fold=2 epoch=18/32 train=0.4771 val=0.5807
[nodo07] fold=2 epoch=19/32 train=0.5434 val=0.5824
[nodo07] fold=2 epoch=20/32 train=0.4884 val=0.5764

[I 2026-08-31 13:13:09,273] Trial 3 finished with value: 0.5426643889565184 and parameters: {'dropout': 0.26252922631624287, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.0460654349180887, 'augmentation_probability': 0.8245417140643799, 'rotation_degrees': 2.161244166074005, 'learning_rate': 0.00013026675580213534, 'weight_decay': 8.55332008176945e-05, 'auxiliary_weight': 0.12254238813892668, 'consistency_weight': 0.010645757235974313, 'feature_top_k': 64, 'pca_variance': 'none'}. Best is trial 2 with value: 0.5376441035028696.

[nodo07] fold=0 epoch=1/32 train=0.7249 val=0.6566
[nodo07] fold=0 epoch=2/32 train=0.6867 val=0.5788
[nodo07] fold=0 epoch=3/32 train=0.6324 val=0.5831
[nodo07] fold=0 epoch=4/32 train=0.6248 val=0.5731
[nodo07] fold=0 epoch=5/32 train=0.6221 val=0.5605
[nodo07] fold=0 epoch=6/32 train=0.6267 val=0.5519
[nodo07] fold=0 epoch=7/32 train=0.6211 val=0.5535
[nodo07] fold=0 epoch=8/32 train=0.6239 val=0.5394
[nodo07] fold=0 epoch=9/32 train=0.6144 val=0.5373
[nodo07] fold=0 epoch=10/32 train=0.6009 val=0.5339
[nodo07] fold=0 epoch=11/32 train=0.5938 val=0.5437
[nodo07] fold=0 epoch=12/32 train=0.5980 val=0.5480
[nodo07] fold=0 epoch=13/32 train=0.6234 val=0.5241
[nodo07] fold=0 epoch=14/32 train=0.5646 val=0.5225
[nodo07] fold=0 epoch=15/32 train=0.5828 val=0.5271
[nodo07] fold=0 epoch=16/32 train=0.5785 val=0.5372
[nodo07] fold=0 epoch=17/32 train=0.5603 val=0.5368
[nodo07] fold=0 epoch=18/32 train=0.5664 val=0.5242
[nodo07] fold=0 epoch=19/32 train=0.5627 val=0.5177
[nodo07] fold=0 epoch=20/32 train=0.5877 val=0.5180
[nodo07] fold=0 epoch=21/32 train=0.5697 val=0.5165
[nodo07] fold=0 epoch=22/32 train=0.5369 val=0.5171
[nodo07] fold=0 epoch=23/32 train=0.5480 val=0.5148
[nodo07] fold=0 epoch=24/32 train=0.5760 val=0.5141
[nodo07] fold=0 epoch=25/32 train=0.5529 val=0.5148
[nodo07] fold=0 epoch=26/32 train=0.5517 val=0.5171
[nodo07] fold=0 epoch=27/32 train=0.5558 val=0.5147
[nodo07] fold=0 epoch=28/32 train=0.5757 val=0.5136
[nodo07] fold=0 epoch=29/32 train=0.5462 val=0.5156
[nodo07] fold=0 epoch=30/32 train=0.5664 val=0.5157
[nodo07] fold=0 epoch=31/32 train=0.5430 val=0.5158
[nodo07] fold=0 epoch=32/32 train=0.5131 val=0.5158
[nodo07] fold=1 epoch=1/32 train=0.7263 val=0.6543
[nodo07] fold=1 epoch=2/32 train=0.6841 val=0.6229
[nodo07] fold=1 epoch=3/32 train=0.6227 val=0.6237
[nodo07] fold=1 epoch=4/32 train=0.6365 val=0.6039
[nodo07] fold=1 epoch=5/32 train=0.6228 val=0.5873
[nodo07] fold=1 epoch=6/32 train=0.6303 val=0.5811
[nodo07] fold=1 epoch=7/32 train=0.5919 val=0.5634
[nodo07] fold=1 epoch=8/32 train=0.5951 val=0.5541
[nodo07] fold=1 epoch=9/32 train=0.5828 val=0.5488
[nodo07] fold=1 epoch=10/32 train=0.5990 val=0.5483
[nodo07] fold=1 epoch=11/32 train=0.5863 val=0.5480
[nodo07] fold=1 epoch=12/32 train=0.5852 val=0.5467
[nodo07] fold=1 epoch=13/32 train=0.5976 val=0.5499
[nodo07] fold=1 epoch=14/32 train=0.5634 val=0.5466
[nodo07] fold=1 epoch=15/32 train=0.5575 val=0.5549
[nodo07] fold=1 epoch=16/32 train=0.5422 val=0.5591
[nodo07] fold=1 epoch=17/32 train=0.5477 val=0.5538
[nodo07] fold=1 epoch=18/32 train=0.5754 val=0.5400
[nodo07] fold=1 epoch=19/32 train=0.5479 val=0.5615
[nodo07] fold=1 epoch=20/32 train=0.5231 val=0.5588
[nodo07] fold=1 epoch=21/32 train=0.5525 val=0.5518
[nodo07] fold=1 epoch=22/32 train=0.5402 val=0.5498
[nodo07] fold=1 epoch=23/32 train=0.5480 val=0.5439
[nodo07] fold=1 epoch=24/32 train=0.5557 val=0.5485
[nodo07] fold=1 epoch=25/32 train=0.5679 val=0.5461
[nodo07] fold=1 epoch=26/32 train=0.5565 val=0.5463
[nodo07] fold=1 epoch=27/32 train=0.5258 val=0.5487
[nodo07] fold=2 epoch=1/32 train=0.7328 val=0.6661
[nodo07] fold=2 epoch=2/32 train=0.6723 val=0.5880
[nodo07] fold=2 epoch=3/32 train=0.6450 val=0.5828
[nodo07] fold=2 epoch=4/32 train=0.6481 val=0.5932
[nodo07] fold=2 epoch=5/32 train=0.6318 val=0.5749
[nodo07] fold=2 epoch=6/32 train=0.6084 val=0.6069
[nodo07] fold=2 epoch=7/32 train=0.6066 val=0.5759
[nodo07] fold=2 epoch=8/32 train=0.6072 val=0.5661
[nodo07] fold=2 epoch=9/32 train=0.5890 val=0.5800
[nodo07] fold=2 epoch=10/32 train=0.6227 val=0.5617
[nodo07] fold=2 epoch=11/32 train=0.5709 val=0.5631
[nodo07] fold=2 epoch=12/32 train=0.5915 val=0.5702
[nodo07] fold=2 epoch=13/32 train=0.5800 val=0.5561
[nodo07] fold=2 epoch=14/32 train=0.5682 val=0.5668
[nodo07] fold=2 epoch=15/32 train=0.5789 val=0.5685
[nodo07] fold=2 epoch=16/32 train=0.5743 val=0.5613
[nodo07] fold=2 epoch=17/32 train=0.5765 val=0.5672
[nodo07] fold=2 epoch=18/32 train=0.5361 val=0.5625
[nodo07] fold=2 epoch=19/32 train=0.5958 val=0.5609
[nodo07] fold=2 epoch=20/32 train=0.5546 val=0.5615
[nodo07] fold=2 epoch=21/32 train=0.5690 val=0.5679
[nodo07] fold=2 epoch=22/32 train=0.5589 val=0.5571

[I 2026-08-31 14:48:03,242] Trial 4 finished with value: 0.5365909376439756 and parameters: {'dropout': 0.30095535361971215, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.038161977654581, 'augmentation_probability': 0.8576264008659471, 'rotation_degrees': 2.3199918827475856, 'learning_rate': 0.0001300239292100639, 'weight_decay': 8.557092783676474e-05, 'auxiliary_weight': 0.10572056994349607, 'consistency_weight': 0.035653506278971334, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 4 with value: 0.5365909376439756.

[nodo07] fold=0 epoch=1/32 train=0.7276 val=0.6763
[nodo07] fold=0 epoch=2/32 train=0.7080 val=0.6513
[nodo07] fold=0 epoch=3/32 train=0.6680 val=0.5973
[nodo07] fold=0 epoch=4/32 train=0.6395 val=0.5917
[nodo07] fold=0 epoch=5/32 train=0.6374 val=0.5704
[nodo07] fold=0 epoch=6/32 train=0.6293 val=0.5643
[nodo07] fold=0 epoch=7/32 train=0.6288 val=0.5615
[nodo07] fold=0 epoch=8/32 train=0.6153 val=0.5564
[nodo07] fold=0 epoch=9/32 train=0.6282 val=0.5486
[nodo07] fold=0 epoch=10/32 train=0.6121 val=0.5469
[nodo07] fold=0 epoch=11/32 train=0.5979 val=0.5549
[nodo07] fold=0 epoch=12/32 train=0.6169 val=0.5675
[nodo07] fold=0 epoch=13/32 train=0.6283 val=0.5452
[nodo07] fold=0 epoch=14/32 train=0.5927 val=0.5425
[nodo07] fold=0 epoch=15/32 train=0.6082 val=0.5475
[nodo07] fold=0 epoch=16/32 train=0.5953 val=0.5457
[nodo07] fold=0 epoch=17/32 train=0.5926 val=0.5474
[nodo07] fold=0 epoch=18/32 train=0.5947 val=0.5375
[nodo07] fold=0 epoch=19/32 train=0.5725 val=0.5385
[nodo07] fold=0 epoch=20/32 train=0.6036 val=0.5388
[nodo07] fold=0 epoch=21/32 train=0.5932 val=0.5401
[nodo07] fold=0 epoch=22/32 train=0.5579 val=0.5370
[nodo07] fold=0 epoch=23/32 train=0.5670 val=0.5391
[nodo07] fold=0 epoch=24/32 train=0.6097 val=0.5357
[nodo07] fold=0 epoch=25/32 train=0.5851 val=0.5365
[nodo07] fold=0 epoch=26/32 train=0.5792 val=0.5379
[nodo07] fold=0 epoch=27/32 train=0.5911 val=0.5368
[nodo07] fold=0 epoch=28/32 train=0.6025 val=0.5359
[nodo07] fold=0 epoch=29/32 train=0.5782 val=0.5364
[nodo07] fold=0 epoch=30/32 train=0.5936 val=0.5365
[nodo07] fold=0 epoch=31/32 train=0.5733 val=0.5365
[nodo07] fold=0 epoch=32/32 train=0.5543 val=0.5364
[nodo07] fold=1 epoch=1/32 train=0.7213 val=0.6514
[nodo07] fold=1 epoch=2/32 train=0.6753 val=0.6371
[nodo07] fold=1 epoch=3/32 train=0.6218 val=0.6272
[nodo07] fold=1 epoch=4/32 train=0.6348 val=0.5975
[nodo07] fold=1 epoch=5/32 train=0.6239 val=0.5945
[nodo07] fold=1 epoch=6/32 train=0.6367 val=0.5863
[nodo07] fold=1 epoch=7/32 train=0.6028 val=0.5821
[nodo07] fold=1 epoch=8/32 train=0.6057 val=0.5738
[nodo07] fold=1 epoch=9/32 train=0.6097 val=0.5736
[nodo07] fold=1 epoch=10/32 train=0.6142 val=0.5873
[nodo07] fold=1 epoch=11/32 train=0.6200 val=0.5683
[nodo07] fold=1 epoch=12/32 train=0.6094 val=0.5679
[nodo07] fold=1 epoch=13/32 train=0.6139 val=0.5686
[nodo07] fold=1 epoch=14/32 train=0.5788 val=0.5674
[nodo07] fold=1 epoch=15/32 train=0.5696 val=0.5725
[nodo07] fold=1 epoch=16/32 train=0.5674 val=0.5704
[nodo07] fold=1 epoch=17/32 train=0.5786 val=0.5728
[nodo07] fold=1 epoch=18/32 train=0.6113 val=0.5601
[nodo07] fold=1 epoch=19/32 train=0.5740 val=0.5706
[nodo07] fold=1 epoch=20/32 train=0.5546 val=0.5736
[nodo07] fold=1 epoch=21/32 train=0.5673 val=0.5673
[nodo07] fold=1 epoch=22/32 train=0.5633 val=0.5625
[nodo07] fold=1 epoch=23/32 train=0.5621 val=0.5581
[nodo07] fold=1 epoch=24/32 train=0.5742 val=0.5627
[nodo07] fold=1 epoch=25/32 train=0.5852 val=0.5565
[nodo07] fold=1 epoch=26/32 train=0.5748 val=0.5579
[nodo07] fold=1 epoch=27/32 train=0.5532 val=0.5594
[nodo07] fold=1 epoch=28/32 train=0.5878 val=0.5580
[nodo07] fold=1 epoch=29/32 train=0.5565 val=0.5586
[nodo07] fold=1 epoch=30/32 train=0.5955 val=0.5580
[nodo07] fold=1 epoch=31/32 train=0.5631 val=0.5581
[nodo07] fold=1 epoch=32/32 train=0.5866 val=0.5582
[nodo07] fold=2 epoch=1/32 train=0.7214 val=0.6783
[nodo07] fold=2 epoch=2/32 train=0.6928 val=0.6147
[nodo07] fold=2 epoch=3/32 train=0.6442 val=0.5872
[nodo07] fold=2 epoch=4/32 train=0.6466 val=0.5897
[nodo07] fold=2 epoch=5/32 train=0.6247 val=0.5781
[nodo07] fold=2 epoch=6/32 train=0.6079 val=0.6121
[nodo07] fold=2 epoch=7/32 train=0.5992 val=0.5848
[nodo07] fold=2 epoch=8/32 train=0.6110 val=0.5696
[nodo07] fold=2 epoch=9/32 train=0.5956 val=0.5768
[nodo07] fold=2 epoch=10/32 train=0.6182 val=0.5752
[nodo07] fold=2 epoch=11/32 train=0.5655 val=0.5692
[nodo07] fold=2 epoch=12/32 train=0.5866 val=0.5799
[nodo07] fold=2 epoch=13/32 train=0.5980 val=0.5661
[nodo07] fold=2 epoch=14/32 train=0.5783 val=0.5736
[nodo07] fold=2 epoch=15/32 train=0.5954 val=0.5758
[nodo07] fold=2 epoch=16/32 train=0.5998 val=0.5653
[nodo07] fold=2 epoch=17/32 train=0.5819 val=0.5703
[nodo07] fold=2 epoch=18/32 train=0.5624 val=0.5676
[nodo07] fold=2 epoch=19/32 train=0.6107 val=0.5693
[nodo07] fold=2 epoch=20/32 train=0.5786 val=0.5657
[nodo07] fold=2 epoch=21/32 train=0.5827 val=0.5707
[nodo07] fold=2 epoch=22/32 train=0.5591 val=0.5646
[nodo07] fold=2 epoch=23/32 train=0.5962 val=0.5655
[nodo07] fold=2 epoch=24/32 train=0.5783 val=0.5624
[nodo07] fold=2 epoch=25/32 train=0.5444 val=0.5630
[nodo07] fold=2 epoch=26/32 train=0.5757 val=0.5603
[nodo07] fold=2 epoch=27/32 train=0.5492 val=0.5628
[nodo07] fold=2 epoch=28/32 train=0.5382 val=0.5631
[nodo07] fold=2 epoch=29/32 train=0.5698 val=0.5618
[nodo07] fold=2 epoch=30/32 train=0.5619 val=0.5613
[nodo07] fold=2 epoch=31/32 train=0.5537 val=0.5613
[nodo07] fold=2 epoch=32/32 train=0.5499 val=0.5615

[I 2026-08-31 15:44:09,278] Trial 5 finished with value: 0.5508430702612078 and parameters: {'dropout': 0.32521749351683216, 'tabular_embedding_dim': 16, 'augmentation_magnitude': 2.116002093532066, 'augmentation_probability': 0.8596290624728309, 'rotation_degrees': 2.99482186716807, 'learning_rate': 0.00019536357181104935, 'weight_decay': 7.767391493163822e-06, 'auxiliary_weight': 0.07853528925313409, 'consistency_weight': 0.02210432173186784, 'feature_top_k': 32, 'pca_variance': '0.95'}. Best is trial 4 with value: 0.5365909376439756.

[nodo07] fold=0 epoch=1/32 train=0.7458 val=0.6894
[nodo07] fold=0 epoch=2/32 train=0.7420 val=0.6928
[nodo07] fold=0 epoch=3/32 train=0.7369 val=0.6922
[nodo07] fold=0 epoch=4/32 train=0.7346 val=0.7024
[nodo07] fold=0 epoch=5/32 train=0.7404 val=0.6951
[nodo07] fold=0 epoch=6/32 train=0.7338 val=0.6898
[nodo07] fold=0 epoch=7/32 train=0.7368 val=0.6905
[nodo07] fold=0 epoch=8/32 train=0.7295 val=0.6861
[nodo07] fold=0 epoch=9/32 train=0.7382 val=0.6855
[nodo07] fold=0 epoch=10/32 train=0.7245 val=0.6810
[nodo07] fold=0 epoch=11/32 train=0.7233 val=0.6752
[nodo07] fold=0 epoch=12/32 train=0.7238 val=0.6852
[nodo07] fold=0 epoch=13/32 train=0.7156 val=0.6708
[nodo07] fold=0 epoch=14/32 train=0.7005 val=0.6827
[nodo07] fold=0 epoch=15/32 train=0.7163 val=0.6904
[nodo07] fold=0 epoch=16/32 train=0.6900 val=0.6887
[nodo07] fold=0 epoch=17/32 train=0.6966 val=0.6526
[nodo07] fold=0 epoch=18/32 train=0.6932 val=0.6382
[nodo07] fold=0 epoch=19/32 train=0.6965 val=0.6355
[nodo07] fold=0 epoch=20/32 train=0.6855 val=0.6622
[nodo07] fold=0 epoch=21/32 train=0.6872 val=0.6488
[nodo07] fold=0 epoch=22/32 train=0.6709 val=0.6284
[nodo07] fold=0 epoch=23/32 train=0.6653 val=0.6196
[nodo07] fold=0 epoch=24/32 train=0.6779 val=0.6198
[nodo07] fold=0 epoch=25/32 train=0.6718 val=0.6159
[nodo07] fold=0 epoch=26/32 train=0.6673 val=0.6316
[nodo07] fold=0 epoch=27/32 train=0.6572 val=0.6225
[nodo07] fold=0 epoch=28/32 train=0.6876 val=0.6208
[nodo07] fold=0 epoch=29/32 train=0.6526 val=0.6213
[nodo07] fold=0 epoch=30/32 train=0.6788 val=0.6198
[nodo07] fold=0 epoch=31/32 train=0.6439 val=0.6198
[nodo07] fold=0 epoch=32/32 train=0.6511 val=0.6189
[nodo07] fold=1 epoch=1/32 train=0.7503 val=0.6916
[nodo07] fold=1 epoch=2/32 train=0.7430 val=0.6895
[nodo07] fold=1 epoch=3/32 train=0.7415 val=0.7015
[nodo07] fold=1 epoch=4/32 train=0.7409 val=0.7057
[nodo07] fold=1 epoch=5/32 train=0.7416 val=0.6866
[nodo07] fold=1 epoch=6/32 train=0.7329 val=0.6964
[nodo07] fold=1 epoch=7/32 train=0.7310 val=0.6840
[nodo07] fold=1 epoch=8/32 train=0.7343 val=0.6860
[nodo07] fold=1 epoch=9/32 train=0.7370 val=0.6836
[nodo07] fold=1 epoch=10/32 train=0.7344 val=0.6830
[nodo07] fold=1 epoch=11/32 train=0.7277 val=0.6807
[nodo07] fold=1 epoch=12/32 train=0.7361 val=0.6871
[nodo07] fold=1 epoch=13/32 train=0.7271 val=0.6825
[nodo07] fold=1 epoch=14/32 train=0.7189 val=0.6723
[nodo07] fold=1 epoch=15/32 train=0.7163 val=0.6768
[nodo07] fold=1 epoch=16/32 train=0.7101 val=0.6799
[nodo07] fold=1 epoch=17/32 train=0.7037 val=0.6622
[nodo07] fold=1 epoch=18/32 train=0.7141 val=0.6650
[nodo07] fold=1 epoch=19/32 train=0.6991 val=0.6720
[nodo07] fold=1 epoch=20/32 train=0.7015 val=0.6809
[nodo07] fold=1 epoch=21/32 train=0.6830 val=0.6629
[nodo07] fold=1 epoch=22/32 train=0.6995 val=0.6494
[nodo07] fold=1 epoch=23/32 train=0.6797 val=0.6433
[nodo07] fold=1 epoch=24/32 train=0.6841 val=0.6469
[nodo07] fold=1 epoch=25/32 train=0.6959 val=0.6411
[nodo07] fold=1 epoch=26/32 train=0.6764 val=0.6431
[nodo07] fold=1 epoch=27/32 train=0.6776 val=0.6512
[nodo07] fold=1 epoch=28/32 train=0.6966 val=0.6438
[nodo07] fold=1 epoch=29/32 train=0.6845 val=0.6408
[nodo07] fold=1 epoch=30/32 train=0.6808 val=0.6394
[nodo07] fold=1 epoch=31/32 train=0.6760 val=0.6404
[nodo07] fold=1 epoch=32/32 train=0.6757 val=0.6406
[nodo07] fold=2 epoch=1/32 train=0.7484 val=0.6841
[nodo07] fold=2 epoch=2/32 train=0.7399 val=0.6829
[nodo07] fold=2 epoch=3/32 train=0.7446 val=0.6841
[nodo07] fold=2 epoch=4/32 train=0.7394 val=0.6927
[nodo07] fold=2 epoch=5/32 train=0.7339 val=0.6802
[nodo07] fold=2 epoch=6/32 train=0.7378 val=0.6901
[nodo07] fold=2 epoch=7/32 train=0.7357 val=0.6769
[nodo07] fold=2 epoch=8/32 train=0.7356 val=0.6727
[nodo07] fold=2 epoch=9/32 train=0.7284 val=0.6784
[nodo07] fold=2 epoch=10/32 train=0.7354 val=0.6820
[nodo07] fold=2 epoch=11/32 train=0.7201 val=0.6726
[nodo07] fold=2 epoch=12/32 train=0.7245 val=0.6806
[nodo07] fold=2 epoch=13/32 train=0.7179 val=0.6652
[nodo07] fold=2 epoch=14/32 train=0.7229 val=0.6675
[nodo07] fold=2 epoch=15/32 train=0.7128 val=0.6644
[nodo07] fold=2 epoch=16/32 train=0.7092 val=0.6598
[nodo07] fold=2 epoch=17/32 train=0.7124 val=0.6595
[nodo07] fold=2 epoch=18/32 train=0.7033 val=0.6572
[nodo07] fold=2 epoch=19/32 train=0.7077 val=0.6636
[nodo07] fold=2 epoch=20/32 train=0.7097 val=0.6512
[nodo07] fold=2 epoch=21/32 train=0.6989 val=0.6559
[nodo07] fold=2 epoch=22/32 train=0.6872 val=0.6442
[nodo07] fold=2 epoch=23/32 train=0.6956 val=0.6436
[nodo07] fold=2 epoch=24/32 train=0.7009 val=0.6438
[nodo07] fold=2 epoch=25/32 train=0.6912 val=0.6392
[nodo07] fold=2 epoch=26/32 train=0.6736 val=0.6371
[nodo07] fold=2 epoch=27/32 train=0.6864 val=0.6369
[nodo07] fold=2 epoch=28/32 train=0.6812 val=0.6376
[nodo07] fold=2 epoch=29/32 train=0.6829 val=0.6382
[nodo07] fold=2 epoch=30/32 train=0.6921 val=0.6373
[nodo07] fold=2 epoch=31/32 train=0.6916 val=0.6373
[nodo07] fold=2 epoch=32/32 train=0.6920 val=0.6373

[I 2026-08-31 16:35:44,161] Trial 6 finished with value: 0.630707153739591 and parameters: {'dropout': 0.28378936430571755, 'tabular_embedding_dim': 16, 'augmentation_magnitude': 2.153792429999304, 'augmentation_probability': 0.8826050622410041, 'rotation_degrees': 3.0448832495514733, 'learning_rate': 0.0002145334713607915, 'weight_decay': 5.255034353298426e-06, 'auxiliary_weight': 0.14323830436500576, 'consistency_weight': 0.009107705873237868, 'feature_top_k': 128, 'pca_variance': '0.95'}. Best is trial 4 with value: 0.5365909376439756.

[nodo07] fold=0 epoch=1/32 train=0.7189 val=0.6615
[nodo07] fold=0 epoch=2/32 train=0.6800 val=0.5871
[nodo07] fold=0 epoch=3/32 train=0.6261 val=0.5738
[nodo07] fold=0 epoch=4/32 train=0.6159 val=0.5727
[nodo07] fold=0 epoch=5/32 train=0.6165 val=0.5586
[nodo07] fold=0 epoch=6/32 train=0.6200 val=0.5487
[nodo07] fold=0 epoch=7/32 train=0.6120 val=0.5462
[nodo07] fold=0 epoch=8/32 train=0.6101 val=0.5367
[nodo07] fold=0 epoch=9/32 train=0.6132 val=0.5357
[nodo07] fold=0 epoch=10/32 train=0.5938 val=0.5287
[nodo07] fold=0 epoch=11/32 train=0.5906 val=0.5345
[nodo07] fold=0 epoch=12/32 train=0.5879 val=0.5431
[nodo07] fold=0 epoch=13/32 train=0.6128 val=0.5197
[nodo07] fold=0 epoch=14/32 train=0.5622 val=0.5206
[nodo07] fold=0 epoch=15/32 train=0.5787 val=0.5212
[nodo07] fold=0 epoch=16/32 train=0.5730 val=0.5288
[nodo07] fold=0 epoch=17/32 train=0.5556 val=0.5237
[nodo07] fold=0 epoch=18/32 train=0.5549 val=0.5172
[nodo07] fold=0 epoch=19/32 train=0.5463 val=0.5138
[nodo07] fold=0 epoch=20/32 train=0.5798 val=0.5156
[nodo07] fold=0 epoch=21/32 train=0.5604 val=0.5141
[nodo07] fold=0 epoch=22/32 train=0.5258 val=0.5121
[nodo07] fold=0 epoch=23/32 train=0.5422 val=0.5118
[nodo07] fold=0 epoch=24/32 train=0.5726 val=0.5105
[nodo07] fold=0 epoch=25/32 train=0.5397 val=0.5111
[nodo07] fold=0 epoch=26/32 train=0.5425 val=0.5135
[nodo07] fold=0 epoch=27/32 train=0.5468 val=0.5111
[nodo07] fold=0 epoch=28/32 train=0.5691 val=0.5098
[nodo07] fold=0 epoch=29/32 train=0.5372 val=0.5110
[nodo07] fold=0 epoch=30/32 train=0.5513 val=0.5111
[nodo07] fold=0 epoch=31/32 train=0.5331 val=0.5112
[nodo07] fold=0 epoch=32/32 train=0.5014 val=0.5112
[nodo07] fold=1 epoch=1/32 train=0.7178 val=0.6511
[nodo07] fold=1 epoch=2/32 train=0.6735 val=0.6228
[nodo07] fold=1 epoch=3/32 train=0.6162 val=0.6361
[nodo07] fold=1 epoch=4/32 train=0.6322 val=0.6012
[nodo07] fold=1 epoch=5/32 train=0.6126 val=0.5847
[nodo07] fold=1 epoch=6/32 train=0.6228 val=0.5867
[nodo07] fold=1 epoch=7/32 train=0.5885 val=0.5614
[nodo07] fold=1 epoch=8/32 train=0.5854 val=0.5583
[nodo07] fold=1 epoch=9/32 train=0.5748 val=0.5486
[nodo07] fold=1 epoch=10/32 train=0.5971 val=0.5502
[nodo07] fold=1 epoch=11/32 train=0.5756 val=0.5465
[nodo07] fold=1 epoch=12/32 train=0.5698 val=0.5456
[nodo07] fold=1 epoch=13/32 train=0.5861 val=0.5467
[nodo07] fold=1 epoch=14/32 train=0.5518 val=0.5427
[nodo07] fold=1 epoch=15/32 train=0.5490 val=0.5512
[nodo07] fold=1 epoch=16/32 train=0.5337 val=0.5550
[nodo07] fold=1 epoch=17/32 train=0.5413 val=0.5562
[nodo07] fold=1 epoch=18/32 train=0.5673 val=0.5388
[nodo07] fold=1 epoch=19/32 train=0.5413 val=0.5659
[nodo07] fold=1 epoch=20/32 train=0.5174 val=0.5607
[nodo07] fold=1 epoch=21/32 train=0.5437 val=0.5482
[nodo07] fold=1 epoch=22/32 train=0.5355 val=0.5502
[nodo07] fold=1 epoch=23/32 train=0.5392 val=0.5439
[nodo07] fold=1 epoch=24/32 train=0.5412 val=0.5461
[nodo07] fold=1 epoch=25/32 train=0.5581 val=0.5401
[nodo07] fold=1 epoch=26/32 train=0.5487 val=0.5426
[nodo07] fold=1 epoch=27/32 train=0.5187 val=0.5476
[nodo07] fold=2 epoch=1/32 train=0.7242 val=0.6591
[nodo07] fold=2 epoch=2/32 train=0.6593 val=0.5904
[nodo07] fold=2 epoch=3/32 train=0.6350 val=0.5847
[nodo07] fold=2 epoch=4/32 train=0.6371 val=0.5914
[nodo07] fold=2 epoch=5/32 train=0.6223 val=0.5744
[nodo07] fold=2 epoch=6/32 train=0.5964 val=0.6020
[nodo07] fold=2 epoch=7/32 train=0.5948 val=0.5710
[nodo07] fold=2 epoch=8/32 train=0.5946 val=0.5615
[nodo07] fold=2 epoch=9/32 train=0.5776 val=0.5698
[nodo07] fold=2 epoch=10/32 train=0.6109 val=0.5571
[nodo07] fold=2 epoch=11/32 train=0.5572 val=0.5546
[nodo07] fold=2 epoch=12/32 train=0.5743 val=0.5662
[nodo07] fold=2 epoch=13/32 train=0.5675 val=0.5524
[nodo07] fold=2 epoch=14/32 train=0.5537 val=0.5616
[nodo07] fold=2 epoch=15/32 train=0.5689 val=0.5699
[nodo07] fold=2 epoch=16/32 train=0.5604 val=0.5617
[nodo07] fold=2 epoch=17/32 train=0.5641 val=0.5641
[nodo07] fold=2 epoch=18/32 train=0.5183 val=0.5589
[nodo07] fold=2 epoch=19/32 train=0.5863 val=0.5607
[nodo07] fold=2 epoch=20/32 train=0.5431 val=0.5588
[nodo07] fold=2 epoch=21/32 train=0.5585 val=0.5723
[nodo07] fold=2 epoch=22/32 train=0.5483 val=0.5598

[I 2026-08-31 17:16:44,150] Trial 7 finished with value: 0.5336554752792667 and parameters: {'dropout': 0.253083893665716, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.0200036878526686, 'augmentation_probability': 0.885256306783847, 'rotation_degrees': 2.7407866279322857, 'learning_rate': 0.00012046001944133536, 'weight_decay': 2.579589552255739e-05, 'auxiliary_weight': 0.08792460891529397, 'consistency_weight': 0.040982166924918725, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 7 with value: 0.5336554752792667.

[nodo07] fold=0 epoch=1/32 train=0.7144 val=0.6532
[nodo07] fold=0 epoch=2/32 train=0.6987 val=0.6161
[nodo07] fold=0 epoch=3/32 train=0.6596 val=0.6019
[nodo07] fold=0 epoch=4/32 train=0.6438 val=0.5924
[nodo07] fold=0 epoch=5/32 train=0.6364 val=0.5802
[nodo07] fold=0 epoch=6/32 train=0.6349 val=0.5708
[nodo07] fold=0 epoch=7/32 train=0.6388 val=0.5766
[nodo07] fold=0 epoch=8/32 train=0.6262 val=0.5645
[nodo07] fold=0 epoch=9/32 train=0.6344 val=0.5615
[nodo07] fold=0 epoch=10/32 train=0.6243 val=0.5605
[nodo07] fold=0 epoch=11/32 train=0.6095 val=0.5717
[nodo07] fold=0 epoch=12/32 train=0.6265 val=0.5718
[nodo07] fold=0 epoch=13/32 train=0.6425 val=0.5540
[nodo07] fold=0 epoch=14/32 train=0.6079 val=0.5548
[nodo07] fold=0 epoch=15/32 train=0.6185 val=0.5600
[nodo07] fold=0 epoch=16/32 train=0.6063 val=0.5629
[nodo07] fold=0 epoch=17/32 train=0.6063 val=0.5555
[nodo07] fold=0 epoch=18/32 train=0.6059 val=0.5456
[nodo07] fold=0 epoch=19/32 train=0.5877 val=0.5447
[nodo07] fold=0 epoch=20/32 train=0.6099 val=0.5530
[nodo07] fold=0 epoch=21/32 train=0.6059 val=0.5490
[nodo07] fold=0 epoch=22/32 train=0.5678 val=0.5442
[nodo07] fold=0 epoch=23/32 train=0.5825 val=0.5449
[nodo07] fold=0 epoch=24/32 train=0.6114 val=0.5454
[nodo07] fold=0 epoch=25/32 train=0.5830 val=0.5439
[nodo07] fold=0 epoch=26/32 train=0.5911 val=0.5463
[nodo07] fold=0 epoch=27/32 train=0.5952 val=0.5458
[nodo07] fold=0 epoch=28/32 train=0.6062 val=0.5437
[nodo07] fold=0 epoch=29/32 train=0.5860 val=0.5450
[nodo07] fold=0 epoch=30/32 train=0.5972 val=0.5445
[nodo07] fold=0 epoch=31/32 train=0.5858 val=0.5446
[nodo07] fold=0 epoch=32/32 train=0.5566 val=0.5444
[nodo07] fold=1 epoch=1/32 train=0.7159 val=0.6468
[nodo07] fold=1 epoch=2/32 train=0.6825 val=0.6322
[nodo07] fold=1 epoch=3/32 train=0.6480 val=0.6212
[nodo07] fold=1 epoch=4/32 train=0.6487 val=0.6166
[nodo07] fold=1 epoch=5/32 train=0.6384 val=0.6038
[nodo07] fold=1 epoch=6/32 train=0.6496 val=0.6050
[nodo07] fold=1 epoch=7/32 train=0.6262 val=0.5948
[nodo07] fold=1 epoch=8/32 train=0.6260 val=0.5937
[nodo07] fold=1 epoch=9/32 train=0.6276 val=0.5896
[nodo07] fold=1 epoch=10/32 train=0.6288 val=0.5932
[nodo07] fold=1 epoch=11/32 train=0.6457 val=0.5816
[nodo07] fold=1 epoch=12/32 train=0.6272 val=0.5811
[nodo07] fold=1 epoch=13/32 train=0.6242 val=0.5813
[nodo07] fold=1 epoch=14/32 train=0.5934 val=0.5818
[nodo07] fold=1 epoch=15/32 train=0.5858 val=0.5816
[nodo07] fold=1 epoch=16/32 train=0.5727 val=0.5859
[nodo07] fold=1 epoch=17/32 train=0.5920 val=0.5816
[nodo07] fold=1 epoch=18/32 train=0.6232 val=0.5750
[nodo07] fold=1 epoch=19/32 train=0.5867 val=0.5783
[nodo07] fold=1 epoch=20/32 train=0.5687 val=0.5791
[nodo07] fold=1 epoch=21/32 train=0.5883 val=0.5841
[nodo07] fold=1 epoch=22/32 train=0.5712 val=0.5732
[nodo07] fold=1 epoch=23/32 train=0.5808 val=0.5691
[nodo07] fold=1 epoch=24/32 train=0.5899 val=0.5704
[nodo07] fold=1 epoch=25/32 train=0.6006 val=0.5682
[nodo07] fold=1 epoch=26/32 train=0.5940 val=0.5683
[nodo07] fold=1 epoch=27/32 train=0.5693 val=0.5699
[nodo07] fold=1 epoch=28/32 train=0.6108 val=0.5688
[nodo07] fold=1 epoch=29/32 train=0.5780 val=0.5680
[nodo07] fold=1 epoch=30/32 train=0.6087 val=0.5675
[nodo07] fold=1 epoch=31/32 train=0.5821 val=0.5678
[nodo07] fold=1 epoch=32/32 train=0.6053 val=0.5677

[I 2026-08-31 17:51:09,507] Trial 8 pruned.

[nodo07] fold=0 epoch=1/32 train=0.7129 val=0.6465
[nodo07] fold=0 epoch=2/32 train=0.6537 val=0.5809
[nodo07] fold=0 epoch=3/32 train=0.6205 val=0.5763
[nodo07] fold=0 epoch=4/32 train=0.6100 val=0.5684
[nodo07] fold=0 epoch=5/32 train=0.6108 val=0.5540
[nodo07] fold=0 epoch=6/32 train=0.6120 val=0.5443
[nodo07] fold=0 epoch=7/32 train=0.6013 val=0.5409
[nodo07] fold=0 epoch=8/32 train=0.6013 val=0.5288
[nodo07] fold=0 epoch=9/32 train=0.6045 val=0.5312
[nodo07] fold=0 epoch=10/32 train=0.5876 val=0.5225
[nodo07] fold=0 epoch=11/32 train=0.5816 val=0.5318
[nodo07] fold=0 epoch=12/32 train=0.5820 val=0.5375
[nodo07] fold=0 epoch=13/32 train=0.6054 val=0.5124
[nodo07] fold=0 epoch=14/32 train=0.5510 val=0.5121
[nodo07] fold=0 epoch=15/32 train=0.5701 val=0.5107
[nodo07] fold=0 epoch=16/32 train=0.5611 val=0.5194
[nodo07] fold=0 epoch=17/32 train=0.5435 val=0.5216
[nodo07] fold=0 epoch=18/32 train=0.5457 val=0.5093
[nodo07] fold=0 epoch=19/32 train=0.5373 val=0.5083
[nodo07] fold=0 epoch=20/32 train=0.5673 val=0.5055
[nodo07] fold=0 epoch=21/32 train=0.5471 val=0.5080
[nodo07] fold=0 epoch=22/32 train=0.5136 val=0.5067
[nodo07] fold=0 epoch=23/32 train=0.5303 val=0.5064
[nodo07] fold=0 epoch=24/32 train=0.5567 val=0.5043
[nodo07] fold=0 epoch=25/32 train=0.5313 val=0.5066
[nodo07] fold=0 epoch=26/32 train=0.5296 val=0.5084
[nodo07] fold=0 epoch=27/32 train=0.5339 val=0.5054
[nodo07] fold=0 epoch=28/32 train=0.5572 val=0.5047
[nodo07] fold=0 epoch=29/32 train=0.5251 val=0.5062
[nodo07] fold=0 epoch=30/32 train=0.5429 val=0.5064
[nodo07] fold=0 epoch=31/32 train=0.5222 val=0.5065
[nodo07] fold=0 epoch=32/32 train=0.4895 val=0.5065
[nodo07] fold=1 epoch=1/32 train=0.7097 val=0.6357
[nodo07] fold=1 epoch=2/32 train=0.6597 val=0.6084
[nodo07] fold=1 epoch=3/32 train=0.6054 val=0.6235
[nodo07] fold=1 epoch=4/32 train=0.6211 val=0.5955
[nodo07] fold=1 epoch=5/32 train=0.6021 val=0.5780
[nodo07] fold=1 epoch=6/32 train=0.6101 val=0.5761
[nodo07] fold=1 epoch=7/32 train=0.5733 val=0.5571
[nodo07] fold=1 epoch=8/32 train=0.5744 val=0.5497
[nodo07] fold=1 epoch=9/32 train=0.5620 val=0.5469
[nodo07] fold=1 epoch=10/32 train=0.5906 val=0.5517
[nodo07] fold=1 epoch=11/32 train=0.5679 val=0.5444
[nodo07] fold=1 epoch=12/32 train=0.5630 val=0.5436
[nodo07] fold=1 epoch=13/32 train=0.5811 val=0.5442
[nodo07] fold=1 epoch=14/32 train=0.5481 val=0.5410
[nodo07] fold=1 epoch=15/32 train=0.5447 val=0.5469
[nodo07] fold=1 epoch=16/32 train=0.5236 val=0.5536
[nodo07] fold=1 epoch=17/32 train=0.5299 val=0.5505
[nodo07] fold=1 epoch=18/32 train=0.5577 val=0.5384
[nodo07] fold=1 epoch=19/32 train=0.5326 val=0.5624
[nodo07] fold=1 epoch=20/32 train=0.5051 val=0.5590
[nodo07] fold=1 epoch=21/32 train=0.5351 val=0.5487
[nodo07] fold=1 epoch=22/32 train=0.5261 val=0.5437
[nodo07] fold=1 epoch=23/32 train=0.5320 val=0.5406
[nodo07] fold=1 epoch=24/32 train=0.5354 val=0.5449
[nodo07] fold=1 epoch=25/32 train=0.5502 val=0.5418
[nodo07] fold=1 epoch=26/32 train=0.5402 val=0.5405
[nodo07] fold=1 epoch=27/32 train=0.5103 val=0.5439
[nodo07] fold=2 epoch=1/32 train=0.7128 val=0.6380
[nodo07] fold=2 epoch=2/32 train=0.6328 val=0.5841
[nodo07] fold=2 epoch=3/32 train=0.6274 val=0.5853
[nodo07] fold=2 epoch=4/32 train=0.6323 val=0.5891
[nodo07] fold=2 epoch=5/32 train=0.6089 val=0.5730
[nodo07] fold=2 epoch=6/32 train=0.5859 val=0.6109
[nodo07] fold=2 epoch=7/32 train=0.5853 val=0.5699
[nodo07] fold=2 epoch=8/32 train=0.5821 val=0.5577
[nodo07] fold=2 epoch=9/32 train=0.5689 val=0.5671
[nodo07] fold=2 epoch=10/32 train=0.6007 val=0.5550
[nodo07] fold=2 epoch=11/32 train=0.5474 val=0.5538
[nodo07] fold=2 epoch=12/32 train=0.5669 val=0.5640
[nodo07] fold=2 epoch=13/32 train=0.5600 val=0.5494
[nodo07] fold=2 epoch=14/32 train=0.5457 val=0.5606
[nodo07] fold=2 epoch=15/32 train=0.5547 val=0.5689
[nodo07] fold=2 epoch=16/32 train=0.5526 val=0.5567
[nodo07] fold=2 epoch=17/32 train=0.5591 val=0.5632
[nodo07] fold=2 epoch=18/32 train=0.5089 val=0.5624
[nodo07] fold=2 epoch=19/32 train=0.5820 val=0.5594
[nodo07] fold=2 epoch=20/32 train=0.5344 val=0.5567
[nodo07] fold=2 epoch=21/32 train=0.5501 val=0.5675
[nodo07] fold=2 epoch=22/32 train=0.5364 val=0.5551

[I 2026-08-31 19:53:03,434] Trial 9 finished with value: 0.53069357448389 and parameters: {'dropout': 0.2629582656620503, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.2425241654120622, 'augmentation_probability': 0.8966289651290336, 'rotation_degrees': 3.0379756530830626, 'learning_rate': 0.00015756413982914887, 'weight_decay': 2.1764068253044486e-05, 'auxiliary_weight': 0.07493136237915807, 'consistency_weight': 0.03564292780477432, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 9 with value: 0.53069357448389.

[nodo07] fold=0 epoch=1/32 train=0.7070 val=0.6070
[nodo07] fold=0 epoch=2/32 train=0.6379 val=0.5437
[nodo07] fold=0 epoch=3/32 train=0.6125 val=0.5388
[nodo07] fold=0 epoch=4/32 train=0.5994 val=0.5137
[nodo07] fold=0 epoch=5/32 train=0.5825 val=0.5075
[nodo07] fold=0 epoch=6/32 train=0.5561 val=0.5032
[nodo07] fold=0 epoch=7/32 train=0.5425 val=0.5048
[nodo07] fold=0 epoch=8/32 train=0.5084 val=0.5122
[nodo07] fold=0 epoch=9/32 train=0.5221 val=0.5140
[nodo07] fold=0 epoch=10/32 train=0.5233 val=0.5035
[nodo07] fold=0 epoch=11/32 train=0.4818 val=0.5233
[nodo07] fold=0 epoch=12/32 train=0.4888 val=0.5214
[nodo07] fold=0 epoch=13/32 train=0.4976 val=0.5166
[nodo07] fold=0 epoch=14/32 train=0.4542 val=0.5236
[nodo07] fold=0 epoch=15/32 train=0.4736 val=0.5200
[nodo07] fold=1 epoch=1/32 train=0.7087 val=0.6162
[nodo07] fold=1 epoch=2/32 train=0.6350 val=0.5991
[nodo07] fold=1 epoch=3/32 train=0.5736 val=0.6114
[nodo07] fold=1 epoch=4/32 train=0.5645 val=0.5921
[nodo07] fold=1 epoch=5/32 train=0.5343 val=0.6021
[nodo07] fold=1 epoch=6/32 train=0.5457 val=0.5805
[nodo07] fold=1 epoch=7/32 train=0.5027 val=0.5863
[nodo07] fold=1 epoch=8/32 train=0.4854 val=0.5923
[nodo07] fold=1 epoch=9/32 train=0.4538 val=0.6189
[nodo07] fold=1 epoch=10/32 train=0.4914 val=0.6122
[nodo07] fold=1 epoch=11/32 train=0.4597 val=0.6098
[nodo07] fold=1 epoch=12/32 train=0.4633 val=0.6076
[nodo07] fold=1 epoch=13/32 train=0.4517 val=0.6313
[nodo07] fold=1 epoch=14/32 train=0.4338 val=0.6366
[nodo07] fold=1 epoch=15/32 train=0.4094 val=0.6498
[nodo07] fold=2 epoch=1/32 train=0.6963 val=0.5826
[nodo07] fold=2 epoch=2/32 train=0.6095 val=0.5710
[nodo07] fold=2 epoch=3/32 train=0.5846 val=0.5742
[nodo07] fold=2 epoch=4/32 train=0.6250 val=0.5796
[nodo07] fold=2 epoch=5/32 train=0.5659 val=0.5557
[nodo07] fold=2 epoch=6/32 train=0.5350 val=0.6062
[nodo07] fold=2 epoch=7/32 train=0.5105 val=0.5737
[nodo07] fold=2 epoch=8/32 train=0.5265 val=0.5660
[nodo07] fold=2 epoch=9/32 train=0.4995 val=0.5925
[nodo07] fold=2 epoch=10/32 train=0.5038 val=0.5878
[nodo07] fold=2 epoch=11/32 train=0.4558 val=0.5892
[nodo07] fold=2 epoch=12/32 train=0.4429 val=0.6156
[nodo07] fold=2 epoch=13/32 train=0.4899 val=0.5953
[nodo07] fold=2 epoch=14/32 train=0.4529 val=0.5814

[I 2026-08-31 20:23:46,483] Trial 10 finished with value: 0.5464727497899872 and parameters: {'dropout': 0.2822850210917319, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.4528894274879933, 'augmentation_probability': 0.8900263350255634, 'rotation_degrees': 2.759115190623958, 'learning_rate': 0.00012275560796307515, 'weight_decay': 2.4736726264715107e-05, 'auxiliary_weight': 0.09152285030693874, 'consistency_weight': 0.026303407192529257, 'feature_top_k': 128, 'pca_variance': 'none'}. Best is trial 9 with value: 0.53069357448389.

[nodo07] fold=0 epoch=1/32 train=0.7167 val=0.6602
[nodo07] fold=0 epoch=2/32 train=0.6693 val=0.5731
[nodo07] fold=0 epoch=3/32 train=0.6208 val=0.5751
[nodo07] fold=0 epoch=4/32 train=0.6101 val=0.5660
[nodo07] fold=0 epoch=5/32 train=0.6130 val=0.5518
[nodo07] fold=0 epoch=6/32 train=0.6136 val=0.5441
[nodo07] fold=0 epoch=7/32 train=0.6039 val=0.5371
[nodo07] fold=0 epoch=8/32 train=0.6038 val=0.5296
[nodo07] fold=0 epoch=9/32 train=0.6032 val=0.5300
[nodo07] fold=0 epoch=10/32 train=0.5860 val=0.5223
[nodo07] fold=0 epoch=11/32 train=0.5826 val=0.5303
[nodo07] fold=0 epoch=12/32 train=0.5837 val=0.5370
[nodo07] fold=0 epoch=13/32 train=0.6060 val=0.5118
[nodo07] fold=0 epoch=14/32 train=0.5530 val=0.5124
[nodo07] fold=0 epoch=15/32 train=0.5726 val=0.5108
[nodo07] fold=0 epoch=16/32 train=0.5646 val=0.5193
[nodo07] fold=0 epoch=17/32 train=0.5435 val=0.5186
[nodo07] fold=0 epoch=18/32 train=0.5508 val=0.5122
[nodo07] fold=0 epoch=19/32 train=0.5442 val=0.5085
[nodo07] fold=0 epoch=20/32 train=0.5664 val=0.5088
[nodo07] fold=0 epoch=21/32 train=0.5504 val=0.5075
[nodo07] fold=0 epoch=22/32 train=0.5145 val=0.5068
[nodo07] fold=0 epoch=23/32 train=0.5356 val=0.5060
[nodo07] fold=0 epoch=24/32 train=0.5598 val=0.5049
[nodo07] fold=0 epoch=25/32 train=0.5337 val=0.5063
[nodo07] fold=0 epoch=26/32 train=0.5309 val=0.5087
[nodo07] fold=0 epoch=27/32 train=0.5375 val=0.5059
[nodo07] fold=0 epoch=28/32 train=0.5572 val=0.5049
[nodo07] fold=0 epoch=29/32 train=0.5275 val=0.5063
[nodo07] fold=0 epoch=30/32 train=0.5473 val=0.5063
[nodo07] fold=0 epoch=31/32 train=0.5220 val=0.5062
[nodo07] fold=0 epoch=32/32 train=0.4929 val=0.5063
[nodo07] fold=1 epoch=1/32 train=0.7161 val=0.6431
[nodo07] fold=1 epoch=2/32 train=0.6641 val=0.6089
[nodo07] fold=1 epoch=3/32 train=0.6054 val=0.6240
[nodo07] fold=1 epoch=4/32 train=0.6222 val=0.6021
[nodo07] fold=1 epoch=5/32 train=0.6046 val=0.5774
[nodo07] fold=1 epoch=6/32 train=0.6102 val=0.5702
[nodo07] fold=1 epoch=7/32 train=0.5712 val=0.5578
[nodo07] fold=1 epoch=8/32 train=0.5753 val=0.5510
[nodo07] fold=1 epoch=9/32 train=0.5633 val=0.5476
[nodo07] fold=1 epoch=10/32 train=0.5881 val=0.5515
[nodo07] fold=1 epoch=11/32 train=0.5677 val=0.5411
[nodo07] fold=1 epoch=12/32 train=0.5642 val=0.5433
[nodo07] fold=1 epoch=13/32 train=0.5838 val=0.5447
[nodo07] fold=1 epoch=14/32 train=0.5467 val=0.5410
[nodo07] fold=1 epoch=15/32 train=0.5395 val=0.5501
[nodo07] fold=1 epoch=16/32 train=0.5244 val=0.5546
[nodo07] fold=1 epoch=17/32 train=0.5336 val=0.5521
[nodo07] fold=1 epoch=18/32 train=0.5594 val=0.5407
[nodo07] fold=1 epoch=19/32 train=0.5343 val=0.5650
[nodo07] fold=1 epoch=20/32 train=0.5090 val=0.5572
[nodo07] fold=1 epoch=21/32 train=0.5348 val=0.5489
[nodo07] fold=1 epoch=22/32 train=0.5268 val=0.5484
[nodo07] fold=1 epoch=23/32 train=0.5312 val=0.5443
[nodo07] fold=1 epoch=24/32 train=0.5353 val=0.5495
[nodo07] fold=1 epoch=25/32 train=0.5512 val=0.5453
[nodo07] fold=1 epoch=26/32 train=0.5404 val=0.5455
[nodo07] fold=1 epoch=27/32 train=0.5105 val=0.5492
[nodo07] fold=2 epoch=1/32 train=0.7193 val=0.6446
[nodo07] fold=2 epoch=2/32 train=0.6416 val=0.5832
[nodo07] fold=2 epoch=3/32 train=0.6280 val=0.5832
[nodo07] fold=2 epoch=4/32 train=0.6334 val=0.5871
[nodo07] fold=2 epoch=5/32 train=0.6140 val=0.5727
[nodo07] fold=2 epoch=6/32 train=0.5900 val=0.6112
[nodo07] fold=2 epoch=7/32 train=0.5898 val=0.5703
[nodo07] fold=2 epoch=8/32 train=0.5899 val=0.5608
[nodo07] fold=2 epoch=9/32 train=0.5707 val=0.5704
[nodo07] fold=2 epoch=10/32 train=0.6048 val=0.5588
[nodo07] fold=2 epoch=11/32 train=0.5530 val=0.5569
[nodo07] fold=2 epoch=12/32 train=0.5659 val=0.5656
[nodo07] fold=2 epoch=13/32 train=0.5618 val=0.5529
[nodo07] fold=2 epoch=14/32 train=0.5493 val=0.5610
[nodo07] fold=2 epoch=15/32 train=0.5576 val=0.5648
[nodo07] fold=2 epoch=16/32 train=0.5558 val=0.5575
[nodo07] fold=2 epoch=17/32 train=0.5594 val=0.5595
[nodo07] fold=2 epoch=18/32 train=0.5153 val=0.5588
[nodo07] fold=2 epoch=19/32 train=0.5794 val=0.5568
[nodo07] fold=2 epoch=20/32 train=0.5357 val=0.5542
[nodo07] fold=2 epoch=21/32 train=0.5460 val=0.5646
[nodo07] fold=2 epoch=22/32 train=0.5378 val=0.5522
[nodo07] fold=2 epoch=23/32 train=0.5609 val=0.5555
[nodo07] fold=2 epoch=24/32 train=0.5351 val=0.5527
[nodo07] fold=2 epoch=25/32 train=0.5160 val=0.5537
[nodo07] fold=2 epoch=26/32 train=0.5398 val=0.5511
[nodo07] fold=2 epoch=27/32 train=0.5197 val=0.5546
[nodo07] fold=2 epoch=28/32 train=0.5109 val=0.5547
[nodo07] fold=2 epoch=29/32 train=0.5383 val=0.5532
[nodo07] fold=2 epoch=30/32 train=0.5354 val=0.5530
[nodo07] fold=2 epoch=31/32 train=0.5310 val=0.5530
[nodo07] fold=2 epoch=32/32 train=0.5166 val=0.5532

[I 2026-08-31 22:00:20,330] Trial 11 finished with value: 0.5322409462191281 and parameters: {'dropout': 0.2771025614055247, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.164859491432268, 'augmentation_probability': 0.8392721658079727, 'rotation_degrees': 2.989852987587441, 'learning_rate': 0.0001626014934225234, 'weight_decay': 1.141396218395385e-05, 'auxiliary_weight': 0.07921821396611241, 'consistency_weight': 0.03975124747990014, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 9 with value: 0.53069357448389.

[nodo07] fold=0 epoch=1/32 train=0.7164 val=0.6657
[nodo07] fold=0 epoch=2/32 train=0.6798 val=0.6108
[nodo07] fold=0 epoch=3/32 train=0.6355 val=0.5847
[nodo07] fold=0 epoch=4/32 train=0.6318 val=0.5710
[nodo07] fold=0 epoch=5/32 train=0.6131 val=0.5500
[nodo07] fold=0 epoch=6/32 train=0.6060 val=0.5422
[nodo07] fold=0 epoch=7/32 train=0.6175 val=0.5384
[nodo07] fold=0 epoch=8/32 train=0.6122 val=0.5330
[nodo07] fold=0 epoch=9/32 train=0.5987 val=0.5317
[nodo07] fold=0 epoch=10/32 train=0.5963 val=0.5276
[nodo07] fold=0 epoch=11/32 train=0.5892 val=0.5405
[nodo07] fold=0 epoch=12/32 train=0.5925 val=0.5343
[nodo07] fold=0 epoch=13/32 train=0.6131 val=0.5211
[nodo07] fold=0 epoch=14/32 train=0.5679 val=0.5184
[nodo07] fold=0 epoch=15/32 train=0.5993 val=0.5275
[nodo07] fold=0 epoch=16/32 train=0.5762 val=0.5343
[nodo07] fold=0 epoch=17/32 train=0.5678 val=0.5300
[nodo07] fold=0 epoch=18/32 train=0.5704 val=0.5209
[nodo07] fold=0 epoch=19/32 train=0.5753 val=0.5217
[nodo07] fold=0 epoch=20/32 train=0.5775 val=0.5220
[nodo07] fold=0 epoch=21/32 train=0.5669 val=0.5214
[nodo07] fold=0 epoch=22/32 train=0.5390 val=0.5143
[nodo07] fold=0 epoch=23/32 train=0.5609 val=0.5131
[nodo07] fold=0 epoch=24/32 train=0.5731 val=0.5138
[nodo07] fold=0 epoch=25/32 train=0.5496 val=0.5137
[nodo07] fold=0 epoch=26/32 train=0.5413 val=0.5162
[nodo07] fold=0 epoch=27/32 train=0.5451 val=0.5150
[nodo07] fold=0 epoch=28/32 train=0.5590 val=0.5139
[nodo07] fold=0 epoch=29/32 train=0.5471 val=0.5153
[nodo07] fold=0 epoch=30/32 train=0.5460 val=0.5156
[nodo07] fold=0 epoch=31/32 train=0.5325 val=0.5154
[nodo07] fold=0 epoch=32/32 train=0.5196 val=0.5153
[nodo07] fold=1 epoch=1/32 train=0.7127 val=0.6520
[nodo07] fold=1 epoch=2/32 train=0.6641 val=0.6292
[nodo07] fold=1 epoch=3/32 train=0.6291 val=0.6236
[nodo07] fold=1 epoch=4/32 train=0.6056 val=0.5987
[nodo07] fold=1 epoch=5/32 train=0.5865 val=0.5921
[nodo07] fold=1 epoch=6/32 train=0.6025 val=0.5966
[nodo07] fold=1 epoch=7/32 train=0.5762 val=0.5808
[nodo07] fold=1 epoch=8/32 train=0.5711 val=0.5743
[nodo07] fold=1 epoch=9/32 train=0.5716 val=0.5771
[nodo07] fold=1 epoch=10/32 train=0.5817 val=0.5770
[nodo07] fold=1 epoch=11/32 train=0.5651 val=0.5855
[nodo07] fold=1 epoch=12/32 train=0.5605 val=0.5715
[nodo07] fold=1 epoch=13/32 train=0.5800 val=0.5773
[nodo07] fold=1 epoch=14/32 train=0.5488 val=0.5800
[nodo07] fold=1 epoch=15/32 train=0.5310 val=0.5839
[nodo07] fold=1 epoch=16/32 train=0.5123 val=0.5884
[nodo07] fold=1 epoch=17/32 train=0.5496 val=0.5836
[nodo07] fold=1 epoch=18/32 train=0.5701 val=0.5696
[nodo07] fold=1 epoch=19/32 train=0.5404 val=0.5872
[nodo07] fold=1 epoch=20/32 train=0.5118 val=0.5919
[nodo07] fold=1 epoch=21/32 train=0.5413 val=0.5818
[nodo07] fold=1 epoch=22/32 train=0.5289 val=0.5782
[nodo07] fold=1 epoch=23/32 train=0.5362 val=0.5767
[nodo07] fold=1 epoch=24/32 train=0.5368 val=0.5764
[nodo07] fold=1 epoch=25/32 train=0.5580 val=0.5694
[nodo07] fold=1 epoch=26/32 train=0.5545 val=0.5685
[nodo07] fold=1 epoch=27/32 train=0.4981 val=0.5737
[nodo07] fold=1 epoch=28/32 train=0.5555 val=0.5729
[nodo07] fold=1 epoch=29/32 train=0.5217 val=0.5745
[nodo07] fold=1 epoch=30/32 train=0.5506 val=0.5731
[nodo07] fold=1 epoch=31/32 train=0.5399 val=0.5733
[nodo07] fold=1 epoch=32/32 train=0.5286 val=0.5733
[nodo07] fold=2 epoch=1/32 train=0.7076 val=0.6428
[nodo07] fold=2 epoch=2/32 train=0.6407 val=0.5742
[nodo07] fold=2 epoch=3/32 train=0.6108 val=0.5724
[nodo07] fold=2 epoch=4/32 train=0.6219 val=0.5875
[nodo07] fold=2 epoch=5/32 train=0.5823 val=0.5654
[nodo07] fold=2 epoch=6/32 train=0.5583 val=0.6067
[nodo07] fold=2 epoch=7/32 train=0.5633 val=0.5635
[nodo07] fold=2 epoch=8/32 train=0.5774 val=0.5514
[nodo07] fold=2 epoch=9/32 train=0.5571 val=0.5640
[nodo07] fold=2 epoch=10/32 train=0.5865 val=0.5583
[nodo07] fold=2 epoch=11/32 train=0.5479 val=0.5460
[nodo07] fold=2 epoch=12/32 train=0.5529 val=0.5627
[nodo07] fold=2 epoch=13/32 train=0.5542 val=0.5458
[nodo07] fold=2 epoch=14/32 train=0.5403 val=0.5639
[nodo07] fold=2 epoch=15/32 train=0.5507 val=0.5707
[nodo07] fold=2 epoch=16/32 train=0.5538 val=0.5558
[nodo07] fold=2 epoch=17/32 train=0.5462 val=0.5610
[nodo07] fold=2 epoch=18/32 train=0.5187 val=0.5568
[nodo07] fold=2 epoch=19/32 train=0.5774 val=0.5587
[nodo07] fold=2 epoch=20/32 train=0.5321 val=0.5515
[nodo07] fold=2 epoch=21/32 train=0.5438 val=0.5638
[nodo07] fold=2 epoch=22/32 train=0.5212 val=0.5548

[I 2026-08-31 22:44:58,034] Trial 12 finished with value: 0.5424560321605735 and parameters: {'dropout': 0.23421073849208515, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.2689246787594284, 'augmentation_probability': 0.8434334891715884, 'rotation_degrees': 3.1121198895594038, 'learning_rate': 0.0001770703523481886, 'weight_decay': 1.829261069538876e-05, 'auxiliary_weight': 0.07286558594089097, 'consistency_weight': 0.03997095465311142, 'feature_top_k': 64, 'pca_variance': '0.95'}. Best is trial 9 with value: 0.53069357448389.

[nodo07] fold=0 epoch=1/32 train=0.7253 val=0.6812
[nodo07] fold=0 epoch=2/32 train=0.7042 val=0.6187
[nodo07] fold=0 epoch=3/32 train=0.6373 val=0.5966
[nodo07] fold=0 epoch=4/32 train=0.6309 val=0.5787
[nodo07] fold=0 epoch=5/32 train=0.6289 val=0.5638
[nodo07] fold=0 epoch=6/32 train=0.6254 val=0.5577
[nodo07] fold=0 epoch=7/32 train=0.6247 val=0.5590
[nodo07] fold=0 epoch=8/32 train=0.6222 val=0.5461
[nodo07] fold=0 epoch=9/32 train=0.6168 val=0.5426
[nodo07] fold=0 epoch=10/32 train=0.6023 val=0.5379
[nodo07] fold=0 epoch=11/32 train=0.6021 val=0.5451
[nodo07] fold=0 epoch=12/32 train=0.6075 val=0.5582
[nodo07] fold=0 epoch=13/32 train=0.6179 val=0.5299
[nodo07] fold=0 epoch=14/32 train=0.5830 val=0.5300
[nodo07] fold=0 epoch=15/32 train=0.6081 val=0.5273
[nodo07] fold=0 epoch=16/32 train=0.5886 val=0.5308
[nodo07] fold=0 epoch=17/32 train=0.5796 val=0.5322
[nodo07] fold=0 epoch=18/32 train=0.5739 val=0.5256
[nodo07] fold=0 epoch=19/32 train=0.5731 val=0.5230
[nodo07] fold=0 epoch=20/32 train=0.5896 val=0.5214
[nodo07] fold=0 epoch=21/32 train=0.5853 val=0.5231
[nodo07] fold=0 epoch=22/32 train=0.5462 val=0.5208
[nodo07] fold=0 epoch=23/32 train=0.5513 val=0.5189
[nodo07] fold=0 epoch=24/32 train=0.5833 val=0.5183
[nodo07] fold=0 epoch=25/32 train=0.5657 val=0.5200
[nodo07] fold=0 epoch=26/32 train=0.5448 val=0.5202
[nodo07] fold=0 epoch=27/32 train=0.5621 val=0.5173
[nodo07] fold=0 epoch=28/32 train=0.5840 val=0.5163
[nodo07] fold=0 epoch=29/32 train=0.5550 val=0.5167
[nodo07] fold=0 epoch=30/32 train=0.5695 val=0.5169
[nodo07] fold=0 epoch=31/32 train=0.5504 val=0.5172
[nodo07] fold=0 epoch=32/32 train=0.5300 val=0.5173
[nodo07] fold=1 epoch=1/32 train=0.7284 val=0.6803
[nodo07] fold=1 epoch=2/32 train=0.7078 val=0.6640
[nodo07] fold=1 epoch=3/32 train=0.6686 val=0.6378
[nodo07] fold=1 epoch=4/32 train=0.6444 val=0.6119
[nodo07] fold=1 epoch=5/32 train=0.6408 val=0.6109
[nodo07] fold=1 epoch=6/32 train=0.6453 val=0.6038
[nodo07] fold=1 epoch=7/32 train=0.6120 val=0.5989
[nodo07] fold=1 epoch=8/32 train=0.6105 val=0.5800
[nodo07] fold=1 epoch=9/32 train=0.6066 val=0.5722
[nodo07] fold=1 epoch=10/32 train=0.6089 val=0.5747
[nodo07] fold=1 epoch=11/32 train=0.6181 val=0.5602
[nodo07] fold=1 epoch=12/32 train=0.5998 val=0.5540
[nodo07] fold=1 epoch=13/32 train=0.6041 val=0.5605
[nodo07] fold=1 epoch=14/32 train=0.5630 val=0.5571
[nodo07] fold=1 epoch=15/32 train=0.5643 val=0.5553
[nodo07] fold=1 epoch=16/32 train=0.5539 val=0.5569
[nodo07] fold=1 epoch=17/32 train=0.5595 val=0.5615
[nodo07] fold=1 epoch=18/32 train=0.5919 val=0.5429
[nodo07] fold=1 epoch=19/32 train=0.5584 val=0.5585
[nodo07] fold=1 epoch=20/32 train=0.5282 val=0.5658
[nodo07] fold=1 epoch=21/32 train=0.5588 val=0.5551
[nodo07] fold=1 epoch=22/32 train=0.5512 val=0.5516
[nodo07] fold=1 epoch=23/32 train=0.5562 val=0.5486
[nodo07] fold=1 epoch=24/32 train=0.5574 val=0.5498
[nodo07] fold=1 epoch=25/32 train=0.5777 val=0.5473
[nodo07] fold=1 epoch=26/32 train=0.5669 val=0.5472
[nodo07] fold=1 epoch=27/32 train=0.5486 val=0.5506
[nodo07] fold=2 epoch=1/32 train=0.7421 val=0.6867
[nodo07] fold=2 epoch=2/32 train=0.7174 val=0.6613
[nodo07] fold=2 epoch=3/32 train=0.6830 val=0.5962
[nodo07] fold=2 epoch=4/32 train=0.6570 val=0.5914
[nodo07] fold=2 epoch=5/32 train=0.6388 val=0.5755
[nodo07] fold=2 epoch=6/32 train=0.6158 val=0.6076
[nodo07] fold=2 epoch=7/32 train=0.6014 val=0.5729
[nodo07] fold=2 epoch=8/32 train=0.6124 val=0.5625
[nodo07] fold=2 epoch=9/32 train=0.5952 val=0.5745
[nodo07] fold=2 epoch=10/32 train=0.6236 val=0.5660
[nodo07] fold=2 epoch=11/32 train=0.5787 val=0.5566
[nodo07] fold=2 epoch=12/32 train=0.5959 val=0.5667
[nodo07] fold=2 epoch=13/32 train=0.5863 val=0.5571
[nodo07] fold=2 epoch=14/32 train=0.5759 val=0.5623
[nodo07] fold=2 epoch=15/32 train=0.5881 val=0.5645
[nodo07] fold=2 epoch=16/32 train=0.5821 val=0.5565
[nodo07] fold=2 epoch=17/32 train=0.5816 val=0.5571
[nodo07] fold=2 epoch=18/32 train=0.5498 val=0.5589
[nodo07] fold=2 epoch=19/32 train=0.6155 val=0.5558
[nodo07] fold=2 epoch=20/32 train=0.5751 val=0.5513
[nodo07] fold=2 epoch=21/32 train=0.5775 val=0.5531
[nodo07] fold=2 epoch=22/32 train=0.5627 val=0.5535
[nodo07] fold=2 epoch=23/32 train=0.5935 val=0.5528
[nodo07] fold=2 epoch=24/32 train=0.5730 val=0.5506
[nodo07] fold=2 epoch=25/32 train=0.5456 val=0.5538
[nodo07] fold=2 epoch=26/32 train=0.5679 val=0.5515
[nodo07] fold=2 epoch=27/32 train=0.5478 val=0.5534
[nodo07] fold=2 epoch=28/32 train=0.5488 val=0.5541
[nodo07] fold=2 epoch=29/32 train=0.5756 val=0.5529
[nodo07] fold=2 epoch=30/32 train=0.5666 val=0.5526
[nodo07] fold=2 epoch=31/32 train=0.5564 val=0.5524
[nodo07] fold=2 epoch=32/32 train=0.5471 val=0.5524

[I 2026-08-31 23:32:17,875] Trial 13 finished with value: 0.5366005149514198 and parameters: {'dropout': 0.334619230731365, 'tabular_embedding_dim': 16, 'augmentation_magnitude': 2.2676214624541715, 'augmentation_probability': 0.8690320071786177, 'rotation_degrees': 2.7915275934254073, 'learning_rate': 0.00013926108473777036, 'weight_decay': 1.0104460200530148e-05, 'auxiliary_weight': 0.09345870211739685, 'consistency_weight': 0.041571788536201026, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 9 with value: 0.53069357448389.

[nodo07] fold=0 epoch=1/32 train=0.7206 val=0.6369
[nodo07] fold=0 epoch=2/32 train=0.6594 val=0.5659
[nodo07] fold=0 epoch=3/32 train=0.6252 val=0.5674
[nodo07] fold=0 epoch=4/32 train=0.6207 val=0.5599
[nodo07] fold=0 epoch=5/32 train=0.6177 val=0.5459
[nodo07] fold=0 epoch=6/32 train=0.6221 val=0.5384
[nodo07] fold=0 epoch=7/32 train=0.6083 val=0.5322
[nodo07] fold=0 epoch=8/32 train=0.6076 val=0.5237
[nodo07] fold=0 epoch=9/32 train=0.6108 val=0.5227
[nodo07] fold=0 epoch=10/32 train=0.5886 val=0.5162
[nodo07] fold=0 epoch=11/32 train=0.5853 val=0.5297
[nodo07] fold=0 epoch=12/32 train=0.5860 val=0.5294
[nodo07] fold=0 epoch=13/32 train=0.6052 val=0.5060
[nodo07] fold=0 epoch=14/32 train=0.5490 val=0.5108
[nodo07] fold=0 epoch=15/32 train=0.5748 val=0.5063
[nodo07] fold=0 epoch=16/32 train=0.5634 val=0.5170
[nodo07] fold=0 epoch=17/32 train=0.5411 val=0.5170
[nodo07] fold=0 epoch=18/32 train=0.5426 val=0.5074
[nodo07] fold=0 epoch=19/32 train=0.5364 val=0.5072
[nodo07] fold=0 epoch=20/32 train=0.5622 val=0.5047
[nodo07] fold=0 epoch=21/32 train=0.5526 val=0.5030
[nodo07] fold=0 epoch=22/32 train=0.5077 val=0.5078
[nodo07] fold=0 epoch=23/32 train=0.5282 val=0.5046
[nodo07] fold=0 epoch=24/32 train=0.5554 val=0.5039
[nodo07] fold=0 epoch=25/32 train=0.5317 val=0.5064
[nodo07] fold=0 epoch=26/32 train=0.5247 val=0.5080
[nodo07] fold=0 epoch=27/32 train=0.5276 val=0.5048
[nodo07] fold=0 epoch=28/32 train=0.5544 val=0.5033
[nodo07] fold=0 epoch=29/32 train=0.5232 val=0.5047
[nodo07] fold=0 epoch=30/32 train=0.5377 val=0.5049
[nodo07] fold=1 epoch=1/32 train=0.7193 val=0.6266
[nodo07] fold=1 epoch=2/32 train=0.6622 val=0.6141
[nodo07] fold=1 epoch=3/32 train=0.6140 val=0.6203
[nodo07] fold=1 epoch=4/32 train=0.6259 val=0.5906
[nodo07] fold=1 epoch=5/32 train=0.6068 val=0.5717
[nodo07] fold=1 epoch=6/32 train=0.6126 val=0.5744
[nodo07] fold=1 epoch=7/32 train=0.5735 val=0.5559
[nodo07] fold=1 epoch=8/32 train=0.5775 val=0.5473
[nodo07] fold=1 epoch=9/32 train=0.5613 val=0.5477
[nodo07] fold=1 epoch=10/32 train=0.5928 val=0.5538
[nodo07] fold=1 epoch=11/32 train=0.5701 val=0.5404
[nodo07] fold=1 epoch=12/32 train=0.5650 val=0.5413
[nodo07] fold=1 epoch=13/32 train=0.5817 val=0.5409
[nodo07] fold=1 epoch=14/32 train=0.5474 val=0.5398
[nodo07] fold=1 epoch=15/32 train=0.5407 val=0.5443
[nodo07] fold=1 epoch=16/32 train=0.5221 val=0.5549
[nodo07] fold=1 epoch=17/32 train=0.5310 val=0.5494
[nodo07] fold=1 epoch=18/32 train=0.5577 val=0.5393
[nodo07] fold=1 epoch=19/32 train=0.5341 val=0.5615
[nodo07] fold=1 epoch=20/32 train=0.5056 val=0.5561
[nodo07] fold=1 epoch=21/32 train=0.5327 val=0.5456
[nodo07] fold=1 epoch=22/32 train=0.5239 val=0.5458
[nodo07] fold=1 epoch=23/32 train=0.5304 val=0.5433
[nodo07] fold=1 epoch=24/32 train=0.5350 val=0.5456
[nodo07] fold=1 epoch=25/32 train=0.5489 val=0.5432
[nodo07] fold=1 epoch=26/32 train=0.5348 val=0.5430
[nodo07] fold=1 epoch=27/32 train=0.5086 val=0.5472
[nodo07] fold=2 epoch=1/32 train=0.7245 val=0.6269
[nodo07] fold=2 epoch=2/32 train=0.6434 val=0.5841
[nodo07] fold=2 epoch=3/32 train=0.6383 val=0.5804
[nodo07] fold=2 epoch=4/32 train=0.6420 val=0.5886
[nodo07] fold=2 epoch=5/32 train=0.6150 val=0.5689
[nodo07] fold=2 epoch=6/32 train=0.5938 val=0.6116
[nodo07] fold=2 epoch=7/32 train=0.5929 val=0.5680
[nodo07] fold=2 epoch=8/32 train=0.5884 val=0.5565
[nodo07] fold=2 epoch=9/32 train=0.5717 val=0.5653
[nodo07] fold=2 epoch=10/32 train=0.6008 val=0.5546
[nodo07] fold=2 epoch=11/32 train=0.5529 val=0.5539
[nodo07] fold=2 epoch=12/32 train=0.5695 val=0.5667
[nodo07] fold=2 epoch=13/32 train=0.5625 val=0.5484
[nodo07] fold=2 epoch=14/32 train=0.5475 val=0.5603
[nodo07] fold=2 epoch=15/32 train=0.5569 val=0.5672
[nodo07] fold=2 epoch=16/32 train=0.5584 val=0.5575
[nodo07] fold=2 epoch=17/32 train=0.5631 val=0.5580
[nodo07] fold=2 epoch=18/32 train=0.5110 val=0.5617
[nodo07] fold=2 epoch=19/32 train=0.5835 val=0.5617
[nodo07] fold=2 epoch=20/32 train=0.5372 val=0.5590
[nodo07] fold=2 epoch=21/32 train=0.5475 val=0.5742
[nodo07] fold=2 epoch=22/32 train=0.5397 val=0.5565

[I 2026-09-01 00:13:52,779] Trial 14 finished with value: 0.5302382705324706 and parameters: {'dropout': 0.2578798686358988, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.1877372729409625, 'augmentation_probability': 0.8183466056010603, 'rotation_degrees': 2.623178535740306, 'learning_rate': 0.0001978968912372132, 'weight_decay': 8.134339974894117e-06, 'auxiliary_weight': 0.10991114130500763, 'consistency_weight': 0.04182021090482068, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 14 with value: 0.5302382705324706.

[nodo07] fold=0 epoch=1/32 train=0.7219 val=0.6292
[nodo07] fold=0 epoch=2/32 train=0.6559 val=0.5634
[nodo07] fold=0 epoch=3/32 train=0.6258 val=0.5697
[nodo07] fold=0 epoch=4/32 train=0.6149 val=0.5595
[nodo07] fold=0 epoch=5/32 train=0.6192 val=0.5439
[nodo07] fold=0 epoch=6/32 train=0.6160 val=0.5357
[nodo07] fold=0 epoch=7/32 train=0.6082 val=0.5297
[nodo07] fold=0 epoch=8/32 train=0.6097 val=0.5186
[nodo07] fold=0 epoch=9/32 train=0.6100 val=0.5202
[nodo07] fold=0 epoch=10/32 train=0.5905 val=0.5121
[nodo07] fold=0 epoch=11/32 train=0.5883 val=0.5258
[nodo07] fold=0 epoch=12/32 train=0.5910 val=0.5280
[nodo07] fold=0 epoch=13/32 train=0.6054 val=0.5031
[nodo07] fold=0 epoch=14/32 train=0.5564 val=0.5055
[nodo07] fold=0 epoch=15/32 train=0.5815 val=0.4993
[nodo07] fold=0 epoch=16/32 train=0.5657 val=0.5150
[nodo07] fold=0 epoch=17/32 train=0.5405 val=0.5124
[nodo07] fold=0 epoch=18/32 train=0.5508 val=0.5029
[nodo07] fold=0 epoch=19/32 train=0.5437 val=0.5026
[nodo07] fold=0 epoch=20/32 train=0.5634 val=0.5013
[nodo07] fold=0 epoch=21/32 train=0.5484 val=0.5006
[nodo07] fold=0 epoch=22/32 train=0.5120 val=0.5046
[nodo07] fold=0 epoch=23/32 train=0.5334 val=0.5042
[nodo07] fold=0 epoch=24/32 train=0.5554 val=0.5017
[nodo07] fold=1 epoch=1/32 train=0.7214 val=0.6262
[nodo07] fold=1 epoch=2/32 train=0.6654 val=0.6188
[nodo07] fold=1 epoch=3/32 train=0.6144 val=0.6146
[nodo07] fold=1 epoch=4/32 train=0.6293 val=0.5951
[nodo07] fold=1 epoch=5/32 train=0.6093 val=0.5718
[nodo07] fold=1 epoch=6/32 train=0.6140 val=0.5681
[nodo07] fold=1 epoch=7/32 train=0.5742 val=0.5556
[nodo07] fold=1 epoch=8/32 train=0.5830 val=0.5400
[nodo07] fold=1 epoch=9/32 train=0.5615 val=0.5523
[nodo07] fold=1 epoch=10/32 train=0.5932 val=0.5588
[nodo07] fold=1 epoch=11/32 train=0.5734 val=0.5428
[nodo07] fold=1 epoch=12/32 train=0.5710 val=0.5400
[nodo07] fold=1 epoch=13/32 train=0.5897 val=0.5398
[nodo07] fold=1 epoch=14/32 train=0.5535 val=0.5380
[nodo07] fold=1 epoch=15/32 train=0.5479 val=0.5445
[nodo07] fold=1 epoch=16/32 train=0.5296 val=0.5527
[nodo07] fold=1 epoch=17/32 train=0.5386 val=0.5496
[nodo07] fold=1 epoch=18/32 train=0.5620 val=0.5360
[nodo07] fold=1 epoch=19/32 train=0.5380 val=0.5570
[nodo07] fold=1 epoch=20/32 train=0.5058 val=0.5534
[nodo07] fold=1 epoch=21/32 train=0.5385 val=0.5416
[nodo07] fold=1 epoch=22/32 train=0.5262 val=0.5427
[nodo07] fold=1 epoch=23/32 train=0.5327 val=0.5404
[nodo07] fold=1 epoch=24/32 train=0.5359 val=0.5424
[nodo07] fold=1 epoch=25/32 train=0.5503 val=0.5409
[nodo07] fold=1 epoch=26/32 train=0.5389 val=0.5407
[nodo07] fold=1 epoch=27/32 train=0.5130 val=0.5432
[nodo07] fold=2 epoch=1/32 train=0.7255 val=0.6249
[nodo07] fold=2 epoch=2/32 train=0.6395 val=0.5811
[nodo07] fold=2 epoch=3/32 train=0.6366 val=0.5811
[nodo07] fold=2 epoch=4/32 train=0.6409 val=0.5893
[nodo07] fold=2 epoch=5/32 train=0.6198 val=0.5675
[nodo07] fold=2 epoch=6/32 train=0.5943 val=0.6123
[nodo07] fold=2 epoch=7/32 train=0.5952 val=0.5665
[nodo07] fold=2 epoch=8/32 train=0.5896 val=0.5552
[nodo07] fold=2 epoch=9/32 train=0.5733 val=0.5614
[nodo07] fold=2 epoch=10/32 train=0.6047 val=0.5536
[nodo07] fold=2 epoch=11/32 train=0.5498 val=0.5517
[nodo07] fold=2 epoch=12/32 train=0.5668 val=0.5671
[nodo07] fold=2 epoch=13/32 train=0.5628 val=0.5482
[nodo07] fold=2 epoch=14/32 train=0.5502 val=0.5516
[nodo07] fold=2 epoch=15/32 train=0.5535 val=0.5643
[nodo07] fold=2 epoch=16/32 train=0.5540 val=0.5531
[nodo07] fold=2 epoch=17/32 train=0.5624 val=0.5530
[nodo07] fold=2 epoch=18/32 train=0.5102 val=0.5575
[nodo07] fold=2 epoch=19/32 train=0.5762 val=0.5563
[nodo07] fold=2 epoch=20/32 train=0.5334 val=0.5561
[nodo07] fold=2 epoch=21/32 train=0.5441 val=0.5621
[nodo07] fold=2 epoch=22/32 train=0.5337 val=0.5594

[I 2026-09-01 00:58:12,248] Trial 15 finished with value: 0.5278276218267456 and parameters: {'dropout': 0.2837786337937264, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.3024100668564436, 'augmentation_probability': 0.8118524033493216, 'rotation_degrees': 2.247626229215371, 'learning_rate': 0.00021653913595958403, 'weight_decay': 6.402978954462206e-06, 'auxiliary_weight': 0.11339705138290415, 'consistency_weight': 0.04190041918907033, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 15 with value: 0.5278276218267456.

[nodo07] fold=0 epoch=1/32 train=0.7126 val=0.6142
[nodo07] fold=0 epoch=2/32 train=0.6447 val=0.5596
[nodo07] fold=0 epoch=3/32 train=0.6211 val=0.5654
[nodo07] fold=0 epoch=4/32 train=0.6144 val=0.5523
[nodo07] fold=0 epoch=5/32 train=0.6127 val=0.5329
[nodo07] fold=0 epoch=6/32 train=0.6091 val=0.5272
[nodo07] fold=0 epoch=7/32 train=0.6038 val=0.5191
[nodo07] fold=0 epoch=8/32 train=0.6012 val=0.5149
[nodo07] fold=0 epoch=9/32 train=0.6006 val=0.5155
[nodo07] fold=0 epoch=10/32 train=0.5812 val=0.5068
[nodo07] fold=0 epoch=11/32 train=0.5738 val=0.5242
[nodo07] fold=0 epoch=12/32 train=0.5796 val=0.5223
[nodo07] fold=0 epoch=13/32 train=0.5895 val=0.5024
[nodo07] fold=0 epoch=14/32 train=0.5317 val=0.5089
[nodo07] fold=0 epoch=15/32 train=0.5629 val=0.5094
[nodo07] fold=0 epoch=16/32 train=0.5493 val=0.5204
[nodo07] fold=0 epoch=17/32 train=0.5263 val=0.5181
[nodo07] fold=0 epoch=18/32 train=0.5275 val=0.5107
[nodo07] fold=0 epoch=19/32 train=0.5220 val=0.5100
[nodo07] fold=0 epoch=20/32 train=0.5490 val=0.5071
[nodo07] fold=0 epoch=21/32 train=0.5348 val=0.5048
[nodo07] fold=0 epoch=22/32 train=0.4924 val=0.5110
[nodo07] fold=1 epoch=1/32 train=0.7107 val=0.6217
[nodo07] fold=1 epoch=2/32 train=0.6575 val=0.6074
[nodo07] fold=1 epoch=3/32 train=0.6094 val=0.6133
[nodo07] fold=1 epoch=4/32 train=0.6177 val=0.5780
[nodo07] fold=1 epoch=5/32 train=0.5889 val=0.5603
[nodo07] fold=1 epoch=6/32 train=0.6012 val=0.5644
[nodo07] fold=1 epoch=7/32 train=0.5618 val=0.5491
[nodo07] fold=1 epoch=8/32 train=0.5704 val=0.5442
[nodo07] fold=1 epoch=9/32 train=0.5528 val=0.5498
[nodo07] fold=1 epoch=10/32 train=0.5856 val=0.5455
[nodo07] fold=1 epoch=11/32 train=0.5615 val=0.5404
[nodo07] fold=1 epoch=12/32 train=0.5629 val=0.5395
[nodo07] fold=1 epoch=13/32 train=0.5763 val=0.5352
[nodo07] fold=1 epoch=14/32 train=0.5474 val=0.5344
[nodo07] fold=1 epoch=15/32 train=0.5381 val=0.5413
[nodo07] fold=1 epoch=16/32 train=0.5185 val=0.5510
[nodo07] fold=1 epoch=17/32 train=0.5264 val=0.5494
[nodo07] fold=1 epoch=18/32 train=0.5519 val=0.5389
[nodo07] fold=1 epoch=19/32 train=0.5230 val=0.5620
[nodo07] fold=1 epoch=20/32 train=0.4962 val=0.5557
[nodo07] fold=1 epoch=21/32 train=0.5273 val=0.5393
[nodo07] fold=1 epoch=22/32 train=0.5178 val=0.5455
[nodo07] fold=1 epoch=23/32 train=0.5242 val=0.5408
[nodo07] fold=2 epoch=1/32 train=0.7192 val=0.6116
[nodo07] fold=2 epoch=2/32 train=0.6330 val=0.5816
[nodo07] fold=2 epoch=3/32 train=0.6311 val=0.5813
[nodo07] fold=2 epoch=4/32 train=0.6375 val=0.5858
[nodo07] fold=2 epoch=5/32 train=0.6099 val=0.5617
[nodo07] fold=2 epoch=6/32 train=0.5837 val=0.6031
[nodo07] fold=2 epoch=7/32 train=0.5863 val=0.5589
[nodo07] fold=2 epoch=8/32 train=0.5823 val=0.5490
[nodo07] fold=2 epoch=9/32 train=0.5673 val=0.5576
[nodo07] fold=2 epoch=10/32 train=0.5902 val=0.5577
[nodo07] fold=2 epoch=11/32 train=0.5426 val=0.5492
[nodo07] fold=2 epoch=12/32 train=0.5563 val=0.5691
[nodo07] fold=2 epoch=13/32 train=0.5538 val=0.5471
[nodo07] fold=2 epoch=14/32 train=0.5359 val=0.5534
[nodo07] fold=2 epoch=15/32 train=0.5386 val=0.5667
[nodo07] fold=2 epoch=16/32 train=0.5456 val=0.5575
[nodo07] fold=2 epoch=17/32 train=0.5462 val=0.5562
[nodo07] fold=2 epoch=18/32 train=0.4926 val=0.5611
[nodo07] fold=2 epoch=19/32 train=0.5661 val=0.5590
[nodo07] fold=2 epoch=20/32 train=0.5191 val=0.5651
[nodo07] fold=2 epoch=21/32 train=0.5292 val=0.5738
[nodo07] fold=2 epoch=22/32 train=0.5191 val=0.5577

[I 2026-09-01 01:34:05,564] Trial 16 finished with value: 0.5279836502514289 and parameters: {'dropout': 0.22862782494195324, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.295794581336268, 'augmentation_probability': 0.8227409627683853, 'rotation_degrees': 2.34797651874165, 'learning_rate': 0.0002467964053213014, 'weight_decay': 7.089980997172589e-06, 'auxiliary_weight': 0.11230428541853803, 'consistency_weight': 0.04066950021238454, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 15 with value: 0.5278276218267456.

[nodo07] fold=0 epoch=1/32 train=0.7301 val=0.6764
[nodo07] fold=0 epoch=2/32 train=0.7143 val=0.6413
[nodo07] fold=0 epoch=3/32 train=0.6654 val=0.5988
[nodo07] fold=0 epoch=4/32 train=0.6439 val=0.5880
[nodo07] fold=0 epoch=5/32 train=0.6393 val=0.5678
[nodo07] fold=0 epoch=6/32 train=0.6327 val=0.5638
[nodo07] fold=0 epoch=7/32 train=0.6347 val=0.5598
[nodo07] fold=0 epoch=8/32 train=0.6199 val=0.5556
[nodo07] fold=0 epoch=9/32 train=0.6308 val=0.5492
[nodo07] fold=0 epoch=10/32 train=0.6131 val=0.5467
[nodo07] fold=0 epoch=11/32 train=0.6066 val=0.5535
[nodo07] fold=0 epoch=12/32 train=0.6229 val=0.5646
[nodo07] fold=0 epoch=13/32 train=0.6360 val=0.5438
[nodo07] fold=0 epoch=14/32 train=0.5951 val=0.5397
[nodo07] fold=0 epoch=15/32 train=0.6140 val=0.5451
[nodo07] fold=0 epoch=16/32 train=0.6034 val=0.5448
[nodo07] fold=0 epoch=17/32 train=0.6019 val=0.5449
[nodo07] fold=0 epoch=18/32 train=0.5979 val=0.5337
[nodo07] fold=0 epoch=19/32 train=0.5759 val=0.5347
[nodo07] fold=0 epoch=20/32 train=0.6094 val=0.5377
[nodo07] fold=0 epoch=21/32 train=0.5937 val=0.5367
[nodo07] fold=0 epoch=22/32 train=0.5491 val=0.5342
[nodo07] fold=0 epoch=23/32 train=0.5641 val=0.5390
[nodo07] fold=0 epoch=24/32 train=0.6069 val=0.5339
[nodo07] fold=0 epoch=25/32 train=0.5828 val=0.5330
[nodo07] fold=0 epoch=26/32 train=0.5795 val=0.5362
[nodo07] fold=0 epoch=27/32 train=0.5841 val=0.5332
[nodo07] fold=0 epoch=28/32 train=0.6018 val=0.5332
[nodo07] fold=0 epoch=29/32 train=0.5731 val=0.5357
[nodo07] fold=0 epoch=30/32 train=0.5968 val=0.5350
[nodo07] fold=0 epoch=31/32 train=0.5669 val=0.5350
[nodo07] fold=0 epoch=32/32 train=0.5461 val=0.5349
[nodo07] fold=1 epoch=1/32 train=0.7224 val=0.6549
[nodo07] fold=1 epoch=2/32 train=0.6796 val=0.6400
[nodo07] fold=1 epoch=3/32 train=0.6236 val=0.6203
[nodo07] fold=1 epoch=4/32 train=0.6358 val=0.5915
[nodo07] fold=1 epoch=5/32 train=0.6226 val=0.5872
[nodo07] fold=1 epoch=6/32 train=0.6368 val=0.5847
[nodo07] fold=1 epoch=7/32 train=0.6060 val=0.5727
[nodo07] fold=1 epoch=8/32 train=0.6030 val=0.5657
[nodo07] fold=1 epoch=9/32 train=0.5973 val=0.5708
[nodo07] fold=1 epoch=10/32 train=0.6145 val=0.5743
[nodo07] fold=1 epoch=11/32 train=0.6067 val=0.5612
[nodo07] fold=1 epoch=12/32 train=0.5997 val=0.5616
[nodo07] fold=1 epoch=13/32 train=0.6039 val=0.5612
[nodo07] fold=1 epoch=14/32 train=0.5733 val=0.5579
[nodo07] fold=1 epoch=15/32 train=0.5656 val=0.5632
[nodo07] fold=1 epoch=16/32 train=0.5569 val=0.5588
[nodo07] fold=1 epoch=17/32 train=0.5629 val=0.5693
[nodo07] fold=1 epoch=18/32 train=0.5913 val=0.5658
[nodo07] fold=1 epoch=19/32 train=0.5625 val=0.5683
[nodo07] fold=1 epoch=20/32 train=0.5430 val=0.5698
[nodo07] fold=1 epoch=21/32 train=0.5685 val=0.5613
[nodo07] fold=1 epoch=22/32 train=0.5524 val=0.5617
[nodo07] fold=1 epoch=23/32 train=0.5494 val=0.5590

[I 2026-09-01 02:03:08,874] Trial 17 pruned.

[nodo07] fold=0 epoch=1/32 train=0.7315 val=0.6716
[nodo07] fold=0 epoch=2/32 train=0.6978 val=0.6091
[nodo07] fold=0 epoch=3/32 train=0.6449 val=0.5837
[nodo07] fold=0 epoch=4/32 train=0.6384 val=0.5761
[nodo07] fold=0 epoch=5/32 train=0.6400 val=0.5642
[nodo07] fold=0 epoch=6/32 train=0.6367 val=0.5573
[nodo07] fold=0 epoch=7/32 train=0.6391 val=0.5589
[nodo07] fold=0 epoch=8/32 train=0.6225 val=0.5539
[nodo07] fold=0 epoch=9/32 train=0.6339 val=0.5459
[nodo07] fold=0 epoch=10/32 train=0.6137 val=0.5432
[nodo07] fold=0 epoch=11/32 train=0.6084 val=0.5516
[nodo07] fold=0 epoch=12/32 train=0.6194 val=0.5537
[nodo07] fold=0 epoch=13/32 train=0.6379 val=0.5388
[nodo07] fold=0 epoch=14/32 train=0.5945 val=0.5331
[nodo07] fold=0 epoch=15/32 train=0.6110 val=0.5354
[nodo07] fold=0 epoch=16/32 train=0.5922 val=0.5418
[nodo07] fold=0 epoch=17/32 train=0.5832 val=0.5385
[nodo07] fold=0 epoch=18/32 train=0.5855 val=0.5310
[nodo07] fold=0 epoch=19/32 train=0.5757 val=0.5297
[nodo07] fold=0 epoch=20/32 train=0.5980 val=0.5298
[nodo07] fold=0 epoch=21/32 train=0.5847 val=0.5279
[nodo07] fold=0 epoch=22/32 train=0.5460 val=0.5256
[nodo07] fold=0 epoch=23/32 train=0.5594 val=0.5246
[nodo07] fold=0 epoch=24/32 train=0.5875 val=0.5250
[nodo07] fold=0 epoch=25/32 train=0.5772 val=0.5242
[nodo07] fold=0 epoch=26/32 train=0.5631 val=0.5270
[nodo07] fold=0 epoch=27/32 train=0.5671 val=0.5246
[nodo07] fold=0 epoch=28/32 train=0.5804 val=0.5236
[nodo07] fold=0 epoch=29/32 train=0.5593 val=0.5244
[nodo07] fold=0 epoch=30/32 train=0.5761 val=0.5245
[nodo07] fold=0 epoch=31/32 train=0.5496 val=0.5245
[nodo07] fold=0 epoch=32/32 train=0.5339 val=0.5245
[nodo07] fold=1 epoch=1/32 train=0.7365 val=0.6540
[nodo07] fold=1 epoch=2/32 train=0.6923 val=0.6323
[nodo07] fold=1 epoch=3/32 train=0.6425 val=0.6186
[nodo07] fold=1 epoch=4/32 train=0.6424 val=0.5957
[nodo07] fold=1 epoch=5/32 train=0.6210 val=0.5827
[nodo07] fold=1 epoch=6/32 train=0.6311 val=0.5882
[nodo07] fold=1 epoch=7/32 train=0.5981 val=0.5737
[nodo07] fold=1 epoch=8/32 train=0.6067 val=0.5630
[nodo07] fold=1 epoch=9/32 train=0.5822 val=0.5703
[nodo07] fold=1 epoch=10/32 train=0.6230 val=0.5691
[nodo07] fold=1 epoch=11/32 train=0.5934 val=0.5716
[nodo07] fold=1 epoch=12/32 train=0.6033 val=0.5583
[nodo07] fold=1 epoch=13/32 train=0.6134 val=0.5577
[nodo07] fold=1 epoch=14/32 train=0.5653 val=0.5561
[nodo07] fold=1 epoch=15/32 train=0.5775 val=0.5605
[nodo07] fold=1 epoch=16/32 train=0.5608 val=0.5612
[nodo07] fold=1 epoch=17/32 train=0.5650 val=0.5646
[nodo07] fold=1 epoch=18/32 train=0.6010 val=0.5508
[nodo07] fold=1 epoch=19/32 train=0.5617 val=0.5649
[nodo07] fold=1 epoch=20/32 train=0.5533 val=0.5680
[nodo07] fold=1 epoch=21/32 train=0.5639 val=0.5620
[nodo07] fold=1 epoch=22/32 train=0.5592 val=0.5616
[nodo07] fold=1 epoch=23/32 train=0.5590 val=0.5504
[nodo07] fold=1 epoch=24/32 train=0.5671 val=0.5543
[nodo07] fold=1 epoch=25/32 train=0.5830 val=0.5498
[nodo07] fold=1 epoch=26/32 train=0.5709 val=0.5470
[nodo07] fold=1 epoch=27/32 train=0.5435 val=0.5521
[nodo07] fold=1 epoch=28/32 train=0.5896 val=0.5475
[nodo07] fold=1 epoch=29/32 train=0.5612 val=0.5497
[nodo07] fold=1 epoch=30/32 train=0.5774 val=0.5481
[nodo07] fold=1 epoch=31/32 train=0.5726 val=0.5483
[nodo07] fold=1 epoch=32/32 train=0.5745 val=0.5484
[nodo07] fold=2 epoch=1/32 train=0.7463 val=0.6757
[nodo07] fold=2 epoch=2/32 train=0.7055 val=0.5983
[nodo07] fold=2 epoch=3/32 train=0.6510 val=0.5870
[nodo07] fold=2 epoch=4/32 train=0.6633 val=0.5923
[nodo07] fold=2 epoch=5/32 train=0.6416 val=0.5749
[nodo07] fold=2 epoch=6/32 train=0.6135 val=0.6074
[nodo07] fold=2 epoch=7/32 train=0.6140 val=0.5744
[nodo07] fold=2 epoch=8/32 train=0.6199 val=0.5684
[nodo07] fold=2 epoch=9/32 train=0.6045 val=0.5729
[nodo07] fold=2 epoch=10/32 train=0.6248 val=0.5701
[nodo07] fold=2 epoch=11/32 train=0.5798 val=0.5594
[nodo07] fold=2 epoch=12/32 train=0.6047 val=0.5687
[nodo07] fold=2 epoch=13/32 train=0.5921 val=0.5608
[nodo07] fold=2 epoch=14/32 train=0.5889 val=0.5655
[nodo07] fold=2 epoch=15/32 train=0.5930 val=0.5720
[nodo07] fold=2 epoch=16/32 train=0.5975 val=0.5621
[nodo07] fold=2 epoch=17/32 train=0.5898 val=0.5618
[nodo07] fold=2 epoch=18/32 train=0.5582 val=0.5669
[nodo07] fold=2 epoch=19/32 train=0.6216 val=0.5660
[nodo07] fold=2 epoch=20/32 train=0.5663 val=0.5633

[I 2026-09-01 02:45:57,626] Trial 18 finished with value: 0.5433247897794699 and parameters: {'dropout': 0.3204556235947922, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.304725433594393, 'augmentation_probability': 0.7672014424756729, 'rotation_degrees': 2.0562299877947323, 'learning_rate': 0.00021513209646025435, 'weight_decay': 5.008605598896513e-06, 'auxiliary_weight': 0.12687911408641406, 'consistency_weight': 0.03743132835840287, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 15 with value: 0.5278276218267456.

[nodo07] fold=0 epoch=1/32 train=0.7012 val=0.5723
[nodo07] fold=0 epoch=2/32 train=0.6340 val=0.5297
[nodo07] fold=0 epoch=3/32 train=0.6131 val=0.5233
[nodo07] fold=0 epoch=4/32 train=0.5940 val=0.5008
[nodo07] fold=0 epoch=5/32 train=0.5699 val=0.5014
[nodo07] fold=0 epoch=6/32 train=0.5428 val=0.4995
[nodo07] fold=0 epoch=7/32 train=0.5186 val=0.5113
[nodo07] fold=0 epoch=8/32 train=0.4913 val=0.5277
[nodo07] fold=0 epoch=9/32 train=0.5059 val=0.5252
[nodo07] fold=0 epoch=10/32 train=0.5048 val=0.5029
[nodo07] fold=0 epoch=11/32 train=0.4596 val=0.5365
[nodo07] fold=0 epoch=12/32 train=0.4667 val=0.5367
[nodo07] fold=0 epoch=13/32 train=0.4657 val=0.5347
[nodo07] fold=0 epoch=14/32 train=0.4268 val=0.5400
[nodo07] fold=0 epoch=15/32 train=0.4359 val=0.5322
[nodo07] fold=1 epoch=1/32 train=0.7054 val=0.5980
[nodo07] fold=1 epoch=2/32 train=0.6272 val=0.5941
[nodo07] fold=1 epoch=3/32 train=0.5691 val=0.6173
[nodo07] fold=1 epoch=4/32 train=0.5574 val=0.5906
[nodo07] fold=1 epoch=5/32 train=0.5196 val=0.6185
[nodo07] fold=1 epoch=6/32 train=0.5253 val=0.5928
[nodo07] fold=1 epoch=7/32 train=0.4917 val=0.6002
[nodo07] fold=1 epoch=8/32 train=0.4664 val=0.6115
[nodo07] fold=1 epoch=9/32 train=0.4427 val=0.6430
[nodo07] fold=1 epoch=10/32 train=0.4749 val=0.5926
[nodo07] fold=1 epoch=11/32 train=0.4391 val=0.6358
[nodo07] fold=1 epoch=12/32 train=0.4396 val=0.6289
[nodo07] fold=1 epoch=13/32 train=0.4170 val=0.6721
[nodo07] fold=2 epoch=1/32 train=0.6864 val=0.5746
[nodo07] fold=2 epoch=2/32 train=0.6101 val=0.5688
[nodo07] fold=2 epoch=3/32 train=0.5831 val=0.5772
[nodo07] fold=2 epoch=4/32 train=0.6196 val=0.5727
[nodo07] fold=2 epoch=5/32 train=0.5588 val=0.5659
[nodo07] fold=2 epoch=6/32 train=0.5234 val=0.6109
[nodo07] fold=2 epoch=7/32 train=0.4881 val=0.5871
[nodo07] fold=2 epoch=8/32 train=0.5074 val=0.5868
[nodo07] fold=2 epoch=9/32 train=0.4716 val=0.6215
[nodo07] fold=2 epoch=10/32 train=0.4743 val=0.6031
[nodo07] fold=2 epoch=11/32 train=0.4341 val=0.6054
[nodo07] fold=2 epoch=12/32 train=0.4172 val=0.6262
[nodo07] fold=2 epoch=13/32 train=0.4673 val=0.6186
[nodo07] fold=2 epoch=14/32 train=0.4258 val=0.6098

[I 2026-09-01 03:08:24,941] Trial 19 finished with value: 0.5520214576796071 and parameters: {'dropout': 0.30281360606370183, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.4631062838235165, 'augmentation_probability': 0.7927370812802346, 'rotation_degrees': 2.5181619078866238, 'learning_rate': 0.00019021052554049308, 'weight_decay': 9.315560400879157e-06, 'auxiliary_weight': 0.12404920049611647, 'consistency_weight': 0.035123755788363874, 'feature_top_k': 128, 'pca_variance': 'none'}. Best is trial 15 with value: 0.5278276218267456.
[I 2026-09-01 03:08:25,147] A new study created in RDB with name: node09_3d_3f9bbf2416

[nodo07] fold=0 epoch=1/32 train=0.7154 val=0.5737
[nodo07] fold=0 epoch=2/32 train=0.6444 val=0.5659
[nodo07] fold=0 epoch=3/32 train=0.6257 val=0.5523
[nodo07] fold=0 epoch=4/32 train=0.6221 val=0.5454
[nodo07] fold=0 epoch=5/32 train=0.6098 val=0.5457
[nodo07] fold=0 epoch=6/32 train=0.6009 val=0.5183
[nodo07] fold=0 epoch=7/32 train=0.5924 val=0.5447
[nodo07] fold=0 epoch=8/32 train=0.5894 val=0.5260
[nodo07] fold=0 epoch=9/32 train=0.5782 val=0.5253
[nodo07] fold=0 epoch=10/32 train=0.5833 val=0.5103
[nodo07] fold=0 epoch=11/32 train=0.5625 val=0.5594
[nodo07] fold=0 epoch=12/32 train=0.5696 val=0.5288
[nodo07] fold=0 epoch=13/32 train=0.5714 val=0.4984
[nodo07] fold=0 epoch=14/32 train=0.5167 val=0.5512
[nodo07] fold=0 epoch=15/32 train=0.5565 val=0.5271
[nodo07] fold=0 epoch=16/32 train=0.5404 val=0.5624
[nodo07] fold=0 epoch=17/32 train=0.5165 val=0.5530
[nodo07] fold=0 epoch=18/32 train=0.5392 val=0.5575
[nodo07] fold=0 epoch=19/32 train=0.5420 val=0.5532
[nodo07] fold=0 epoch=20/32 train=0.5372 val=0.5510
[nodo07] fold=0 epoch=21/32 train=0.5148 val=0.5320
[nodo07] fold=0 epoch=22/32 train=0.4811 val=0.5547
[nodo07] fold=1 epoch=1/32 train=0.7109 val=0.6164
[nodo07] fold=1 epoch=2/32 train=0.6484 val=0.6114
[nodo07] fold=1 epoch=3/32 train=0.6019 val=0.6362
[nodo07] fold=1 epoch=4/32 train=0.5964 val=0.5916
[nodo07] fold=1 epoch=5/32 train=0.5780 val=0.6364
[nodo07] fold=1 epoch=6/32 train=0.5924 val=0.6336
[nodo07] fold=1 epoch=7/32 train=0.5557 val=0.6250
[nodo07] fold=1 epoch=8/32 train=0.5683 val=0.6245
[nodo07] fold=1 epoch=9/32 train=0.5275 val=0.6670
[nodo07] fold=1 epoch=10/32 train=0.5935 val=0.5645
[nodo07] fold=1 epoch=11/32 train=0.5274 val=0.6522
[nodo07] fold=1 epoch=12/32 train=0.5398 val=0.6332
[nodo07] fold=1 epoch=13/32 train=0.5353 val=0.6371
[nodo07] fold=1 epoch=14/32 train=0.5123 val=0.6526
[nodo07] fold=1 epoch=15/32 train=0.4950 val=0.6601
[nodo07] fold=1 epoch=16/32 train=0.4669 val=0.6892
[nodo07] fold=1 epoch=17/32 train=0.5164 val=0.6650
[nodo07] fold=1 epoch=18/32 train=0.5354 val=0.6476
[nodo07] fold=1 epoch=19/32 train=0.5023 val=0.6821
[nodo07] fold=2 epoch=1/32 train=0.6757 val=0.5775
[nodo07] fold=2 epoch=2/32 train=0.6327 val=0.5647
[nodo07] fold=2 epoch=3/32 train=0.6214 val=0.6033
[nodo07] fold=2 epoch=4/32 train=0.6554 val=0.5757
[nodo07] fold=2 epoch=5/32 train=0.5756 val=0.5952
[nodo07] fold=2 epoch=6/32 train=0.5616 val=0.6752
[nodo07] fold=2 epoch=7/32 train=0.5538 val=0.6174
[nodo07] fold=2 epoch=8/32 train=0.5703 val=0.6025
[nodo07] fold=2 epoch=9/32 train=0.5568 val=0.6175
[nodo07] fold=2 epoch=10/32 train=0.5813 val=0.6002
[nodo07] fold=2 epoch=11/32 train=0.5298 val=0.5982

[I 2026-09-01 03:39:39,313] Trial 0 finished with value: 0.5425339045786125 and parameters: {'dropout': 0.30506770120532095, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.260130592734807, 'augmentation_probability': 0.9124124560308408, 'rotation_degrees': 1.3693577865016247, 'learning_rate': 0.00013134702829321461, 'weight_decay': 2.2382720151515393e-05, 'auxiliary_weight': 0.14425273039563025, 'consistency_weight': 0.0714917927365403, 'feature_top_k': 64, 'pca_variance': 'none'}. Best is trial 0 with value: 0.5425339045786125.

[nodo07] fold=0 epoch=1/32 train=0.7184 val=0.6398
[nodo07] fold=0 epoch=2/32 train=0.6422 val=0.5666
[nodo07] fold=0 epoch=3/32 train=0.6161 val=0.5578
[nodo07] fold=0 epoch=4/32 train=0.6080 val=0.5568
[nodo07] fold=0 epoch=5/32 train=0.5990 val=0.5402
[nodo07] fold=0 epoch=6/32 train=0.5987 val=0.5378
[nodo07] fold=0 epoch=7/32 train=0.5871 val=0.5656
[nodo07] fold=0 epoch=8/32 train=0.5815 val=0.5449
[nodo07] fold=0 epoch=9/32 train=0.5727 val=0.5295
[nodo07] fold=0 epoch=10/32 train=0.5793 val=0.5195
[nodo07] fold=0 epoch=11/32 train=0.5543 val=0.5477
[nodo07] fold=0 epoch=12/32 train=0.5739 val=0.5462
[nodo07] fold=0 epoch=13/32 train=0.5771 val=0.5130
[nodo07] fold=0 epoch=14/32 train=0.5122 val=0.5656
[nodo07] fold=0 epoch=15/32 train=0.5668 val=0.5325
[nodo07] fold=0 epoch=16/32 train=0.5385 val=0.5511
[nodo07] fold=0 epoch=17/32 train=0.5089 val=0.5624
[nodo07] fold=0 epoch=18/32 train=0.5342 val=0.5653
[nodo07] fold=0 epoch=19/32 train=0.5321 val=0.5659
[nodo07] fold=0 epoch=20/32 train=0.5334 val=0.5607
[nodo07] fold=0 epoch=21/32 train=0.5337 val=0.5437
[nodo07] fold=0 epoch=22/32 train=0.4853 val=0.5686
[nodo07] fold=1 epoch=1/32 train=0.6974 val=0.6034
[nodo07] fold=1 epoch=2/32 train=0.6335 val=0.5917
[nodo07] fold=1 epoch=3/32 train=0.5834 val=0.6383
[nodo07] fold=1 epoch=4/32 train=0.5854 val=0.5867
[nodo07] fold=1 epoch=5/32 train=0.5533 val=0.6096
[nodo07] fold=1 epoch=6/32 train=0.5758 val=0.6225
[nodo07] fold=1 epoch=7/32 train=0.5389 val=0.6173
[nodo07] fold=1 epoch=8/32 train=0.5514 val=0.6057
[nodo07] fold=1 epoch=9/32 train=0.5281 val=0.6379
[nodo07] fold=1 epoch=10/32 train=0.5733 val=0.5582
[nodo07] fold=1 epoch=11/32 train=0.5232 val=0.6300
[nodo07] fold=1 epoch=12/32 train=0.5269 val=0.6163
[nodo07] fold=1 epoch=13/32 train=0.5395 val=0.6158
[nodo07] fold=1 epoch=14/32 train=0.4990 val=0.6321
[nodo07] fold=1 epoch=15/32 train=0.4886 val=0.6440
[nodo07] fold=1 epoch=16/32 train=0.4621 val=0.6699
[nodo07] fold=1 epoch=17/32 train=0.5109 val=0.6491
[nodo07] fold=1 epoch=18/32 train=0.5161 val=0.6350
[nodo07] fold=1 epoch=19/32 train=0.5081 val=0.6646
[nodo07] fold=2 epoch=1/32 train=0.7037 val=0.5823
[nodo07] fold=2 epoch=2/32 train=0.6245 val=0.5663
[nodo07] fold=2 epoch=3/32 train=0.6069 val=0.6098
[nodo07] fold=2 epoch=4/32 train=0.6461 val=0.5939
[nodo07] fold=2 epoch=5/32 train=0.5826 val=0.6041
[nodo07] fold=2 epoch=6/32 train=0.5575 val=0.6588
[nodo07] fold=2 epoch=7/32 train=0.5438 val=0.6149
[nodo07] fold=2 epoch=8/32 train=0.5714 val=0.6066
[nodo07] fold=2 epoch=9/32 train=0.5592 val=0.5976
[nodo07] fold=2 epoch=10/32 train=0.5716 val=0.5910
[nodo07] fold=2 epoch=11/32 train=0.5384 val=0.5730

[I 2026-09-01 04:10:48,982] Trial 1 finished with value: 0.5458212318528836 and parameters: {'dropout': 0.2921340503598765, 'tabular_embedding_dim': 16, 'augmentation_magnitude': 2.3208139076319774, 'augmentation_probability': 0.9063688658215314, 'rotation_degrees': 0.7228035942780833, 'learning_rate': 0.00012102415011826003, 'weight_decay': 1.4251971967482864e-05, 'auxiliary_weight': 0.10262840073427965, 'consistency_weight': 0.038055601162031355, 'feature_top_k': 64, 'pca_variance': 'none'}. Best is trial 0 with value: 0.5425339045786125.

[nodo07] fold=0 epoch=1/32 train=0.7499 val=0.6797
[nodo07] fold=0 epoch=2/32 train=0.7214 val=0.6660
[nodo07] fold=0 epoch=3/32 train=0.6843 val=0.5994
[nodo07] fold=0 epoch=4/32 train=0.6658 val=0.6128
[nodo07] fold=0 epoch=5/32 train=0.6599 val=0.6052
[nodo07] fold=0 epoch=6/32 train=0.6584 val=0.5820
[nodo07] fold=0 epoch=7/32 train=0.6537 val=0.6283
[nodo07] fold=0 epoch=8/32 train=0.6483 val=0.5838
[nodo07] fold=0 epoch=9/32 train=0.6510 val=0.5757
[nodo07] fold=0 epoch=10/32 train=0.6292 val=0.5776
[nodo07] fold=0 epoch=11/32 train=0.6324 val=0.5988
[nodo07] fold=0 epoch=12/32 train=0.6507 val=0.5846
[nodo07] fold=0 epoch=13/32 train=0.6519 val=0.5667
[nodo07] fold=0 epoch=14/32 train=0.6073 val=0.6046
[nodo07] fold=0 epoch=15/32 train=0.6361 val=0.5801
[nodo07] fold=0 epoch=16/32 train=0.6040 val=0.5760
[nodo07] fold=0 epoch=17/32 train=0.6059 val=0.5850
[nodo07] fold=0 epoch=18/32 train=0.6089 val=0.5775
[nodo07] fold=0 epoch=19/32 train=0.5992 val=0.5660
[nodo07] fold=0 epoch=20/32 train=0.6324 val=0.5709
[nodo07] fold=0 epoch=21/32 train=0.6139 val=0.5605
[nodo07] fold=0 epoch=22/32 train=0.5793 val=0.5676
[nodo07] fold=0 epoch=23/32 train=0.5953 val=0.5669
[nodo07] fold=0 epoch=24/32 train=0.6474 val=0.5652
[nodo07] fold=0 epoch=25/32 train=0.5887 val=0.5636
[nodo07] fold=0 epoch=26/32 train=0.6044 val=0.5691
[nodo07] fold=0 epoch=27/32 train=0.5972 val=0.5667
[nodo07] fold=0 epoch=28/32 train=0.6262 val=0.5618
[nodo07] fold=0 epoch=29/32 train=0.5764 val=0.5621
[nodo07] fold=0 epoch=30/32 train=0.6110 val=0.5627
[nodo07] fold=1 epoch=1/32 train=0.7439 val=0.6489
[nodo07] fold=1 epoch=2/32 train=0.7104 val=0.6160
[nodo07] fold=1 epoch=3/32 train=0.6594 val=0.6355
[nodo07] fold=1 epoch=4/32 train=0.6838 val=0.6038
[nodo07] fold=1 epoch=5/32 train=0.6543 val=0.6334
[nodo07] fold=1 epoch=6/32 train=0.6714 val=0.6144
[nodo07] fold=1 epoch=7/32 train=0.6468 val=0.6128
[nodo07] fold=1 epoch=8/32 train=0.6547 val=0.5952
[nodo07] fold=1 epoch=9/32 train=0.6400 val=0.5953
[nodo07] fold=1 epoch=10/32 train=0.6492 val=0.5723
[nodo07] fold=1 epoch=11/32 train=0.6535 val=0.6021
[nodo07] fold=1 epoch=12/32 train=0.6452 val=0.5785
[nodo07] fold=1 epoch=13/32 train=0.6304 val=0.5836
[nodo07] fold=1 epoch=14/32 train=0.6071 val=0.5985
[nodo07] fold=1 epoch=15/32 train=0.5988 val=0.6310
[nodo07] fold=1 epoch=16/32 train=0.6017 val=0.6310
[nodo07] fold=1 epoch=17/32 train=0.6212 val=0.6241
[nodo07] fold=1 epoch=18/32 train=0.6407 val=0.5809
[nodo07] fold=1 epoch=19/32 train=0.5849 val=0.6167
[nodo07] fold=2 epoch=1/32 train=0.7589 val=0.6638
[nodo07] fold=2 epoch=2/32 train=0.7005 val=0.5908
[nodo07] fold=2 epoch=3/32 train=0.6770 val=0.6168
[nodo07] fold=2 epoch=4/32 train=0.6847 val=0.6053
[nodo07] fold=2 epoch=5/32 train=0.6603 val=0.6073
[nodo07] fold=2 epoch=6/32 train=0.6308 val=0.6363
[nodo07] fold=2 epoch=7/32 train=0.6394 val=0.6170
[nodo07] fold=2 epoch=8/32 train=0.6489 val=0.5877
[nodo07] fold=2 epoch=9/32 train=0.6266 val=0.5956
[nodo07] fold=2 epoch=10/32 train=0.6556 val=0.5743
[nodo07] fold=2 epoch=11/32 train=0.6198 val=0.5783
[nodo07] fold=2 epoch=12/32 train=0.6265 val=0.6077
[nodo07] fold=2 epoch=13/32 train=0.6238 val=0.5884
[nodo07] fold=2 epoch=14/32 train=0.5991 val=0.5928
[nodo07] fold=2 epoch=15/32 train=0.6237 val=0.5972
[nodo07] fold=2 epoch=16/32 train=0.6044 val=0.6187
[nodo07] fold=2 epoch=17/32 train=0.6005 val=0.6034
[nodo07] fold=2 epoch=18/32 train=0.5923 val=0.6154
[nodo07] fold=2 epoch=19/32 train=0.6672 val=0.5993

[I 2026-09-01 04:50:39,815] Trial 2 finished with value: 0.5690545958762393 and parameters: {'dropout': 0.32054158990831416, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.353598898589532, 'augmentation_probability': 0.864178064041328, 'rotation_degrees': 1.7972137118997307, 'learning_rate': 7.481077889595557e-05, 'weight_decay': 5.672938088102955e-06, 'auxiliary_weight': 0.16214421629972015, 'consistency_weight': 0.07657069564332465, 'feature_top_k': 32, 'pca_variance': '0.95'}. Best is trial 0 with value: 0.5425339045786125.

[nodo07] fold=0 epoch=1/32 train=0.7246 val=0.6211
[nodo07] fold=0 epoch=2/32 train=0.6674 val=0.6210
[nodo07] fold=0 epoch=3/32 train=0.6621 val=0.5768
[nodo07] fold=0 epoch=4/32 train=0.6348 val=0.5864
[nodo07] fold=0 epoch=5/32 train=0.6380 val=0.6008
[nodo07] fold=0 epoch=6/32 train=0.6431 val=0.5500
[nodo07] fold=0 epoch=7/32 train=0.6304 val=0.5931
[nodo07] fold=0 epoch=8/32 train=0.6167 val=0.5685
[nodo07] fold=0 epoch=9/32 train=0.6318 val=0.5392
[nodo07] fold=0 epoch=10/32 train=0.6256 val=0.5440
[nodo07] fold=0 epoch=11/32 train=0.6075 val=0.5554
[nodo07] fold=0 epoch=12/32 train=0.6229 val=0.5399
[nodo07] fold=0 epoch=13/32 train=0.6205 val=0.5329
[nodo07] fold=0 epoch=14/32 train=0.5685 val=0.5715
[nodo07] fold=0 epoch=15/32 train=0.6128 val=0.5396
[nodo07] fold=0 epoch=16/32 train=0.5871 val=0.5481
[nodo07] fold=0 epoch=17/32 train=0.5756 val=0.5685
[nodo07] fold=0 epoch=18/32 train=0.5850 val=0.5485
[nodo07] fold=0 epoch=19/32 train=0.5714 val=0.5556
[nodo07] fold=0 epoch=20/32 train=0.6078 val=0.5444
[nodo07] fold=0 epoch=21/32 train=0.5922 val=0.5268
[nodo07] fold=0 epoch=22/32 train=0.5434 val=0.5414
[nodo07] fold=0 epoch=23/32 train=0.5604 val=0.5459
[nodo07] fold=0 epoch=24/32 train=0.6047 val=0.5306
[nodo07] fold=0 epoch=25/32 train=0.5633 val=0.5381
[nodo07] fold=0 epoch=26/32 train=0.5556 val=0.5383
[nodo07] fold=0 epoch=27/32 train=0.5554 val=0.5402
[nodo07] fold=0 epoch=28/32 train=0.5859 val=0.5342
[nodo07] fold=0 epoch=29/32 train=0.5477 val=0.5322
[nodo07] fold=0 epoch=30/32 train=0.5823 val=0.5318
[nodo07] fold=1 epoch=1/32 train=0.7312 val=0.6149
[nodo07] fold=1 epoch=2/32 train=0.6865 val=0.6207
[nodo07] fold=1 epoch=3/32 train=0.6365 val=0.6565
[nodo07] fold=1 epoch=4/32 train=0.6587 val=0.5854
[nodo07] fold=1 epoch=5/32 train=0.6274 val=0.6323
[nodo07] fold=1 epoch=6/32 train=0.6380 val=0.5959
[nodo07] fold=1 epoch=7/32 train=0.6148 val=0.6096
[nodo07] fold=1 epoch=8/32 train=0.6030 val=0.5799
[nodo07] fold=1 epoch=9/32 train=0.5966 val=0.5974
[nodo07] fold=1 epoch=10/32 train=0.6165 val=0.5427
[nodo07] fold=1 epoch=11/32 train=0.5915 val=0.6157
[nodo07] fold=1 epoch=12/32 train=0.6218 val=0.5710
[nodo07] fold=1 epoch=13/32 train=0.6071 val=0.5703
[nodo07] fold=1 epoch=14/32 train=0.5793 val=0.5775
[nodo07] fold=1 epoch=15/32 train=0.5679 val=0.6030
[nodo07] fold=1 epoch=16/32 train=0.5608 val=0.5994
[nodo07] fold=1 epoch=17/32 train=0.5712 val=0.5893
[nodo07] fold=1 epoch=18/32 train=0.6018 val=0.5483
[nodo07] fold=1 epoch=19/32 train=0.5422 val=0.6033
[nodo07] fold=2 epoch=1/32 train=0.7209 val=0.5856
[nodo07] fold=2 epoch=2/32 train=0.6534 val=0.5736
[nodo07] fold=2 epoch=3/32 train=0.6451 val=0.5944
[nodo07] fold=2 epoch=4/32 train=0.6629 val=0.5946
[nodo07] fold=2 epoch=5/32 train=0.6226 val=0.5748
[nodo07] fold=2 epoch=6/32 train=0.6012 val=0.6417
[nodo07] fold=2 epoch=7/32 train=0.6023 val=0.5966
[nodo07] fold=2 epoch=8/32 train=0.6013 val=0.5628
[nodo07] fold=2 epoch=9/32 train=0.5880 val=0.6110
[nodo07] fold=2 epoch=10/32 train=0.6125 val=0.5675
[nodo07] fold=2 epoch=11/32 train=0.5604 val=0.5568
[nodo07] fold=2 epoch=12/32 train=0.5808 val=0.5881
[nodo07] fold=2 epoch=13/32 train=0.5777 val=0.5756
[nodo07] fold=2 epoch=14/32 train=0.5684 val=0.5795
[nodo07] fold=2 epoch=15/32 train=0.5826 val=0.5794
[nodo07] fold=2 epoch=16/32 train=0.5811 val=0.6142
[nodo07] fold=2 epoch=17/32 train=0.5670 val=0.5980
[nodo07] fold=2 epoch=18/32 train=0.5366 val=0.5969
[nodo07] fold=2 epoch=19/32 train=0.6224 val=0.5965
[nodo07] fold=2 epoch=20/32 train=0.5429 val=0.5966

[I 2026-09-01 05:31:02,357] Trial 3 finished with value: 0.5421006317287116 and parameters: {'dropout': 0.31053716538911136, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.0714245993567797, 'augmentation_probability': 0.9048973731712826, 'rotation_degrees': 0.7085853284192994, 'learning_rate': 0.00019828185625010928, 'weight_decay': 8.725332046025304e-06, 'auxiliary_weight': 0.14238611577116755, 'consistency_weight': 0.09413476828443679, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 3 with value: 0.5421006317287116.

[nodo07] fold=0 epoch=1/32 train=0.7271 val=0.6158
[nodo07] fold=0 epoch=2/32 train=0.6642 val=0.6153
[nodo07] fold=0 epoch=3/32 train=0.6557 val=0.5837
[nodo07] fold=0 epoch=4/32 train=0.6318 val=0.5969
[nodo07] fold=0 epoch=5/32 train=0.6418 val=0.6018
[nodo07] fold=0 epoch=6/32 train=0.6401 val=0.5600
[nodo07] fold=0 epoch=7/32 train=0.6290 val=0.5959
[nodo07] fold=0 epoch=8/32 train=0.6165 val=0.5764
[nodo07] fold=0 epoch=9/32 train=0.6297 val=0.5435
[nodo07] fold=0 epoch=10/32 train=0.6110 val=0.5593
[nodo07] fold=0 epoch=11/32 train=0.6035 val=0.5689
[nodo07] fold=0 epoch=12/32 train=0.6149 val=0.5400
[nodo07] fold=0 epoch=13/32 train=0.6143 val=0.5181
[nodo07] fold=0 epoch=14/32 train=0.5590 val=0.5749
[nodo07] fold=0 epoch=15/32 train=0.6083 val=0.5291
[nodo07] fold=0 epoch=16/32 train=0.5775 val=0.5511
[nodo07] fold=0 epoch=17/32 train=0.5710 val=0.5488
[nodo07] fold=0 epoch=18/32 train=0.5667 val=0.5382
[nodo07] fold=0 epoch=19/32 train=0.5621 val=0.5464
[nodo07] fold=0 epoch=20/32 train=0.5999 val=0.5413
[nodo07] fold=0 epoch=21/32 train=0.5836 val=0.5267
[nodo07] fold=0 epoch=22/32 train=0.5405 val=0.5355
[nodo07] fold=1 epoch=1/32 train=0.7367 val=0.6468
[nodo07] fold=1 epoch=2/32 train=0.6734 val=0.5987
[nodo07] fold=1 epoch=3/32 train=0.6354 val=0.6347
[nodo07] fold=1 epoch=4/32 train=0.6511 val=0.5780
[nodo07] fold=1 epoch=5/32 train=0.6170 val=0.6023
[nodo07] fold=1 epoch=6/32 train=0.6325 val=0.5913
[nodo07] fold=1 epoch=7/32 train=0.6098 val=0.5896
[nodo07] fold=1 epoch=8/32 train=0.6082 val=0.5807
[nodo07] fold=1 epoch=9/32 train=0.6030 val=0.5877
[nodo07] fold=1 epoch=10/32 train=0.6172 val=0.5471
[nodo07] fold=1 epoch=11/32 train=0.6042 val=0.6062
[nodo07] fold=1 epoch=12/32 train=0.6193 val=0.5695
[nodo07] fold=1 epoch=13/32 train=0.6212 val=0.5771
[nodo07] fold=1 epoch=14/32 train=0.5841 val=0.5795
[nodo07] fold=1 epoch=15/32 train=0.5854 val=0.6317
[nodo07] fold=1 epoch=16/32 train=0.5761 val=0.5905
[nodo07] fold=1 epoch=17/32 train=0.5833 val=0.6029
[nodo07] fold=1 epoch=18/32 train=0.6124 val=0.5514
[nodo07] fold=1 epoch=19/32 train=0.5488 val=0.6109
[nodo07] fold=2 epoch=1/32 train=0.7087 val=0.6001
[nodo07] fold=2 epoch=2/32 train=0.6600 val=0.5926
[nodo07] fold=2 epoch=3/32 train=0.6566 val=0.6029
[nodo07] fold=2 epoch=4/32 train=0.6656 val=0.6075
[nodo07] fold=2 epoch=5/32 train=0.6347 val=0.5818
[nodo07] fold=2 epoch=6/32 train=0.6002 val=0.6437
[nodo07] fold=2 epoch=7/32 train=0.6082 val=0.6003
[nodo07] fold=2 epoch=8/32 train=0.6116 val=0.5833
[nodo07] fold=2 epoch=9/32 train=0.5994 val=0.6075
[nodo07] fold=2 epoch=10/32 train=0.6206 val=0.5739
[nodo07] fold=2 epoch=11/32 train=0.5808 val=0.5744
[nodo07] fold=2 epoch=12/32 train=0.5796 val=0.6059
[nodo07] fold=2 epoch=13/32 train=0.5894 val=0.5893
[nodo07] fold=2 epoch=14/32 train=0.5604 val=0.5897
[nodo07] fold=2 epoch=15/32 train=0.5877 val=0.5874
[nodo07] fold=2 epoch=16/32 train=0.5654 val=0.6190
[nodo07] fold=2 epoch=17/32 train=0.5671 val=0.6089
[nodo07] fold=2 epoch=18/32 train=0.5453 val=0.6129
[nodo07] fold=2 epoch=19/32 train=0.6232 val=0.5955

[I 2026-09-01 06:07:25,177] Trial 4 finished with value: 0.5463685662376215 and parameters: {'dropout': 0.252079184629877, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.357071423812877, 'augmentation_probability': 0.9520891718994687, 'rotation_degrees': 1.144489821198826, 'learning_rate': 0.00010132899745809597, 'weight_decay': 7.900557521606566e-06, 'auxiliary_weight': 0.13719408780928088, 'consistency_weight': 0.03983954162832684, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 3 with value: 0.5421006317287116.

[nodo07] fold=0 epoch=1/32 train=0.6751 val=0.5839
[nodo07] fold=0 epoch=2/32 train=0.6472 val=0.5444
[nodo07] fold=0 epoch=3/32 train=0.6147 val=0.5376
[nodo07] fold=0 epoch=4/32 train=0.6017 val=0.5198
[nodo07] fold=0 epoch=5/32 train=0.5911 val=0.5206
[nodo07] fold=0 epoch=6/32 train=0.5826 val=0.5086
[nodo07] fold=0 epoch=7/32 train=0.5680 val=0.5704
[nodo07] fold=0 epoch=8/32 train=0.5775 val=0.5548
[nodo07] fold=0 epoch=9/32 train=0.5707 val=0.5389
[nodo07] fold=0 epoch=10/32 train=0.5652 val=0.5204
[nodo07] fold=0 epoch=11/32 train=0.5287 val=0.5830
[nodo07] fold=0 epoch=12/32 train=0.5255 val=0.5723
[nodo07] fold=0 epoch=13/32 train=0.5357 val=0.5606
[nodo07] fold=0 epoch=14/32 train=0.4921 val=0.6256
[nodo07] fold=0 epoch=15/32 train=0.5152 val=0.6037
[nodo07] fold=1 epoch=1/32 train=0.6935 val=0.6002
[nodo07] fold=1 epoch=2/32 train=0.6447 val=0.6442
[nodo07] fold=1 epoch=3/32 train=0.5992 val=0.6076
[nodo07] fold=1 epoch=4/32 train=0.5791 val=0.5865
[nodo07] fold=1 epoch=5/32 train=0.5536 val=0.6837
[nodo07] fold=1 epoch=6/32 train=0.5753 val=0.6498
[nodo07] fold=1 epoch=7/32 train=0.5431 val=0.6360
[nodo07] fold=1 epoch=8/32 train=0.5454 val=0.6253
[nodo07] fold=1 epoch=9/32 train=0.5095 val=0.7034
[nodo07] fold=1 epoch=10/32 train=0.5699 val=0.5874
[nodo07] fold=1 epoch=11/32 train=0.4996 val=0.6955
[nodo07] fold=1 epoch=12/32 train=0.5066 val=0.6283
[nodo07] fold=1 epoch=13/32 train=0.5116 val=0.6557
[nodo07] fold=2 epoch=1/32 train=0.6792 val=0.5899
[nodo07] fold=2 epoch=2/32 train=0.6425 val=0.5771
[nodo07] fold=2 epoch=3/32 train=0.6159 val=0.6406
[nodo07] fold=2 epoch=4/32 train=0.6553 val=0.6123
[nodo07] fold=2 epoch=5/32 train=0.5821 val=0.6035
[nodo07] fold=2 epoch=6/32 train=0.5573 val=0.6898
[nodo07] fold=2 epoch=7/32 train=0.5442 val=0.6546
[nodo07] fold=2 epoch=8/32 train=0.5594 val=0.6055
[nodo07] fold=2 epoch=9/32 train=0.5267 val=0.6357
[nodo07] fold=2 epoch=10/32 train=0.5400 val=0.6405
[nodo07] fold=2 epoch=11/32 train=0.4946 val=0.6371

[I 2026-09-01 06:31:03,394] Trial 5 finished with value: 0.5573981395157347 and parameters: {'dropout': 0.27472818079832495, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.333427716140086, 'augmentation_probability': 0.9354152238512983, 'rotation_degrees': 0.6851228801472286, 'learning_rate': 0.0002118821422445362, 'weight_decay': 2.9442196458037918e-05, 'auxiliary_weight': 0.15494588248066815, 'consistency_weight': 0.05878538581878828, 'feature_top_k': 64, 'pca_variance': 'none'}. Best is trial 3 with value: 0.5421006317287116.

[nodo07] fold=0 epoch=1/32 train=0.7347 val=0.6553
[nodo07] fold=0 epoch=2/32 train=0.6780 val=0.6141
[nodo07] fold=0 epoch=3/32 train=0.6460 val=0.5805
[nodo07] fold=0 epoch=4/32 train=0.6356 val=0.5803
[nodo07] fold=0 epoch=5/32 train=0.6339 val=0.5696
[nodo07] fold=0 epoch=6/32 train=0.6362 val=0.5519
[nodo07] fold=0 epoch=7/32 train=0.6324 val=0.5759
[nodo07] fold=0 epoch=8/32 train=0.6161 val=0.5616
[nodo07] fold=0 epoch=9/32 train=0.6298 val=0.5415
[nodo07] fold=0 epoch=10/32 train=0.6118 val=0.5346
[nodo07] fold=0 epoch=11/32 train=0.5984 val=0.5597
[nodo07] fold=0 epoch=12/32 train=0.6141 val=0.5459
[nodo07] fold=0 epoch=13/32 train=0.6212 val=0.5278
[nodo07] fold=0 epoch=14/32 train=0.5667 val=0.5696
[nodo07] fold=0 epoch=15/32 train=0.6026 val=0.5368
[nodo07] fold=0 epoch=16/32 train=0.5858 val=0.5489
[nodo07] fold=0 epoch=17/32 train=0.5763 val=0.5560
[nodo07] fold=0 epoch=18/32 train=0.5832 val=0.5460
[nodo07] fold=0 epoch=19/32 train=0.5758 val=0.5408
[nodo07] fold=0 epoch=20/32 train=0.6042 val=0.5335
[nodo07] fold=0 epoch=21/32 train=0.5821 val=0.5228
[nodo07] fold=0 epoch=22/32 train=0.5321 val=0.5338
[nodo07] fold=0 epoch=23/32 train=0.5529 val=0.5430
[nodo07] fold=0 epoch=24/32 train=0.6061 val=0.5361
[nodo07] fold=0 epoch=25/32 train=0.5601 val=0.5387
[nodo07] fold=0 epoch=26/32 train=0.5651 val=0.5409
[nodo07] fold=0 epoch=27/32 train=0.5591 val=0.5393
[nodo07] fold=0 epoch=28/32 train=0.5858 val=0.5348
[nodo07] fold=0 epoch=29/32 train=0.5604 val=0.5370
[nodo07] fold=0 epoch=30/32 train=0.5844 val=0.5355
[nodo07] fold=1 epoch=1/32 train=0.7327 val=0.6485
[nodo07] fold=1 epoch=2/32 train=0.6902 val=0.6068
[nodo07] fold=1 epoch=3/32 train=0.6388 val=0.6510
[nodo07] fold=1 epoch=4/32 train=0.6609 val=0.5945
[nodo07] fold=1 epoch=5/32 train=0.6345 val=0.6187
[nodo07] fold=1 epoch=6/32 train=0.6477 val=0.6002
[nodo07] fold=1 epoch=7/32 train=0.6181 val=0.5958
[nodo07] fold=1 epoch=8/32 train=0.6118 val=0.5924
[nodo07] fold=1 epoch=9/32 train=0.6088 val=0.5953
[nodo07] fold=1 epoch=10/32 train=0.6261 val=0.5535
[nodo07] fold=1 epoch=11/32 train=0.6069 val=0.5851
[nodo07] fold=1 epoch=12/32 train=0.6161 val=0.5755
[nodo07] fold=1 epoch=13/32 train=0.6173 val=0.5676
[nodo07] fold=1 epoch=14/32 train=0.5818 val=0.5808
[nodo07] fold=1 epoch=15/32 train=0.5816 val=0.6166
[nodo07] fold=1 epoch=16/32 train=0.5799 val=0.5745
[nodo07] fold=1 epoch=17/32 train=0.5781 val=0.6034
[nodo07] fold=1 epoch=18/32 train=0.6201 val=0.5536
[nodo07] fold=1 epoch=19/32 train=0.5480 val=0.6108
[nodo07] fold=2 epoch=1/32 train=0.7352 val=0.6098
[nodo07] fold=2 epoch=2/32 train=0.6574 val=0.5794
[nodo07] fold=2 epoch=3/32 train=0.6458 val=0.6015
[nodo07] fold=2 epoch=4/32 train=0.6676 val=0.5989
[nodo07] fold=2 epoch=5/32 train=0.6368 val=0.5773
[nodo07] fold=2 epoch=6/32 train=0.5999 val=0.6479
[nodo07] fold=2 epoch=7/32 train=0.6033 val=0.6039
[nodo07] fold=2 epoch=8/32 train=0.6102 val=0.5726
[nodo07] fold=2 epoch=9/32 train=0.5969 val=0.6256
[nodo07] fold=2 epoch=10/32 train=0.6163 val=0.5680
[nodo07] fold=2 epoch=11/32 train=0.5732 val=0.5624
[nodo07] fold=2 epoch=12/32 train=0.5933 val=0.5856
[nodo07] fold=2 epoch=13/32 train=0.5876 val=0.5768
[nodo07] fold=2 epoch=14/32 train=0.5777 val=0.5696
[nodo07] fold=2 epoch=15/32 train=0.5935 val=0.5821
[nodo07] fold=2 epoch=16/32 train=0.5789 val=0.5920
[nodo07] fold=2 epoch=17/32 train=0.5783 val=0.5875
[nodo07] fold=2 epoch=18/32 train=0.5435 val=0.5888
[nodo07] fold=2 epoch=19/32 train=0.6295 val=0.5812
[nodo07] fold=2 epoch=20/32 train=0.5542 val=0.5990

[I 2026-09-01 07:11:46,473] Trial 6 finished with value: 0.5462255691882841 and parameters: {'dropout': 0.28524651467188256, 'tabular_embedding_dim': 16, 'augmentation_magnitude': 2.4977140108393048, 'augmentation_probability': 0.9158305212198063, 'rotation_degrees': 1.2918894762713578, 'learning_rate': 0.00015667237950059705, 'weight_decay': 1.8960108129290245e-05, 'auxiliary_weight': 0.13924459576032877, 'consistency_weight': 0.05242379535913067, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 3 with value: 0.5421006317287116.

[nodo07] fold=0 epoch=1/32 train=0.7160 val=0.6169
[nodo07] fold=0 epoch=2/32 train=0.6396 val=0.6039
[nodo07] fold=0 epoch=3/32 train=0.6401 val=0.5556
[nodo07] fold=0 epoch=4/32 train=0.6306 val=0.5672
[nodo07] fold=0 epoch=5/32 train=0.6160 val=0.5669
[nodo07] fold=0 epoch=6/32 train=0.6178 val=0.5362
[nodo07] fold=0 epoch=7/32 train=0.6092 val=0.5656
[nodo07] fold=0 epoch=8/32 train=0.6137 val=0.5468
[nodo07] fold=0 epoch=9/32 train=0.6081 val=0.5297
[nodo07] fold=0 epoch=10/32 train=0.6056 val=0.5302
[nodo07] fold=0 epoch=11/32 train=0.5771 val=0.5635
[nodo07] fold=0 epoch=12/32 train=0.5965 val=0.5410
[nodo07] fold=0 epoch=13/32 train=0.5964 val=0.5097
[nodo07] fold=0 epoch=14/32 train=0.5430 val=0.5519
[nodo07] fold=0 epoch=15/32 train=0.5844 val=0.5128
[nodo07] fold=0 epoch=16/32 train=0.5548 val=0.5314
[nodo07] fold=0 epoch=17/32 train=0.5440 val=0.5488
[nodo07] fold=0 epoch=18/32 train=0.5616 val=0.5380
[nodo07] fold=0 epoch=19/32 train=0.5629 val=0.5346
[nodo07] fold=0 epoch=20/32 train=0.5814 val=0.5325
[nodo07] fold=0 epoch=21/32 train=0.5600 val=0.5256
[nodo07] fold=0 epoch=22/32 train=0.5266 val=0.5331
[nodo07] fold=1 epoch=1/32 train=0.7227 val=0.6280
[nodo07] fold=1 epoch=2/32 train=0.6713 val=0.6047
[nodo07] fold=1 epoch=3/32 train=0.6180 val=0.6566
[nodo07] fold=1 epoch=4/32 train=0.6269 val=0.5977
[nodo07] fold=1 epoch=5/32 train=0.5893 val=0.6835
[nodo07] fold=1 epoch=6/32 train=0.6059 val=0.6247
[nodo07] fold=1 epoch=7/32 train=0.5885 val=0.6345
[nodo07] fold=1 epoch=8/32 train=0.5721 val=0.5856
[nodo07] fold=1 epoch=9/32 train=0.5632 val=0.6435
[nodo07] fold=1 epoch=10/32 train=0.6072 val=0.5807
[nodo07] fold=1 epoch=11/32 train=0.5584 val=0.6319
[nodo07] fold=1 epoch=12/32 train=0.5675 val=0.6065
[nodo07] fold=1 epoch=13/32 train=0.5776 val=0.6334
[nodo07] fold=1 epoch=14/32 train=0.5584 val=0.6305
[nodo07] fold=1 epoch=15/32 train=0.5448 val=0.6423
[nodo07] fold=1 epoch=16/32 train=0.5264 val=0.6597
[nodo07] fold=1 epoch=17/32 train=0.5444 val=0.6401
[nodo07] fold=1 epoch=18/32 train=0.5745 val=0.6251
[nodo07] fold=1 epoch=19/32 train=0.5313 val=0.6537
[nodo07] fold=2 epoch=1/32 train=0.7199 val=0.6167
[nodo07] fold=2 epoch=2/32 train=0.6377 val=0.5942
[nodo07] fold=2 epoch=3/32 train=0.6296 val=0.6310
[nodo07] fold=2 epoch=4/32 train=0.6557 val=0.6208
[nodo07] fold=2 epoch=5/32 train=0.6184 val=0.6005
[nodo07] fold=2 epoch=6/32 train=0.5872 val=0.6786
[nodo07] fold=2 epoch=7/32 train=0.5883 val=0.6024
[nodo07] fold=2 epoch=8/32 train=0.6060 val=0.5824
[nodo07] fold=2 epoch=9/32 train=0.5956 val=0.6019
[nodo07] fold=2 epoch=10/32 train=0.6246 val=0.5545
[nodo07] fold=2 epoch=11/32 train=0.5668 val=0.5443
[nodo07] fold=2 epoch=12/32 train=0.5635 val=0.5961
[nodo07] fold=2 epoch=13/32 train=0.5659 val=0.5656
[nodo07] fold=2 epoch=14/32 train=0.5633 val=0.5903
[nodo07] fold=2 epoch=15/32 train=0.5713 val=0.5893
[nodo07] fold=2 epoch=16/32 train=0.5541 val=0.5954
[nodo07] fold=2 epoch=17/32 train=0.5617 val=0.6049
[nodo07] fold=2 epoch=18/32 train=0.5553 val=0.5967
[nodo07] fold=2 epoch=19/32 train=0.6098 val=0.5884
[nodo07] fold=2 epoch=20/32 train=0.5410 val=0.5962

[I 2026-09-01 07:47:40,830] Trial 7 finished with value: 0.5448926346636 and parameters: {'dropout': 0.3182776951339025, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.035086703076872, 'augmentation_probability': 0.9401376550373752, 'rotation_degrees': 1.6957320367990638, 'learning_rate': 0.0001280696281143168, 'weight_decay': 7.220899186485923e-06, 'auxiliary_weight': 0.10569324694723435, 'consistency_weight': 0.08580716891506404, 'feature_top_k': 64, 'pca_variance': '0.98'}. Best is trial 3 with value: 0.5421006317287116.

[nodo07] fold=0 epoch=1/32 train=0.7420 val=0.6344
[nodo07] fold=0 epoch=2/32 train=0.6829 val=0.6275
[nodo07] fold=0 epoch=3/32 train=0.6798 val=0.5791
[nodo07] fold=0 epoch=4/32 train=0.6526 val=0.5890
[nodo07] fold=0 epoch=5/32 train=0.6499 val=0.6143
[nodo07] fold=0 epoch=6/32 train=0.6515 val=0.5573
[nodo07] fold=0 epoch=7/32 train=0.6521 val=0.6282
[nodo07] fold=0 epoch=8/32 train=0.6315 val=0.5826
[nodo07] fold=0 epoch=9/32 train=0.6458 val=0.5424
[nodo07] fold=0 epoch=10/32 train=0.6310 val=0.5499
[nodo07] fold=0 epoch=11/32 train=0.6208 val=0.5651
[nodo07] fold=0 epoch=12/32 train=0.6290 val=0.5528
[nodo07] fold=0 epoch=13/32 train=0.6346 val=0.5448
[nodo07] fold=0 epoch=14/32 train=0.5846 val=0.5781
[nodo07] fold=0 epoch=15/32 train=0.6188 val=0.5390
[nodo07] fold=0 epoch=16/32 train=0.5973 val=0.5542
[nodo07] fold=0 epoch=17/32 train=0.5820 val=0.5605
[nodo07] fold=0 epoch=18/32 train=0.5956 val=0.5431
[nodo07] fold=0 epoch=19/32 train=0.5768 val=0.5498
[nodo07] fold=0 epoch=20/32 train=0.6148 val=0.5418
[nodo07] fold=0 epoch=21/32 train=0.5976 val=0.5245
[nodo07] fold=0 epoch=22/32 train=0.5431 val=0.5309
[nodo07] fold=0 epoch=23/32 train=0.5631 val=0.5361
[nodo07] fold=0 epoch=24/32 train=0.6103 val=0.5337
[nodo07] fold=0 epoch=25/32 train=0.5678 val=0.5311
[nodo07] fold=0 epoch=26/32 train=0.5707 val=0.5357
[nodo07] fold=0 epoch=27/32 train=0.5644 val=0.5355
[nodo07] fold=0 epoch=28/32 train=0.5950 val=0.5306
[nodo07] fold=0 epoch=29/32 train=0.5527 val=0.5298
[nodo07] fold=0 epoch=30/32 train=0.5898 val=0.5289
[nodo07] fold=1 epoch=1/32 train=0.7439 val=0.6270
[nodo07] fold=1 epoch=2/32 train=0.6965 val=0.6043
[nodo07] fold=1 epoch=3/32 train=0.6563 val=0.6578
[nodo07] fold=1 epoch=4/32 train=0.6685 val=0.5903
[nodo07] fold=1 epoch=5/32 train=0.6426 val=0.6331
[nodo07] fold=1 epoch=6/32 train=0.6558 val=0.5985
[nodo07] fold=1 epoch=7/32 train=0.6251 val=0.6026
[nodo07] fold=1 epoch=8/32 train=0.6176 val=0.6006
[nodo07] fold=1 epoch=9/32 train=0.6178 val=0.6077
[nodo07] fold=1 epoch=10/32 train=0.6416 val=0.5471
[nodo07] fold=1 epoch=11/32 train=0.6141 val=0.6144
[nodo07] fold=1 epoch=12/32 train=0.6365 val=0.5797
[nodo07] fold=1 epoch=13/32 train=0.6354 val=0.5613
[nodo07] fold=1 epoch=14/32 train=0.5946 val=0.5802
[nodo07] fold=1 epoch=15/32 train=0.5917 val=0.6048
[nodo07] fold=1 epoch=16/32 train=0.5872 val=0.5950
[nodo07] fold=1 epoch=17/32 train=0.5875 val=0.5936
[nodo07] fold=1 epoch=18/32 train=0.6259 val=0.5431
[nodo07] fold=1 epoch=19/32 train=0.5624 val=0.6067
[nodo07] fold=1 epoch=20/32 train=0.5676 val=0.6185
[nodo07] fold=1 epoch=21/32 train=0.5926 val=0.5825
[nodo07] fold=1 epoch=22/32 train=0.5687 val=0.5786
[nodo07] fold=1 epoch=23/32 train=0.5673 val=0.5764
[nodo07] fold=1 epoch=24/32 train=0.5838 val=0.5696
[nodo07] fold=1 epoch=25/32 train=0.5921 val=0.5590
[nodo07] fold=1 epoch=26/32 train=0.5731 val=0.5641
[nodo07] fold=1 epoch=27/32 train=0.5632 val=0.5711
[nodo07] fold=2 epoch=1/32 train=0.7324 val=0.5771
[nodo07] fold=2 epoch=2/32 train=0.6638 val=0.5730
[nodo07] fold=2 epoch=3/32 train=0.6571 val=0.5893
[nodo07] fold=2 epoch=4/32 train=0.6727 val=0.5920
[nodo07] fold=2 epoch=5/32 train=0.6368 val=0.5757
[nodo07] fold=2 epoch=6/32 train=0.6111 val=0.6391
[nodo07] fold=2 epoch=7/32 train=0.6118 val=0.6044
[nodo07] fold=2 epoch=8/32 train=0.6178 val=0.5748
[nodo07] fold=2 epoch=9/32 train=0.5967 val=0.6035
[nodo07] fold=2 epoch=10/32 train=0.6184 val=0.5622
[nodo07] fold=2 epoch=11/32 train=0.5728 val=0.5564
[nodo07] fold=2 epoch=12/32 train=0.5845 val=0.5901
[nodo07] fold=2 epoch=13/32 train=0.5867 val=0.5828
[nodo07] fold=2 epoch=14/32 train=0.5645 val=0.5732
[nodo07] fold=2 epoch=15/32 train=0.5828 val=0.5783
[nodo07] fold=2 epoch=16/32 train=0.5761 val=0.6096
[nodo07] fold=2 epoch=17/32 train=0.5665 val=0.5942
[nodo07] fold=2 epoch=18/32 train=0.5457 val=0.6085
[nodo07] fold=2 epoch=19/32 train=0.6242 val=0.5926
[nodo07] fold=2 epoch=20/32 train=0.5405 val=0.5968

[I 2026-09-01 08:31:24,386] Trial 8 finished with value: 0.5413053227910657 and parameters: {'dropout': 0.303449174560057, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.148906866015274, 'augmentation_probability': 0.8965685175890187, 'rotation_degrees': 0.6512830515419543, 'learning_rate': 0.00019332472272842616, 'weight_decay': 3.1402459439535528e-06, 'auxiliary_weight': 0.18491404908988887, 'consistency_weight': 0.07418048966437449, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 8 with value: 0.5413053227910657.

[nodo07] fold=0 epoch=1/32 train=0.7523 val=0.6825
[nodo07] fold=0 epoch=2/32 train=0.7284 val=0.6187
[nodo07] fold=0 epoch=3/32 train=0.6854 val=0.5916
[nodo07] fold=0 epoch=4/32 train=0.6603 val=0.6138
[nodo07] fold=0 epoch=5/32 train=0.6682 val=0.6240
[nodo07] fold=0 epoch=6/32 train=0.6661 val=0.5817
[nodo07] fold=0 epoch=7/32 train=0.6625 val=0.6435
[nodo07] fold=0 epoch=8/32 train=0.6608 val=0.6010
[nodo07] fold=0 epoch=9/32 train=0.6635 val=0.5883
[nodo07] fold=0 epoch=10/32 train=0.6525 val=0.5830
[nodo07] fold=0 epoch=11/32 train=0.6349 val=0.5971
[nodo07] fold=0 epoch=12/32 train=0.6553 val=0.5772
[nodo07] fold=0 epoch=13/32 train=0.6654 val=0.5589
[nodo07] fold=0 epoch=14/32 train=0.6003 val=0.6022
[nodo07] fold=0 epoch=15/32 train=0.6310 val=0.5722
[nodo07] fold=0 epoch=16/32 train=0.6083 val=0.5861
[nodo07] fold=0 epoch=17/32 train=0.6071 val=0.5911
[nodo07] fold=0 epoch=18/32 train=0.6114 val=0.5776
[nodo07] fold=0 epoch=19/32 train=0.5978 val=0.5714
[nodo07] fold=0 epoch=20/32 train=0.6386 val=0.5666
[nodo07] fold=0 epoch=21/32 train=0.6221 val=0.5556
[nodo07] fold=0 epoch=22/32 train=0.5770 val=0.5621
[nodo07] fold=0 epoch=23/32 train=0.5884 val=0.5637
[nodo07] fold=0 epoch=24/32 train=0.6368 val=0.5583
[nodo07] fold=0 epoch=25/32 train=0.5923 val=0.5649
[nodo07] fold=0 epoch=26/32 train=0.6025 val=0.5652
[nodo07] fold=0 epoch=27/32 train=0.5941 val=0.5645
[nodo07] fold=0 epoch=28/32 train=0.6135 val=0.5591
[nodo07] fold=0 epoch=29/32 train=0.5906 val=0.5594
[nodo07] fold=0 epoch=30/32 train=0.6176 val=0.5580
[nodo07] fold=1 epoch=1/32 train=0.7555 val=0.6669
[nodo07] fold=1 epoch=2/32 train=0.7302 val=0.6333
[nodo07] fold=1 epoch=3/32 train=0.6733 val=0.6681
[nodo07] fold=1 epoch=4/32 train=0.6893 val=0.6083
[nodo07] fold=1 epoch=5/32 train=0.6715 val=0.6484
[nodo07] fold=1 epoch=6/32 train=0.6821 val=0.6335
[nodo07] fold=1 epoch=7/32 train=0.6490 val=0.6104
[nodo07] fold=1 epoch=8/32 train=0.6518 val=0.6058
[nodo07] fold=1 epoch=9/32 train=0.6542 val=0.6174
[nodo07] fold=1 epoch=10/32 train=0.6489 val=0.5666
[nodo07] fold=1 epoch=11/32 train=0.6590 val=0.6055
[nodo07] fold=1 epoch=12/32 train=0.6471 val=0.5883
[nodo07] fold=1 epoch=13/32 train=0.6415 val=0.5712
[nodo07] fold=1 epoch=14/32 train=0.6030 val=0.5998
[nodo07] fold=1 epoch=15/32 train=0.6095 val=0.6115
[nodo07] fold=1 epoch=16/32 train=0.5858 val=0.6199
[nodo07] fold=1 epoch=17/32 train=0.6139 val=0.6071
[nodo07] fold=1 epoch=18/32 train=0.6469 val=0.5547
[nodo07] fold=1 epoch=19/32 train=0.5849 val=0.6118
[nodo07] fold=1 epoch=20/32 train=0.5820 val=0.6195
[nodo07] fold=1 epoch=21/32 train=0.6256 val=0.5991
[nodo07] fold=1 epoch=22/32 train=0.5827 val=0.6007
[nodo07] fold=1 epoch=23/32 train=0.5839 val=0.5873
[nodo07] fold=1 epoch=24/32 train=0.6026 val=0.5811
[nodo07] fold=1 epoch=25/32 train=0.6167 val=0.5699
[nodo07] fold=1 epoch=26/32 train=0.5989 val=0.5716
[nodo07] fold=1 epoch=27/32 train=0.5760 val=0.5783

[I 2026-09-01 09:05:24,470] Trial 9 pruned.

[nodo07] fold=0 epoch=1/32 train=0.7458 val=0.6376
[nodo07] fold=0 epoch=2/32 train=0.6859 val=0.6395
[nodo07] fold=0 epoch=3/32 train=0.6736 val=0.5799
[nodo07] fold=0 epoch=4/32 train=0.6526 val=0.5834
[nodo07] fold=0 epoch=5/32 train=0.6513 val=0.5992
[nodo07] fold=0 epoch=6/32 train=0.6534 val=0.5485
[nodo07] fold=0 epoch=7/32 train=0.6441 val=0.5986
[nodo07] fold=0 epoch=8/32 train=0.6324 val=0.5810
[nodo07] fold=0 epoch=9/32 train=0.6489 val=0.5415
[nodo07] fold=0 epoch=10/32 train=0.6403 val=0.5418
[nodo07] fold=0 epoch=11/32 train=0.6165 val=0.5583
[nodo07] fold=0 epoch=12/32 train=0.6285 val=0.5431
[nodo07] fold=0 epoch=13/32 train=0.6249 val=0.5347
[nodo07] fold=0 epoch=14/32 train=0.5805 val=0.5768
[nodo07] fold=0 epoch=15/32 train=0.6135 val=0.5334
[nodo07] fold=0 epoch=16/32 train=0.5879 val=0.5417
[nodo07] fold=0 epoch=17/32 train=0.5761 val=0.5594
[nodo07] fold=0 epoch=18/32 train=0.5853 val=0.5465
[nodo07] fold=0 epoch=19/32 train=0.5773 val=0.5564
[nodo07] fold=0 epoch=20/32 train=0.6129 val=0.5317
[nodo07] fold=0 epoch=21/32 train=0.5943 val=0.5206
[nodo07] fold=0 epoch=22/32 train=0.5396 val=0.5316
[nodo07] fold=0 epoch=23/32 train=0.5606 val=0.5395
[nodo07] fold=0 epoch=24/32 train=0.5986 val=0.5341
[nodo07] fold=0 epoch=25/32 train=0.5631 val=0.5330
[nodo07] fold=0 epoch=26/32 train=0.5588 val=0.5308
[nodo07] fold=0 epoch=27/32 train=0.5596 val=0.5317
[nodo07] fold=0 epoch=28/32 train=0.5840 val=0.5287
[nodo07] fold=0 epoch=29/32 train=0.5493 val=0.5266
[nodo07] fold=0 epoch=30/32 train=0.5761 val=0.5264
[nodo07] fold=1 epoch=1/32 train=0.7396 val=0.6344
[nodo07] fold=1 epoch=2/32 train=0.6978 val=0.6196
[nodo07] fold=1 epoch=3/32 train=0.6509 val=0.6498
[nodo07] fold=1 epoch=4/32 train=0.6714 val=0.5838
[nodo07] fold=1 epoch=5/32 train=0.6388 val=0.6274
[nodo07] fold=1 epoch=6/32 train=0.6547 val=0.5902
[nodo07] fold=1 epoch=7/32 train=0.6257 val=0.5941
[nodo07] fold=1 epoch=8/32 train=0.6133 val=0.6004
[nodo07] fold=1 epoch=9/32 train=0.6101 val=0.5962
[nodo07] fold=1 epoch=10/32 train=0.6299 val=0.5570
[nodo07] fold=1 epoch=11/32 train=0.6201 val=0.6277
[nodo07] fold=1 epoch=12/32 train=0.6369 val=0.5864
[nodo07] fold=1 epoch=13/32 train=0.6295 val=0.5536
[nodo07] fold=1 epoch=14/32 train=0.5916 val=0.5705
[nodo07] fold=1 epoch=15/32 train=0.5849 val=0.6091
[nodo07] fold=1 epoch=16/32 train=0.5849 val=0.5729
[nodo07] fold=1 epoch=17/32 train=0.5810 val=0.5934
[nodo07] fold=1 epoch=18/32 train=0.6206 val=0.5392
[nodo07] fold=1 epoch=19/32 train=0.5593 val=0.6067
[nodo07] fold=1 epoch=20/32 train=0.5615 val=0.6086
[nodo07] fold=1 epoch=21/32 train=0.5884 val=0.5830
[nodo07] fold=1 epoch=22/32 train=0.5622 val=0.5790
[nodo07] fold=1 epoch=23/32 train=0.5581 val=0.5738
[nodo07] fold=1 epoch=24/32 train=0.5773 val=0.5700
[nodo07] fold=1 epoch=25/32 train=0.5885 val=0.5609
[nodo07] fold=1 epoch=26/32 train=0.5696 val=0.5619
[nodo07] fold=1 epoch=27/32 train=0.5577 val=0.5666
[nodo07] fold=2 epoch=1/32 train=0.7363 val=0.5878
[nodo07] fold=2 epoch=2/32 train=0.6663 val=0.5752
[nodo07] fold=2 epoch=3/32 train=0.6637 val=0.5888
[nodo07] fold=2 epoch=4/32 train=0.6787 val=0.5953
[nodo07] fold=2 epoch=5/32 train=0.6369 val=0.5770
[nodo07] fold=2 epoch=6/32 train=0.6098 val=0.6271
[nodo07] fold=2 epoch=7/32 train=0.6148 val=0.5940
[nodo07] fold=2 epoch=8/32 train=0.6046 val=0.5763
[nodo07] fold=2 epoch=9/32 train=0.6028 val=0.6067
[nodo07] fold=2 epoch=10/32 train=0.6178 val=0.5710
[nodo07] fold=2 epoch=11/32 train=0.5774 val=0.5552
[nodo07] fold=2 epoch=12/32 train=0.5867 val=0.5928
[nodo07] fold=2 epoch=13/32 train=0.5884 val=0.5683
[nodo07] fold=2 epoch=14/32 train=0.5740 val=0.5738
[nodo07] fold=2 epoch=15/32 train=0.5922 val=0.5882
[nodo07] fold=2 epoch=16/32 train=0.5854 val=0.6213
[nodo07] fold=2 epoch=17/32 train=0.5774 val=0.5979
[nodo07] fold=2 epoch=18/32 train=0.5456 val=0.5880
[nodo07] fold=2 epoch=19/32 train=0.6331 val=0.5789
[nodo07] fold=2 epoch=20/32 train=0.5462 val=0.5938

[I 2026-09-01 10:25:45,337] Trial 10 finished with value: 0.5383430627224257 and parameters: {'dropout': 0.30107817880640764, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.096992910498502, 'augmentation_probability': 0.9128816406981138, 'rotation_degrees': 1.114031505708279, 'learning_rate': 0.00019885690352756317, 'weight_decay': 4.700003863613711e-06, 'auxiliary_weight': 0.18927241107793813, 'consistency_weight': 0.05534154491946679, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 10 with value: 0.5383430627224257.

[nodo07] fold=0 epoch=1/32 train=0.7210 val=0.5979
[nodo07] fold=0 epoch=2/32 train=0.6781 val=0.6095
[nodo07] fold=0 epoch=3/32 train=0.6587 val=0.5710
[nodo07] fold=0 epoch=4/32 train=0.6423 val=0.5685
[nodo07] fold=0 epoch=5/32 train=0.6458 val=0.5788
[nodo07] fold=0 epoch=6/32 train=0.6430 val=0.5441
[nodo07] fold=0 epoch=7/32 train=0.6415 val=0.5882
[nodo07] fold=0 epoch=8/32 train=0.6273 val=0.5724
[nodo07] fold=0 epoch=9/32 train=0.6379 val=0.5330
[nodo07] fold=0 epoch=10/32 train=0.6268 val=0.5246
[nodo07] fold=0 epoch=11/32 train=0.6123 val=0.5563
[nodo07] fold=0 epoch=12/32 train=0.6301 val=0.5441
[nodo07] fold=0 epoch=13/32 train=0.6268 val=0.5339
[nodo07] fold=0 epoch=14/32 train=0.5723 val=0.5628
[nodo07] fold=0 epoch=15/32 train=0.6140 val=0.5321
[nodo07] fold=0 epoch=16/32 train=0.5964 val=0.5440
[nodo07] fold=0 epoch=17/32 train=0.5835 val=0.5512
[nodo07] fold=0 epoch=18/32 train=0.5938 val=0.5366
[nodo07] fold=0 epoch=19/32 train=0.5697 val=0.5454
[nodo07] fold=1 epoch=1/32 train=0.7305 val=0.6152
[nodo07] fold=1 epoch=2/32 train=0.6850 val=0.6089
[nodo07] fold=1 epoch=3/32 train=0.6405 val=0.6383
[nodo07] fold=1 epoch=4/32 train=0.6507 val=0.5788
[nodo07] fold=1 epoch=5/32 train=0.6255 val=0.6310
[nodo07] fold=1 epoch=6/32 train=0.6375 val=0.5921
[nodo07] fold=1 epoch=7/32 train=0.6140 val=0.6059
[nodo07] fold=1 epoch=8/32 train=0.6097 val=0.5969
[nodo07] fold=1 epoch=9/32 train=0.5986 val=0.5933
[nodo07] fold=1 epoch=10/32 train=0.6224 val=0.5513
[nodo07] fold=1 epoch=11/32 train=0.6007 val=0.6362
[nodo07] fold=1 epoch=12/32 train=0.6234 val=0.5728
[nodo07] fold=1 epoch=13/32 train=0.6080 val=0.5543
[nodo07] fold=1 epoch=14/32 train=0.5863 val=0.5641
[nodo07] fold=1 epoch=15/32 train=0.5739 val=0.6099
[nodo07] fold=1 epoch=16/32 train=0.5717 val=0.5793
[nodo07] fold=1 epoch=17/32 train=0.5761 val=0.5900
[nodo07] fold=1 epoch=18/32 train=0.6156 val=0.5408
[nodo07] fold=1 epoch=19/32 train=0.5567 val=0.5915
[nodo07] fold=1 epoch=20/32 train=0.5537 val=0.6023
[nodo07] fold=1 epoch=21/32 train=0.5871 val=0.5683
[nodo07] fold=1 epoch=22/32 train=0.5528 val=0.5739
[nodo07] fold=1 epoch=23/32 train=0.5577 val=0.5781
[nodo07] fold=1 epoch=24/32 train=0.5750 val=0.5734
[nodo07] fold=1 epoch=25/32 train=0.5877 val=0.5701
[nodo07] fold=1 epoch=26/32 train=0.5677 val=0.5652
[nodo07] fold=1 epoch=27/32 train=0.5590 val=0.5682
[nodo07] fold=2 epoch=1/32 train=0.7157 val=0.5790
[nodo07] fold=2 epoch=2/32 train=0.6586 val=0.5748
[nodo07] fold=2 epoch=3/32 train=0.6490 val=0.5860
[nodo07] fold=2 epoch=4/32 train=0.6672 val=0.5907
[nodo07] fold=2 epoch=5/32 train=0.6302 val=0.5693
[nodo07] fold=2 epoch=6/32 train=0.5989 val=0.6376
[nodo07] fold=2 epoch=7/32 train=0.6051 val=0.5921
[nodo07] fold=2 epoch=8/32 train=0.6023 val=0.5648
[nodo07] fold=2 epoch=9/32 train=0.5841 val=0.6059
[nodo07] fold=2 epoch=10/32 train=0.6062 val=0.5681
[nodo07] fold=2 epoch=11/32 train=0.5637 val=0.5610
[nodo07] fold=2 epoch=12/32 train=0.5746 val=0.5941
[nodo07] fold=2 epoch=13/32 train=0.5792 val=0.5871
[nodo07] fold=2 epoch=14/32 train=0.5579 val=0.5850
[nodo07] fold=2 epoch=15/32 train=0.5728 val=0.5880
[nodo07] fold=2 epoch=16/32 train=0.5679 val=0.6126
[nodo07] fold=2 epoch=17/32 train=0.5604 val=0.6011
[nodo07] fold=2 epoch=18/32 train=0.5324 val=0.6002
[nodo07] fold=2 epoch=19/32 train=0.6154 val=0.5993
[nodo07] fold=2 epoch=20/32 train=0.5308 val=0.6101

[I 2026-09-01 11:12:06,668] Trial 11 finished with value: 0.5421382020164991 and parameters: {'dropout': 0.29075872339009, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.129463072274405, 'augmentation_probability': 0.8688730564344589, 'rotation_degrees': 1.4265413059696335, 'learning_rate': 0.0002220793831702413, 'weight_decay': 3.6488256880161217e-06, 'auxiliary_weight': 0.162178940813392, 'consistency_weight': 0.049394709709192575, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 10 with value: 0.5383430627224257.

[nodo07] fold=0 epoch=1/32 train=0.7326 val=0.5912
[nodo07] fold=0 epoch=2/32 train=0.6809 val=0.5986
[nodo07] fold=0 epoch=3/32 train=0.6703 val=0.5721
[nodo07] fold=0 epoch=4/32 train=0.6485 val=0.5824
[nodo07] fold=0 epoch=5/32 train=0.6506 val=0.5789
[nodo07] fold=0 epoch=6/32 train=0.6498 val=0.5397
[nodo07] fold=0 epoch=7/32 train=0.6388 val=0.6084
[nodo07] fold=0 epoch=8/32 train=0.6230 val=0.5890
[nodo07] fold=0 epoch=9/32 train=0.6440 val=0.5400
[nodo07] fold=0 epoch=10/32 train=0.6246 val=0.5389
[nodo07] fold=0 epoch=11/32 train=0.6174 val=0.5553
[nodo07] fold=0 epoch=12/32 train=0.6214 val=0.5366
[nodo07] fold=0 epoch=13/32 train=0.6243 val=0.5194
[nodo07] fold=0 epoch=14/32 train=0.5662 val=0.5715
[nodo07] fold=0 epoch=15/32 train=0.6077 val=0.5268
[nodo07] fold=0 epoch=16/32 train=0.5825 val=0.5438
[nodo07] fold=0 epoch=17/32 train=0.5775 val=0.5497
[nodo07] fold=0 epoch=18/32 train=0.5798 val=0.5320
[nodo07] fold=0 epoch=19/32 train=0.5620 val=0.5491
[nodo07] fold=0 epoch=20/32 train=0.6071 val=0.5418
[nodo07] fold=0 epoch=21/32 train=0.5842 val=0.5211
[nodo07] fold=0 epoch=22/32 train=0.5487 val=0.5329
[nodo07] fold=1 epoch=1/32 train=0.7436 val=0.6007
[nodo07] fold=1 epoch=2/32 train=0.6834 val=0.5885
[nodo07] fold=1 epoch=3/32 train=0.6440 val=0.6255
[nodo07] fold=1 epoch=4/32 train=0.6583 val=0.5727
[nodo07] fold=1 epoch=5/32 train=0.6254 val=0.6134
[nodo07] fold=1 epoch=6/32 train=0.6444 val=0.5954
[nodo07] fold=1 epoch=7/32 train=0.6231 val=0.5940
[nodo07] fold=1 epoch=8/32 train=0.6175 val=0.5980
[nodo07] fold=1 epoch=9/32 train=0.6069 val=0.5933
[nodo07] fold=1 epoch=10/32 train=0.6249 val=0.5500
[nodo07] fold=1 epoch=11/32 train=0.6147 val=0.6585
[nodo07] fold=1 epoch=12/32 train=0.6351 val=0.5703
[nodo07] fold=1 epoch=13/32 train=0.6248 val=0.5696
[nodo07] fold=1 epoch=14/32 train=0.5987 val=0.5774
[nodo07] fold=1 epoch=15/32 train=0.5861 val=0.6237
[nodo07] fold=1 epoch=16/32 train=0.5864 val=0.5969
[nodo07] fold=1 epoch=17/32 train=0.5865 val=0.5903
[nodo07] fold=1 epoch=18/32 train=0.6140 val=0.5499
[nodo07] fold=1 epoch=19/32 train=0.5522 val=0.6253
[nodo07] fold=1 epoch=20/32 train=0.5647 val=0.6210
[nodo07] fold=1 epoch=21/32 train=0.5913 val=0.5859
[nodo07] fold=1 epoch=22/32 train=0.5575 val=0.5773
[nodo07] fold=1 epoch=23/32 train=0.5592 val=0.5742
[nodo07] fold=1 epoch=24/32 train=0.5729 val=0.5751
[nodo07] fold=1 epoch=25/32 train=0.5919 val=0.5639
[nodo07] fold=1 epoch=26/32 train=0.5769 val=0.5660
[nodo07] fold=1 epoch=27/32 train=0.5543 val=0.5750
[nodo07] fold=2 epoch=1/32 train=0.7189 val=0.5992
[nodo07] fold=2 epoch=2/32 train=0.6714 val=0.5901
[nodo07] fold=2 epoch=3/32 train=0.6647 val=0.5953
[nodo07] fold=2 epoch=4/32 train=0.6775 val=0.6051
[nodo07] fold=2 epoch=5/32 train=0.6391 val=0.5856
[nodo07] fold=2 epoch=6/32 train=0.6027 val=0.6343
[nodo07] fold=2 epoch=7/32 train=0.6236 val=0.5982
[nodo07] fold=2 epoch=8/32 train=0.6144 val=0.5753
[nodo07] fold=2 epoch=9/32 train=0.6000 val=0.6143
[nodo07] fold=2 epoch=10/32 train=0.6243 val=0.5844
[nodo07] fold=2 epoch=11/32 train=0.5850 val=0.5693
[nodo07] fold=2 epoch=12/32 train=0.5932 val=0.6052
[nodo07] fold=2 epoch=13/32 train=0.5959 val=0.5978
[nodo07] fold=2 epoch=14/32 train=0.5723 val=0.5829
[nodo07] fold=2 epoch=15/32 train=0.5942 val=0.5826
[nodo07] fold=2 epoch=16/32 train=0.5823 val=0.6243
[nodo07] fold=2 epoch=17/32 train=0.5699 val=0.6063
[nodo07] fold=2 epoch=18/32 train=0.5542 val=0.6083
[nodo07] fold=2 epoch=19/32 train=0.6313 val=0.5993
[nodo07] fold=2 epoch=20/32 train=0.5441 val=0.6079

[I 2026-09-01 11:50:07,783] Trial 12 finished with value: 0.5462202026076943 and parameters: {'dropout': 0.3100413032396562, 'tabular_embedding_dim': 48, 'augmentation_magnitude': 2.1973777168789033, 'augmentation_probability': 0.8799241716036846, 'rotation_degrees': 0.6226428227233244, 'learning_rate': 0.00017143223697621261, 'weight_decay': 7.4521661356477634e-06, 'auxiliary_weight': 0.18651731948203362, 'consistency_weight': 0.0682509938241693, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 10 with value: 0.5383430627224257.

[nodo07] fold=0 epoch=1/32 train=0.7428 val=0.6333
[nodo07] fold=0 epoch=2/32 train=0.6851 val=0.6031
[nodo07] fold=0 epoch=3/32 train=0.6705 val=0.5854
[nodo07] fold=0 epoch=4/32 train=0.6497 val=0.5991
[nodo07] fold=0 epoch=5/32 train=0.6530 val=0.6051
[nodo07] fold=0 epoch=6/32 train=0.6526 val=0.5529
[nodo07] fold=0 epoch=7/32 train=0.6461 val=0.6096
[nodo07] fold=0 epoch=8/32 train=0.6312 val=0.5768
[nodo07] fold=0 epoch=9/32 train=0.6432 val=0.5445
[nodo07] fold=0 epoch=10/32 train=0.6334 val=0.5500
[nodo07] fold=0 epoch=11/32 train=0.6136 val=0.5586
[nodo07] fold=0 epoch=12/32 train=0.6292 val=0.5466
[nodo07] fold=0 epoch=13/32 train=0.6341 val=0.5319
[nodo07] fold=0 epoch=14/32 train=0.5778 val=0.5670
[nodo07] fold=0 epoch=15/32 train=0.6082 val=0.5347
[nodo07] fold=0 epoch=16/32 train=0.5898 val=0.5436
[nodo07] fold=0 epoch=17/32 train=0.5809 val=0.5621
[nodo07] fold=0 epoch=18/32 train=0.5870 val=0.5474
[nodo07] fold=0 epoch=19/32 train=0.5821 val=0.5553
[nodo07] fold=0 epoch=20/32 train=0.6146 val=0.5320
[nodo07] fold=0 epoch=21/32 train=0.5957 val=0.5248
[nodo07] fold=0 epoch=22/32 train=0.5512 val=0.5341
[nodo07] fold=0 epoch=23/32 train=0.5644 val=0.5408
[nodo07] fold=0 epoch=24/32 train=0.6136 val=0.5344
[nodo07] fold=0 epoch=25/32 train=0.5577 val=0.5327
[nodo07] fold=0 epoch=26/32 train=0.5634 val=0.5350
[nodo07] fold=0 epoch=27/32 train=0.5653 val=0.5325
[nodo07] fold=0 epoch=28/32 train=0.5882 val=0.5301
[nodo07] fold=0 epoch=29/32 train=0.5556 val=0.5292
[nodo07] fold=0 epoch=30/32 train=0.5842 val=0.5289
[nodo07] fold=1 epoch=1/32 train=0.7453 val=0.6239
[nodo07] fold=1 epoch=2/32 train=0.7046 val=0.6177
[nodo07] fold=1 epoch=3/32 train=0.6617 val=0.6544
[nodo07] fold=1 epoch=4/32 train=0.6758 val=0.5885
[nodo07] fold=1 epoch=5/32 train=0.6460 val=0.6191
[nodo07] fold=1 epoch=6/32 train=0.6575 val=0.5918
[nodo07] fold=1 epoch=7/32 train=0.6270 val=0.5985
[nodo07] fold=1 epoch=8/32 train=0.6173 val=0.5868
[nodo07] fold=1 epoch=9/32 train=0.6216 val=0.5982
[nodo07] fold=1 epoch=10/32 train=0.6285 val=0.5567
[nodo07] fold=1 epoch=11/32 train=0.6280 val=0.6010
[nodo07] fold=1 epoch=12/32 train=0.6391 val=0.5654
[nodo07] fold=1 epoch=13/32 train=0.6274 val=0.5647
[nodo07] fold=1 epoch=14/32 train=0.5946 val=0.5731
[nodo07] fold=1 epoch=15/32 train=0.5867 val=0.6020
[nodo07] fold=1 epoch=16/32 train=0.5785 val=0.5827
[nodo07] fold=1 epoch=17/32 train=0.5845 val=0.5891
[nodo07] fold=1 epoch=18/32 train=0.6213 val=0.5405
[nodo07] fold=1 epoch=19/32 train=0.5497 val=0.5908
[nodo07] fold=1 epoch=20/32 train=0.5635 val=0.6052
[nodo07] fold=1 epoch=21/32 train=0.6034 val=0.5802
[nodo07] fold=1 epoch=22/32 train=0.5618 val=0.5756
[nodo07] fold=1 epoch=23/32 train=0.5582 val=0.5693
[nodo07] fold=1 epoch=24/32 train=0.5794 val=0.5619
[nodo07] fold=1 epoch=25/32 train=0.5953 val=0.5550
[nodo07] fold=1 epoch=26/32 train=0.5689 val=0.5584
[nodo07] fold=1 epoch=27/32 train=0.5569 val=0.5637
[nodo07] fold=2 epoch=1/32 train=0.7414 val=0.6049
[nodo07] fold=2 epoch=2/32 train=0.6655 val=0.5728
[nodo07] fold=2 epoch=3/32 train=0.6556 val=0.5866
[nodo07] fold=2 epoch=4/32 train=0.6764 val=0.5946
[nodo07] fold=2 epoch=5/32 train=0.6396 val=0.5734
[nodo07] fold=2 epoch=6/32 train=0.6075 val=0.6283
[nodo07] fold=2 epoch=7/32 train=0.6106 val=0.5989
[nodo07] fold=2 epoch=8/32 train=0.6173 val=0.5721
[nodo07] fold=2 epoch=9/32 train=0.5990 val=0.5971
[nodo07] fold=2 epoch=10/32 train=0.6276 val=0.5735
[nodo07] fold=2 epoch=11/32 train=0.5764 val=0.5630
[nodo07] fold=2 epoch=12/32 train=0.5932 val=0.5967
[nodo07] fold=2 epoch=13/32 train=0.6064 val=0.5817
[nodo07] fold=2 epoch=14/32 train=0.5770 val=0.5773
[nodo07] fold=2 epoch=15/32 train=0.5954 val=0.5963
[nodo07] fold=2 epoch=16/32 train=0.5894 val=0.6256
[nodo07] fold=2 epoch=17/32 train=0.5816 val=0.5993
[nodo07] fold=2 epoch=18/32 train=0.5500 val=0.6099
[nodo07] fold=2 epoch=19/32 train=0.6456 val=0.6011
[nodo07] fold=2 epoch=20/32 train=0.5566 val=0.6082

[I 2026-09-01 12:29:52,571] Trial 13 finished with value: 0.54275831657091 and parameters: {'dropout': 0.2612758364114421, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.1416462280307944, 'augmentation_probability': 0.9106448277829298, 'rotation_degrees': 0.7716058657250899, 'learning_rate': 0.00014253314322308343, 'weight_decay': 3.5126026091764303e-06, 'auxiliary_weight': 0.18988976688440945, 'consistency_weight': 0.07874547880765556, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 10 with value: 0.5383430627224257.

[nodo07] fold=0 epoch=1/32 train=0.7412 val=0.6570
[nodo07] fold=0 epoch=2/32 train=0.7327 val=0.6564
[nodo07] fold=0 epoch=3/32 train=0.6958 val=0.6104
[nodo07] fold=0 epoch=4/32 train=0.6933 val=0.6205
[nodo07] fold=0 epoch=5/32 train=0.7041 val=0.6241
[nodo07] fold=0 epoch=6/32 train=0.6883 val=0.6132
[nodo07] fold=0 epoch=7/32 train=0.7068 val=0.6376
[nodo07] fold=0 epoch=8/32 train=0.6933 val=0.6093
[nodo07] fold=0 epoch=9/32 train=0.6859 val=0.6074
[nodo07] fold=0 epoch=10/32 train=0.6800 val=0.6038
[nodo07] fold=0 epoch=11/32 train=0.6754 val=0.6251
[nodo07] fold=0 epoch=12/32 train=0.6767 val=0.6338
[nodo07] fold=0 epoch=13/32 train=0.6849 val=0.5837
[nodo07] fold=0 epoch=14/32 train=0.6293 val=0.5812
[nodo07] fold=0 epoch=15/32 train=0.6477 val=0.5829
[nodo07] fold=0 epoch=16/32 train=0.6063 val=0.6260
[nodo07] fold=0 epoch=17/32 train=0.6126 val=0.6505
[nodo07] fold=0 epoch=18/32 train=0.6314 val=0.6134
[nodo07] fold=0 epoch=19/32 train=0.6196 val=0.6000
[nodo07] fold=0 epoch=20/32 train=0.6300 val=0.5870
[nodo07] fold=0 epoch=21/32 train=0.6159 val=0.5873
[nodo07] fold=0 epoch=22/32 train=0.5868 val=0.5786
[nodo07] fold=0 epoch=23/32 train=0.6142 val=0.5819
[nodo07] fold=0 epoch=24/32 train=0.6255 val=0.5893
[nodo07] fold=0 epoch=25/32 train=0.5896 val=0.5726
[nodo07] fold=0 epoch=26/32 train=0.6010 val=0.5949
[nodo07] fold=0 epoch=27/32 train=0.5976 val=0.5870
[nodo07] fold=0 epoch=28/32 train=0.6150 val=0.5705
[nodo07] fold=0 epoch=29/32 train=0.5749 val=0.5791
[nodo07] fold=0 epoch=30/32 train=0.6066 val=0.5709
[nodo07] fold=0 epoch=31/32 train=0.5589 val=0.5712
[nodo07] fold=0 epoch=32/32 train=0.5694 val=0.5703
[nodo07] fold=1 epoch=1/32 train=0.7538 val=0.6611
[nodo07] fold=1 epoch=2/32 train=0.7182 val=0.6396
[nodo07] fold=1 epoch=3/32 train=0.6855 val=0.6889
[nodo07] fold=1 epoch=4/32 train=0.6988 val=0.6383
[nodo07] fold=1 epoch=5/32 train=0.6920 val=0.6520
[nodo07] fold=1 epoch=6/32 train=0.7025 val=0.6479
[nodo07] fold=1 epoch=7/32 train=0.6727 val=0.6263
[nodo07] fold=1 epoch=8/32 train=0.6726 val=0.6239
[nodo07] fold=1 epoch=9/32 train=0.6922 val=0.6243
[nodo07] fold=1 epoch=10/32 train=0.6861 val=0.6136
[nodo07] fold=1 epoch=11/32 train=0.6838 val=0.6276
[nodo07] fold=1 epoch=12/32 train=0.6820 val=0.6063
[nodo07] fold=1 epoch=13/32 train=0.6758 val=0.6104
[nodo07] fold=1 epoch=14/32 train=0.6444 val=0.6082
[nodo07] fold=1 epoch=15/32 train=0.6293 val=0.6157
[nodo07] fold=1 epoch=16/32 train=0.6239 val=0.6205
[nodo07] fold=1 epoch=17/32 train=0.6416 val=0.6204
[nodo07] fold=1 epoch=18/32 train=0.6594 val=0.5926
[nodo07] fold=1 epoch=19/32 train=0.6340 val=0.6415
[nodo07] fold=1 epoch=20/32 train=0.5872 val=0.6381
[nodo07] fold=1 epoch=21/32 train=0.6487 val=0.6224
[nodo07] fold=1 epoch=22/32 train=0.6117 val=0.6041
[nodo07] fold=1 epoch=23/32 train=0.6060 val=0.5972
[nodo07] fold=1 epoch=24/32 train=0.6286 val=0.5916
[nodo07] fold=1 epoch=25/32 train=0.6107 val=0.5886
[nodo07] fold=1 epoch=26/32 train=0.5943 val=0.6025
[nodo07] fold=1 epoch=27/32 train=0.6067 val=0.5978
[nodo07] fold=1 epoch=28/32 train=0.6371 val=0.5903
[nodo07] fold=1 epoch=29/32 train=0.5968 val=0.5918
[nodo07] fold=1 epoch=30/32 train=0.6259 val=0.5888
[nodo07] fold=1 epoch=31/32 train=0.5746 val=0.5909
[nodo07] fold=1 epoch=32/32 train=0.5937 val=0.5918

[I 2026-09-01 13:08:44,168] Trial 14 pruned.

[nodo07] fold=0 epoch=1/32 train=0.7273 val=0.6097
[nodo07] fold=0 epoch=2/32 train=0.6734 val=0.6168
[nodo07] fold=0 epoch=3/32 train=0.6594 val=0.5749
[nodo07] fold=0 epoch=4/32 train=0.6433 val=0.5693
[nodo07] fold=0 epoch=5/32 train=0.6380 val=0.5881
[nodo07] fold=0 epoch=6/32 train=0.6408 val=0.5399
[nodo07] fold=0 epoch=7/32 train=0.6316 val=0.5998
[nodo07] fold=0 epoch=8/32 train=0.6191 val=0.5702
[nodo07] fold=0 epoch=9/32 train=0.6362 val=0.5300
[nodo07] fold=0 epoch=10/32 train=0.6255 val=0.5321
[nodo07] fold=0 epoch=11/32 train=0.6072 val=0.5461
[nodo07] fold=0 epoch=12/32 train=0.6232 val=0.5315
[nodo07] fold=0 epoch=13/32 train=0.6134 val=0.5328
[nodo07] fold=0 epoch=14/32 train=0.5705 val=0.5701
[nodo07] fold=0 epoch=15/32 train=0.6075 val=0.5252
[nodo07] fold=0 epoch=16/32 train=0.5905 val=0.5328
[nodo07] fold=0 epoch=17/32 train=0.5721 val=0.5410
[nodo07] fold=0 epoch=18/32 train=0.5777 val=0.5331
[nodo07] fold=0 epoch=19/32 train=0.5652 val=0.5453
[nodo07] fold=0 epoch=20/32 train=0.6059 val=0.5239
[nodo07] fold=0 epoch=21/32 train=0.5845 val=0.5126
[nodo07] fold=0 epoch=22/32 train=0.5374 val=0.5277
[nodo07] fold=0 epoch=23/32 train=0.5574 val=0.5320
[nodo07] fold=0 epoch=24/32 train=0.5970 val=0.5266
[nodo07] fold=0 epoch=25/32 train=0.5653 val=0.5289
[nodo07] fold=0 epoch=26/32 train=0.5585 val=0.5270
[nodo07] fold=0 epoch=27/32 train=0.5541 val=0.5289
[nodo07] fold=0 epoch=28/32 train=0.5863 val=0.5240
[nodo07] fold=0 epoch=29/32 train=0.5493 val=0.5240
[nodo07] fold=0 epoch=30/32 train=0.5806 val=0.5225
[nodo07] fold=1 epoch=1/32 train=0.7333 val=0.6148
[nodo07] fold=1 epoch=2/32 train=0.6862 val=0.6081
[nodo07] fold=1 epoch=3/32 train=0.6412 val=0.6482
[nodo07] fold=1 epoch=4/32 train=0.6530 val=0.5760
[nodo07] fold=1 epoch=5/32 train=0.6214 val=0.6419
[nodo07] fold=1 epoch=6/32 train=0.6383 val=0.5894
[nodo07] fold=1 epoch=7/32 train=0.6114 val=0.6045
[nodo07] fold=1 epoch=8/32 train=0.6066 val=0.6132
[nodo07] fold=1 epoch=9/32 train=0.6067 val=0.6079
[nodo07] fold=1 epoch=10/32 train=0.6229 val=0.5520
[nodo07] fold=1 epoch=11/32 train=0.6089 val=0.6552
[nodo07] fold=1 epoch=12/32 train=0.6313 val=0.5817
[nodo07] fold=1 epoch=13/32 train=0.6161 val=0.5556
[nodo07] fold=1 epoch=14/32 train=0.5888 val=0.5749
[nodo07] fold=1 epoch=15/32 train=0.5770 val=0.6174
[nodo07] fold=1 epoch=16/32 train=0.5739 val=0.5779
[nodo07] fold=1 epoch=17/32 train=0.5761 val=0.5964
[nodo07] fold=1 epoch=18/32 train=0.6109 val=0.5417
[nodo07] fold=1 epoch=19/32 train=0.5525 val=0.6083
[nodo07] fold=1 epoch=20/32 train=0.5551 val=0.6091
[nodo07] fold=1 epoch=21/32 train=0.5854 val=0.5802
[nodo07] fold=1 epoch=22/32 train=0.5565 val=0.5734
[nodo07] fold=1 epoch=23/32 train=0.5497 val=0.5730
[nodo07] fold=1 epoch=24/32 train=0.5663 val=0.5728
[nodo07] fold=1 epoch=25/32 train=0.5857 val=0.5700
[nodo07] fold=1 epoch=26/32 train=0.5617 val=0.5670
[nodo07] fold=1 epoch=27/32 train=0.5471 val=0.5681
[nodo07] fold=2 epoch=1/32 train=0.7094 val=0.5790
[nodo07] fold=2 epoch=2/32 train=0.6588 val=0.5711
[nodo07] fold=2 epoch=3/32 train=0.6397 val=0.5915
[nodo07] fold=2 epoch=4/32 train=0.6613 val=0.5860
[nodo07] fold=2 epoch=5/32 train=0.6232 val=0.5655
[nodo07] fold=2 epoch=6/32 train=0.5911 val=0.6362
[nodo07] fold=2 epoch=7/32 train=0.6016 val=0.6003
[nodo07] fold=2 epoch=8/32 train=0.5964 val=0.5779
[nodo07] fold=2 epoch=9/32 train=0.5888 val=0.6140
[nodo07] fold=2 epoch=10/32 train=0.6057 val=0.5790
[nodo07] fold=2 epoch=11/32 train=0.5678 val=0.5542
[nodo07] fold=2 epoch=12/32 train=0.5759 val=0.5863
[nodo07] fold=2 epoch=13/32 train=0.5754 val=0.5716
[nodo07] fold=2 epoch=14/32 train=0.5598 val=0.5711
[nodo07] fold=2 epoch=15/32 train=0.5715 val=0.5956
[nodo07] fold=2 epoch=16/32 train=0.5713 val=0.6237
[nodo07] fold=2 epoch=17/32 train=0.5670 val=0.6024
[nodo07] fold=2 epoch=18/32 train=0.5312 val=0.6052
[nodo07] fold=2 epoch=19/32 train=0.6180 val=0.5962
[nodo07] fold=2 epoch=20/32 train=0.5409 val=0.6097

[I 2026-09-01 13:58:44,732] Trial 15 finished with value: 0.5361371208029735 and parameters: {'dropout': 0.27951009060840626, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.2659949777414106, 'augmentation_probability': 0.9177373627655305, 'rotation_degrees': 0.8255641709381976, 'learning_rate': 0.00023638189774427958, 'weight_decay': 6.204432418528044e-06, 'auxiliary_weight': 0.16748990464018143, 'consistency_weight': 0.04218193832649623, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 15 with value: 0.5361371208029735.

[nodo07] fold=0 epoch=1/32 train=0.7264 val=0.6197
[nodo07] fold=0 epoch=2/32 train=0.6668 val=0.6277
[nodo07] fold=0 epoch=3/32 train=0.6494 val=0.5773
[nodo07] fold=0 epoch=4/32 train=0.6409 val=0.5916
[nodo07] fold=0 epoch=5/32 train=0.6327 val=0.5649
[nodo07] fold=0 epoch=6/32 train=0.6326 val=0.5446
[nodo07] fold=0 epoch=7/32 train=0.6216 val=0.5833
[nodo07] fold=0 epoch=8/32 train=0.6083 val=0.5557
[nodo07] fold=0 epoch=9/32 train=0.6217 val=0.5321
[nodo07] fold=0 epoch=10/32 train=0.6046 val=0.5333
[nodo07] fold=0 epoch=11/32 train=0.6039 val=0.5515
[nodo07] fold=0 epoch=12/32 train=0.6163 val=0.5355
[nodo07] fold=0 epoch=13/32 train=0.6058 val=0.5229
[nodo07] fold=0 epoch=14/32 train=0.5699 val=0.5475
[nodo07] fold=0 epoch=15/32 train=0.5966 val=0.5388
[nodo07] fold=0 epoch=16/32 train=0.5769 val=0.5358
[nodo07] fold=0 epoch=17/32 train=0.5697 val=0.5520
[nodo07] fold=0 epoch=18/32 train=0.5697 val=0.5414
[nodo07] fold=0 epoch=19/32 train=0.5568 val=0.5432
[nodo07] fold=0 epoch=20/32 train=0.6031 val=0.5385
[nodo07] fold=0 epoch=21/32 train=0.5736 val=0.5225
[nodo07] fold=0 epoch=22/32 train=0.5385 val=0.5315
[nodo07] fold=0 epoch=23/32 train=0.5504 val=0.5347
[nodo07] fold=0 epoch=24/32 train=0.6009 val=0.5283
[nodo07] fold=0 epoch=25/32 train=0.5667 val=0.5259
[nodo07] fold=0 epoch=26/32 train=0.5546 val=0.5316
[nodo07] fold=0 epoch=27/32 train=0.5597 val=0.5292
[nodo07] fold=0 epoch=28/32 train=0.5879 val=0.5248
[nodo07] fold=0 epoch=29/32 train=0.5397 val=0.5268
[nodo07] fold=0 epoch=30/32 train=0.5768 val=0.5271
[nodo07] fold=1 epoch=1/32 train=0.7056 val=0.6049
[nodo07] fold=1 epoch=2/32 train=0.6762 val=0.6054
[nodo07] fold=1 epoch=3/32 train=0.6359 val=0.6214
[nodo07] fold=1 epoch=4/32 train=0.6463 val=0.5826
[nodo07] fold=1 epoch=5/32 train=0.6217 val=0.6127
[nodo07] fold=1 epoch=6/32 train=0.6454 val=0.5990
[nodo07] fold=1 epoch=7/32 train=0.6232 val=0.5906
[nodo07] fold=1 epoch=8/32 train=0.6175 val=0.5758
[nodo07] fold=1 epoch=9/32 train=0.6012 val=0.5793
[nodo07] fold=1 epoch=10/32 train=0.6245 val=0.5670
[nodo07] fold=1 epoch=11/32 train=0.5983 val=0.6175
[nodo07] fold=1 epoch=12/32 train=0.6146 val=0.5802
[nodo07] fold=1 epoch=13/32 train=0.6099 val=0.5774
[nodo07] fold=1 epoch=14/32 train=0.5876 val=0.5782
[nodo07] fold=1 epoch=15/32 train=0.5694 val=0.6224
[nodo07] fold=1 epoch=16/32 train=0.5751 val=0.5887
[nodo07] fold=1 epoch=17/32 train=0.5832 val=0.6076
[nodo07] fold=1 epoch=18/32 train=0.6122 val=0.5734
[nodo07] fold=1 epoch=19/32 train=0.5673 val=0.6185
[nodo07] fold=2 epoch=1/32 train=0.7158 val=0.5993
[nodo07] fold=2 epoch=2/32 train=0.6529 val=0.5892
[nodo07] fold=2 epoch=3/32 train=0.6499 val=0.5955
[nodo07] fold=2 epoch=4/32 train=0.6592 val=0.6109
[nodo07] fold=2 epoch=5/32 train=0.6251 val=0.5884
[nodo07] fold=2 epoch=6/32 train=0.6052 val=0.6414
[nodo07] fold=2 epoch=7/32 train=0.6111 val=0.6146
[nodo07] fold=2 epoch=8/32 train=0.6142 val=0.5730
[nodo07] fold=2 epoch=9/32 train=0.5902 val=0.5974
[nodo07] fold=2 epoch=10/32 train=0.6214 val=0.5787
[nodo07] fold=2 epoch=11/32 train=0.5831 val=0.5638
[nodo07] fold=2 epoch=12/32 train=0.5913 val=0.5776
[nodo07] fold=2 epoch=13/32 train=0.5822 val=0.5683
[nodo07] fold=2 epoch=14/32 train=0.5583 val=0.5748
[nodo07] fold=2 epoch=15/32 train=0.5881 val=0.5835
[nodo07] fold=2 epoch=16/32 train=0.5739 val=0.6088
[nodo07] fold=2 epoch=17/32 train=0.5695 val=0.5926
[nodo07] fold=2 epoch=18/32 train=0.5450 val=0.5934
[nodo07] fold=2 epoch=19/32 train=0.6167 val=0.5840
[nodo07] fold=2 epoch=20/32 train=0.5508 val=0.5945

[I 2026-09-01 14:41:59,659] Trial 16 finished with value: 0.5510751858719806 and parameters: {'dropout': 0.23647012411955232, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.280004958370176, 'augmentation_probability': 0.9032145055866011, 'rotation_degrees': 0.7394121821665891, 'learning_rate': 0.00018582804141608337, 'weight_decay': 9.445870558815918e-06, 'auxiliary_weight': 0.13523320781401382, 'consistency_weight': 0.044631981839699256, 'feature_top_k': 32, 'pca_variance': '0.95'}. Best is trial 15 with value: 0.5361371208029735.

[nodo07] fold=0 epoch=1/32 train=0.7397 val=0.6323
[nodo07] fold=0 epoch=2/32 train=0.6813 val=0.6163
[nodo07] fold=0 epoch=3/32 train=0.6754 val=0.5860
[nodo07] fold=0 epoch=4/32 train=0.6544 val=0.5707
[nodo07] fold=0 epoch=5/32 train=0.6528 val=0.5824
[nodo07] fold=0 epoch=6/32 train=0.6565 val=0.5512
[nodo07] fold=0 epoch=7/32 train=0.6461 val=0.5960
[nodo07] fold=0 epoch=8/32 train=0.6352 val=0.5787
[nodo07] fold=0 epoch=9/32 train=0.6445 val=0.5381
[nodo07] fold=0 epoch=10/32 train=0.6410 val=0.5397
[nodo07] fold=0 epoch=11/32 train=0.6195 val=0.5633
[nodo07] fold=0 epoch=12/32 train=0.6399 val=0.5428
[nodo07] fold=0 epoch=13/32 train=0.6383 val=0.5308
[nodo07] fold=0 epoch=14/32 train=0.5829 val=0.5705
[nodo07] fold=0 epoch=15/32 train=0.6256 val=0.5333
[nodo07] fold=0 epoch=16/32 train=0.6015 val=0.5509
[nodo07] fold=0 epoch=17/32 train=0.5943 val=0.5579
[nodo07] fold=0 epoch=18/32 train=0.6022 val=0.5442
[nodo07] fold=0 epoch=19/32 train=0.5829 val=0.5495
[nodo07] fold=0 epoch=20/32 train=0.6151 val=0.5390
[nodo07] fold=0 epoch=21/32 train=0.6036 val=0.5252
[nodo07] fold=0 epoch=22/32 train=0.5555 val=0.5373
[nodo07] fold=0 epoch=23/32 train=0.5745 val=0.5367
[nodo07] fold=0 epoch=24/32 train=0.6145 val=0.5292
[nodo07] fold=0 epoch=25/32 train=0.5784 val=0.5359
[nodo07] fold=0 epoch=26/32 train=0.5683 val=0.5365
[nodo07] fold=0 epoch=27/32 train=0.5696 val=0.5371
[nodo07] fold=0 epoch=28/32 train=0.5985 val=0.5323
[nodo07] fold=0 epoch=29/32 train=0.5653 val=0.5322
[nodo07] fold=0 epoch=30/32 train=0.5904 val=0.5304
[nodo07] fold=1 epoch=1/32 train=0.7390 val=0.6479
[nodo07] fold=1 epoch=2/32 train=0.6991 val=0.6110
[nodo07] fold=1 epoch=3/32 train=0.6562 val=0.6349
[nodo07] fold=1 epoch=4/32 train=0.6697 val=0.5860
[nodo07] fold=1 epoch=5/32 train=0.6469 val=0.6338
[nodo07] fold=1 epoch=6/32 train=0.6564 val=0.6027
[nodo07] fold=1 epoch=7/32 train=0.6239 val=0.5874
[nodo07] fold=1 epoch=8/32 train=0.6166 val=0.6064
[nodo07] fold=1 epoch=9/32 train=0.6154 val=0.6102
[nodo07] fold=1 epoch=10/32 train=0.6358 val=0.5509
[nodo07] fold=1 epoch=11/32 train=0.6160 val=0.6200
[nodo07] fold=1 epoch=12/32 train=0.6392 val=0.5760
[nodo07] fold=1 epoch=13/32 train=0.6266 val=0.5505
[nodo07] fold=1 epoch=14/32 train=0.5888 val=0.5700
[nodo07] fold=1 epoch=15/32 train=0.5848 val=0.6052
[nodo07] fold=1 epoch=16/32 train=0.5825 val=0.5831
[nodo07] fold=1 epoch=17/32 train=0.5879 val=0.5864
[nodo07] fold=1 epoch=18/32 train=0.6135 val=0.5403
[nodo07] fold=1 epoch=19/32 train=0.5637 val=0.6059
[nodo07] fold=1 epoch=20/32 train=0.5647 val=0.6127
[nodo07] fold=1 epoch=21/32 train=0.6027 val=0.5765
[nodo07] fold=1 epoch=22/32 train=0.5683 val=0.5758
[nodo07] fold=1 epoch=23/32 train=0.5676 val=0.5731
[nodo07] fold=1 epoch=24/32 train=0.5848 val=0.5711
[nodo07] fold=1 epoch=25/32 train=0.5943 val=0.5659
[nodo07] fold=1 epoch=26/32 train=0.5811 val=0.5595
[nodo07] fold=1 epoch=27/32 train=0.5598 val=0.5627
[nodo07] fold=2 epoch=1/32 train=0.7257 val=0.5918
[nodo07] fold=2 epoch=2/32 train=0.6672 val=0.5748
[nodo07] fold=2 epoch=3/32 train=0.6549 val=0.5922
[nodo07] fold=2 epoch=4/32 train=0.6735 val=0.5970
[nodo07] fold=2 epoch=5/32 train=0.6378 val=0.5722
[nodo07] fold=2 epoch=6/32 train=0.6127 val=0.6333
[nodo07] fold=2 epoch=7/32 train=0.6133 val=0.6005
[nodo07] fold=2 epoch=8/32 train=0.6166 val=0.5990
[nodo07] fold=2 epoch=9/32 train=0.6022 val=0.6163
[nodo07] fold=2 epoch=10/32 train=0.6253 val=0.5678
[nodo07] fold=2 epoch=11/32 train=0.5737 val=0.5534
[nodo07] fold=2 epoch=12/32 train=0.5896 val=0.5893
[nodo07] fold=2 epoch=13/32 train=0.5935 val=0.5811
[nodo07] fold=2 epoch=14/32 train=0.5800 val=0.5718
[nodo07] fold=2 epoch=15/32 train=0.5926 val=0.5837
[nodo07] fold=2 epoch=16/32 train=0.5877 val=0.6126
[nodo07] fold=2 epoch=17/32 train=0.5826 val=0.5892
[nodo07] fold=2 epoch=18/32 train=0.5483 val=0.6041
[nodo07] fold=2 epoch=19/32 train=0.6326 val=0.5865
[nodo07] fold=2 epoch=20/32 train=0.5554 val=0.5988

[I 2026-09-01 15:30:45,872] Trial 17 finished with value: 0.5396182395357962 and parameters: {'dropout': 0.33062902941781824, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.1991211901688645, 'augmentation_probability': 0.9550313936047683, 'rotation_degrees': 1.0750275049722207, 'learning_rate': 0.00020507713228841887, 'weight_decay': 9.051406470661161e-06, 'auxiliary_weight': 0.18311341683002977, 'consistency_weight': 0.05155612491684292, 'feature_top_k': 32, 'pca_variance': '0.98'}. Best is trial 15 with value: 0.5361371208029735.

[nodo07] fold=0 epoch=1/32 train=0.7235 val=0.5902
[nodo07] fold=0 epoch=2/32 train=0.6547 val=0.5896
[nodo07] fold=0 epoch=3/32 train=0.6387 val=0.5420
[nodo07] fold=0 epoch=4/32 train=0.6197 val=0.5520
[nodo07] fold=0 epoch=5/32 train=0.6082 val=0.5521
[nodo07] fold=0 epoch=6/32 train=0.6025 val=0.5173
[nodo07] fold=0 epoch=7/32 train=0.5930 val=0.5584
[nodo07] fold=0 epoch=8/32 train=0.5993 val=0.5414
[nodo07] fold=0 epoch=9/32 train=0.6011 val=0.5328
[nodo07] fold=0 epoch=10/32 train=0.5925 val=0.5121
[nodo07] fold=0 epoch=11/32 train=0.5554 val=0.5578
[nodo07] fold=0 epoch=12/32 train=0.5760 val=0.5318
[nodo07] fold=0 epoch=13/32 train=0.5757 val=0.5226
[nodo07] fold=0 epoch=14/32 train=0.5287 val=0.5658
[nodo07] fold=0 epoch=15/32 train=0.5624 val=0.5520
[nodo07] fold=0 epoch=16/32 train=0.5484 val=0.5715
[nodo07] fold=0 epoch=17/32 train=0.5294 val=0.5700
[nodo07] fold=0 epoch=18/32 train=0.5460 val=0.5663
[nodo07] fold=0 epoch=19/32 train=0.5373 val=0.5667
[nodo07] fold=1 epoch=1/32 train=0.7264 val=0.6399
[nodo07] fold=1 epoch=2/32 train=0.6619 val=0.6010
[nodo07] fold=1 epoch=3/32 train=0.6046 val=0.6254
[nodo07] fold=1 epoch=4/32 train=0.6018 val=0.5938
[nodo07] fold=1 epoch=5/32 train=0.5698 val=0.6935
[nodo07] fold=1 epoch=6/32 train=0.5881 val=0.6524
[nodo07] fold=1 epoch=7/32 train=0.5668 val=0.6281
[nodo07] fold=1 epoch=8/32 train=0.5673 val=0.6117
[nodo07] fold=1 epoch=9/32 train=0.5537 val=0.6490
[nodo07] fold=1 epoch=10/32 train=0.5898 val=0.5652
[nodo07] fold=1 epoch=11/32 train=0.5260 val=0.6682
[nodo07] fold=1 epoch=12/32 train=0.5526 val=0.6233
[nodo07] fold=1 epoch=13/32 train=0.5602 val=0.6337
[nodo07] fold=1 epoch=14/32 train=0.5431 val=0.6375
[nodo07] fold=1 epoch=15/32 train=0.5192 val=0.6588
[nodo07] fold=1 epoch=16/32 train=0.5026 val=0.6469
[nodo07] fold=1 epoch=17/32 train=0.5335 val=0.6362
[nodo07] fold=1 epoch=18/32 train=0.5310 val=0.6436
[nodo07] fold=1 epoch=19/32 train=0.5297 val=0.6521
[nodo07] fold=2 epoch=1/32 train=0.6978 val=0.5862
[nodo07] fold=2 epoch=2/32 train=0.6322 val=0.5696
[nodo07] fold=2 epoch=3/32 train=0.6204 val=0.6066
[nodo07] fold=2 epoch=4/32 train=0.6458 val=0.6127
[nodo07] fold=2 epoch=5/32 train=0.5919 val=0.5678
[nodo07] fold=2 epoch=6/32 train=0.5699 val=0.6648
[nodo07] fold=2 epoch=7/32 train=0.5705 val=0.6196
[nodo07] fold=2 epoch=8/32 train=0.5925 val=0.5819
[nodo07] fold=2 epoch=9/32 train=0.5698 val=0.6039
[nodo07] fold=2 epoch=10/32 train=0.5978 val=0.5657
[nodo07] fold=2 epoch=11/32 train=0.5633 val=0.5549
[nodo07] fold=2 epoch=12/32 train=0.5539 val=0.6089
[nodo07] fold=2 epoch=13/32 train=0.5590 val=0.5723
[nodo07] fold=2 epoch=14/32 train=0.5407 val=0.5812
[nodo07] fold=2 epoch=15/32 train=0.5337 val=0.6024
[nodo07] fold=2 epoch=16/32 train=0.5525 val=0.5819
[nodo07] fold=2 epoch=17/32 train=0.5434 val=0.5892
[nodo07] fold=2 epoch=18/32 train=0.5358 val=0.5969
[nodo07] fold=2 epoch=19/32 train=0.5887 val=0.5694
[nodo07] fold=2 epoch=20/32 train=0.5179 val=0.5880

[I 2026-09-01 16:06:27,324] Trial 18 finished with value: 0.5440502071013964 and parameters: {'dropout': 0.2905619940365809, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.141379932015432, 'augmentation_probability': 0.9254298585708998, 'rotation_degrees': 0.7259050668214446, 'learning_rate': 0.0002251674549190005, 'weight_decay': 5.126569242481291e-06, 'auxiliary_weight': 0.12510580671071264, 'consistency_weight': 0.05475555277087675, 'feature_top_k': 64, 'pca_variance': '0.98'}. Best is trial 15 with value: 0.5361371208029735.

[nodo07] fold=0 epoch=1/32 train=0.7512 val=0.6749
[nodo07] fold=0 epoch=2/32 train=0.7291 val=0.6835
[nodo07] fold=0 epoch=3/32 train=0.7059 val=0.6088
[nodo07] fold=0 epoch=4/32 train=0.6789 val=0.6190
[nodo07] fold=0 epoch=5/32 train=0.6945 val=0.6209
[nodo07] fold=0 epoch=6/32 train=0.6851 val=0.6083
[nodo07] fold=0 epoch=7/32 train=0.6955 val=0.6151
[nodo07] fold=0 epoch=8/32 train=0.6864 val=0.6026
[nodo07] fold=0 epoch=9/32 train=0.6886 val=0.6067
[nodo07] fold=0 epoch=10/32 train=0.6779 val=0.6118
[nodo07] fold=0 epoch=11/32 train=0.6778 val=0.6327
[nodo07] fold=0 epoch=12/32 train=0.6820 val=0.6354
[nodo07] fold=0 epoch=13/32 train=0.7061 val=0.6125
[nodo07] fold=0 epoch=14/32 train=0.6469 val=0.6106
[nodo07] fold=0 epoch=15/32 train=0.6543 val=0.6046
[nodo07] fold=0 epoch=16/32 train=0.6442 val=0.6166
[nodo07] fold=0 epoch=17/32 train=0.6437 val=0.6573
[nodo07] fold=1 epoch=1/32 train=0.7532 val=0.6821
[nodo07] fold=1 epoch=2/32 train=0.7275 val=0.6457
[nodo07] fold=1 epoch=3/32 train=0.6817 val=0.6943
[nodo07] fold=1 epoch=4/32 train=0.6960 val=0.6376
[nodo07] fold=1 epoch=5/32 train=0.6860 val=0.6642
[nodo07] fold=1 epoch=6/32 train=0.6961 val=0.6602
[nodo07] fold=1 epoch=7/32 train=0.6742 val=0.6225
[nodo07] fold=1 epoch=8/32 train=0.6685 val=0.6220
[nodo07] fold=1 epoch=9/32 train=0.6925 val=0.6156
[nodo07] fold=1 epoch=10/32 train=0.6787 val=0.6193
[nodo07] fold=1 epoch=11/32 train=0.6837 val=0.6110
[nodo07] fold=1 epoch=12/32 train=0.6751 val=0.6131
[nodo07] fold=1 epoch=13/32 train=0.6668 val=0.6181
[nodo07] fold=1 epoch=14/32 train=0.6387 val=0.6053
[nodo07] fold=1 epoch=15/32 train=0.6239 val=0.6116
[nodo07] fold=1 epoch=16/32 train=0.6256 val=0.6113
[nodo07] fold=1 epoch=17/32 train=0.6347 val=0.6288
[nodo07] fold=1 epoch=18/32 train=0.6612 val=0.5964
[nodo07] fold=1 epoch=19/32 train=0.6376 val=0.6372
[nodo07] fold=1 epoch=20/32 train=0.6039 val=0.6655
[nodo07] fold=1 epoch=21/32 train=0.6480 val=0.6099
[nodo07] fold=1 epoch=22/32 train=0.6096 val=0.6037
[nodo07] fold=1 epoch=23/32 train=0.6130 val=0.6140
[nodo07] fold=1 epoch=24/32 train=0.6353 val=0.5973
[nodo07] fold=1 epoch=25/32 train=0.6205 val=0.5909
[nodo07] fold=1 epoch=26/32 train=0.6065 val=0.6058
[nodo07] fold=1 epoch=27/32 train=0.6130 val=0.6106
[nodo07] fold=1 epoch=28/32 train=0.6419 val=0.5961
[nodo07] fold=1 epoch=29/32 train=0.6149 val=0.6017
[nodo07] fold=1 epoch=30/32 train=0.6401 val=0.5960
[nodo07] fold=1 epoch=31/32 train=0.5970 val=0.5988
[nodo07] fold=1 epoch=32/32 train=0.6182 val=0.5997

[I 2026-09-01 16:37:40,174] Trial 19 pruned.

[nodo07] fold=0 epoch=1/32 train=0.7272 val=0.6079
[nodo07] fold=0 epoch=2/32 train=0.6638 val=0.6005
[nodo07] fold=0 epoch=3/32 train=0.6519 val=0.5709
[nodo07] fold=0 epoch=4/32 train=0.6318 val=0.5693
[nodo07] fold=0 epoch=5/32 train=0.6275 val=0.5618
[nodo07] fold=0 epoch=6/32 train=0.6277 val=0.5336
[nodo07] fold=0 epoch=7/32 train=0.6224 val=0.5670
[nodo07] fold=0 epoch=8/32 train=0.6040 val=0.5671
[nodo07] fold=0 epoch=9/32 train=0.6128 val=0.5307
[nodo07] fold=0 epoch=10/32 train=0.6005 val=0.5139
[nodo07] fold=0 epoch=11/32 train=0.5819 val=0.5477
[nodo07] fold=0 epoch=12/32 train=0.5978 val=0.5479
[nodo07] fold=0 epoch=13/32 train=0.5989 val=0.5221
[nodo07] fold=0 epoch=14/32 train=0.5372 val=0.5835
[nodo07] fold=0 epoch=15/32 train=0.5806 val=0.5283
[nodo07] fold=0 epoch=16/32 train=0.5577 val=0.5538
[nodo07] fold=0 epoch=17/32 train=0.5453 val=0.5643
[nodo07] fold=0 epoch=18/32 train=0.5418 val=0.5520
[nodo07] fold=0 epoch=19/32 train=0.5584 val=0.5537
[nodo07] fold=1 epoch=1/32 train=0.7357 val=0.6232
[nodo07] fold=1 epoch=2/32 train=0.6975 val=0.6131
[nodo07] fold=1 epoch=3/32 train=0.6533 val=0.6374
[nodo07] fold=1 epoch=4/32 train=0.6447 val=0.5742
[nodo07] fold=1 epoch=5/32 train=0.6207 val=0.6208
[nodo07] fold=1 epoch=6/32 train=0.6484 val=0.6153
[nodo07] fold=1 epoch=7/32 train=0.6062 val=0.6132
[nodo07] fold=1 epoch=8/32 train=0.6185 val=0.5926
[nodo07] fold=1 epoch=9/32 train=0.5863 val=0.6093
[nodo07] fold=1 epoch=10/32 train=0.6342 val=0.5471
[nodo07] fold=1 epoch=11/32 train=0.5889 val=0.6708
[nodo07] fold=1 epoch=12/32 train=0.6217 val=0.6098
[nodo07] fold=1 epoch=13/32 train=0.6168 val=0.6100
[nodo07] fold=1 epoch=14/32 train=0.5967 val=0.5897
[nodo07] fold=1 epoch=15/32 train=0.5778 val=0.6159
[nodo07] fold=1 epoch=16/32 train=0.5649 val=0.6001
[nodo07] fold=1 epoch=17/32 train=0.5663 val=0.6302
[nodo07] fold=1 epoch=18/32 train=0.6121 val=0.5778
[nodo07] fold=1 epoch=19/32 train=0.5428 val=0.6289
[nodo07] fold=2 epoch=1/32 train=0.7181 val=0.5807
[nodo07] fold=2 epoch=2/32 train=0.6653 val=0.5721
[nodo07] fold=2 epoch=3/32 train=0.6564 val=0.5867
[nodo07] fold=2 epoch=4/32 train=0.6731 val=0.6033
[nodo07] fold=2 epoch=5/32 train=0.6366 val=0.5616
[nodo07] fold=2 epoch=6/32 train=0.6012 val=0.6599
[nodo07] fold=2 epoch=7/32 train=0.6097 val=0.5944
[nodo07] fold=2 epoch=8/32 train=0.6102 val=0.5691
[nodo07] fold=2 epoch=9/32 train=0.5969 val=0.6115
[nodo07] fold=2 epoch=10/32 train=0.6262 val=0.5669
[nodo07] fold=2 epoch=11/32 train=0.5738 val=0.5629
[nodo07] fold=2 epoch=12/32 train=0.5915 val=0.5944
[nodo07] fold=2 epoch=13/32 train=0.5845 val=0.5743
[nodo07] fold=2 epoch=14/32 train=0.5686 val=0.5672

[I 2026-09-01 17:13:21,639] Trial 20 finished with value: 0.5408736737092611 and parameters: {'dropout': 0.2726340961044135, 'tabular_embedding_dim': 24, 'augmentation_magnitude': 2.0417203891792073, 'augmentation_probability': 0.9013329878987006, 'rotation_degrees': 1.1540778411112926, 'learning_rate': 0.0001795213430490994, 'weight_decay': 1.8247973520742044e-05, 'auxiliary_weight': 0.17800919828542902, 'consistency_weight': 0.040752715836708794, 'feature_top_k': 32, 'pca_variance': 'none'}. Best is trial 15 with value: 0.5361371208029735.

,study_name,source_candidate_id,source_node07_rank,selection_roles,architecture,feature_variant,lateral_strategy,completed_trials,total_trials,search_log_loss,fixed_epochs,candidate_id
0,node09_slab2d_23f042f62f,23f042f62f40d03e,1,top_1_overall,slab2d,image_radiomics_sbr,random_flip,18,18,0.524060,25,555b81376733bb67
1,node09_25d_fb93ea204b,fb93ea204b0ec32f,2,top_2_overall,2.5d,image_radiomics_sbr,random_flip,18,20,0.527828,15,c56be99202976455
2,node09_3d_3f9bbf2416,3f9bbf24164bd1dc,3,best_3d,3d,image_radiomics_sbr,random_flip,18,21,0.536137,18,a37f424ba911f6cc

Abre o vuelve a ejecutar el **nodo 08** y selecciona `node09:node09_fine_v1` para comparar estas trayectorias con los nodos 06 y 07.

## 4. Evaluación final de los tres ganadores

Optuna entrega un ganador por cada rama. Sólo esos tres modelos se reentrenan en los cinco folds congelados; son 15 entrenamientos finales. El fold externo no controla early stopping: el número de épocas proviene de la mediana de la búsqueda, con un mínimo de ocho para evitar el entrenamiento demasiado corto observado antes.

In [6]:
with RunLock(RUN_DIR / "final.lock"):
    final_result = run_final_stage(prepared, EXPERIMENT, device=DEVICE)
display(final_result.metrics)
display(Markdown(
    f"**Modelo primario nodo 09:** `{final_result.deployment_manifest['primary_candidate_id']}` · "
    f"**modelos por fold del primario:** `{final_result.deployment_manifest['n_fold_models']}`"
))

[nodo07] fold=0 epoch=1/25 train=0.7412 val=nan
[nodo07] fold=0 epoch=2/25 train=0.7068 val=nan
[nodo07] fold=0 epoch=3/25 train=0.6499 val=nan
[nodo07] fold=0 epoch=4/25 train=0.6299 val=nan
[nodo07] fold=0 epoch=5/25 train=0.6163 val=nan
[nodo07] fold=0 epoch=6/25 train=0.5824 val=nan
[nodo07] fold=0 epoch=7/25 train=0.6003 val=nan
[nodo07] fold=0 epoch=8/25 train=0.5702 val=nan
[nodo07] fold=0 epoch=9/25 train=0.5926 val=nan
[nodo07] fold=0 epoch=10/25 train=0.5957 val=nan
[nodo07] fold=0 epoch=11/25 train=0.5761 val=nan
[nodo07] fold=0 epoch=12/25 train=0.6042 val=nan
[nodo07] fold=0 epoch=13/25 train=0.5551 val=nan
[nodo07] fold=0 epoch=14/25 train=0.5615 val=nan
[nodo07] fold=0 epoch=15/25 train=0.5603 val=nan
[nodo07] fold=0 epoch=16/25 train=0.5593 val=nan
[nodo07] fold=0 epoch=17/25 train=0.5543 val=nan
[nodo07] fold=0 epoch=18/25 train=0.5524 val=nan
[nodo07] fold=0 epoch=19/25 train=0.5560 val=nan
[nodo07] fold=0 epoch=20/25 train=0.5708 val=nan
[nodo07] fold=0 epoch=21/25 train=0.5489 val=nan
[nodo07] fold=0 epoch=22/25 train=0.5244 val=nan
[nodo07] fold=0 epoch=23/25 train=0.5542 val=nan
[nodo07] fold=0 epoch=24/25 train=0.5412 val=nan
[nodo07] fold=0 epoch=25/25 train=0.5603 val=0.5507
[nodo07] fold=1 epoch=1/25 train=0.7233 val=nan
[nodo07] fold=1 epoch=2/25 train=0.6388 val=nan
[nodo07] fold=1 epoch=3/25 train=0.6386 val=nan
[nodo07] fold=1 epoch=4/25 train=0.6077 val=nan
[nodo07] fold=1 epoch=5/25 train=0.5935 val=nan
[nodo07] fold=1 epoch=6/25 train=0.5870 val=nan
[nodo07] fold=1 epoch=7/25 train=0.5750 val=nan
[nodo07] fold=1 epoch=8/25 train=0.5647 val=nan
[nodo07] fold=1 epoch=9/25 train=0.5995 val=nan
[nodo07] fold=1 epoch=10/25 train=0.5760 val=nan
[nodo07] fold=1 epoch=11/25 train=0.5876 val=nan
[nodo07] fold=1 epoch=12/25 train=0.5958 val=nan
[nodo07] fold=1 epoch=13/25 train=0.5585 val=nan
[nodo07] fold=1 epoch=14/25 train=0.5568 val=nan
[nodo07] fold=1 epoch=15/25 train=0.5520 val=nan
[nodo07] fold=1 epoch=16/25 train=0.5363 val=nan
[nodo07] fold=1 epoch=17/25 train=0.5423 val=nan
[nodo07] fold=1 epoch=18/25 train=0.5388 val=nan
[nodo07] fold=1 epoch=19/25 train=0.5182 val=nan
[nodo07] fold=1 epoch=20/25 train=0.5522 val=nan
[nodo07] fold=1 epoch=21/25 train=0.5460 val=nan
[nodo07] fold=1 epoch=22/25 train=0.5131 val=nan
[nodo07] fold=1 epoch=23/25 train=0.5489 val=nan
[nodo07] fold=1 epoch=24/25 train=0.5089 val=nan
[nodo07] fold=1 epoch=25/25 train=0.5381 val=0.5869
[nodo07] fold=2 epoch=1/25 train=0.7435 val=nan
[nodo07] fold=2 epoch=2/25 train=0.6665 val=nan
[nodo07] fold=2 epoch=3/25 train=0.6458 val=nan
[nodo07] fold=2 epoch=4/25 train=0.6463 val=nan
[nodo07] fold=2 epoch=5/25 train=0.6142 val=nan
[nodo07] fold=2 epoch=6/25 train=0.5981 val=nan
[nodo07] fold=2 epoch=7/25 train=0.5842 val=nan
[nodo07] fold=2 epoch=8/25 train=0.5919 val=nan
[nodo07] fold=2 epoch=9/25 train=0.5671 val=nan
[nodo07] fold=2 epoch=10/25 train=0.5872 val=nan
[nodo07] fold=2 epoch=11/25 train=0.5928 val=nan
[nodo07] fold=2 epoch=12/25 train=0.5686 val=nan
[nodo07] fold=2 epoch=13/25 train=0.5733 val=nan
[nodo07] fold=2 epoch=14/25 train=0.5513 val=nan
[nodo07] fold=2 epoch=15/25 train=0.5364 val=nan
[nodo07] fold=2 epoch=16/25 train=0.5374 val=nan
[nodo07] fold=2 epoch=17/25 train=0.5454 val=nan
[nodo07] fold=2 epoch=18/25 train=0.5412 val=nan
[nodo07] fold=2 epoch=19/25 train=0.5286 val=nan
[nodo07] fold=2 epoch=20/25 train=0.5592 val=nan
[nodo07] fold=2 epoch=21/25 train=0.5386 val=nan
[nodo07] fold=2 epoch=22/25 train=0.5220 val=nan
[nodo07] fold=2 epoch=23/25 train=0.5136 val=nan
[nodo07] fold=2 epoch=24/25 train=0.5149 val=nan
[nodo07] fold=2 epoch=25/25 train=0.5213 val=0.5679
[nodo07] fold=3 epoch=1/25 train=0.7326 val=nan
[nodo07] fold=3 epoch=2/25 train=0.6904 val=nan
[nodo07] fold=3 epoch=3/25 train=0.6411 val=nan
[nodo07] fold=3 epoch=4/25 train=0.5977 val=nan
[nodo07] fold=3 epoch=5/25 train=0.6044 val=nan
[nodo07] fold=3 epoch=6/25 train=0.6184 val=nan
[nodo07] fold=3 epoch=7/25 train=0.5974 val=nan
[nodo07] fold=3 epoch=8/25 train=0.5816 val=nan
[nodo07] fold=3 epoch=9/25 train=0.5829 val=nan
[nodo07] fold=3 epoch=10/25 train=0.5846 val=nan
[nodo07] fold=3 epoch=11/25 train=0.5721 val=nan
[nodo07] fold=3 epoch=12/25 train=0.5644 val=nan
[nodo07] fold=3 epoch=13/25 train=0.5523 val=nan
[nodo07] fold=3 epoch=14/25 train=0.5494 val=nan
[nodo07] fold=3 epoch=15/25 train=0.5484 val=nan
[nodo07] fold=3 epoch=16/25 train=0.5622 val=nan
[nodo07] fold=3 epoch=17/25 train=0.5397 val=nan
[nodo07] fold=3 epoch=18/25 train=0.5524 val=nan
[nodo07] fold=3 epoch=19/25 train=0.5453 val=nan
[nodo07] fold=3 epoch=20/25 train=0.5613 val=nan
[nodo07] fold=3 epoch=21/25 train=0.5395 val=nan
[nodo07] fold=3 epoch=22/25 train=0.5313 val=nan
[nodo07] fold=3 epoch=23/25 train=0.5540 val=nan
[nodo07] fold=3 epoch=24/25 train=0.5472 val=nan
[nodo07] fold=3 epoch=25/25 train=0.5477 val=0.4657
[nodo07] fold=4 epoch=1/25 train=0.7162 val=nan
[nodo07] fold=4 epoch=2/25 train=0.6625 val=nan
[nodo07] fold=4 epoch=3/25 train=0.6227 val=nan
[nodo07] fold=4 epoch=4/25 train=0.6320 val=nan
[nodo07] fold=4 epoch=5/25 train=0.6092 val=nan
[nodo07] fold=4 epoch=6/25 train=0.5679 val=nan
[nodo07] fold=4 epoch=7/25 train=0.6020 val=nan
[nodo07] fold=4 epoch=8/25 train=0.5844 val=nan
[nodo07] fold=4 epoch=9/25 train=0.5752 val=nan
[nodo07] fold=4 epoch=10/25 train=0.5479 val=nan
[nodo07] fold=4 epoch=11/25 train=0.5534 val=nan
[nodo07] fold=4 epoch=12/25 train=0.5484 val=nan
[nodo07] fold=4 epoch=13/25 train=0.5688 val=nan
[nodo07] fold=4 epoch=14/25 train=0.5560 val=nan
[nodo07] fold=4 epoch=15/25 train=0.5235 val=nan
[nodo07] fold=4 epoch=16/25 train=0.5382 val=nan
[nodo07] fold=4 epoch=17/25 train=0.5524 val=nan
[nodo07] fold=4 epoch=18/25 train=0.5277 val=nan
[nodo07] fold=4 epoch=19/25 train=0.5388 val=nan
[nodo07] fold=4 epoch=20/25 train=0.5268 val=nan
[nodo07] fold=4 epoch=21/25 train=0.5568 val=nan
[nodo07] fold=4 epoch=22/25 train=0.5136 val=nan
[nodo07] fold=4 epoch=23/25 train=0.5086 val=nan
[nodo07] fold=4 epoch=24/25 train=0.5533 val=nan
[nodo07] fold=4 epoch=25/25 train=0.5320 val=0.5683
[nodo07] fold=0 epoch=1/15 train=0.7222 val=nan
[nodo07] fold=0 epoch=2/15 train=0.6676 val=nan
[nodo07] fold=0 epoch=3/15 train=0.6322 val=nan
[nodo07] fold=0 epoch=4/15 train=0.6261 val=nan
[nodo07] fold=0 epoch=5/15 train=0.5969 val=nan
[nodo07] fold=0 epoch=6/15 train=0.5819 val=nan
[nodo07] fold=0 epoch=7/15 train=0.6009 val=nan
[nodo07] fold=0 epoch=8/15 train=0.5825 val=nan
[nodo07] fold=0 epoch=9/15 train=0.5962 val=nan
[nodo07] fold=0 epoch=10/15 train=0.5854 val=nan
[nodo07] fold=0 epoch=11/15 train=0.5855 val=nan
[nodo07] fold=0 epoch=12/15 train=0.6138 val=nan
[nodo07] fold=0 epoch=13/15 train=0.5595 val=nan
[nodo07] fold=0 epoch=14/15 train=0.5678 val=nan
[nodo07] fold=0 epoch=15/15 train=0.5722 val=0.5734
[nodo07] fold=1 epoch=1/15 train=0.6979 val=nan
[nodo07] fold=1 epoch=2/15 train=0.6108 val=nan
[nodo07] fold=1 epoch=3/15 train=0.6239 val=nan
[nodo07] fold=1 epoch=4/15 train=0.5870 val=nan
[nodo07] fold=1 epoch=5/15 train=0.5901 val=nan
[nodo07] fold=1 epoch=6/15 train=0.5710 val=nan
[nodo07] fold=1 epoch=7/15 train=0.5707 val=nan
[nodo07] fold=1 epoch=8/15 train=0.5574 val=nan
[nodo07] fold=1 epoch=9/15 train=0.5892 val=nan
[nodo07] fold=1 epoch=10/15 train=0.5806 val=nan
[nodo07] fold=1 epoch=11/15 train=0.5747 val=nan
[nodo07] fold=1 epoch=12/15 train=0.5798 val=nan
[nodo07] fold=1 epoch=13/15 train=0.5605 val=nan
[nodo07] fold=1 epoch=14/15 train=0.5706 val=nan
[nodo07] fold=1 epoch=15/15 train=0.5679 val=0.5890
[nodo07] fold=2 epoch=1/15 train=0.7100 val=nan
[nodo07] fold=2 epoch=2/15 train=0.6435 val=nan
[nodo07] fold=2 epoch=3/15 train=0.6256 val=nan
[nodo07] fold=2 epoch=4/15 train=0.6338 val=nan
[nodo07] fold=2 epoch=5/15 train=0.6110 val=nan
[nodo07] fold=2 epoch=6/15 train=0.5936 val=nan
[nodo07] fold=2 epoch=7/15 train=0.5804 val=nan
[nodo07] fold=2 epoch=8/15 train=0.5998 val=nan
[nodo07] fold=2 epoch=9/15 train=0.5650 val=nan
[nodo07] fold=2 epoch=10/15 train=0.5948 val=nan
[nodo07] fold=2 epoch=11/15 train=0.5934 val=nan
[nodo07] fold=2 epoch=12/15 train=0.5772 val=nan
[nodo07] fold=2 epoch=13/15 train=0.5856 val=nan
[nodo07] fold=2 epoch=14/15 train=0.5748 val=nan
[nodo07] fold=2 epoch=15/15 train=0.5637 val=0.5703
[nodo07] fold=3 epoch=1/15 train=0.7198 val=nan
[nodo07] fold=3 epoch=2/15 train=0.6847 val=nan
[nodo07] fold=3 epoch=3/15 train=0.6409 val=nan
[nodo07] fold=3 epoch=4/15 train=0.6087 val=nan
[nodo07] fold=3 epoch=5/15 train=0.6221 val=nan
[nodo07] fold=3 epoch=6/15 train=0.6299 val=nan
[nodo07] fold=3 epoch=7/15 train=0.6136 val=nan
[nodo07] fold=3 epoch=8/15 train=0.5927 val=nan
[nodo07] fold=3 epoch=9/15 train=0.6030 val=nan
[nodo07] fold=3 epoch=10/15 train=0.5953 val=nan
[nodo07] fold=3 epoch=11/15 train=0.5915 val=nan
[nodo07] fold=3 epoch=12/15 train=0.5875 val=nan
[nodo07] fold=3 epoch=13/15 train=0.5889 val=nan
[nodo07] fold=3 epoch=14/15 train=0.5808 val=nan
[nodo07] fold=3 epoch=15/15 train=0.5769 val=0.4889
[nodo07] fold=4 epoch=1/15 train=0.7063 val=nan
[nodo07] fold=4 epoch=2/15 train=0.6506 val=nan
[nodo07] fold=4 epoch=3/15 train=0.6208 val=nan
[nodo07] fold=4 epoch=4/15 train=0.6227 val=nan
[nodo07] fold=4 epoch=5/15 train=0.6048 val=nan
[nodo07] fold=4 epoch=6/15 train=0.5676 val=nan
[nodo07] fold=4 epoch=7/15 train=0.6037 val=nan
[nodo07] fold=4 epoch=8/15 train=0.5815 val=nan
[nodo07] fold=4 epoch=9/15 train=0.5896 val=nan
[nodo07] fold=4 epoch=10/15 train=0.5561 val=nan
[nodo07] fold=4 epoch=11/15 train=0.5565 val=nan
[nodo07] fold=4 epoch=12/15 train=0.5538 val=nan
[nodo07] fold=4 epoch=13/15 train=0.5774 val=nan
[nodo07] fold=4 epoch=14/15 train=0.5764 val=nan
[nodo07] fold=4 epoch=15/15 train=0.5334 val=0.5866
[nodo07] fold=0 epoch=1/18 train=0.7515 val=nan
[nodo07] fold=0 epoch=2/18 train=0.7012 val=nan
[nodo07] fold=0 epoch=3/18 train=0.7059 val=nan
[nodo07] fold=0 epoch=4/18 train=0.7028 val=nan
[nodo07] fold=0 epoch=5/18 train=0.6742 val=nan
[nodo07] fold=0 epoch=6/18 train=0.6739 val=nan
[nodo07] fold=0 epoch=7/18 train=0.6807 val=nan
[nodo07] fold=0 epoch=8/18 train=0.6723 val=nan
[nodo07] fold=0 epoch=9/18 train=0.6828 val=nan
[nodo07] fold=0 epoch=10/18 train=0.6892 val=nan
[nodo07] fold=0 epoch=11/18 train=0.6767 val=nan
[nodo07] fold=0 epoch=12/18 train=0.6936 val=nan
[nodo07] fold=0 epoch=13/18 train=0.6503 val=nan
[nodo07] fold=0 epoch=14/18 train=0.6561 val=nan
[nodo07] fold=0 epoch=15/18 train=0.6639 val=nan
[nodo07] fold=0 epoch=16/18 train=0.6437 val=nan
[nodo07] fold=0 epoch=17/18 train=0.6361 val=nan
[nodo07] fold=0 epoch=18/18 train=0.6556 val=0.6842
[nodo07] fold=1 epoch=1/18 train=0.7148 val=nan
[nodo07] fold=1 epoch=2/18 train=0.6320 val=nan
[nodo07] fold=1 epoch=3/18 train=0.6700 val=nan
[nodo07] fold=1 epoch=4/18 train=0.6193 val=nan
[nodo07] fold=1 epoch=5/18 train=0.6257 val=nan
[nodo07] fold=1 epoch=6/18 train=0.6040 val=nan
[nodo07] fold=1 epoch=7/18 train=0.6043 val=nan
[nodo07] fold=1 epoch=8/18 train=0.5710 val=nan
[nodo07] fold=1 epoch=9/18 train=0.6047 val=nan
[nodo07] fold=1 epoch=10/18 train=0.5893 val=nan
[nodo07] fold=1 epoch=11/18 train=0.5983 val=nan
[nodo07] fold=1 epoch=12/18 train=0.5946 val=nan
[nodo07] fold=1 epoch=13/18 train=0.5806 val=nan
[nodo07] fold=1 epoch=14/18 train=0.5745 val=nan
[nodo07] fold=1 epoch=15/18 train=0.5697 val=nan
[nodo07] fold=1 epoch=16/18 train=0.5446 val=nan
[nodo07] fold=1 epoch=17/18 train=0.5571 val=nan
[nodo07] fold=1 epoch=18/18 train=0.5706 val=0.6171
[nodo07] fold=2 epoch=1/18 train=0.7163 val=nan
[nodo07] fold=2 epoch=2/18 train=0.6474 val=nan
[nodo07] fold=2 epoch=3/18 train=0.6551 val=nan
[nodo07] fold=2 epoch=4/18 train=0.6458 val=nan
[nodo07] fold=2 epoch=5/18 train=0.6311 val=nan
[nodo07] fold=2 epoch=6/18 train=0.6047 val=nan
[nodo07] fold=2 epoch=7/18 train=0.5939 val=nan
[nodo07] fold=2 epoch=8/18 train=0.6095 val=nan
[nodo07] fold=2 epoch=9/18 train=0.5844 val=nan
[nodo07] fold=2 epoch=10/18 train=0.6204 val=nan
[nodo07] fold=2 epoch=11/18 train=0.6048 val=nan
[nodo07] fold=2 epoch=12/18 train=0.5799 val=nan
[nodo07] fold=2 epoch=13/18 train=0.5936 val=nan
[nodo07] fold=2 epoch=14/18 train=0.5887 val=nan
[nodo07] fold=2 epoch=15/18 train=0.5514 val=nan
[nodo07] fold=2 epoch=16/18 train=0.5685 val=nan
[nodo07] fold=2 epoch=17/18 train=0.5822 val=nan
[nodo07] fold=2 epoch=18/18 train=0.5597 val=0.6515
[nodo07] fold=3 epoch=1/18 train=0.7288 val=nan
[nodo07] fold=3 epoch=2/18 train=0.6814 val=nan
[nodo07] fold=3 epoch=3/18 train=0.6606 val=nan
[nodo07] fold=3 epoch=4/18 train=0.6264 val=nan
[nodo07] fold=3 epoch=5/18 train=0.6350 val=nan
[nodo07] fold=3 epoch=6/18 train=0.6373 val=nan
[nodo07] fold=3 epoch=7/18 train=0.6246 val=nan
[nodo07] fold=3 epoch=8/18 train=0.6126 val=nan
[nodo07] fold=3 epoch=9/18 train=0.6174 val=nan
[nodo07] fold=3 epoch=10/18 train=0.6056 val=nan
[nodo07] fold=3 epoch=11/18 train=0.5941 val=nan
[nodo07] fold=3 epoch=12/18 train=0.5875 val=nan
[nodo07] fold=3 epoch=13/18 train=0.5996 val=nan
[nodo07] fold=3 epoch=14/18 train=0.5800 val=nan
[nodo07] fold=3 epoch=15/18 train=0.5870 val=nan
[nodo07] fold=3 epoch=16/18 train=0.6057 val=nan
[nodo07] fold=3 epoch=17/18 train=0.5639 val=nan
[nodo07] fold=3 epoch=18/18 train=0.5952 val=0.4730
[nodo07] fold=4 epoch=1/18 train=0.7148 val=nan
[nodo07] fold=4 epoch=2/18 train=0.6667 val=nan
[nodo07] fold=4 epoch=3/18 train=0.6421 val=nan
[nodo07] fold=4 epoch=4/18 train=0.6483 val=nan
[nodo07] fold=4 epoch=5/18 train=0.6243 val=nan
[nodo07] fold=4 epoch=6/18 train=0.5950 val=nan
[nodo07] fold=4 epoch=7/18 train=0.6176 val=nan
[nodo07] fold=4 epoch=8/18 train=0.5759 val=nan
[nodo07] fold=4 epoch=9/18 train=0.5999 val=nan
[nodo07] fold=4 epoch=10/18 train=0.5748 val=nan
[nodo07] fold=4 epoch=11/18 train=0.5657 val=nan
[nodo07] fold=4 epoch=12/18 train=0.5828 val=nan
[nodo07] fold=4 epoch=13/18 train=0.5986 val=nan
[nodo07] fold=4 epoch=14/18 train=0.5824 val=nan
[nodo07] fold=4 epoch=15/18 train=0.5515 val=nan
[nodo07] fold=4 epoch=16/18 train=0.5599 val=nan
[nodo07] fold=4 epoch=17/18 train=0.5914 val=nan
[nodo07] fold=4 epoch=18/18 train=0.5401 val=0.6281

,candidate_id,architecture,feature_variant,lateral_strategy,raw_log_loss,raw_brier,raw_auc,raw_balanced_accuracy_0_5,raw_ece_10,calibrated_log_loss,calibrated_brier,calibrated_auc,calibrated_balanced_accuracy_0_5,calibrated_ece_10,deployment_temperature
0,555b81376733bb67,slab2d,image_radiomics_sbr,random_flip,0.547940,0.182645,0.801811,0.734904,0.050513,0.543655,0.181365,0.800133,0.734904,0.037625,1.234490
1,c56be99202976455,2.5d,image_radiomics_sbr,random_flip,0.561650,0.188128,0.785729,0.740164,0.044513,0.558443,0.187208,0.784103,0.740164,0.042201,1.210187
2,a37f424ba911f6cc,3d,image_radiomics_sbr,random_flip,0.610864,0.202112,0.775264,0.713962,0.087669,0.571392,0.193613,0.772863,0.713962,0.031732,1.737770

**Modelo primario nodo 09:** `555b81376733bb67` · **modelos por fold del primario:** `5`

## Lectura del resultado

El nodo 09 mejora la resolución de la optimización, pero no garantiza una mejora real. Se promueve un candidato sólo si el CV5 congelado supera al nodo 07 en log loss cross-calibrado y conserva estabilidad por fold y familia. Para revisar progreso parcial, curvas de aprendizaje, pruning, calibración y comparación entre redes, usa el nodo 08.